import type { PastExamSolutionProcess } from "@/components/pastExam/solutionProcessTypes";

export const ALGORITHM_PAST_EXAM_SOLUTION_PROCESSES = {
  "2017-1-q12": {
    title: "퀵 정렬 partition 한 번 추적",
    overview: "교재의 Partition 함수처럼 맨 왼쪽 피벗을 잡고 Left/Right가 교차한 뒤 A[Right]와 피벗을 교환하는 지점을 추적한다.",
    steps: [
      { title: "피벗 잡기", body: "맨 왼쪽 원소 15를 피벗으로 표시한다." },
      { title: "Left/Right 교차", body: "Left는 22에서 멈추고 Right는 11에서 멈춘다. Left가 Right를 지나쳤으므로 교재 절차의 마지막 교환 단계로 간다." },
      { title: "A[Right]와 교환", body: "피벗 15와 A[Right]=11을 교환하므로 원래 피벗 칸으로 들어오는 데이터는 11이다." },
    ],
    visual: {
      kind: "array",
      title: "15 1 7 11 22 분할 추적",
      frames: [
        {
          title: "1. 피벗 표시",
          caption: "맨 왼쪽 15를 기준값으로 잡고 나머지 원소를 비교한다.",
          array: [
            { label: "pivot", value: "15", variant: "active" },
            { value: "1" },
            { value: "7" },
            { value: "11" },
            { value: "22" },
          ],
        },
        {
          title: "2. Left/Right 정지 위치",
          caption: "Left는 피벗보다 크거나 같은 22에서, Right는 피벗보다 작은 11에서 멈춘다.",
          array: [
            { label: "pivot", value: "15", variant: "active" },
            { value: "1", variant: "done" },
            { value: "7", variant: "done" },
            { label: "Right", value: "11", variant: "answer" },
            { label: "Left", value: "22", variant: "active" },
          ],
        },
        {
          title: "3. 마지막 교환 결과",
          caption: "피벗 15와 A[Right]인 11을 교환한다. 따라서 피벗이 있던 첫 칸에는 11이 들어간다.",
          array: [
            { label: "answer", value: "11", variant: "answer" },
            { value: "1", variant: "done" },
            { value: "7", variant: "done" },
            { label: "pivot", value: "15", variant: "active" },
            { value: "22" },
          ],
        },
      ],
    },
    checkpoint: "partition 문항은 정렬 전체를 끝까지 하지 않고, 한 번의 분할 결과만 검산한다.",
  },
  "2019-1-q22": {
    title: "버블 정렬 교환 횟수 세기",
    overview: "역순 배열의 버블 정렬 교환 횟수는 인접 교환이 곧 역전쌍 제거라는 관점으로 센다.",
    steps: [
      { title: "역순 확인", body: "50 40 30 20 10은 다섯 원소가 완전히 내림차순이다." },
      { title: "역전쌍 계산", body: "다섯 원소의 역전쌍 수는 4+3+2+1이다." },
      { title: "교환 횟수 확정", body: "버블 정렬의 인접 교환 횟수는 역전쌍 수와 같으므로 10회이다." },
    ],
    visual: {
      kind: "array",
      title: "50 40 30 20 10의 swap 카운터",
      frames: [
        {
          title: "1. 초기 배열",
          caption: "모든 큰 값이 작은 값보다 앞에 있는 완전 역순 상태이다.",
          array: [
            { value: "50", variant: "active" },
            { value: "40", variant: "active" },
            { value: "30", variant: "active" },
            { value: "20", variant: "active" },
            { value: "10", variant: "active" },
          ],
        },
        {
          title: "2. 원소별 역전쌍 수",
          caption: "50은 4개, 40은 3개, 30은 2개, 20은 1개 원소와 자리를 바꿔야 한다.",
          table: {
            columns: ["원소", "뒤에 있는 더 작은 원소 수"],
            rows: [
              { cells: ["50", "4"], variant: "active" },
              { cells: ["40", "3"], variant: "active" },
              { cells: ["30", "2"], variant: "active" },
              { cells: ["20", "1"], variant: "active" },
              { cells: ["10", "0"] },
            ],
          },
        },
        {
          title: "3. 총 교환 횟수",
          caption: "4+3+2+1=10이므로 정답은 10회이다.",
          formula: [
            { value: "4" },
            { value: "+" },
            { value: "3" },
            { value: "+" },
            { value: "2" },
            { value: "+" },
            { value: "1" },
            { value: "=" },
            { value: "10", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "버블 정렬 swap 횟수는 실제 모든 패스를 그리지 않아도 역전쌍 수로 빠르게 확인할 수 있다.",
  },
  "2017-1-q24": {
    title: "DFS 방문 순서 스택 추적",
    overview: "원문 표가 이미 1, 3으로 시작하므로 그 경로를 유지한 채 스택 top의 미방문 인접 정점으로 깊게 내려간다.",
    steps: [
      { title: "주어진 시작 순서 유지", body: "방문 순서 표에 1 다음 3이 주어져 있으므로 스택은 1→3 경로에서 출발한다." },
      { title: "3에서 5로 진행", body: "3의 미방문 인접 정점 5로 내려가면 빈칸 (a)는 5가 된다." },
      { title: "5에서 2 확인", body: "5에서 아직 방문하지 않은 인접 정점 2로 내려가므로 빈칸 (b)는 2이다." },
    ],
    visual: {
      kind: "stack",
      title: "DFS 스택으로 빈칸 b 찾기",
      frames: [
        {
          title: "1. 표의 시작 순서 1 → 3",
          caption: "문항의 방문 순서가 1, 3으로 시작하므로 현재 스택 top은 3이다.",
          nodes: [
            { id: "1", label: "1", x: 50, y: 18, variant: "done" },
            { id: "2", label: "2", x: 24, y: 48 },
            { id: "3", label: "3", x: 50, y: 48, variant: "done" },
            { id: "4", label: "4", x: 76, y: 48 },
            { id: "5", label: "5", x: 36, y: 78 },
            { id: "6", label: "6", x: 64, y: 78 },
          ],
          edges: [
            { from: "1", to: "2" },
            { from: "1", to: "3", variant: "done" },
            { from: "1", to: "4" },
            { from: "2", to: "5" },
            { from: "3", to: "5" },
            { from: "4", to: "6" },
          ],
          array: [
            { label: "stack", value: "1", variant: "done" },
            { label: "top", value: "3", variant: "done" },
          ],
        },
        {
          title: "2. 3에서 5로 깊게 내려가기",
          caption: "DFS는 스택 top인 3의 미방문 인접 정점 5를 먼저 방문한다.",
          nodes: [
            { id: "1", label: "1", x: 50, y: 18, variant: "done" },
            { id: "2", label: "2", x: 24, y: 48 },
            { id: "3", label: "3", x: 50, y: 48, variant: "done" },
            { id: "4", label: "4", x: 76, y: 48 },
            { id: "5", label: "(a)=5", x: 36, y: 78, variant: "active" },
            { id: "6", label: "6", x: 64, y: 78 },
          ],
          edges: [
            { from: "1", to: "2" },
            { from: "1", to: "3", variant: "done" },
            { from: "1", to: "4" },
            { from: "2", to: "5" },
            { from: "3", to: "5", label: "a", variant: "active" },
            { from: "4", to: "6" },
          ],
          array: [
            { label: "stack", value: "1", variant: "done" },
            { label: "stack", value: "3", variant: "done" },
            { label: "next", value: "5", variant: "active" },
          ],
        },
        {
          title: "3. 빈칸 b 확정",
          caption: "5의 미방문 인접 정점 2가 다음으로 스택에 올라가므로 밑줄 친 빈칸 (b)는 2이다.",
          nodes: [
            { id: "1", label: "1", x: 50, y: 18, variant: "done" },
            { id: "2", label: "(b)=2", x: 24, y: 48, variant: "answer" },
            { id: "3", label: "3", x: 50, y: 48, variant: "done" },
            { id: "4", label: "4", x: 76, y: 48 },
            { id: "5", label: "(a)=5", x: 36, y: 78, variant: "done" },
            { id: "6", label: "6", x: 64, y: 78 },
          ],
          edges: [
            { from: "1", to: "3", variant: "done" },
            { from: "3", to: "5", label: "a", variant: "done" },
            { from: "5", to: "2", label: "b", variant: "answer" },
            { from: "1", to: "2" },
            { from: "1", to: "4" },
            { from: "4", to: "6" },
          ],
          array: [
            { label: "order", value: "1", variant: "done" },
            { label: "order", value: "3", variant: "done" },
            { label: "a", value: "5", variant: "done" },
            { label: "b", value: "2", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "DFS는 다음 칸을 보기 전에 현재 경로의 가장 깊은 미방문 정점을 먼저 확인한다.",
  },
  "2018-1-q28": {
    title: "BST 두 자식 노드 삭제",
    overview: "BST 삭제 문항은 삭제할 노드의 오른쪽 부분트리에서 가장 작은 값을 찾는 과정을 보여줄 때 효과적이다.",
    steps: [
      { title: "삭제 노드 확인", body: "삭제 대상 35는 두 자식을 가진 노드이므로 단순 제거가 아니다." },
      { title: "중위 후속자 찾기", body: "오른쪽 부분트리에서 55→44→40처럼 계속 왼쪽으로 내려가 40을 찾는다." },
      { title: "자리 대체", body: "35의 자리에는 중위 후속자 40이 들어간다." },
    ],
    visual: {
      kind: "tree",
      title: "35 삭제 후 40이 올라오는 이유",
      frames: [
        {
          title: "1. 삭제 대상 35",
          caption: "35는 왼쪽과 오른쪽 자식을 모두 가지므로 대체 노드를 찾아야 한다.",
          nodes: [
            { id: "35", label: "35", x: 50, y: 14, variant: "active" },
            { id: "30", label: "30", x: 28, y: 46 },
            { id: "55", label: "55", x: 72, y: 46 },
            { id: "15", label: "15", x: 18, y: 70 },
            { id: "44", label: "44", x: 58, y: 70 },
            { id: "88", label: "88", x: 86, y: 78 },
            { id: "7", label: "7", x: 10, y: 90 },
            { id: "22", label: "22", x: 28, y: 90 },
            { id: "40", label: "40", x: 50, y: 90 },
          ],
          edges: [
            { from: "35", to: "30" },
            { from: "35", to: "55" },
            { from: "30", to: "15" },
            { from: "15", to: "7" },
            { from: "15", to: "22" },
            { from: "55", to: "44" },
            { from: "44", to: "40" },
            { from: "55", to: "88" },
          ],
        },
        {
          title: "2. 오른쪽 부분트리의 최소값",
          caption: "오른쪽 부분트리의 가장 왼쪽 노드가 35의 중위 후속자이다.",
          nodes: [
            { id: "35", label: "35", x: 50, y: 14, variant: "cut" },
            { id: "30", label: "30", x: 28, y: 46 },
            { id: "55", label: "55", x: 72, y: 46, variant: "active" },
            { id: "15", label: "15", x: 18, y: 70 },
            { id: "44", label: "44", x: 58, y: 70, variant: "active" },
            { id: "88", label: "88", x: 86, y: 78 },
            { id: "7", label: "7", x: 10, y: 90 },
            { id: "22", label: "22", x: 28, y: 90 },
            { id: "40", label: "40", x: 50, y: 90, variant: "answer" },
          ],
          edges: [
            { from: "35", to: "55", label: "right", variant: "active" },
            { from: "55", to: "44", label: "left", variant: "active" },
            { from: "44", to: "40", label: "left", variant: "answer" },
            { from: "35", to: "30" },
            { from: "30", to: "15" },
            { from: "15", to: "7" },
            { from: "15", to: "22" },
            { from: "55", to: "88" },
          ],
        },
        {
          title: "3. 40으로 대체",
          caption: "중위 순서를 깨지 않도록 40이 35의 자리를 대신한다.",
          nodes: [
            { id: "40", label: "40", x: 50, y: 14, variant: "answer" },
            { id: "30", label: "30", x: 28, y: 46 },
            { id: "55", label: "55", x: 72, y: 46 },
            { id: "15", label: "15", x: 18, y: 70 },
            { id: "44", label: "44", x: 58, y: 70 },
            { id: "88", label: "88", x: 86, y: 78 },
            { id: "7", label: "7", x: 10, y: 90 },
            { id: "22", label: "22", x: 28, y: 90 },
          ],
          edges: [
            { from: "40", to: "30" },
            { from: "40", to: "55" },
            { from: "30", to: "15" },
            { from: "15", to: "7" },
            { from: "15", to: "22" },
            { from: "55", to: "44" },
            { from: "55", to: "88" },
          ],
        },
      ],
    },
    checkpoint: "두 자식 BST 삭제는 오른쪽 부분트리의 최솟값 또는 왼쪽 부분트리의 최댓값으로 대체한다.",
  },
  "2018-1-q30": {
    title: "B-트리 삽입 중 분할",
    overview: "B-트리 삽입 문항은 새 키를 넣은 뒤 가득 찬 노드를 나누며 부모로 올라가는 키를 확인한다.",
    steps: [
      { title: "삽입 위치 찾기", body: "70은 루트 30, 50보다 크므로 오른쪽 리프 [60, 80, 90]으로 내려간다." },
      { title: "가득 찬 노드 분할", body: "t=2인 B-트리의 리프 [60, 80, 90]은 이미 3개 키를 가진 포화 노드라 가운데 키 80을 부모로 올린다." },
      { title: "70 삽입 위치", body: "분할 뒤 70은 왼쪽 새 리프 [60]에 들어가 [60, 70]이 되고, 부모로 보내진 키는 80이다." },
    ],
    visual: {
      kind: "tree",
      title: "70 삽입 후 80 승격",
      frames: [
        {
          title: "1. 오른쪽 리프 확인",
          caption: "루트 [30, 50]에서 70은 가장 오른쪽 자식 [60, 80, 90] 범위에 속한다.",
          nodes: [
            { id: "root", label: "30 | 50", x: 50, y: 18, variant: "done" },
            { id: "left", label: "10 | 20", x: 20, y: 70 },
            { id: "mid", label: "40 | 45", x: 50, y: 70 },
            { id: "right", label: "60 | 80 | 90", x: 80, y: 70, variant: "active" },
          ],
          edges: [
            { from: "root", to: "left" },
            { from: "root", to: "mid" },
            { from: "root", to: "right", variant: "active" },
          ],
        },
        {
          title: "2. 포화 리프 분할",
          caption: "t=2에서는 키 3개 리프를 만나면 가운데 키 80을 부모로 올리고 [60]과 [90]으로 나눈다.",
          array: [
            { value: "60", variant: "done" },
            { label: "승격", value: "80", variant: "active" },
            { value: "90", variant: "done" },
          ],
        },
        {
          title: "3. 부모로 보내지는 키",
          caption: "80이 부모 [30, 50]으로 올라가고, 70은 [60] 쪽 리프에 삽입된다.",
          nodes: [
            { id: "root", label: "30 | 50 | 80", x: 50, y: 20, variant: "answer" },
            { id: "left", label: "10 | 20", x: 16, y: 70 },
            { id: "mid", label: "40 | 45", x: 42, y: 70 },
            { id: "L", label: "60 | 70", x: 68, y: 70, variant: "done" },
            { id: "R", label: "90", x: 90, y: 70, variant: "done" },
          ],
          edges: [
            { from: "root", to: "left" },
            { from: "root", to: "mid" },
            { from: "root", to: "L" },
            { from: "root", to: "R" },
          ],
        },
      ],
    },
    checkpoint: "B-트리 삽입은 새 키를 넣은 뒤 정렬된 키 묶음에서 부모로 올라가는 키를 찾는다.",
  },
  "2017-1-q28": {
    title: "플로이드 행렬 빈칸 비교",
    overview: "플로이드 문항은 모든 값을 다시 계산하기보다 D⁽⁰⁾에서 D⁽⁴⁾로 가며 빈칸 후보를 비교하는 형태로 푼다.",
    steps: [
      { title: "초기 행렬 확인", body: "D⁽⁰⁾는 직접 간선 비용을 담는다. 예를 들어 1→2는 4, 1→3은 2, 4→1은 3이다." },
      { title: "최단 거리 갱신", body: "플로이드 점화식으로 경유 정점을 허용하면 1→2는 1→3→2 경로 때문에 1로 줄어든다." },
      { title: "빈칸 값 비교", body: "최종 D⁽⁴⁾에서 (a)=1, (b)=2, (c)=4, (d)=5이므로 가장 작은 값은 (a)이다." },
    ],
    visual: {
      kind: "table",
      title: "D⁽⁰⁾에서 D⁽⁴⁾까지",
      frames: [
        {
          title: "1. D⁽⁰⁾",
          caption: "초기 행렬은 직접 간선만 반영한 출발점이다.",
          table: {
            columns: ["행", "1", "2", "3", "4"],
            rows: [
              { cells: ["1", "0", "4", "2", "∞"], variant: "active" },
              { cells: ["2", "∞", "0", "5", "∞"] },
              { cells: ["3", "∞", "-1", "0", "∞"] },
              { cells: ["4", "3", "∞", "∞", "0"] },
            ],
          },
        },
        {
          title: "2. D⁽⁴⁾ 빈칸 계산",
          caption: "최종 행렬에서 빈칸은 1→2, 1→3, 4→2, 4→3의 최단 거리이다.",
          table: {
            columns: ["빈칸", "위치", "계산 결과"],
            rows: [
              { cells: ["(a)", "d₁₂", "min(4, 1→3→2 = 2 + -1) = 1"], variant: "answer" },
              { cells: ["(b)", "d₁₃", "2"] },
              { cells: ["(c)", "d₄₂", "4→1→3→2 = 3 + 2 + -1 = 4"] },
              { cells: ["(d)", "d₄₃", "4→1→3 = 3 + 2 = 5"] },
            ],
          },
        },
        {
          title: "3. 최종 빈칸 비교",
          caption: "1, 2, 4, 5 중 최솟값은 1이므로 보기 ① (a)를 고른다.",
          array: [
            { label: "(a)", value: "1", variant: "answer" },
            { label: "(b)", value: "2" },
            { label: "(c)", value: "4" },
            { label: "(d)", value: "5" },
          ],
        },
      ],
    },
    checkpoint: "플로이드는 경유 정점을 하나씩 허용하는 표 갱신 문제로 보고 최종 빈칸을 비교한다.",
  },
  "2019-1-q18": {
    title: "MST 가중치 합 추적",
    overview: "최소 신장 트리는 간선을 고르는 순서와 사이클 여부를 같이 봐야 하므로 누적합 시각화가 필요한 문항이다.",
    steps: [
      { title: "작은 간선부터 보기", body: "그래프의 간선을 c-e=1, b-e=2, a-c=3, d-f=4, a-b=5, e-f=6, a-d=7 순서로 본다." },
      { title: "사이클 제거", body: "c-e, b-e, a-c, d-f를 넣은 뒤 a-b=5는 a-b가 이미 a-c-e-b로 연결되어 있어 사이클을 만든다." },
      { title: "누적합 계산", body: "마지막으로 e-f=6을 넣으면 모든 정점이 연결되고 합은 1+2+3+4+6=16이다." },
    ],
    visual: {
      kind: "graph",
      title: "간선 선택과 누적합",
      frames: [
        {
          title: "1. 후보 간선 정렬",
          caption: "원문 그래프의 가중치를 오름차순으로 나열한다.",
          array: [
            { label: "1", value: "c-e", variant: "active" },
            { label: "2", value: "b-e", variant: "active" },
            { label: "3", value: "a-c", variant: "active" },
            { label: "4", value: "d-f", variant: "active" },
            { label: "5", value: "a-b" },
            { label: "6", value: "e-f" },
            { label: "7", value: "a-d" },
          ],
        },
        {
          title: "2. 선택 간선과 제외 간선",
          caption: "a-b=5는 이미 연결된 a와 b를 다시 잇기 때문에 제외하고, e-f=6으로 두 성분을 합친다.",
          nodes: [
            { id: "a", label: "a", x: 50, y: 12, variant: "done" },
            { id: "b", label: "b", x: 18, y: 42, variant: "done" },
            { id: "c", label: "c", x: 50, y: 42, variant: "done" },
            { id: "d", label: "d", x: 82, y: 42, variant: "done" },
            { id: "e", label: "e", x: 34, y: 76, variant: "done" },
            { id: "f", label: "f", x: 72, y: 76, variant: "done" },
          ],
          edges: [
            { from: "c", to: "e", label: "1", variant: "done" },
            { from: "b", to: "e", label: "2", variant: "done" },
            { from: "a", to: "c", label: "3", variant: "done" },
            { from: "d", to: "f", label: "4", variant: "done" },
            { from: "a", to: "b", label: "5 cycle", variant: "cut" },
            { from: "e", to: "f", label: "6", variant: "answer" },
            { from: "a", to: "d", label: "7" },
          ],
        },
        {
          title: "3. 가중치 합",
          caption: "선택된 다섯 간선이 여섯 정점을 모두 연결하므로 최소 신장 트리의 합은 16이다.",
          formula: [
            { value: "1" },
            { value: "+" },
            { value: "2" },
            { value: "+" },
            { value: "3" },
            { value: "+" },
            { value: "4" },
            { value: "+" },
            { value: "6" },
            { value: "=" },
            { value: "16", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "MST는 가장 작은 간선만 무조건 고르는 문제가 아니라, 사이클을 만들지 않는 간선만 누적한다.",
  },
  "2018-1-q16": {
    title: "작업 스케줄링 첫 배정 찾기",
    overview: "작업 스케줄링 문항은 작업 선택 문제처럼 종료 시간을 먼저 보지 않고, 시작 시간이 빠른 순서로 작업을 기계에 배정하는 절차를 따른다.",
    steps: [
      { title: "문제 유형 확인", body: "문항은 최대 호환 작업 집합을 묻는 작업 선택이 아니라, 주어진 작업들을 기계에 배정하는 작업 스케줄링 문제라고 명시한다." },
      { title: "시작 시간 비교", body: "표에서 t₅=(0,7), t₄=(1,4), t₁=(2,5), t₈=(5,8) 순서로 시작 시간이 빠르다." },
      { title: "첫 배정 확정", body: "가장 먼저 처리할 작업은 시작 시간이 0인 t₅이므로 첫 번째로 기계에 할당되는 작업은 t₅이다." },
    ],
    visual: {
      kind: "table",
      title: "시작 시간 기준 스케줄링",
      frames: [
        {
          title: "1. 표에서 시작 시간 분리",
          caption: "작업 스케줄링은 각 작업의 왼쪽 값, 즉 시작 시간을 먼저 비교한다.",
          table: {
            columns: ["작업", "구간", "시작", "종료"],
            rows: [
              { cells: ["t₁", "(2,5)", "2", "5"] },
              { cells: ["t₂", "(6,9)", "6", "9"] },
              { cells: ["t₃", "(4,9)", "4", "9"] },
              { cells: ["t₄", "(1,4)", "1", "4"], variant: "active" },
              { cells: ["t₅", "(0,7)", "0", "7"], variant: "answer" },
              { cells: ["t₆", "(9,10)", "9", "10"] },
              { cells: ["t₇", "(7,10)", "7", "10"] },
              { cells: ["t₈", "(5,8)", "5", "8"] },
            ],
          },
        },
        {
          title: "2. 보기만 시작 시간순으로 정렬",
          caption: "보기 후보 중에서도 t₅가 가장 왼쪽 시간축에서 출발한다.",
          array: [
            { label: "start 0", value: "t₅", variant: "answer" },
            { label: "start 1", value: "t₄", variant: "active" },
            { label: "start 2", value: "t₁" },
            { label: "start 5", value: "t₈" },
          ],
        },
        {
          title: "3. 첫 기계 배정",
          caption: "시간 0에 시작하는 t₅를 첫 기계에 올린 뒤 나머지 작업을 계속 배정한다.",
          array: [
            { label: "machine 1", value: "t₅ (0→7)", variant: "answer" },
            { label: "next", value: "t₄ (1→4)", variant: "active" },
            { label: "later", value: "t₁/t₈" },
          ],
        },
      ],
    },
    checkpoint: "작업 선택은 종료 시간, 작업 스케줄링은 시작 시간순 처리라는 차이를 먼저 구분해야 한다.",
  },
  "2019-1-q19": {
    title: "작업 선택 첫 작업 고르기",
    overview: "작업 선택 문제는 종료 시간이 빠른 작업부터 보는 욕심쟁이 절차를 화면에 두는 것이 가장 빠르다.",
    steps: [
      { title: "종료 시간 기준 정렬", body: "t₁=(0,4), t₂=(4,8), t₃=(9,10), t₄=(1,6), t₅=(6,9), t₆=(1,3), t₇=(3,8), t₈=(4,6)의 종료 시간을 비교한다." },
      { title: "가장 먼저 끝나는 작업", body: "종료 시간이 3인 t₆이 표의 모든 작업 중 가장 빨리 끝난다." },
      { title: "첫 배정 확정", body: "가장 먼저 기계에 할당되는 작업은 t₆이다." },
    ],
    visual: {
      kind: "table",
      title: "종료 시간 우선 선택",
      frames: [
        {
          title: "1. 작업 표 읽기",
          caption: "작업 선택 문제는 작업 구간 표에서 종료 시간을 먼저 본다.",
          table: {
            columns: ["작업", "구간", "종료 시간"],
            rows: [
              { cells: ["t₁", "(0,4)", "4"] },
              { cells: ["t₂", "(4,8)", "8"] },
              { cells: ["t₃", "(9,10)", "10"] },
              { cells: ["t₄", "(1,6)", "6"] },
              { cells: ["t₅", "(6,9)", "9"] },
              { cells: ["t₆", "(1,3)", "3"], variant: "answer" },
              { cells: ["t₇", "(3,8)", "8"] },
              { cells: ["t₈", "(4,6)", "6"] },
            ],
          },
        },
        {
          title: "2. 가장 빠른 종료 작업",
          caption: "종료 시간만 오름차순으로 놓으면 t₆이 첫 위치에 온다.",
          array: [
            { label: "end 3", value: "t₆", variant: "answer" },
            { label: "end 4", value: "t₁" },
            { label: "end 6", value: "t₄" },
            { label: "end 6", value: "t₈" },
            { label: "end 8", value: "t₂/t₇" },
            { label: "end 9", value: "t₅" },
            { label: "end 10", value: "t₃" },
          ],
        },
        {
          title: "3. 첫 선택",
          caption: "첫 배정 작업은 t₆이다.",
          array: [
            { label: "first", value: "t₆", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "작업 선택 문제에서 첫 선택은 시작 시간이 아니라 종료 시간이 빠른 작업이다.",
  },
  "2019-1-q16": {
    title: "분할 가능 배낭 비율 추적",
    overview: "물체를 쪼갤 수 있는 배낭 문항은 단위 무게당 이익 순서로 채우는 과정만 추적하면 된다.",
    steps: [
      { title: "비율 계산", body: "물체1은 9/3=3, 물체2는 15/3=5, 물체3은 14/4=3.5, 물체4는 20/5=4이다." },
      { title: "큰 비율부터 채우기", body: "용량 10에 물체2 전체 3, 물체4 전체 5를 넣으면 남은 용량은 2이다." },
      { title: "남은 용량만큼 분할", body: "다음 비율인 물체3을 2만큼 쪼개 넣으면 추가 이익은 14×2/4=7, 전체 이익은 42이다." },
    ],
    visual: {
      kind: "array",
      title: "용량 10을 비율순으로 채우기",
      frames: [
        {
          title: "1. 단위 이익 비교",
          caption: "분할 가능 배낭은 총 이익이 아니라 이익/무게 비율이 먼저다.",
          table: {
            columns: ["물체", "무게", "이익", "단위 이익"],
            rows: [
              { cells: ["물체1", "3", "9", "3"] },
              { cells: ["물체2", "3", "15", "5"], variant: "answer" },
              { cells: ["물체3", "4", "14", "3.5"], variant: "active" },
              { cells: ["물체4", "5", "20", "4"], variant: "answer" },
            ],
          },
        },
        {
          title: "2. 용량 채우기",
          caption: "단위 이익 순서 2→4→3에 따라 용량 10을 채운다.",
          array: [
            { label: "start", value: "10", variant: "active" },
            { label: "물체2", value: "-3 / +15", variant: "done" },
            { label: "물체4", value: "-5 / +20", variant: "done" },
            { label: "remain", value: "2", variant: "active" },
            { label: "물체3 일부", value: "-2 / +7", variant: "answer" },
          ],
        },
        {
          title: "3. 최대 이익",
          caption: "물체2와 물체4를 모두 넣고 물체3을 절반만 넣는 분할 가능 배낭 계산이다.",
          formula: [
            { value: "15" },
            { value: "+" },
            { value: "20" },
            { value: "+" },
            { value: "14×2/4" },
            { value: "=" },
            { value: "42", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "분할 가능 배낭은 물체를 쪼갤 수 있으므로 마지막 선택도 남은 용량만큼 부분 선택한다.",
  },
  "2018-1-q25": {
    title: "힙 정렬 한 단계 재구성",
    overview: "힙 정렬 문항은 루트 최댓값을 뒤로 보낸 뒤 남은 구간을 다시 최대 힙으로 만드는 과정이 필요하다.",
    steps: [
      { title: "루트 최댓값 분리", body: "초기 힙 배열 80 60 70 40 20 30 50 10에서 루트 80과 마지막 10을 교환해 80을 정렬 구간에 둔다." },
      { title: "남은 힙 재구성", body: "루트로 올라온 10을 더 큰 자식 70, 다시 50과 교환해 최대 힙 성질을 회복한다." },
      { title: "배열 상태 확인", body: "한 번 수행 후 배열은 70 60 50 40 20 30 10 80이다." },
    ],
    visual: {
      kind: "array",
      title: "최댓값 삭제 후 힙 재구성",
      frames: [
        {
          title: "1. 80과 10 교환",
          caption: "최댓값 80을 배열 끝으로 보내고, 끝에 있던 10을 루트로 올린다.",
          array: [
            { value: "10", variant: "active" },
            { value: "60" },
            { value: "70" },
            { value: "40" },
            { value: "20" },
            { value: "30" },
            { value: "50" },
            { value: "80", variant: "done" },
          ],
        },
        {
          title: "2. 앞 구간 재힙화",
          caption: "10을 더 큰 자식과 내려보낸다. 먼저 70과, 그 다음 50과 바뀐다.",
          array: [
            { value: "70", variant: "active" },
            { value: "60" },
            { value: "50", variant: "active" },
            { value: "40" },
            { value: "20" },
            { value: "30" },
            { value: "10" },
            { value: "80", variant: "done" },
          ],
        },
        {
          title: "3. 한 단계 후 배열",
          caption: "정렬 구간 80을 제외한 앞쪽은 다시 최대 힙 모양을 갖는다.",
          array: [
            { value: "70", variant: "answer" },
            { value: "60", variant: "answer" },
            { value: "50", variant: "answer" },
            { value: "40", variant: "answer" },
            { value: "20", variant: "answer" },
            { value: "30", variant: "answer" },
            { value: "10", variant: "answer" },
            { value: "80", variant: "done" },
          ],
        },
      ],
    },
    checkpoint: "힙 정렬은 끝으로 보낸 값은 고정하고, 남은 앞 구간만 다시 힙으로 만든다.",
  },
  "2019-1-q35": {
    title: "MST 기반 TSP 근사 흐름",
    overview: "근사 알고리즘 설명 문항은 주어진 절차가 어떤 문제의 전형적인 풀이 흐름인지 연결해야 한다.",
    steps: [
      { title: "MST 구성", body: "그래프에서 먼저 최소 신장 트리를 만든다." },
      { title: "DFS 순회", body: "임의의 루트에서 최소 신장 트리를 깊이 우선 탐색 순서로 나열한다." },
      { title: "첫 정점 복귀", body: "마지막에 첫 정점을 다시 붙여 순회 경로를 만들므로 외판원 문제 절차이다." },
    ],
    visual: {
      kind: "graph",
      title: "MST → DFS preorder → tour",
      frames: [
        {
          title: "1. 최소 신장 트리 만들기",
          caption: "모든 정점을 연결하되 사이클 없는 최소 가중치 트리를 만든다.",
          nodes: [
            { id: "r", label: "root", x: 50, y: 16, variant: "active" },
            { id: "a", label: "A", x: 25, y: 52 },
            { id: "b", label: "B", x: 50, y: 52 },
            { id: "c", label: "C", x: 75, y: 52 },
            { id: "d", label: "D", x: 50, y: 82 },
          ],
          edges: [
            { from: "r", to: "a", variant: "done" },
            { from: "r", to: "b", variant: "done" },
            { from: "r", to: "c", variant: "done" },
            { from: "b", to: "d", variant: "done" },
          ],
        },
        {
          title: "2. DFS 순서 나열",
          caption: "트리를 깊이 우선으로 방문한 정점 순서를 만든다.",
          array: [
            { value: "root", variant: "done" },
            { value: "A", variant: "done" },
            { value: "B", variant: "active" },
            { value: "D", variant: "active" },
            { value: "C", variant: "active" },
          ],
        },
        {
          title: "3. 시작 정점으로 복귀",
          caption: "방문 순서 끝에 첫 정점을 한 번 더 붙이면 순회 경로가 되므로 외판원 문제에 해당한다.",
          array: [
            { value: "root", variant: "answer" },
            { value: "A", variant: "done" },
            { value: "B", variant: "done" },
            { value: "D", variant: "done" },
            { value: "C", variant: "done" },
            { value: "root", variant: "answer" },
          ],
        },
      ],
    },
    checkpoint: "MST를 만들고 DFS 순서 뒤 첫 정점으로 돌아오는 절차는 외판원 문제 근사 알고리즘의 설명이다.",
  },
} satisfies Record<string, PastExamSolutionProcess>;
