export const lectures = [
  {
    id: 1,
    title: "컴퓨터통신망의 소개",
    subtitle: "OSI 모델, 통신 시스템, 프로토콜",
    color: "lecture1",
    bgClass: "bg-blue-500",
    textClass: "text-blue-500",
    borderClass: "border-blue-500",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 2,
    title: "데이터 통신의 기초",
    subtitle: "변조/복조, PCM, 전송 부호",
    color: "lecture2",
    bgClass: "bg-emerald-500",
    textClass: "text-emerald-500",
    borderClass: "border-emerald-500",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 3,
    title: "데이터 통신의 요소",
    subtitle: "통신선로, 전송매체, 네트워크 토폴로지",
    color: "lecture3",
    bgClass: "bg-amber-500",
    textClass: "text-amber-500",
    borderClass: "border-amber-500",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 4,
    title: "데이터 통신의 전송 기술(1)",
    subtitle: "교환 방식, 다중화, 동기화",
    color: "lecture4",
    bgClass: "bg-violet-500",
    textClass: "text-violet-500",
    borderClass: "border-violet-500",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 5,
    title: "데이터 통신의 전송 기술(2)",
    subtitle: "오류제어, ARQ, 슬라이딩 윈도우",
    color: "lecture5",
    bgClass: "bg-rose-500",
    textClass: "text-rose-500",
    borderClass: "border-rose-500",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 6,
    title: "데이터 통신의 전송 기술(3)",
    subtitle: "흐름제어, 혼잡제어, 라우팅",
    color: "lecture6",
    bgClass: "bg-sky-500",
    textClass: "text-sky-500",
    borderClass: "border-sky-500",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 7,
    title: "컴퓨터 통신망 구조",
    subtitle: "OSI 참조 모델, TCP/IP 4계층, 캡슐화",
    color: "lecture7",
    bgClass: "bg-lime-500",
    textClass: "text-lime-500",
    borderClass: "border-lime-500",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
  {
    id: 8,
    title: "TCP/IP: 네트워크 계층",
    subtitle: "IP, ARP/RARP, ICMP, IGMP, DHCP",
    color: "lecture8",
    bgClass: "bg-pink-500",
    textClass: "text-pink-500",
    borderClass: "border-pink-500",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 9,
    title: "전송 계층",
    subtitle: "UDP, TCP, 3-way handshake, sliding window",
    color: "lecture9",
    bgClass: "bg-yellow-500",
    textClass: "text-yellow-500",
    borderClass: "border-yellow-500",
    bgLightClass: "bg-yellow-50 dark:bg-yellow-950",
  },
  {
    id: 10,
    title: "응용 계층",
    subtitle: "HTTP/HTTPS, FTP, TELNET/SSH, Mail",
    color: "lecture10",
    bgClass: "bg-red-500",
    textClass: "text-red-500",
    borderClass: "border-red-500",
    bgLightClass: "bg-red-50 dark:bg-red-950",
  },
] as const;

export const aiLectures = [
  {
    id: 1,
    title: "인공지능의 개요",
    subtitle: "튜링 테스트, 생성형 AI, AI 역사와 접근 방향",
    color: "ai1",
    bgClass: "bg-indigo-500",
    textClass: "text-indigo-500",
    borderClass: "border-indigo-500",
    bgLightClass: "bg-indigo-50 dark:bg-indigo-950",
  },
  {
    id: 2,
    title: "문제풀이(1)",
    subtitle: "상태공간 탐색, DFS, BFS, 균일비용 탐색",
    color: "ai2",
    bgClass: "bg-cyan-500",
    textClass: "text-cyan-500",
    borderClass: "border-cyan-500",
    bgLightClass: "bg-cyan-50 dark:bg-cyan-950",
  },
  {
    id: 3,
    title: "문제풀이(2)",
    subtitle: "언덕오르기, 모의 담금질, A* 알고리즘",
    color: "ai3",
    bgClass: "bg-teal-500",
    textClass: "text-teal-500",
    borderClass: "border-teal-500",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 4,
    title: "게임트리",
    subtitle: "미니맥스, α-β 가지치기, MCTS, AlphaGo",
    color: "ai4",
    bgClass: "bg-fuchsia-500",
    textClass: "text-fuchsia-500",
    borderClass: "border-fuchsia-500",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 5,
    title: "지식과 인공지능",
    subtitle: "논리, 규칙, 시맨틱 네트, 프레임, 전문가 시스템",
    color: "ai5",
    bgClass: "bg-orange-500",
    textClass: "text-orange-500",
    borderClass: "border-orange-500",
    bgLightClass: "bg-orange-50 dark:bg-orange-950",
  },
] as const;

export const securityLectures = [
  {
    id: 6,
    title: "네트워크 보안의 개요",
    subtitle: "보안위협 3종, 보안목표 7가지, OSI 보안서비스, TCP/IP 보안",
    color: "sec6",
    bgClass: "bg-purple-600",
    textClass: "text-purple-600",
    borderClass: "border-purple-600",
    bgLightClass: "bg-purple-50 dark:bg-purple-950",
  },
  {
    id: 7,
    title: "보안 시스템 I",
    subtitle: "방화벽 구성방식·구축형태 5종, VPN 목적·분류, NAC",
    color: "sec7",
    bgClass: "bg-violet-600",
    textClass: "text-violet-600",
    borderClass: "border-violet-600",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 8,
    title: "보안 시스템 II",
    subtitle: "IDS 구성·분석방법 3종·분류, IPS HIPS/NIPS",
    color: "sec8",
    bgClass: "bg-fuchsia-600",
    textClass: "text-fuchsia-600",
    borderClass: "border-fuchsia-600",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 9,
    title: "이메일 보안",
    subtitle: "PGP 보안서비스·키·키링·신뢰고리, S/MIME",
    color: "sec9",
    bgClass: "bg-rose-600",
    textClass: "text-rose-600",
    borderClass: "border-rose-600",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 10,
    title: "웹 보안 및 모바일 보안",
    subtitle: "웹위협 4종, 무선LAN 보안 WEP→WPA3",
    color: "sec10",
    bgClass: "bg-pink-600",
    textClass: "text-pink-600",
    borderClass: "border-pink-600",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
] as const;
