export const lectures = [
  {
    id: 1,
    title: "컴퓨터통신망의 소개",
    subtitle: "OSI 모델, 통신 시스템, 프로토콜",
    color: "lecture1",
    bgClass: "bg-blue-500",
    textClass: "text-blue-500",
    borderClass: "border-blue-500",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 2,
    title: "데이터 통신의 기초",
    subtitle: "변조/복조, PCM, 전송 부호",
    color: "lecture2",
    bgClass: "bg-emerald-500",
    textClass: "text-emerald-500",
    borderClass: "border-emerald-500",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 3,
    title: "데이터 통신의 요소",
    subtitle: "통신선로, 전송매체, 네트워크 토폴로지",
    color: "lecture3",
    bgClass: "bg-amber-500",
    textClass: "text-amber-500",
    borderClass: "border-amber-500",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 4,
    title: "데이터 통신의 전송 기술(1)",
    subtitle: "교환 방식, 다중화, 동기화",
    color: "lecture4",
    bgClass: "bg-violet-500",
    textClass: "text-violet-500",
    borderClass: "border-violet-500",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 5,
    title: "데이터 통신의 전송 기술(2)",
    subtitle: "오류제어, ARQ, 슬라이딩 윈도우",
    color: "lecture5",
    bgClass: "bg-rose-500",
    textClass: "text-rose-500",
    borderClass: "border-rose-500",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 6,
    title: "데이터 통신의 전송 기술(3)",
    subtitle: "흐름제어, 혼잡제어, 라우팅",
    color: "lecture6",
    bgClass: "bg-sky-500",
    textClass: "text-sky-500",
    borderClass: "border-sky-500",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 7,
    title: "컴퓨터 통신망 구조",
    subtitle: "OSI 참조 모델, TCP/IP 4계층, 캡슐화",
    color: "lecture7",
    bgClass: "bg-lime-500",
    textClass: "text-lime-500",
    borderClass: "border-lime-500",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
  {
    id: 8,
    title: "TCP/IP: 네트워크 계층",
    subtitle: "IP, ARP/RARP, ICMP, IGMP, DHCP",
    color: "lecture8",
    bgClass: "bg-pink-500",
    textClass: "text-pink-500",
    borderClass: "border-pink-500",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 9,
    title: "전송 계층",
    subtitle: "UDP, TCP, 3-way handshake, sliding window",
    color: "lecture9",
    bgClass: "bg-yellow-500",
    textClass: "text-yellow-500",
    borderClass: "border-yellow-500",
    bgLightClass: "bg-yellow-50 dark:bg-yellow-950",
  },
  {
    id: 10,
    title: "응용 계층",
    subtitle: "HTTP/HTTPS, FTP, TELNET/SSH, Mail",
    color: "lecture10",
    bgClass: "bg-red-500",
    textClass: "text-red-500",
    borderClass: "border-red-500",
    bgLightClass: "bg-red-50 dark:bg-red-950",
  },
  {
    id: 11,
    title: "근거리 통신망 기초",
    subtitle: "LAN 정의, 특성, 분류, 매체접근",
    color: "lecture11",
    bgClass: "bg-blue-600",
    textClass: "text-blue-600 dark:text-blue-400",
    borderClass: "border-blue-600",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 12,
    title: "근거리 통신망 모델",
    subtitle: "IEEE 802, 유선/무선 LAN, 고속 LAN",
    color: "lecture12",
    bgClass: "bg-emerald-600",
    textClass: "text-emerald-600 dark:text-emerald-400",
    borderClass: "border-emerald-600",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 13,
    title: "네트워크 보안 기초",
    subtitle: "CIA, 시스템 보안, 공격 유형, 악성 프로그램",
    color: "lecture13",
    bgClass: "bg-rose-600",
    textClass: "text-rose-600 dark:text-rose-400",
    borderClass: "border-rose-600",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 14,
    title: "네트워크 보안 기술",
    subtitle: "암호화, 디지털 서명, 방화벽, 프락시",
    color: "lecture14",
    bgClass: "bg-amber-500",
    textClass: "text-amber-600 dark:text-amber-400",
    borderClass: "border-amber-500",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 15,
    title: "최신 정보통신 기술",
    subtitle: "이동통신, IoT, SDN, NFV, MEC, SD-WAN",
    color: "lecture15",
    bgClass: "bg-violet-600",
    textClass: "text-violet-600 dark:text-violet-400",
    borderClass: "border-violet-600",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
] as const;

export const aiLectures = [
  {
    id: 1,
    title: "인공지능의 개요",
    subtitle: "튜링 테스트, 생성형 AI, AI 역사와 접근 방향",
    color: "ai1",
    bgClass: "bg-indigo-500",
    textClass: "text-indigo-500",
    borderClass: "border-indigo-500",
    bgLightClass: "bg-indigo-50 dark:bg-indigo-950",
  },
  {
    id: 2,
    title: "문제풀이(1)",
    subtitle: "상태공간 탐색, DFS, BFS, 균일비용 탐색",
    color: "ai2",
    bgClass: "bg-cyan-500",
    textClass: "text-cyan-500",
    borderClass: "border-cyan-500",
    bgLightClass: "bg-cyan-50 dark:bg-cyan-950",
  },
  {
    id: 3,
    title: "문제풀이(2)",
    subtitle: "언덕오르기, 모의 담금질, A* 알고리즘",
    color: "ai3",
    bgClass: "bg-teal-500",
    textClass: "text-teal-500",
    borderClass: "border-teal-500",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 4,
    title: "게임트리",
    subtitle: "미니맥스, α-β 가지치기, MCTS, AlphaGo",
    color: "ai4",
    bgClass: "bg-fuchsia-500",
    textClass: "text-fuchsia-500",
    borderClass: "border-fuchsia-500",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 5,
    title: "지식과 인공지능",
    subtitle: "논리, 규칙, 시맨틱 네트, 프레임, 전문가 시스템",
    color: "ai5",
    bgClass: "bg-orange-500",
    textClass: "text-orange-500",
    borderClass: "border-orange-500",
    bgLightClass: "bg-orange-50 dark:bg-orange-950",
  },
  {
    id: 6,
    title: "논리에 의한 지식표현",
    subtitle: "명제논리, 술어논리, 도출연역",
    color: "ai6",
    bgClass: "bg-violet-500",
    textClass: "text-violet-500",
    borderClass: "border-violet-500",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 7,
    title: "퍼지이론",
    subtitle: "퍼지집합, 퍼지논리, 퍼지추론",
    color: "ai7",
    bgClass: "bg-lime-500",
    textClass: "text-lime-600 dark:text-lime-400",
    borderClass: "border-lime-500",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
  {
    id: 8,
    title: "컴퓨터 시각과 패턴인식(1)",
    subtitle: "디지털 영상, 전처리, 영상 분할",
    color: "ai8",
    bgClass: "bg-sky-500",
    textClass: "text-sky-500",
    borderClass: "border-sky-500",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 9,
    title: "컴퓨터 시각과 패턴인식(2)",
    subtitle: "정규화, 특징 추출, 거리측정자, 패턴인식",
    color: "ai9",
    bgClass: "bg-pink-500",
    textClass: "text-pink-500",
    borderClass: "border-pink-500",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 10,
    title: "머신러닝(1)",
    subtitle: "학습 유형, 귀납적 학습, 결정트리",
    color: "ai10",
    bgClass: "bg-amber-500",
    textClass: "text-amber-600 dark:text-amber-400",
    borderClass: "border-amber-500",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 11,
    title: "머신러닝(2)",
    subtitle: "선형회귀, 로지스틱 회귀, 군집화",
    color: "ai11",
    bgClass: "bg-emerald-500",
    textClass: "text-emerald-500",
    borderClass: "border-emerald-500",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 12,
    title: "인공 신경망(1)",
    subtitle: "신경망 개념, 활성함수, 퍼셉트론 학습",
    color: "ai12",
    bgClass: "bg-rose-500",
    textClass: "text-rose-500",
    borderClass: "border-rose-500",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 13,
    title: "인공 신경망(2)",
    subtitle: "오차역전파, RBM, SOM, LVQ",
    color: "ai13",
    bgClass: "bg-purple-500",
    textClass: "text-purple-500",
    borderClass: "border-purple-500",
    bgLightClass: "bg-purple-50 dark:bg-purple-950",
  },
  {
    id: 14,
    title: "딥러닝(1)",
    subtitle: "학습 개선, CNN, 합성곱과 풀링",
    color: "ai14",
    bgClass: "bg-teal-600",
    textClass: "text-teal-600 dark:text-teal-400",
    borderClass: "border-teal-600",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 15,
    title: "딥러닝(2)",
    subtitle: "ResNet, RNN, LSTM/GRU, 트랜스포머",
    color: "ai15",
    bgClass: "bg-red-500",
    textClass: "text-red-500",
    borderClass: "border-red-500",
    bgLightClass: "bg-red-50 dark:bg-red-950",
  },
] as const;

export const securityLectures = [
  {
    id: 1,
    title: "컴퓨터 보안의 개요",
    subtitle: "정보보호 정의, CIA triad, 정보화 역기능, 보안 역사",
    color: "sec1",
    bgClass: "bg-slate-600",
    textClass: "text-slate-600 dark:text-slate-300",
    borderClass: "border-slate-600",
    bgLightClass: "bg-slate-50 dark:bg-slate-950",
  },
  {
    id: 2,
    title: "암호의 개념",
    subtitle: "평문·암호문, 전치·치환, 대칭키와 공개키 암호",
    color: "sec2",
    bgClass: "bg-cyan-600",
    textClass: "text-cyan-600 dark:text-cyan-300",
    borderClass: "border-cyan-600",
    bgLightClass: "bg-cyan-50 dark:bg-cyan-950",
  },
  {
    id: 3,
    title: "인증",
    subtitle: "메시지 인증, MAC, HMAC/CMAC, 사용자 인증과 2FA",
    color: "sec3",
    bgClass: "bg-teal-600",
    textClass: "text-teal-600 dark:text-teal-300",
    borderClass: "border-teal-600",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 4,
    title: "사이버 공격",
    subtitle: "악성코드, 네트워크 공격, 스팸·피싱, APT",
    color: "sec4",
    bgClass: "bg-orange-600",
    textClass: "text-orange-600 dark:text-orange-300",
    borderClass: "border-orange-600",
    bgLightClass: "bg-orange-50 dark:bg-orange-950",
  },
  {
    id: 5,
    title: "서버 보안",
    subtitle: "침입 단계, 계정 공격, 접근제어, 파일·로그 관리",
    color: "sec5",
    bgClass: "bg-amber-600",
    textClass: "text-amber-600 dark:text-amber-300",
    borderClass: "border-amber-600",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 6,
    title: "네트워크 보안의 개요",
    subtitle: "보안위협 3종, 보안목표 7가지, OSI 보안서비스, TCP/IP 보안",
    color: "sec6",
    bgClass: "bg-purple-600",
    textClass: "text-purple-600",
    borderClass: "border-purple-600",
    bgLightClass: "bg-purple-50 dark:bg-purple-950",
  },
  {
    id: 7,
    title: "보안 시스템 I",
    subtitle: "방화벽 구성방식·구축형태 5종, VPN 목적·분류, NAC",
    color: "sec7",
    bgClass: "bg-violet-600",
    textClass: "text-violet-600",
    borderClass: "border-violet-600",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 8,
    title: "보안 시스템 II",
    subtitle: "IDS 구성·분석방법 3종·분류, IPS HIPS/NIPS",
    color: "sec8",
    bgClass: "bg-fuchsia-600",
    textClass: "text-fuchsia-600",
    borderClass: "border-fuchsia-600",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 9,
    title: "이메일 보안",
    subtitle: "PGP 보안서비스·키·키링·신뢰고리, S/MIME",
    color: "sec9",
    bgClass: "bg-rose-600",
    textClass: "text-rose-600",
    borderClass: "border-rose-600",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 10,
    title: "웹 보안 및 모바일 보안",
    subtitle: "웹위협 4종, 무선LAN 보안 WEP→WPA3",
    color: "sec10",
    bgClass: "bg-pink-600",
    textClass: "text-pink-600",
    borderClass: "border-pink-600",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 11,
    title: "디지털 포렌식",
    subtitle: "디지털 증거, 법적 허용성, 포렌식 절차, 안티포렌식",
    color: "sec11",
    bgClass: "bg-indigo-600",
    textClass: "text-indigo-600 dark:text-indigo-300",
    borderClass: "border-indigo-600",
    bgLightClass: "bg-indigo-50 dark:bg-indigo-950",
  },
  {
    id: 12,
    title: "대칭키 암호",
    subtitle: "Feistel·SPN, ECB/CBC/CFB/OFB/CTR, LFSR, DES·AES",
    color: "sec12",
    bgClass: "bg-blue-600",
    textClass: "text-blue-600 dark:text-blue-300",
    borderClass: "border-blue-600",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 13,
    title: "공개키 암호",
    subtitle: "일방향 함수, RSA, ElGamal, ECC",
    color: "sec13",
    bgClass: "bg-sky-600",
    textClass: "text-sky-600 dark:text-sky-300",
    borderClass: "border-sky-600",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 14,
    title: "해시함수 및 전자서명",
    subtitle: "해시 요구조건, SHA 계열, 전자서명, DSS",
    color: "sec14",
    bgClass: "bg-emerald-600",
    textClass: "text-emerald-600 dark:text-emerald-300",
    borderClass: "border-emerald-600",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 15,
    title: "키 관리",
    subtitle: "DHKE, MITM, 공개키 분배, PKI, X.509, CRL",
    color: "sec15",
    bgClass: "bg-lime-600",
    textClass: "text-lime-600 dark:text-lime-300",
    borderClass: "border-lime-600",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
] as const;

export const softwareLectures = [
  {
    id: 1,
    title: "소프트웨어 공학 개요",
    subtitle: "소프트웨어 정의, 성질, 공학 환경, 좋은 소프트웨어 기준",
    color: "sw1",
    bgClass: "bg-emerald-600",
    textClass: "text-emerald-600 dark:text-emerald-300",
    borderClass: "border-emerald-600",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 2,
    title: "소프트웨어 프로세스",
    subtitle: "폭포수, 반복 진화형, 점증적, 나선형, V 모델, 애자일",
    color: "sw2",
    bgClass: "bg-sky-600",
    textClass: "text-sky-600 dark:text-sky-300",
    borderClass: "border-sky-600",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 3,
    title: "프로젝트 관리",
    subtitle: "관리 활동, WBS, Gantt, PERT/CPM, CMMI",
    color: "sw3",
    bgClass: "bg-amber-600",
    textClass: "text-amber-600 dark:text-amber-300",
    borderClass: "border-amber-600",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 4,
    title: "소프트웨어 품질",
    subtitle: "품질 특성, 표준, 신뢰도, 가용성, 품질 보증",
    color: "sw4",
    bgClass: "bg-rose-600",
    textClass: "text-rose-600 dark:text-rose-300",
    borderClass: "border-rose-600",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 5,
    title: "소프트웨어 테스트",
    subtitle: "화이트박스, 블랙박스, 테스트 케이스, V&V, 회귀 테스트",
    color: "sw5",
    bgClass: "bg-violet-600",
    textClass: "text-violet-600 dark:text-violet-300",
    borderClass: "border-violet-600",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 6,
    title: "사용자 요구 분석",
    subtitle: "요구사항 수집·분석, SRS, 유스케이스, 요구사항 품질",
    color: "sw6",
    bgClass: "bg-cyan-600",
    textClass: "text-cyan-600 dark:text-cyan-300",
    borderClass: "border-cyan-600",
    bgLightClass: "bg-cyan-50 dark:bg-cyan-950",
  },
  {
    id: 7,
    title: "소프트웨어 설계",
    subtitle: "아키텍처, 구조적 설계, 모듈화, 결합도·응집도, SOLID",
    color: "sw7",
    bgClass: "bg-lime-600",
    textClass: "text-lime-700 dark:text-lime-300",
    borderClass: "border-lime-600",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
  {
    id: 8,
    title: "코딩과 소프트웨어 유지보수",
    subtitle: "코딩 표준, 인스펙션, 리팩터링, 유지보수 유형, 형상 관리",
    color: "sw8",
    bgClass: "bg-orange-600",
    textClass: "text-orange-600 dark:text-orange-300",
    borderClass: "border-orange-600",
    bgLightClass: "bg-orange-50 dark:bg-orange-950",
  },
  {
    id: 9,
    title: "UML과 객체지향 개발",
    subtitle: "객체지향 개념, UML 뷰, 모델, 다이어그램, 스테레오 타입",
    color: "sw9",
    bgClass: "bg-indigo-600",
    textClass: "text-indigo-600 dark:text-indigo-300",
    borderClass: "border-indigo-600",
    bgLightClass: "bg-indigo-50 dark:bg-indigo-950",
  },
  {
    id: 10,
    title: "유스케이스 및 다이어그램 명세",
    subtitle: "액터, 시스템 경계, include, extend, 유스케이스 명세",
    color: "sw10",
    bgClass: "bg-fuchsia-600",
    textClass: "text-fuchsia-600 dark:text-fuchsia-300",
    borderClass: "border-fuchsia-600",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 11,
    title: "액티비티 다이어그램",
    subtitle: "액션, 제어 흐름, 객체 흐름, 포크·조인, 파티션",
    color: "sw11",
    bgClass: "bg-teal-600",
    textClass: "text-teal-600 dark:text-teal-300",
    borderClass: "border-teal-600",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 12,
    title: "상호작용 다이어그램",
    subtitle: "시퀀스, 통신, 라이프라인, 메시지, 활성화 막대",
    color: "sw12",
    bgClass: "bg-blue-600",
    textClass: "text-blue-600 dark:text-blue-300",
    borderClass: "border-blue-600",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 13,
    title: "클래스 다이어그램과 객체 다이어그램",
    subtitle: "클래스, 속성, 연산, 연관·집합·합성·상속, 객체 링크",
    color: "sw13",
    bgClass: "bg-pink-600",
    textClass: "text-pink-600 dark:text-pink-300",
    borderClass: "border-pink-600",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 14,
    title: "상태 머신 다이어그램",
    subtitle: "상태, 전이, 이벤트, 가드 조건, 활동, 복합 상태",
    color: "sw14",
    bgClass: "bg-purple-600",
    textClass: "text-purple-600 dark:text-purple-300",
    borderClass: "border-purple-600",
    bgLightClass: "bg-purple-50 dark:bg-purple-950",
  },
  {
    id: 15,
    title: "컴포넌트·배포·패키지 다이어그램",
    subtitle: "컴포넌트, 인터페이스, 노드, 아티팩트, 패키지 의존",
    color: "sw15",
    bgClass: "bg-slate-700",
    textClass: "text-slate-700 dark:text-slate-300",
    borderClass: "border-slate-700",
    bgLightClass: "bg-slate-50 dark:bg-slate-950",
  },
] as const;

export const javaLectures = [
  {
    id: 1,
    title: "Java와 객체지향 프로그래밍",
    subtitle: "Java 언어 개요, JDK, 소스 구성, JVM과 바이트코드",
    color: "java1",
    bgClass: "bg-amber-600",
    textClass: "text-amber-700 dark:text-amber-300",
    borderClass: "border-amber-600",
    bgLightClass: "bg-amber-50 dark:bg-amber-950",
  },
  {
    id: 2,
    title: "Java 기본 문법(1)",
    subtitle: "식별자, 키워드, 자료형, 리터럴, 연산자, 제어문",
    color: "java2",
    bgClass: "bg-blue-600",
    textClass: "text-blue-600 dark:text-blue-300",
    borderClass: "border-blue-600",
    bgLightClass: "bg-blue-50 dark:bg-blue-950",
  },
  {
    id: 3,
    title: "Java 기본 문법(2), 클래스와 상속(1)",
    subtitle: "배열, 문자열, Scanner, 클래스 정의, 접근 제어자",
    color: "java3",
    bgClass: "bg-emerald-600",
    textClass: "text-emerald-600 dark:text-emerald-300",
    borderClass: "border-emerald-600",
    bgLightClass: "bg-emerald-50 dark:bg-emerald-950",
  },
  {
    id: 4,
    title: "클래스와 상속(2)",
    subtitle: "static, final, 초기화, 오버로딩, 오버라이딩, this/super",
    color: "java4",
    bgClass: "bg-rose-600",
    textClass: "text-rose-600 dark:text-rose-300",
    borderClass: "border-rose-600",
    bgLightClass: "bg-rose-50 dark:bg-rose-950",
  },
  {
    id: 5,
    title: "인터페이스와 다형성",
    subtitle: "추상 클래스, 인터페이스, default 메소드, 다형성, 익명 클래스",
    color: "java5",
    bgClass: "bg-violet-600",
    textClass: "text-violet-600 dark:text-violet-300",
    borderClass: "border-violet-600",
    bgLightClass: "bg-violet-50 dark:bg-violet-950",
  },
  {
    id: 6,
    title: "제네릭과 람다식",
    subtitle: "제네릭 타입, raw 타입, 타입 제한, 람다식, 함수형 인터페이스",
    color: "java6",
    bgClass: "bg-cyan-600",
    textClass: "text-cyan-600 dark:text-cyan-300",
    borderClass: "border-cyan-600",
    bgLightClass: "bg-cyan-50 dark:bg-cyan-950",
  },
  {
    id: 7,
    title: "패키지와 예외처리",
    subtitle: "package, import, classpath, try-catch-finally, throw/throws",
    color: "java7",
    bgClass: "bg-lime-600",
    textClass: "text-lime-700 dark:text-lime-300",
    borderClass: "border-lime-600",
    bgLightClass: "bg-lime-50 dark:bg-lime-950",
  },
  {
    id: 8,
    title: "java.lang 패키지",
    subtitle: "Object, String, StringBuffer, StringBuilder, System",
    color: "java8",
    bgClass: "bg-orange-600",
    textClass: "text-orange-600 dark:text-orange-300",
    borderClass: "border-orange-600",
    bgLightClass: "bg-orange-50 dark:bg-orange-950",
  },
  {
    id: 9,
    title: "java.io 패키지와 스트림",
    subtitle: "입출력 스트림, 바이트/문자 스트림, File, 보조 스트림",
    color: "java9",
    bgClass: "bg-indigo-600",
    textClass: "text-indigo-600 dark:text-indigo-300",
    borderClass: "border-indigo-600",
    bgLightClass: "bg-indigo-50 dark:bg-indigo-950",
  },
  {
    id: 10,
    title: "java.nio 패키지의 활용",
    subtitle: "Path, Files, Buffer, FileChannel, WatchService",
    color: "java10",
    bgClass: "bg-fuchsia-600",
    textClass: "text-fuchsia-600 dark:text-fuchsia-300",
    borderClass: "border-fuchsia-600",
    bgLightClass: "bg-fuchsia-50 dark:bg-fuchsia-950",
  },
  {
    id: 11,
    title: "컬렉션",
    subtitle: "JCF, HashSet, ArrayList, LinkedList, Iterator, HashMap",
    color: "java11",
    bgClass: "bg-teal-600",
    textClass: "text-teal-600 dark:text-teal-300",
    borderClass: "border-teal-600",
    bgLightClass: "bg-teal-50 dark:bg-teal-950",
  },
  {
    id: 12,
    title: "컬렉션과 스트림",
    subtitle: "forEach, 스트림 생성, 파이프라인, 중간/종료 연산",
    color: "java12",
    bgClass: "bg-sky-600",
    textClass: "text-sky-600 dark:text-sky-300",
    borderClass: "border-sky-600",
    bgLightClass: "bg-sky-50 dark:bg-sky-950",
  },
  {
    id: 13,
    title: "멀티 스레드 프로그래밍",
    subtitle: "Thread, Runnable, 상태 제어, join, interrupt, synchronized",
    color: "java13",
    bgClass: "bg-pink-600",
    textClass: "text-pink-600 dark:text-pink-300",
    borderClass: "border-pink-600",
    bgLightClass: "bg-pink-50 dark:bg-pink-950",
  },
  {
    id: 14,
    title: "JDBC 프로그래밍",
    subtitle: "MariaDB, DriverManager, Connection, Statement, ResultSet",
    color: "java14",
    bgClass: "bg-purple-600",
    textClass: "text-purple-600 dark:text-purple-300",
    borderClass: "border-purple-600",
    bgLightClass: "bg-purple-50 dark:bg-purple-950",
  },
  {
    id: 15,
    title: "라이브러리와 모듈",
    subtitle: "JAR, classpath, Javadoc, module-info, requires/exports",
    color: "java15",
    bgClass: "bg-slate-700",
    textClass: "text-slate-700 dark:text-slate-300",
    borderClass: "border-slate-700",
    bgLightClass: "bg-slate-50 dark:bg-slate-950",
  },
] as const;
