import { buildSecurityChoiceExplanation } from "@/lib/securityChoiceExplanations";
import type {
  SecurityChoiceKey,
  SecurityPastExamQuestion,
  SecurityPastExamYear,
} from "./types";

type TopicKey =
  | "infoProtection"
  | "cia"
  | "cryptoBasics"
  | "transposition"
  | "symmetricCrypto"
  | "publicKeyCrypto"
  | "messageAuth"
  | "userAuth"
  | "malware"
  | "attackTypes"
  | "serverIntrusion"
  | "accessControl"
  | "pcSecurity"
  | "spamPhishing"
  | "cyberAttackEvolution"
  | "ipAddressing"
  | "networkSecurity"
  | "firewall"
  | "vpn"
  | "ids"
  | "emailSecurity"
  | "webSecurity"
  | "wirelessSecurity"
  | "forensics"
  | "antiForensics";

type Topic = {
  concept: string;
  lectureId: number;
  lectureLabel: string;
  tags: string[];
  basis: string;
  examSkill: string;
  textbook: string;
};

type RawQuestion = {
  year: SecurityPastExamYear;
  number: number;
  prompt: string;
  choices: [string, string, string, string];
  correctChoice: SecurityChoiceKey;
  topic: TopicKey;
  tags?: string[];
  examSkill?: string;
};

const choiceLabels: Record<SecurityChoiceKey, string> = {
  "1": "①",
  "2": "②",
  "3": "③",
  "4": "④",
};

function extractEmbeddedChoiceMap(prompt: string) {
  const entries = Array.from(prompt.matchAll(/^([가-힣])\.\s+(.+)$/gm));
  return Object.fromEntries(entries.map(([, key, value]) => [key, value.trim()]));
}

function expandEmbeddedChoice(choiceText: string, embeddedChoices: Record<string, string>) {
  const trimmed = choiceText.trim();
  const embedded = embeddedChoices[trimmed];
  return embedded ? `${trimmed}. ${embedded}` : choiceText;
}

export const securityPastExamYears = [2015, 2016, 2017, 2018, 2019] as const;

export const securityPastExamTopics: Record<TopicKey, Topic> = {
  infoProtection: {
    concept: "정보보호 개념",
    lectureId: 1,
    lectureLabel: "1강 컴퓨터 보안의 개요",
    tags: ["정보보호", "보안 목표"],
    basis: "정보보호는 여러 위험으로부터 정보를 보호하기 위한 정책과 기법이며, 정보 상태와 위협 유형을 함께 고려한다.",
    examSkill: "정의와 예외 판별",
    textbook: "교재 1장 컴퓨터 보안의 개요",
  },
  cia: {
    concept: "CIA triad",
    lectureId: 1,
    lectureLabel: "1강 컴퓨터 보안의 개요",
    tags: ["CIA", "보안 목표"],
    basis: "정보보호의 핵심 3요소는 기밀성, 무결성, 가용성이고 인증, 부인방지, 접근제어는 보안 서비스로 함께 다룬다.",
    examSkill: "보안 목표 구분",
    textbook: "교재 1장 컴퓨터 보안의 개요",
  },
  cryptoBasics: {
    concept: "암호 기본 용어",
    lectureId: 2,
    lectureLabel: "2강 암호의 개념",
    tags: ["암호", "평문/암호문"],
    basis: "암호는 평문을 암호문으로 변환해 안전하지 않은 통신 경로에서도 제3자가 내용을 알 수 없게 한다.",
    examSkill: "암호 용어 매칭",
    textbook: "교재 2장 암호의 개념",
  },
  transposition: {
    concept: "전치법과 치환법",
    lectureId: 2,
    lectureLabel: "2강 암호의 개념",
    tags: ["전치법", "치환법"],
    basis: "전치법은 문자의 위치를 바꾸고, 치환법은 문자를 다른 문자로 대체한다. 스파르타 봉 암호와 시프트 암호는 서로 다른 고전 암호 유형이다.",
    examSkill: "고전 암호 방식 판별",
    textbook: "교재 2장 암호의 개념",
  },
  symmetricCrypto: {
    concept: "대칭키 암호",
    lectureId: 2,
    lectureLabel: "2강 암호의 개념",
    tags: ["대칭키", "블록/스트림"],
    basis: "대칭키 암호는 하나의 비밀키를 암호화와 복호화에 함께 사용하며 AES, DES, IDEA 등이 대표적이다.",
    examSkill: "알고리즘 분류",
    textbook: "교재 2장 암호의 개념",
  },
  publicKeyCrypto: {
    concept: "공개키 암호",
    lectureId: 2,
    lectureLabel: "2강 암호의 개념",
    tags: ["공개키", "키 쌍"],
    basis: "공개키 암호는 공개키와 개인키를 분리해 키 분배 문제를 완화하지만 일반적으로 대칭키 암호보다 느리다.",
    examSkill: "키 구조와 성능 비교",
    textbook: "교재 2장 암호의 개념",
  },
  messageAuth: {
    concept: "메시지 인증",
    lectureId: 3,
    lectureLabel: "3강 인증",
    tags: ["메시지 인증", "MAC"],
    basis: "메시지 인증은 전송 중 메시지가 불법적으로 변경되지 않았는지 확인하며 HMAC은 해시 기반, CMAC은 블록 암호 기반이다.",
    examSkill: "인증 코드 기반 구분",
    textbook: "교재 3장 인증",
  },
  userAuth: {
    concept: "사용자 인증",
    lectureId: 3,
    lectureLabel: "3강 인증",
    tags: ["사용자 인증", "비밀번호/토큰/생체"],
    basis: "사용자 인증은 지식 기반, 소유 기반, 생체 기반 요소를 활용해 사용자의 신원을 확인한다.",
    examSkill: "인증 요소 판별",
    textbook: "교재 3장 인증",
  },
  malware: {
    concept: "악성코드 분류",
    lectureId: 4,
    lectureLabel: "4강 사이버 공격",
    tags: ["악성코드", "바이러스/웜/랜섬웨어"],
    basis: "악성코드는 바이러스, 웜, 트로이 목마, 백도어, 랜섬웨어처럼 감염 방식과 목적에 따라 구분한다.",
    examSkill: "악성코드 증상 판별",
    textbook: "교재 4장 사이버 공격",
  },
  attackTypes: {
    concept: "사이버 공격 유형",
    lectureId: 4,
    lectureLabel: "4강 사이버 공격",
    tags: ["공격 유형", "스푸핑/스니핑/DoS"],
    basis: "사이버 공격은 스캐닝, 스푸핑, 스니핑, 버퍼 오버플로, 사전 공격, 사회공학, DoS/DDoS처럼 공격 행위와 결과로 구분한다.",
    examSkill: "사례 기반 공격명 선택",
    textbook: "교재 4장 사이버 공격",
  },
  serverIntrusion: {
    concept: "서버 침입 단계",
    lectureId: 5,
    lectureLabel: "5강 서버 보안",
    tags: ["서버 침입", "단계"],
    basis: "서버 침입은 정보획득, 권한획득, 공격, 은닉 또는 재침입 준비 같은 단계로 분석한다.",
    examSkill: "단계와 행위 연결",
    textbook: "교재 5장 서버 보안",
  },
  accessControl: {
    concept: "시스템 접근제어",
    lectureId: 5,
    lectureLabel: "5강 서버 보안",
    tags: ["접근제어", "MAC/DAC/RBAC"],
    basis: "시스템 접근제어는 강제적 접근제어, 임의적 접근제어, 역할 기반 접근제어, 최소 권한 원칙으로 주체의 객체 접근을 제한한다.",
    examSkill: "접근제어 정책 구분",
    textbook: "교재 5장 서버 보안",
  },
  pcSecurity: {
    concept: "PC 보안 대책",
    lectureId: 4,
    lectureLabel: "4강 사이버 공격",
    tags: ["PC 보안", "취약점"],
    basis: "PC 보안에서는 물리적 접근, 보안 인식, 소프트웨어 품질, 공유 설정과 관리자 계정 관리 같은 취약 요인을 점검한다.",
    examSkill: "취약점과 대책 구분",
    textbook: "교재 4장 사이버 공격",
  },
  spamPhishing: {
    concept: "스팸 메일과 피싱",
    lectureId: 4,
    lectureLabel: "4강 사이버 공격",
    tags: ["스팸", "피싱"],
    basis: "스팸 메일은 불특정 다수에게 일방적·대량으로 전달되는 이메일이고, 피싱은 기관을 사칭해 개인정보나 금융정보를 얻어 내는 행위다.",
    examSkill: "사례 기반 공격명 판별",
    textbook: "교재 4장 사이버 공격",
  },
  cyberAttackEvolution: {
    concept: "최근 공격도구의 특징",
    lectureId: 4,
    lectureLabel: "4강 사이버 공격",
    tags: ["에이전트화", "분산화", "자동화", "은닉화"],
    basis: "근래의 공격도구들은 효율적인 공격을 위해 에이전트화, 분산화, 자동화, 은닉화의 특징을 보인다.",
    examSkill: "공격도구 특징 판별",
    textbook: "교재 4장 사이버 공격",
  },
  ipAddressing: {
    concept: "IPv4 주소 구조",
    lectureId: 6,
    lectureLabel: "6강 네트워크 보안의 개요",
    tags: ["IPv4", "netid/hostid"],
    basis: "IPv4 주소는 클래스에 따라 netid와 hostid의 크기가 달라지며 IPsec 설명의 배경이 되는 IP 구조로 다룬다.",
    examSkill: "클래스와 hostid 판별",
    textbook: "교재 6장 네트워크 보안의 개요",
  },
  networkSecurity: {
    concept: "네트워크 보안",
    lectureId: 6,
    lectureLabel: "6강 네트워크 보안의 개요",
    tags: ["네트워크 보안", "IPsec"],
    basis: "네트워크 보안은 기밀성, 무결성, 인증, 접근제어, 부인방지 등을 목표로 하며 IPsec은 IP 데이터그램 보호 메커니즘이다.",
    examSkill: "보안 목표와 프로토콜 연결",
    textbook: "교재 6장 네트워크 보안의 개요",
  },
  firewall: {
    concept: "방화벽과 보안 시스템",
    lectureId: 7,
    lectureLabel: "7강 보안 시스템 I",
    tags: ["방화벽", "DMZ"],
    basis: "방화벽은 외부망과 내부망 사이 트래픽을 통제하며 패킷 필터링, 서킷 게이트웨이, 애플리케이션 게이트웨이, 스크린 서브넷 형태로 구분한다.",
    examSkill: "구성 방식 판별",
    textbook: "교재 7장 보안 시스템 I",
  },
  vpn: {
    concept: "가상사설망(VPN)",
    lectureId: 7,
    lectureLabel: "7강 보안 시스템 I",
    tags: ["VPN", "터널링"],
    basis: "VPN은 공중망을 사설망처럼 사용하도록 터널링 기반의 가상 정보 흐름 통로를 제공한다.",
    examSkill: "VPN 기반 기술 판별",
    textbook: "교재 7장 보안 시스템 I",
  },
  ids: {
    concept: "IDS/IPS",
    lectureId: 8,
    lectureLabel: "8강 보안 시스템 II",
    tags: ["IDS", "IPS", "분석방법"],
    basis: "IDS는 침입을 탐지하고 IPS는 탐지 후 자동 대응까지 수행한다. IDS 분석 방법에는 시그니처, 통계적, 무결성 분석이 있다.",
    examSkill: "탐지 방식과 구성요소 매칭",
    textbook: "교재 8장 보안 시스템 II",
  },
  emailSecurity: {
    concept: "전자우편 보안",
    lectureId: 9,
    lectureLabel: "9강 이메일 보안",
    tags: ["PGP", "S/MIME", "Radix-64"],
    basis: "PGP와 S/MIME은 전자우편에 암호화와 전자서명을 제공하며 Radix-64는 전송 가능한 문자 표현으로 변환한다.",
    examSkill: "메일 보안 서비스와 계산",
    textbook: "교재 9장 이메일 보안",
  },
  webSecurity: {
    concept: "웹 보안",
    lectureId: 10,
    lectureLabel: "10강 웹 보안 및 모바일 보안",
    tags: ["SQL injection", "XSS", "접근제어"],
    basis: "웹 보안에서는 SQL injection, XSS, 접근제어 실패, 웹 서버 취약점처럼 웹 서비스 계층별 위협을 구분한다.",
    examSkill: "웹 공격 유형 판별",
    textbook: "교재 10장 웹 보안 및 모바일 보안",
  },
  wirelessSecurity: {
    concept: "무선 LAN 보안",
    lectureId: 10,
    lectureLabel: "10강 웹 보안 및 모바일 보안",
    tags: ["WEP", "WPA/RSN"],
    basis: "무선 LAN 보안은 WEP의 취약성 이후 WPA, RSN, TKIP, CCMP, EAP 중심으로 발전했다.",
    examSkill: "무선 보안 프로토콜 구분",
    textbook: "교재 10장 웹 보안 및 모바일 보안",
  },
  forensics: {
    concept: "디지털 포렌식",
    lectureId: 11,
    lectureLabel: "11강 디지털 포렌식",
    tags: ["디지털 증거", "포렌식 절차"],
    basis: "디지털 증거는 비가시성, 변조 가능성, 휘발성, 대규모성 등의 특성을 가지며 정해진 절차로 수집·분석한다.",
    examSkill: "증거 특성과 절차 판별",
    textbook: "교재 11장 디지털 포렌식",
  },
  antiForensics: {
    concept: "안티 포렌식",
    lectureId: 11,
    lectureLabel: "11강 디지털 포렌식",
    tags: ["안티 포렌식", "분석 방해"],
    basis: "안티 포렌식은 데이터 삭제, 메타데이터 변조, 암호화 등으로 증거 수집과 분석을 방해한다.",
    examSkill: "분석 방해 행위 판별",
    textbook: "교재 11장 디지털 포렌식",
  },
};

const rawQuestions: RawQuestion[] = [
  {
    year: 2015,
    number: 36,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 서비스 거부 공격(DoS)\n\n네트워크를 통해 스스로 감염되며 숙주가 필요하지 않은 악성코드는?",
    choices: ["가", "나", "라", "바"],
    correctChoice: "1",
    topic: "malware",
    tags: ["웜"],
  },
  {
    year: 2015,
    number: 37,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 서비스 거부 공격(DoS)\n\n공격자가 시스템에 침입한 후 이후에도 손쉽게 피해 시스템에 대한 접근 권한을 획득하기 위한 용도로 설치한 악성코드는?",
    choices: ["가", "다", "마", "사"],
    correctChoice: "2",
    topic: "malware",
    tags: ["백도어"],
  },
  {
    year: 2015,
    number: 38,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 서비스 거부 공격(DoS)\n\n괄호 안에 공통으로 들어갈 사이버 공격 방식은?\nPassive (    )은 무차별 모드를 이용하여 패킷 내의 정보를 조작 없이 단순히 도청하는 것이며, active (    )은 ARP 스푸핑을 이용하여 공격 대상자들의 패킷 방향을 조작하여 내용을 훔쳐보거나 변조하는 방식임",
    choices: ["가", "마", "바", "사"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["스니핑"],
  },
  {
    year: 2015,
    number: 39,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 서비스 거부 공격(DoS)\n\n특정 서비스나 자원의 가용성을 떨어뜨리는 결과를 초래하는 유형의 공격으로 대량의 데이터를 전송하거나 무수히 많은 네트워크 연결 요청을 하는 등의 공격 방식은?",
    choices: ["나", "다", "바", "아"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["DoS"],
  },
  {
    year: 2015,
    number: 40,
    prompt: "다음 설명에 가장 적합한 최근의 사이버 공격 방식은?\n침입탐지시스템 등의 보안 시스템을 우회하기 위해 많은 수의 시스템에서 단일의 시스템 또는 다수의 시스템을 공격하는 방법을 사용하며, 원격 명령으로 공격을 수행하여 공격자의 위치를 감출 수 있고 보다 빠르게 공격대상 시스템에 대한 정보를 수집할 수 있음",
    choices: ["에이전트화", "분산화", "자동화", "은닉화"],
    correctChoice: "2",
    topic: "cyberAttackEvolution",
    tags: ["분산화"],
  },
  {
    year: 2015,
    number: 41,
    prompt: "IPv4 구조의 주소는 netid와 hostid로 구분되며 이들은 class별로 서로 다른 크기로 정의된다. 참고로 hostid를 표현하기 위해 Class A는 3바이트, Class B는 2바이트, Class C는 1바이트가 사용된다. 다음 주소에서 hostid는 어느 것인가?\n211.46.136.13\n(이진수 표현: 11010011.00101110.10001000.00001101)",
    choices: ["46.136.13", "136.13", "13", "211"],
    correctChoice: "3",
    topic: "ipAddressing",
    tags: ["hostid"],
  },
  {
    year: 2015,
    number: 42,
    prompt: "다음 설명에 해당하는 것은?\n- IP를 위한 보안 메커니즘 제시\n- AH 프로토콜과 ESP 프로토콜 존재",
    choices: ["SSL", "UDP", "TCP", "IPsec"],
    correctChoice: "4",
    topic: "networkSecurity",
    tags: ["IPsec", "AH/ESP"],
  },
  {
    year: 2015,
    number: 43,
    prompt: "전자우편 보안도구인 PGP가 기밀성을 보장하는 방법은?",
    choices: ["공개키 방식 암호화만 이용", "대칭키 방식 암호화만 이용", "두 가지 방식을 모두 이용", "PGP는 기밀성을 보장하지 못함"],
    correctChoice: "3",
    topic: "emailSecurity",
    tags: ["PGP", "기밀성"],
  },
  {
    year: 2015,
    number: 44,
    prompt: "기수 64(Radix-64)는 데이터를 6비트 단위로 나눠서 각각을 하나의 문자로 표현하는 방법이다. 기수 64를 적용한 결과 12개의 문자로 표현이 되었다면 적용 전의 데이터의 크기는 몇 바이트인가? (단, 마지막 패드 문자는 고려하지 않는다고 가정)",
    choices: ["9", "12", "16", "6"],
    correctChoice: "1",
    topic: "emailSecurity",
    tags: ["Radix-64", "계산"],
  },
  {
    year: 2015,
    number: 45,
    prompt: "S/MIME에 대한 설명으로 바르지 못한 것은?",
    choices: [
      "인터넷 전자우편 표준에 보안기능을 강화함",
      "메시지 암호화는 대칭키 방식, 세션키 분배는 공개키 방식을 이용함",
      "클리어 서명 데이터는 전자서명만 base64로 부호화",
      "암호화된 데이터는 서명될 수 있으나 서명된 데이터는 암호화될 수 없음",
    ],
    correctChoice: "4",
    topic: "emailSecurity",
    tags: ["S/MIME"],
  },
  {
    year: 2015,
    number: 46,
    prompt: "PC의 보안을 위협하는 취약점과 거리가 먼 것은?",
    choices: ["물리적 접근의 용이", "보안 문제에 대한 인식 결여", "낮은 수준의 소프트웨어 품질", "낮은 이동성"],
    correctChoice: "4",
    topic: "pcSecurity",
  },
  {
    year: 2015,
    number: 47,
    prompt: "다음 설명에 해당하는 것은?\n불특정 다수를 대상으로 일방적이며 대량으로 전달되는 전자우편으로, 적은 비용으로 다수의 대상에게 상품을 광고하거나 특정 종교를 포교하는 목적으로 이용됨",
    choices: ["스팸", "피싱", "스푸핑", "스파이웨어"],
    correctChoice: "1",
    topic: "spamPhishing",
    tags: ["스팸"],
  },
  {
    year: 2015,
    number: 48,
    prompt: "서버의 침입 및 정보유출 단계에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "정보획득 단계 - 포트 스캔을 통해 시스템에 대한 정보를 획득",
      "권한획득 단계 - 최종적으로 관리자 권한을 획득함",
      "공격 단계 - 관리자 권한을 이용해서 침입흔적을 지움",
      "재침입 단계 - 백도어를 설치함",
    ],
    correctChoice: "4",
    topic: "serverIntrusion",
  },
  {
    year: 2015,
    number: 49,
    prompt: "다음 중 사람을 속여서 민감한 정보를 유출하게 하는 기술은?",
    choices: ["계정 크랙 공격", "레이스 컨디션 공격", "사회공학적인 공격", "기본 설정 오류를 이용한 공격"],
    correctChoice: "3",
    topic: "attackTypes",
    tags: ["사회공학"],
  },
  {
    year: 2015,
    number: 50,
    prompt: "다음 설명에 가장 부합하는 보안 시스템은?\n허가받지 않은 접근이나 해킹 시도를 감지하여 시스템 또는 망 관리자에게 통보해 주는 시스템",
    choices: ["침입탐지 시스템", "침입차단 시스템", "침입방지 시스템", "가상사설망"],
    correctChoice: "1",
    topic: "ids",
  },
  {
    year: 2015,
    number: 51,
    prompt: "다음 설명에 해당하는 방화벽의 구성방식은?\n- OSI 7계층 중 7계층인 응용 계층에서 방화벽 기능을 수행\n- 각 서비스 별로 프락시 서버(proxy server)가 존재할 수 있음\n- 응용 계층에서 처리하므로 속도가 떨어질 수 있음",
    choices: ["애플리케이션 게이트웨이", "서킷 게이트웨이", "패킷 필터링", "하이브리드 방식"],
    correctChoice: "1",
    topic: "firewall",
    tags: ["애플리케이션 게이트웨이"],
  },
  {
    year: 2015,
    number: 52,
    prompt: "다음 설명에 해당하는 방화벽의 형태는?\n스크리닝 라우터와 베스천 호스트 혹은 듀얼 홈 호스트가 결합된 시스템으로, 트래픽을 2단으로 방어하여 안정성이 우수함",
    choices: ["스크리닝 라우터", "듀얼 홈 호스트", "스크린 호스트 게이트웨이", "스크린 서브넷 게이트웨이"],
    correctChoice: "3",
    topic: "firewall",
    tags: ["스크린 호스트 게이트웨이"],
  },
  {
    year: 2015,
    number: 53,
    prompt: "침입탐지 시스템의 구성과 설명이 잘못 짝지어진 것은?",
    choices: ["모니터링부 - 정보수집", "분석 및 조치부 - 정보가공 및 축약", "분석 및 조치부 - 분석 및 침입탐지", "관리부 - 보고 및 조치"],
    correctChoice: "4",
    topic: "ids",
    tags: ["IDS 구성"],
  },
  {
    year: 2015,
    number: 54,
    prompt: "다음 설명에 해당하는 분석 방법은?\n- 알려진 공격이나 시스템 오용과 관련된 것을 규정한 패턴과의 일치 여부 확인\n- 정의된 패턴에 해당되지 않는 공격은 대처 불가",
    choices: ["통계적 분석", "시그니처 분석", "무결성 분석", "임의적 분석"],
    correctChoice: "2",
    topic: "ids",
    tags: ["시그니처 분석"],
  },
  {
    year: 2015,
    number: 55,
    prompt: "침입방지 시스템에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "감지된 행위에 대해 자동으로 대응 작업을 수행",
      "침입탐지 시스템과는 대비되어 능동적으로 동작",
      "호스트 기반 침입방지 시스템은 보통 하드웨어 제품임",
      "네트워크 기반 침입방지 시스템은 초고속 환경에서 적용 가능하도록 성능개선 중임",
    ],
    correctChoice: "3",
    topic: "ids",
    tags: ["IPS"],
  },
  {
    year: 2015,
    number: 56,
    prompt: "가상사설망(VPN)에 대한 설명으로 틀린 것은?",
    choices: ["공중망을 이용하여 사설망처럼 직접 운용 관리하는 것", "높은 비용으로 성능향상 제공", "기밀정보의 안전한 전송을 보장", "서비스 품질(QoS) 제공"],
    correctChoice: "2",
    topic: "vpn",
  },
  {
    year: 2015,
    number: 57,
    prompt: "공중망을 통하여 기업 내 본사 네트워크와 원격지의 공장 혹은 지점의 네트워크 사이만 연결한 VPN은?",
    choices: ["익스트라넷 VPN", "원격접속 VPN", "인트라넷 VPN", "복합형 VPN"],
    correctChoice: "3",
    topic: "vpn",
    tags: ["인트라넷 VPN"],
  },
  {
    year: 2015,
    number: 58,
    prompt: "다음은 범죄 현장에서 발견한 것들이다. 이 중 디지털 포렌식과 가장 관련된 것은?",
    choices: ["명함집", "내비게이션", "운동화", "목걸이"],
    correctChoice: "2",
    topic: "forensics",
  },
  {
    year: 2015,
    number: 59,
    prompt: "디지털 포렌식 절차는 사전준비부터 보고서 작성까지 총 여섯 단계이다. 그 사이 네 단계의 순서가 가장 바르게 나열된 것은?",
    choices: [
      "포장 및 이송 → 증거수집 → 조사분석 → 정밀검토",
      "증거수집 → 포장 및 이송 → 조사분석 → 정밀검토",
      "증거수집 → 정밀검토 → 조사분석 → 포장 및 이송",
      "조사분석 → 포장 및 이송 → 정밀검토 → 증거수집",
    ],
    correctChoice: "2",
    topic: "forensics",
    tags: ["절차"],
  },
  {
    year: 2015,
    number: 60,
    prompt: "파일 시스템, 파일 내부의 메타데이터 등 다양한 곳에 저장되어 있는 시간 정보를 이용하여 시스템 사용자의 행위를 추적하는 것은?",
    choices: ["타임라인 분석", "디스크 브라우징", "데이터 뷰잉", "파일 복구"],
    correctChoice: "1",
    topic: "forensics",
    tags: ["타임라인 분석"],
  },
  {
    year: 2016,
    number: 36,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 분산 서비스 거부 공격(DDoS)\n\n악성 코드와 거리가 먼 것은?",
    choices: ["가", "나", "라", "마"],
    correctChoice: "4",
    topic: "malware",
  },
  {
    year: 2016,
    number: 37,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 분산 서비스 거부 공격(DDoS)\n\n시스템이나 사용자의 파일에 자신을 복제하고 그 컴퓨터 시스템 내에서 증식하거나 시스템을 파괴하는 악성코드는?",
    choices: ["가", "나", "라", "바"],
    correctChoice: "3",
    topic: "malware",
    tags: ["바이러스"],
  },
  {
    year: 2016,
    number: 38,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 분산 서비스 거부 공격(DDoS)\n\n공격자가 공격자의 제어 하에 있는 호스트를 피해 호스트가 신뢰하는 호스트로 가장함으로써 피해 호스트로부터 생성되는 정보를 수집하거나 가로채는 방식의 공격은?",
    choices: ["나", "다", "마", "바"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["스푸핑"],
  },
  {
    year: 2016,
    number: 39,
    prompt: "다음 보기 중에서 고르시오.\n가. 웜(Worm)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 바이러스(Virus)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n아. 분산 서비스 거부 공격(DDoS)\n\n괄호 안에 들어갈 사이버 공격 방식은?\n(    )은 여러 대의 공격자를 분산적으로 배치해 동시에 특정 서비스나 자원의 가용성을 떨어트리는 결과를 초래하는 유형의 공격 방식임",
    choices: ["가", "바", "사", "아"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["DDoS"],
  },
  {
    year: 2016,
    number: 40,
    prompt: "에이전트와 공격자간의 통신에 암호화 및 터널링 기법을 적용하여 탐지하기 어렵게 하는 최근의 사이버 공격 방식의 특징은?",
    choices: ["에이전트화", "분산화", "자동화", "은닉화"],
    correctChoice: "4",
    topic: "cyberAttackEvolution",
    tags: ["은닉화"],
  },
  {
    year: 2016,
    number: 41,
    prompt: "IPv4 구조의 주소가 다음과 같을 때 이 주소가 속하는 클래스는?\n121.46.136.13\n(이진수 표현: 01111001.00101110.10001000.00001101)",
    choices: ["Class A", "Class B", "Class C", "Class D"],
    correctChoice: "1",
    topic: "ipAddressing",
    tags: ["IPv4 클래스"],
  },
  {
    year: 2016,
    number: 42,
    prompt: "네트워크 보안의 목표와 거리가 먼 것은?",
    choices: ["기밀성", "무결성", "유일성", "가용성"],
    correctChoice: "3",
    topic: "networkSecurity",
  },
  {
    year: 2016,
    number: 43,
    prompt: "SSL 3.0을 기반으로 한 업그레이드 프로토콜로 트랜스포트 계층에 적용하는 보안 프로토콜은?",
    choices: ["TCP", "TLS", "UDP", "ICMP"],
    correctChoice: "2",
    topic: "networkSecurity",
    tags: ["TLS", "SSL"],
  },
  {
    year: 2016,
    number: 44,
    prompt: "전자우편 보안도구인 PGP의 송신측 전송 과정이 가장 바르게 나열된 것은?",
    choices: [
      "암호화 → 압축 → 서명 → 기수 64 변환",
      "서명 → 압축 → 암호화 → 기수 64 변환",
      "기수 64 변환 → 암호화 → 압축 → 서명",
      "기수 64 변환 → 서명 → 압축 → 암호화",
    ],
    correctChoice: "2",
    topic: "emailSecurity",
    tags: ["PGP 전송 과정"],
  },
  {
    year: 2016,
    number: 45,
    prompt: "기수 64(Radix-64)는 데이터를 6비트 단위로 나눠서 각각을 하나의 문자로 표현하는 방법이다. 만약 12바이트의 데이터에 기수 64를 적용한다면 몇 개의 문자로 변환되는가? (단, 마지막 패드 문자는 고려하지 않는다고 가정)",
    choices: ["16", "12", "9", "6"],
    correctChoice: "1",
    topic: "emailSecurity",
    tags: ["Radix-64", "계산"],
  },
  {
    year: 2016,
    number: 46,
    prompt: "S/MIME에 대한 설명으로 바른 것은?",
    choices: [
      "인터넷 전자우편 표준에서 보안기능을 제거함",
      "메시지 암호화는 공개키 방식, 세션키 분배는 대칭키 방식을 이용함",
      "클리어 서명 데이터는 전자서명만 base64로 부호화",
      "암호화된 데이터는 서명될 수 있으나 서명된 데이터는 암호화될 수 없음",
    ],
    correctChoice: "3",
    topic: "emailSecurity",
    tags: ["S/MIME"],
  },
  {
    year: 2016,
    number: 47,
    prompt: "PC 보안 대책으로 부적절한 것은?",
    choices: ["시스템 자원에 대한 주기적 백업을 실시", "파일 공유 프로그램을 적극 활용", "공유 폴더는 읽기 권한으로 설정", "Administrator 계정의 패스워드는 반드시 설정"],
    correctChoice: "2",
    topic: "pcSecurity",
  },
  {
    year: 2016,
    number: 48,
    prompt: "서버의 침입 및 정보유출 단계에 대한 설명으로 바른 것은?",
    choices: [
      "정보획득 단계 - 서버를 통해 다른 시스템을 공격함",
      "권한획득 단계 - 최종적으로 일반 사용자 권한을 획득함",
      "공격 단계 - 관리자 권한을 이용해서 침입흔적을 지움",
      "재침입 단계 - 백도어를 설치함",
    ],
    correctChoice: "3",
    topic: "serverIntrusion",
  },
  {
    year: 2016,
    number: 49,
    prompt: "다음 중 설명이 바르지 않은 것은?",
    choices: [
      "무차별 공격 - 사전파일의 단어를 대입하여 공격",
      "네트워크 공격 - 스푸핑, 스니핑 등이 해당됨",
      "버퍼 오버플로우 공격 - 시스템 오류를 이용한 공격",
      "사회공학적인 공격 - 사람을 속여서 민감한 정보를 유출",
    ],
    correctChoice: "1",
    topic: "attackTypes",
  },
  {
    year: 2016,
    number: 50,
    prompt: "시스템 접근제어 기술에 대한 설명으로 올바른 것은?",
    choices: [
      "강제적 접근제어 - 역할에 따른 접근권한을 부여",
      "임의적 접근제어 - 객체에 포함된 정보의 비밀성과 이에 대해 주체가 갖는 정형화된 권한에 근거하여 접근권한을 부여",
      "역할기반 보안정책 - 객체 소유자의 자율적 판단에 따라 다른 사용자에게 접근권한을 부여",
      "다단계 접근제어 - 객체와 사용자에게 보안 등급을 부여하여 기본적으로 사용자는 자신의 보안 등급보다 높은 보안 등급을 갖는 객체에 대한 접근이 제한됨",
    ],
    correctChoice: "4",
    topic: "accessControl",
    tags: ["다단계 접근제어"],
  },
  {
    year: 2016,
    number: 51,
    prompt: "다음 설명에 가장 부합하는 보안 시스템은?\n- 허가받지 않은 접근이나 해킹 시도를 감지하여 자동으로 대응 작업을 수행하여 행위를 중지시키는 시스템",
    choices: ["침입탐지 시스템(IDS)", "침입차단 시스템(Firewall)", "침입방지 시스템(IPS)", "가상사설망(VPN)"],
    correctChoice: "3",
    topic: "ids",
    tags: ["IPS"],
  },
  {
    year: 2016,
    number: 52,
    prompt: "다음 중 방화벽의 구성방식과 거리가 먼 것은?",
    choices: ["애플리케이션 게이트웨이", "서킷 게이트웨이", "패킷 필터링", "아날로그 방식"],
    correctChoice: "4",
    topic: "firewall",
  },
  {
    year: 2016,
    number: 53,
    prompt: "다음 방화벽의 형태 중 라우터를 이용하지 않는 것은?",
    choices: ["스크리닝 라우터", "듀얼 홈 호스트", "스크린 호스트 게이트웨이", "스크린 서브넷 게이트웨이"],
    correctChoice: "2",
    topic: "firewall",
    tags: ["듀얼 홈 호스트"],
  },
  {
    year: 2016,
    number: 54,
    prompt: "침입탐지 시스템의 구성과 설명이 바르게 짝지어진 것은?",
    choices: ["모니터링부 - 정보가공 및 축약", "분석 및 조치부 - 분석 및 침입탐지", "관리부 - 보고 및 조치", "모니터링부 - 통제 및 관리, 보안정책 제공"],
    correctChoice: "2",
    topic: "ids",
    tags: ["IDS 구성"],
  },
  {
    year: 2016,
    number: 55,
    prompt: "다음 설명에 해당하는 분석 방법은?\n- 파일이나 객체의 어떤 측면이 변경되었는지에 초점\n- 해시 알고리즘 같은 강력한 암호 메커니즘 사용",
    choices: ["통계적 분석", "시그니처 분석", "무결성 분석", "임의적 분석"],
    correctChoice: "3",
    topic: "ids",
    tags: ["무결성 분석"],
  },
  {
    year: 2016,
    number: 56,
    prompt: "가상사설망(VPN)에 대한 설명으로 틀린 것은?",
    choices: ["공중망을 이용하여 사설망처럼 직접 운용 관리하는 것", "저렴한 비용으로 성능향상 제공", "방화벽 기반 VPN이 라우터 기반 VPN보다 보안성은 낮지만 성능이 좋음", "서비스 품질(QoS) 제공"],
    correctChoice: "3",
    topic: "vpn",
  },
  {
    year: 2016,
    number: 57,
    prompt: "공중망을 통하여 기업과 전략적인 업무파트너 기업 사이만 연결한 VPN은?",
    choices: ["익스트라넷 VPN", "원격접속 VPN", "인트라넷 VPN", "복합형 VPN"],
    correctChoice: "1",
    topic: "vpn",
    tags: ["익스트라넷 VPN"],
  },
  {
    year: 2016,
    number: 58,
    prompt: "다음은 범죄 현장에서 발견한 것들이다. 이 중 디지털 포렌식과 가장 거리가 먼 것은?",
    choices: ["전자책", "레코드판", "블랙박스", "스마트시계"],
    correctChoice: "2",
    topic: "forensics",
  },
  {
    year: 2016,
    number: 59,
    prompt: "디지털 포렌식 절차가 가장 바르게 나열된 것은?",
    choices: [
      "사전준비 → 증거수집 → 포장 및 이송 → 조사분석 → 정밀검토 → 보고서 작성",
      "포장 및 이송 → 사전준비 → 증거수집 → 조사분석 → 정밀검토 → 보고서 작성",
      "사전준비 → 증거수집 → 정밀검토 → 조사분석 → 보고서 작성 → 포장 및 이송",
      "사전준비 → 조사분석 → 포장 및 이송 → 정밀검토 → 증거수집 → 보고서 작성",
    ],
    correctChoice: "1",
    topic: "forensics",
    tags: ["절차"],
  },
  {
    year: 2016,
    number: 60,
    prompt: "디지털 증거의 특성과 거리가 먼 것은?",
    choices: ["가시성", "휘발성", "복제 용이성", "초국경성"],
    correctChoice: "1",
    topic: "forensics",
  },
  {
    year: 2017,
    number: 36,
    prompt: "다음 중 정보보호의 핵심목표(CIA triad)에 포함되지 않는 것은?",
    choices: ["기밀성(confidentiality)", "무결성(integrity)", "가용성(availability)", "접근제어(access control)"],
    correctChoice: "4",
    topic: "cia",
    tags: ["CIA", "예외"],
  },
  {
    year: 2017,
    number: 37,
    prompt: "다음 중 허락된 자가 정보에 접근하고자 할 때 이것이 방해 받지 않도록 하는 정보보호의 목표는?",
    choices: ["기밀성(confidentiality)", "무결성(integrity)", "가용성(availability)", "접근제어(access control)"],
    correctChoice: "3",
    topic: "cia",
  },
  {
    year: 2017,
    number: 38,
    prompt: "암호와 관련된 설명으로 바른 것은?",
    choices: [
      "두 사람이 안전하지 않은 채널을 통해 정보를 주고받더라도 제3자는 이 정보의 내용을 알 수 없도록 하는 것",
      "평문이란 코드화된 메시지를 의미함",
      "평문을 암호문으로 변환하는 과정을 복호화라 함",
      "키는 암호화에는 중요하지만 복호화에는 중요하지 않음",
    ],
    correctChoice: "1",
    topic: "cryptoBasics",
  },
  {
    year: 2017,
    number: 39,
    prompt: "스파르타의 봉 암호로 평문 '12345678'을 암호화할 때 만들어질 수 없는 암호문은?",
    choices: ["13572468", "12348765", "14725836", "15263748"],
    correctChoice: "2",
    topic: "transposition",
    tags: ["스파르타 봉", "계산"],
  },
  {
    year: 2017,
    number: 40,
    prompt: "다음 중 대칭키 암호 알고리즘은?",
    choices: ["RSA", "AES", "ECC", "ElGamal"],
    correctChoice: "2",
    topic: "symmetricCrypto",
  },
  {
    year: 2017,
    number: 41,
    prompt: "다음 중 공개키 암호에 대한 설명으로 바른 것은?",
    choices: [
      "암호화와 복호화에 하나의 같은 키를 사용함",
      "대칭키 암호에 비해 속도가 빠름",
      "누구나 공개키를 이용하여 암호화를 할 수 있음",
      "블록 암호와 스트림 암호로 나누어짐",
    ],
    correctChoice: "3",
    topic: "publicKeyCrypto",
  },
  {
    year: 2017,
    number: 42,
    prompt: "다음 중 메시지 인증에 대한 설명으로 잘못된 것은?",
    choices: [
      "메시지의 내용이 전송 도중 불법적으로 변경되지 않고 정확하고 완전하게 수신되었는지 확인하는 것",
      "메시지에 대한 무결성을 확인",
      "HMAC은 공개키 암호에 기반을 둠",
      "CMAC은 블록 암호에 기반을 둠",
    ],
    correctChoice: "3",
    topic: "messageAuth",
  },
  {
    year: 2017,
    number: 43,
    prompt: "지문, 홍채, 음성 등 개개인의 고유한 정보를 이용하는 사용자 인증 방식은?",
    choices: ["비밀번호 방식", "생체인식 방식", "토큰 방식", "2단계 인증"],
    correctChoice: "2",
    topic: "userAuth",
  },
  {
    year: 2017,
    number: 44,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 랜섬웨어(Ransomware)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n\n공격자가 시스템에 침입한 후 이후에도 손쉽게 피해 시스템에 대한 접근권한을 획득하기 위한 용도로 설치하는 악성코드는?",
    choices: ["가", "다", "라", "마"],
    correctChoice: "2",
    topic: "malware",
    tags: ["백도어"],
  },
  {
    year: 2017,
    number: 45,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 랜섬웨어(Ransomware)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n\n사용자의 중요한 정보를 인질로 삼아 금전을 요구하는 악성코드는?",
    choices: ["가", "다", "라", "바"],
    correctChoice: "3",
    topic: "malware",
    tags: ["랜섬웨어"],
  },
  {
    year: 2017,
    number: 46,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 트로이 목마(Trojan Horse)\n다. 백도어(Backdoor)\n라. 랜섬웨어(Ransomware)\n마. 스캐닝(Scanning)\n바. 스푸핑(Spoofing)\n사. 스니핑(Sniffing)\n\n네트워크상의 데이터를 도청하는 행위를 일컫는 사이버 공격 방식은?",
    choices: ["가", "나", "라", "사"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["스니핑"],
  },
  {
    year: 2017,
    number: 47,
    prompt: "과도한 데이터를 입력하여 프로그램의 복귀주소를 조작함으로써 공격자가 원하는 코드를 실행하는 공격은?",
    choices: ["버퍼 오버플로 공격", "사전 공격", "사회공학적인 공격", "스푸핑"],
    correctChoice: "1",
    topic: "attackTypes",
  },
  {
    year: 2017,
    number: 48,
    prompt: "네트워크 보안에서 공격의 방식과 그에 대한 설명이 잘못 짝지어진 것은?",
    choices: [
      "능동적 공격 - 암호화로 방어",
      "수동적 공격 - 통신 회선상의 데이터를 암호화하여 방어",
      "능동적 공격 - 통신 회선상의 정보를 변조, 위조하는 행위",
      "수동적 공격 - 수신 측에서 데이터에 대한 무결성을 확인하여 방어",
    ],
    correctChoice: "4",
    topic: "networkSecurity",
  },
  {
    year: 2017,
    number: 49,
    prompt: "네트워크 보안의 목표와 거리가 먼 것은?",
    choices: ["기밀성", "가용성", "부인방지", "다양성"],
    correctChoice: "4",
    topic: "networkSecurity",
  },
  {
    year: 2017,
    number: 50,
    prompt: "다음 설명에 가장 부합하는 보안 시스템은?\n- 외부 네트워크와 내부 네트워크 사이에 위치시켜 두 네트워크 사이를 오가는 트래픽의 종류와 양을 제어\n- 정상적인 사용자에 대해서만 접근을 가능하게 해주고 불법적이고 인증되지 않은 사용자의 접근을 차단시키는 시스템",
    choices: ["침입차단 시스템(방화벽)", "침입탐지 시스템(IDS)", "침입방지 시스템(IPS)", "가상사설망(VPN)"],
    correctChoice: "1",
    topic: "firewall",
  },
  {
    year: 2017,
    number: 51,
    prompt: "침입차단 시스템의 구축 형태 중 중립적인 네트워크인 비무장지대(DMZ)를 구축하는 것은?",
    choices: ["스크리닝 라우터", "베스천 호스트", "스크린 호스트 게이트웨이", "스크린 서브넷 게이트웨이"],
    correctChoice: "4",
    topic: "firewall",
    tags: ["DMZ"],
  },
  {
    year: 2017,
    number: 52,
    prompt: "다음 설명에 해당하는 분석 방법은?\n- 지금까지 알려지지 않은 공격을 검출할 수 있음\n- 잘못된 경고 신호를 보낼 가능성이 높음",
    choices: ["통계적 분석", "시그니처 분석", "무결성 분석", "임의적 분석"],
    correctChoice: "1",
    topic: "ids",
  },
  {
    year: 2017,
    number: 53,
    prompt: "다음 설명에 해당하는 가상사설망의 기반 기술은?\n- 특정 사용자들 간에 전용망처럼 사용할 수 있게 하는 것\n- 인터넷 상의 가상정보 흐름 통로를 이용",
    choices: ["터널링 기술", "키 관리 기술", "VPN 관리 기술", "멀티캐스트 기술"],
    correctChoice: "1",
    topic: "vpn",
  },
  {
    year: 2017,
    number: 54,
    prompt: "PGP에서 사용되는 키의 종류가 아닌 것은?",
    choices: ["세션키", "공개키", "개인키", "평문구문"],
    correctChoice: "4",
    topic: "emailSecurity",
  },
  {
    year: 2017,
    number: 55,
    prompt: "S/MIME의 보안 서비스와 알고리즘이 잘못 짝지어진 것은?",
    choices: ["메시지 암호화 - RSA", "전자서명 - RSA", "세션키 분배 - RSA", "해시함수 - SHA-256"],
    correctChoice: "1",
    topic: "emailSecurity",
  },
  {
    year: 2017,
    number: 56,
    prompt: "메일이나 웹페이지에 추가적인 악성 스크립트를 포함시켜 웹 클라이언트가 이를 열면 자동으로 악성 스크립트가 실행되게 하는 공격은?",
    choices: ["SQL injection", "크로스 사이트 스크립팅(XSS)", "접근제어 실패", "웹 서버 공격"],
    correctChoice: "2",
    topic: "webSecurity",
    tags: ["XSS"],
  },
  {
    year: 2017,
    number: 57,
    prompt: "접근제어에 대한 공격을 방어하는 방법으로 가장 올바른 것은?",
    choices: ["관리자 페이지에 대한 링크를 만들지 않음", "관리자 페이지 자체에 접근권한을 설정", "URL에 사용자 ID를 포함", "디렉터리 목록 보여주는 기능 활성화"],
    correctChoice: "2",
    topic: "webSecurity",
    tags: ["접근제어"],
  },
  {
    year: 2017,
    number: 58,
    prompt: "무선 LAN 환경에서 기밀성을 제공하기 위한 알고리즘이지만 현재는 취약성이 드러나 사용하지 않는 것은?",
    choices: ["WEP", "RSN", "EAP", "WPA2"],
    correctChoice: "1",
    topic: "wirelessSecurity",
  },
  {
    year: 2017,
    number: 59,
    prompt: "다음 중 디지털 증거를 찾을 수 없는 것은?",
    choices: ["외장하드", "블랙박스", "진주목걸이", "스마트폰"],
    correctChoice: "3",
    topic: "forensics",
  },
  {
    year: 2017,
    number: 60,
    prompt: "다음 중 디지털 증거의 특성으로 바른 것은?",
    choices: ["가시성", "소규모성", "휘발성", "지역성"],
    correctChoice: "3",
    topic: "forensics",
  },
  {
    year: 2018,
    number: 36,
    prompt: "다음 중 정보보호의 핵심목표(CIA triad)에 포함되는 것은?",
    choices: ["인증(authentication)", "가용성(availability)", "부인방지(non-repudiation)", "접근제어(access control)"],
    correctChoice: "2",
    topic: "cia",
  },
  {
    year: 2018,
    number: 37,
    prompt: "다음 중 허락되지 않은 자가 정보를 함부로 수정할 수 없도록 하는 것을 의미하는 정보보호의 목표는?",
    choices: ["부인방지(non-repudiation)", "무결성(integrity)", "가용성(availability)", "기밀성(confidentiality)"],
    correctChoice: "2",
    topic: "cia",
  },
  {
    year: 2018,
    number: 38,
    prompt: "암호는 정보보호의 목표 중 무엇을 보장하기 위한 필수적인 기술인가?",
    choices: ["기밀성(confidentiality)", "가용성(availability)", "부인방지(non-repudiation)", "접근제어(access control)"],
    correctChoice: "1",
    topic: "cryptoBasics",
  },
  {
    year: 2018,
    number: 39,
    prompt: "다음 중 전치법에 대한 설명으로 바른 것은?",
    choices: [
      "평문의 문자들을 다른 문자로 치환함으로써 암호화함",
      "대표적인 전치법으로 시저 암호가 있음",
      "스파르타의 봉 암호는 봉의 굵기가 키임",
      "시프트 암호는 시저 암호를 일반화함",
    ],
    correctChoice: "3",
    topic: "transposition",
  },
  {
    year: 2018,
    number: 40,
    prompt: "다음 암호에 대한 설명 중 틀린 것은?",
    choices: [
      "대칭키 암호는 암호화와 복호화에 하나의 같은 키를 사용함",
      "공개키 암호는 암호화와 복호화에 서로 다른 키를 사용함",
      "대칭키 암호는 암호화와 복호화 속도가 빠름",
      "공개키 암호는 키 분배의 문제가 있음",
    ],
    correctChoice: "4",
    topic: "publicKeyCrypto",
  },
  {
    year: 2018,
    number: 41,
    prompt: "다음 중 공개키 암호 알고리즘은?",
    choices: ["DES", "IDEA", "RSA", "AES"],
    correctChoice: "3",
    topic: "publicKeyCrypto",
  },
  {
    year: 2018,
    number: 42,
    prompt: "비밀번호 방식의 사용자 인증을 이용하는 경우, 시스템에 저장된 비밀번호가 유출될 경우를 대비하여 비밀번호 대신 무엇을 시스템에 저장하는가?",
    choices: ["개인키", "공개키", "해시함수", "해시코드"],
    correctChoice: "4",
    topic: "userAuth",
  },
  {
    year: 2018,
    number: 43,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n\n네트워크를 통해 스스로 감염되며 숙주가 필요 없는 악성코드는?",
    choices: ["가", "나", "다", "라"],
    correctChoice: "2",
    topic: "malware",
    tags: ["웜"],
  },
  {
    year: 2018,
    number: 44,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n\n정상적인 기능을 하는 프로그램으로 가장하여 프로그램 내에 숨어서 의도하지 않은 기능을 수행하는 악성코드는?",
    choices: ["다", "라", "마", "바"],
    correctChoice: "1",
    topic: "malware",
    tags: ["트로이 목마"],
  },
  {
    year: 2018,
    number: 45,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n\n공격대상 호스트들이나 네트워크에 대한 취약점을 발견하기 위한 사전 정보수집 활동은?",
    choices: ["마", "바", "사", "아"],
    correctChoice: "2",
    topic: "attackTypes",
    tags: ["스캐닝"],
  },
  {
    year: 2018,
    number: 46,
    prompt: "서버의 침입 및 정보유출 단계에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "정보획득 단계 - 공격대상 시스템에 대한 정보를 획득",
      "권한획득 단계 - 최종적으로 관리자 권한을 획득함",
      "공격 단계 - 관리자 권한을 이용해서 침입흔적을 지움",
      "재침입 단계 - 백도어를 설치함",
    ],
    correctChoice: "4",
    topic: "serverIntrusion",
  },
  {
    year: 2018,
    number: 47,
    prompt: "사람을 속여서 민감한 정보를 유출하게 하는 공격은?",
    choices: ["버퍼 오버플로 공격", "사전 공격", "사회공학적인 공격", "레이스 컨디션 공격"],
    correctChoice: "3",
    topic: "attackTypes",
  },
  {
    year: 2018,
    number: 48,
    prompt: "강력한 로그인, 감시 기능이 있으며 프락시 서버를 활용하여 확장성이 우수하지만 속도가 빠르지 않은 방화벽의 구성 방식은?",
    choices: ["패킷 필터링", "서킷 게이트웨이", "애플리케이션 게이트웨이", "하이브리드 방식"],
    correctChoice: "3",
    topic: "firewall",
  },
  {
    year: 2018,
    number: 49,
    prompt: "침입탐지 시스템의 구성과 설명이 바르게 짝지어지지 않은 것은?",
    choices: [
      "모니터링부 - 정보수집",
      "분석 및 조치부 - 분석 및 침입탐지",
      "관리부 - 보고 및 조치",
      "관리부 - 통제 및 관리, 보안정책 제공",
    ],
    correctChoice: "3",
    topic: "ids",
  },
  {
    year: 2018,
    number: 50,
    prompt: "다음 설명에 해당하는 분석 방법은?\n- 알려진 공격에 대한 패턴을 활용하여 침입을 탐지\n- 패턴에 해당하지 않는 공격은 대처 불가",
    choices: ["통계적 분석", "시그니처 분석", "무결성 분석", "임의적 분석"],
    correctChoice: "2",
    topic: "ids",
  },
  {
    year: 2018,
    number: 51,
    prompt: "가상사설망(VPN)에 대한 설명으로 가장 바른 것은?",
    choices: [
      "공중망을 이용하여 사설망처럼 직접 운용 관리하는 것",
      "높은 비용으로 성능향상 제공",
      "방화벽 기반 VPN이 라우터 기반 VPN보다 보안성은 낮지만 성능이 좋음",
      "서비스 품질(QoS)은 제공하지 못함",
    ],
    correctChoice: "1",
    topic: "vpn",
  },
  {
    year: 2018,
    number: 52,
    prompt: "PGP 보안 서비스와 사용되는 알고리즘이 바르게 짝지어진 것은?",
    choices: ["인증 - RSA, SHA", "기밀성 - DES, ECC", "압축 - AES", "전자우편 호환성 - 유니코드 변환"],
    correctChoice: "1",
    topic: "emailSecurity",
  },
  {
    year: 2018,
    number: 53,
    prompt: "기수 64(Radix-64)는 데이터를 6비트 단위로 나눠서 각 6비트를 하나의 문자로 표현하는 방법이다. 만약 6바이트의 데이터에 기수 64를 적용한다면 몇 개의 문자로 변환되는가? (단, 마지막 패드 문자는 고려하지 않는다고 가정)",
    choices: ["1", "3", "6", "8"],
    correctChoice: "4",
    topic: "emailSecurity",
    tags: ["Radix-64", "계산"],
  },
  {
    year: 2018,
    number: 54,
    prompt: "S/MIME의 메시지 구성에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "봉인된 데이터 - 암호화된 콘텐츠 타입과 수신자를 위한 복호화된 콘텐츠 암호키로 구성",
      "서명된 데이터 - 콘텐츠와 전자서명을 base64로 부호화",
      "클리어 서명 데이터 - 전자서명만 base64로 부호화",
      "서명 및 봉인된 데이터 - 암호화된 데이터는 서명될 수 있고 서명된 데이터나 클리어 서명 데이터는 암호화될 수 있음",
    ],
    correctChoice: "1",
    topic: "emailSecurity",
  },
  {
    year: 2018,
    number: 55,
    prompt: "데이터베이스 쿼리에 추가적인 SQL을 삽입함으로써 악의적인 행위를 가능하게 하는 공격 방법은?",
    choices: ["SQL injection", "크로스 사이트 스크립팅(XSS)", "접근제어 실패", "웹 서버 공격"],
    correctChoice: "1",
    topic: "webSecurity",
  },
  {
    year: 2018,
    number: 56,
    prompt: "공격자가 악성 스크립트를 특정 게시판에 등록하여 사용자가 해당 게시판에 접속하여 이 게시물을 열면 자동으로 악성 스크립트가 실행되게 하는 공격은?",
    choices: ["SQL injection", "저장된 크로스 사이트 스크립팅(XSS)", "반사된 크로스 사이트 스크립팅(XSS)", "접근제어 실패"],
    correctChoice: "2",
    topic: "webSecurity",
    tags: ["저장형 XSS"],
  },
  {
    year: 2018,
    number: 57,
    prompt: "임시 키 무결성 프로토콜로 WEP로 구현된 하드웨어의 펌웨어 업데이트를 위해 사용되는 것은?",
    choices: ["WEP", "TKIP", "WPA", "WPA2"],
    correctChoice: "2",
    topic: "wirelessSecurity",
    tags: ["TKIP"],
  },
  {
    year: 2018,
    number: 58,
    prompt: "디지털 포렌식 절차가 가장 바르게 나열된 것은?",
    choices: [
      "사전준비 → 조사분석 → 포장 및 이송 → 정밀검토 → 증거수집 → 보고서 작성",
      "사전준비 → 증거수집 → 조사분석 → 정밀검토 → 보고서 작성 → 포장 및 이송",
      "포장 및 이송 → 사전준비 → 증거수집 → 조사분석 → 정밀검토 → 보고서 작성",
      "사전준비 → 증거수집 → 포장 및 이송 → 조사분석 → 정밀검토 → 보고서 작성",
    ],
    correctChoice: "4",
    topic: "forensics",
    tags: ["절차"],
  },
  {
    year: 2018,
    number: 59,
    prompt: "다음 중 디지털 증거의 특성으로 바른 것은?",
    choices: ["지역성", "영구성", "대규모성", "가시성"],
    correctChoice: "3",
    topic: "forensics",
  },
  {
    year: 2018,
    number: 60,
    prompt: "디지털 포렌식 절차 중 지켜져야 할 사항으로 바르지 않은 것은?",
    choices: ["적법절차의 준수", "원본의 안전한 보존", "증거의 무결성 확보", "분석결과의 비반복성"],
    correctChoice: "4",
    topic: "forensics",
  },
  {
    year: 2019,
    number: 36,
    prompt: "정보보호에 대한 설명으로 바른 것은?",
    choices: [
      "정보를 여러 가지 위협으로부터 보호하기 위한 정책 및 기법",
      "정보의 상태는 전달 중인 경우만 고려",
      "위협의 종류에는 허락된 접근과 허락된 수정이 있음",
      "컴퓨터 보안보다 좁은 개념임",
    ],
    correctChoice: "1",
    topic: "infoProtection",
  },
  {
    year: 2019,
    number: 37,
    prompt: "다음 중 허락되지 않은 자가 정보의 내용을 알 수 없도록 하는 것을 의미하는 정보보호의 목표는?",
    choices: ["가용성(availability)", "기밀성(confidentiality)", "인증(authentication)", "무결성(integrity)"],
    correctChoice: "2",
    topic: "cia",
  },
  {
    year: 2019,
    number: 38,
    prompt: "정보를 보낸 사람이 나중에 정보를 보냈다는 것을 부인하지 못하도록 하는 것은?",
    choices: ["발신 부인방지", "수신 부인방지", "발신 접근제어", "수신 접근제어"],
    correctChoice: "1",
    topic: "cia",
    tags: ["부인방지"],
  },
  {
    year: 2019,
    number: 39,
    prompt: "암호와 관련된 용어 설명이 바른 것은?",
    choices: [
      "평문(plaintext) - 코드화된 메시지",
      "암호문(ciphertext) - 원래의 메시지",
      "복호화(decryption) - 암호문 → 다른 암호문",
      "암호화(encryption) - 평문 → 암호문",
    ],
    correctChoice: "4",
    topic: "cryptoBasics",
  },
  {
    year: 2019,
    number: 40,
    prompt: "다음 중 치환법에 대한 설명으로 바른 것은?",
    choices: [
      "평문에 있는 문자들의 순서를 바꿈으로써 암호화함",
      "대표적인 치환법으로 스파르타의 봉 암호가 있음",
      "시프트 암호는 스파르타의 봉 암호를 일반화함",
      "시프트 암호는 알파벳에 대해 26가지의 서로 다른 키 존재",
    ],
    correctChoice: "4",
    topic: "transposition",
  },
  {
    year: 2019,
    number: 41,
    prompt: "다음 중 대칭키 암호에 대한 설명으로 바른 것은?",
    choices: [
      "암호화와 복호화에 두 개의 서로 다른 키를 사용함",
      "공개키 암호에 비해 속도가 느림",
      "블록 암호와 스트림 암호로 나누어짐",
      "대표적인 알고리즘으로 RSA가 있음",
    ],
    correctChoice: "3",
    topic: "symmetricCrypto",
  },
  {
    year: 2019,
    number: 42,
    prompt: "다음 중 공개키 암호에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "공개키와 개인키를 사용",
      "누구나 공개키를 이용하여 암호화 가능",
      "오직 자신만 개인키를 이용하여 복호화 가능",
      "개인키로 암호화하면 개인키로 복호화 가능",
    ],
    correctChoice: "4",
    topic: "publicKeyCrypto",
  },
  {
    year: 2019,
    number: 43,
    prompt: "스마트카드 등 사용자가 소유하고 있는 특정한 정보를 이용하는 사용자 인증 방식은?",
    choices: ["비밀번호 방식", "생체인식 방식", "토큰 방식", "메시지 인증 방식"],
    correctChoice: "3",
    topic: "userAuth",
  },
  {
    year: 2019,
    number: 44,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n자. 서비스 거부(DoS) 공격\n차. 분산 서비스 거부(DDoS) 공격\n\n시스템이나 사용자의 파일에 자신을 복제하고 그 컴퓨터 시스템 내에서 증식하거나 시스템을 파괴하는 악성코드는?",
    choices: ["가", "나", "라", "아"],
    correctChoice: "1",
    topic: "malware",
    tags: ["바이러스"],
  },
  {
    year: 2019,
    number: 45,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n자. 서비스 거부(DoS) 공격\n차. 분산 서비스 거부(DDoS) 공격\n\n사용자의 문서 파일 등을 암호화한 후 암호를 풀기 위해서는 비트코인 등을 송금하도록 유도하는 악성코드는?",
    choices: ["나", "마", "바", "자"],
    correctChoice: "2",
    topic: "malware",
    tags: ["랜섬웨어"],
  },
  {
    year: 2019,
    number: 46,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n자. 서비스 거부(DoS) 공격\n차. 분산 서비스 거부(DDoS) 공격\n\n피해 호스트가 신뢰하는 호스트로 가장하여 정보를 수집하거나 가로채는 방식의 공격은?",
    choices: ["라", "마", "바", "사"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["스푸핑"],
  },
  {
    year: 2019,
    number: 47,
    prompt: "다음 보기 중에서 고르시오.\n가. 바이러스(Virus)\n나. 웜(Worm)\n다. 트로이 목마(Trojan Horse)\n라. 백도어(Backdoor)\n마. 랜섬웨어(Ransomware)\n바. 스캐닝(Scanning)\n사. 스푸핑(Spoofing)\n아. 스니핑(Sniffing)\n자. 서비스 거부(DoS) 공격\n차. 분산 서비스 거부(DDoS) 공격\n\n여러 대의 공격자를 분산적으로 배치해 동시에 대량의 데이터를 전송하여 특정 서비스나 자원의 가용성을 떨어뜨리는 결과를 초래하는 유형의 공격은?",
    choices: ["다", "사", "아", "차"],
    correctChoice: "4",
    topic: "attackTypes",
    tags: ["DDoS"],
  },
  {
    year: 2019,
    number: 48,
    prompt: "ID와 패스워드가 될 가능성이 있는 단어를 미리 모아두고 이 단어를 대입하며 계정을 크랙하는 공격은?",
    choices: ["무차별 공격", "사전 공격", "버퍼 오버플로 공격", "레이스 컨디션 공격"],
    correctChoice: "2",
    topic: "attackTypes",
    tags: ["계정 공격"],
  },
  {
    year: 2019,
    number: 49,
    prompt: "네트워크 보안 메커니즘의 하나로 IP 데이터그램의 무결성이나 기밀성을 보장할 수 있는 것은?",
    choices: ["IPsec", "SSL", "TLS", "MAC"],
    correctChoice: "1",
    topic: "networkSecurity",
    tags: ["IPsec"],
  },
  {
    year: 2019,
    number: 50,
    prompt: "침입탐지 시스템(IDS)의 분석 방법 설명이 바르게 짝지어진 것은?",
    choices: [
      "시그니처 분석 - 알려진 공격에 대한 패턴을 활용하여 침입을 탐지",
      "시그니처 분석 - 잘못된 경고 신호를 보낼 가능성이 높음",
      "통계적 분석 - 알려지지 않은 공격은 대처 불가",
      "무결성 분석 - 실시간 대응에 적합",
    ],
    correctChoice: "1",
    topic: "ids",
  },
  {
    year: 2019,
    number: 51,
    prompt: "다음 설명에 가장 부합하는 보안 시스템은?\n- 공중망을 이용하여 사설망처럼 직접 운용 관리하는 것\n- 중요한 기반 기술로 터널링 기술이 있음",
    choices: ["침입차단 시스템(방화벽)", "침입탐지 시스템(IDS)", "침입방지 시스템(IPS)", "가상사설망(VPN)"],
    correctChoice: "4",
    topic: "vpn",
  },
  {
    year: 2019,
    number: 52,
    prompt: "메일 보안에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "일반적인 메일은 송수신자 주소와 내용까지 노출됨",
      "일반적인 메일은 도청은 가능하지만 변조는 불가능",
      "메일 보안 기술로는 PGP, S/MIME이 있음",
      "PGP는 기밀성, 인증, 무결성 등을 지원",
    ],
    correctChoice: "2",
    topic: "emailSecurity",
  },
  {
    year: 2019,
    number: 53,
    prompt: "기수 64(Radix-64)는 데이터를 6비트 단위로 나눠서 각 6비트를 하나의 문자로 표현하는 방법이다. 만약 9바이트의 데이터에 기수 64를 적용한다면 몇 개의 문자로 변환되는가? (단, 마지막 패드 문자는 고려하지 않는다고 가정)",
    choices: ["9", "12", "36", "54"],
    correctChoice: "2",
    topic: "emailSecurity",
    tags: ["Radix-64", "계산"],
  },
  {
    year: 2019,
    number: 54,
    prompt: "S/MIME의 메시지 구성에 대한 설명으로 바른 것은?",
    choices: [
      "봉인된 데이터 - 암호화된 콘텐츠 타입과 수신자를 위한 복호화된 콘텐츠 암호키로 구성",
      "서명된 데이터 - 전자서명만 base64로 부호화",
      "클리어 서명 데이터 - 콘텐츠와 전자서명을 base64로 부호화",
      "서명 및 봉인된 데이터 - 암호화된 데이터는 서명될 수 있고 서명된 데이터나 클리어 서명 데이터는 암호화될 수 있음",
    ],
    correctChoice: "4",
    topic: "emailSecurity",
  },
  {
    year: 2019,
    number: 55,
    prompt: "웹 보안에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "다양한 공격으로부터 웹 서비스를 지키기 위한 것",
      "네트워크 부분은 SSL/TLS를 적용하여 해결 가능",
      "웹 클라이언트 부분은 백신으로만 해결 가능",
      "웹 서버 부분은 주기적인 취약점 점검 및 보안 패치 적용 필요",
    ],
    correctChoice: "3",
    topic: "webSecurity",
  },
  {
    year: 2019,
    number: 56,
    prompt: "URL에 사용자 ID를 포함하도록 웹 서비스를 구성한 경우 이를 통한 공격을 일으키는 위험 요소는?",
    choices: ["SQL injection", "크로스 사이트 스크립팅(XSS)", "접근제어 실패", "웹 클라이언트 공격"],
    correctChoice: "3",
    topic: "webSecurity",
    tags: ["접근제어"],
  },
  {
    year: 2019,
    number: 57,
    prompt: "IEEE 802.11i 표준인 RSN(Robust Security Network)의 프로토콜이 아닌 것은?",
    choices: ["TKIP", "CCMP", "WEP", "EAP"],
    correctChoice: "3",
    topic: "wirelessSecurity",
    tags: ["RSN"],
  },
  {
    year: 2019,
    number: 58,
    prompt: "다음은 범죄 현장에서 발견된 것들이다. 이 중 디지털 증거와 가장 거리가 먼 것은?",
    choices: ["USB 메모리", "종이사전", "디지털 액자", "블랙박스"],
    correctChoice: "2",
    topic: "forensics",
  },
  {
    year: 2019,
    number: 59,
    prompt: "다음 중 메모리나 네트워크 상에서만 일시적으로 존재하고 작업이 끝나거나 전원이 꺼지면 사라지는 디지털 증거의 특성은?",
    choices: ["비가시성", "변조 가능성", "휘발성", "초국경성"],
    correctChoice: "3",
    topic: "forensics",
  },
  {
    year: 2019,
    number: 60,
    prompt: "안티 포렌식에 대한 설명으로 바르지 않은 것은?",
    choices: [
      "포렌식 기술을 위해 증거물을 온전하게 남기려는 활동",
      "단순 포맷이 아닌 전문 제품으로 데이터를 완전 삭제",
      "메타 데이터를 변조하여 타임라인 분석 방어",
      "데이터를 암호화하여 증거로 사용되지 못하도록 방어",
    ],
    correctChoice: "1",
    topic: "antiForensics",
  },
];

function buildQuestion(question: RawQuestion): SecurityPastExamQuestion {
  const topic = securityPastExamTopics[question.topic];
  const embeddedChoices = extractEmbeddedChoiceMap(question.prompt);

  return {
    id: `security-${question.year}-${question.number}`,
    year: question.year,
    semester: "1",
    examName: `${question.year}학년도 1학기 기말시험`,
    number: question.number,
    prompt: question.prompt,
    choices: question.choices.map((text, index) => {
      const key = String(index + 1) as SecurityChoiceKey;
      const isCorrect = key === question.correctChoice;
      const expandedText = expandEmbeddedChoice(text, embeddedChoices);
      return {
        key,
        label: choiceLabels[key],
        text: expandedText,
        explanation: buildSecurityChoiceExplanation({
          choiceText: expandedText,
          isCorrect,
          questionPrompt: question.prompt,
          topicConcept: topic.concept,
          topicBasis: topic.basis,
          textbook: topic.textbook,
        }),
      };
    }),
    correctChoice: question.correctChoice,
    lectureRefs: [
      {
        lectureId: topic.lectureId,
        label: topic.lectureLabel,
        href: `/security/lecture/${topic.lectureId}`,
        concept: topic.concept,
      },
    ],
    conceptTags: Array.from(new Set([...(question.tags ?? []), ...topic.tags])).slice(0, 4),
    basis: topic.basis,
    examSkill: question.examSkill ?? topic.examSkill,
  };
}

export const securityPastExamQuestions = rawQuestions.map(buildQuestion);

export const securityPastExamTopicEntries = Object.entries(securityPastExamTopics).map(([key, value]) => ({
  key: key as TopicKey,
  ...value,
}));
