import type {
  NetworkAnswerKeySet,
  NetworkChoiceKey,
  NetworkExamCategory,
  NetworkExamPattern,
  NetworkFrequentConcept,
  NetworkLectureRef,
  NetworkPastExamChoice,
  NetworkPastExamYear,
  NetworkReconstructedQuestion,
} from "./types";

const choiceLabels: Record<NetworkChoiceKey, string> = {
  "1": "①",
  "2": "②",
  "3": "③",
  "4": "④",
};

function expandAnswerGroups(groups: string[]) {
  return groups.join("").split("") as NetworkChoiceKey[];
}

function yearsFromRefs(refs: string[]) {
  return Array.from(new Set(refs.map((ref) => Number(ref.slice(0, 4)) as NetworkPastExamYear))).sort(
    (a, b) => a - b,
  );
}

function lectureRef(lectureId: number, concept: string): NetworkLectureRef {
  return {
    lectureId,
    label: `${lectureId}강 ${concept}`,
    href: `/network/lecture/${lectureId}`,
    concept,
  };
}

function c(
  key: NetworkChoiceKey,
  text: string,
  verdict: "correct" | "wrong",
  reason: string,
  conceptBasis: string,
): NetworkPastExamChoice {
  return {
    key,
    label: choiceLabels[key],
    text,
    explanation: { verdict, reason, conceptBasis },
  };
}

export const networkPastExamYears = [2015, 2016, 2017, 2018, 2019] as const;

export const networkExamCategories: NetworkExamCategory[] = [
  "통신망 기초",
  "프로토콜·계층",
  "신호·전송",
  "오류·흐름 제어",
  "TCP/IP",
  "LAN",
  "보안",
];

function visual(
  file: string,
  width: number,
  height: number,
  sourceLabel: string,
  caption: string,
): NonNullable<NetworkExamPattern["visuals"]>[number] {
  return {
    src: `/network/frequent-concepts/figures/${file}`,
    alt: `${sourceLabel} 도식`,
    caption,
    sourceLabel,
    width,
    height,
  };
}

const networkConceptVisuals: Record<string, NonNullable<NetworkExamPattern["visuals"]>> = {
  "protocol-layering-basics": [
    visual(
      "osi-seven-layer-model.png",
      780,
      400,
      "교재 1강 OSI 모델",
      "OSI 모델은 물리 계층에서 응용 계층까지 통신 기능을 7계층으로 분해.",
    ),
  ],
  "signal-coding": [
    visual(
      "pcm-encoding-process.png",
      850,
      500,
      "교재 2강 PCM 부호화 과정",
      "PCM은 표본화, 양자화, 부호화 단계를 거쳐 아날로그 원신호를 디지털 부호로 변환.",
    ),
  ],
  "wireless-multidrop": [
    visual(
      "multidrop-line.png",
      790,
      490,
      "교재 3강 멀티드롭 선로",
      "여러 단말이 하나의 통신선로를 공유할 때 중앙 단말과 흐름 제어가 중요.",
    ),
  ],
  "switching-multiplexing-sync": [
    visual(
      "virtual-circuit-packet-switching.png",
      820,
      250,
      "교재 4강 가상회선 방식",
      "가상회선은 연결을 설정한 뒤 패킷을 논리 경로를 따라 순서대로 전달.",
    ),
  ],
  "error-detection-codes": [
    visual(
      "crc-polynomial-division.png",
      500,
      360,
      "교재 5강 CRC 계산",
      "CRC는 비트열을 다항식으로 보고 생성 다항식으로 나눈 나머지를 검사부호로 붙임.",
    ),
  ],
  "arq-error-control": [
    visual(
      "sliding-window-arq.png",
      820,
      310,
      "교재 5강 N-프레임 후퇴 ARQ",
      "Go-Back-N은 송신 윈도우에서 오류 프레임 이후를 되돌려 재전송.",
    ),
  ],
  "layering-encapsulation": [
    visual(
      "encapsulation-deencapsulation.png",
      810,
      370,
      "교재 7강 캡슐화와 역캡슐화",
      "송신 측은 계층을 내려가며 제어정보를 붙이고, 수신 측은 올라가며 제거.",
    ),
  ],
  "ip-helper-protocols": [
    visual(
      "ip-datagram-header.png",
      820,
      450,
      "교재 8강 IP 데이터그램 형식",
      "IP 헤더의 TTL, 프로토콜, 주소, 단편화 관련 필드를 위치로 함께 확인.",
    ),
  ],
  "tcp-udp-apps": [
    visual(
      "tcp-segment-header.png",
      820,
      460,
      "교재 9강 TCP 세그먼트 형식",
      "TCP 세그먼트는 포트, 순서번호, 응답번호, 제어비트, 윈도우, 체크섬 필드로 구성.",
    ),
  ],
  "lan-model-mac": [
    visual(
      "csmacd-flowchart.png",
      820,
      630,
      "교재 11장 CSMA/CD 동작 방식",
      "CSMA/CD는 회선 사용 감지, 전송, 충돌 감지, 대기 후 재시도를 순서도로 판별.",
    ),
    visual(
      "token-ring-operation.png",
      780,
      910,
      "교재 11장 토큰링 동작 방식",
      "토큰링은 자유 토큰을 얻은 노드가 데이터를 보내고, 목적지 확인 뒤 토큰을 반환.",
    ),
  ],
  "crypto-signature": [
    visual(
      "digital-signature-flow.png",
      820,
      270,
      "교재 14장 디지털 서명 처리",
      "서명은 송신자 개인키로 만들고 송신자 공개키로 검증하며, 암호화 방향과 구분.",
    ),
  ],
  "firewall-systems": [
    visual(
      "firewall-system-structure.png",
      780,
      340,
      "교재 14장 방화벽 시스템 구조",
      "방화벽은 내부 네트워크와 인터넷 사이에서 허용된 트래픽만 통과시키는 통제 지점.",
    ),
  ],
};

export const networkAnswerKeySets: NetworkAnswerKeySet[] = [
  {
    year: 2015,
    groups: ["12414", "33224", "13413", "22134", "12231", "34413", "24421"],
    answers: expandAnswerGroups(["12414", "33224", "13413", "22134", "12231", "34413", "24421"]),
  },
  {
    year: 2016,
    groups: ["31442", "13232", "14241", "32413", "32413", "23414", "24312"],
    answers: expandAnswerGroups(["31442", "13232", "14241", "32413", "32413", "23414", "24312"]),
  },
  {
    year: 2017,
    groups: ["11444", "32344", "43242", "33211", "42334", "11412", "12212"],
    answers: expandAnswerGroups(["11444", "32344", "43242", "33211", "42334", "11412", "12212"]),
  },
  {
    year: 2018,
    groups: ["23414", "32134", "12124", "34321", "43212", "43143", "12243"],
    answers: expandAnswerGroups(["23414", "32134", "12124", "34321", "43212", "43143", "12243"]),
  },
  {
    year: 2019,
    groups: ["23144", "32142", "33423", "13241", "12434", "22413", "31241"],
    answers: expandAnswerGroups(["23144", "32142", "33423", "13241", "12434", "22413", "31241"]),
  },
];

export const networkExamPatterns: NetworkExamPattern[] = [
  {
    id: "distributed-coupling",
    label: "분산시스템 결합도와 망 규모",
    category: "통신망 기초",
    lectureIds: [1],
    refs: ["2016-1", "2017-1", "2018-1", "2019-1"],
    sourceLabel: "1강·교재 1장",
    definition: "강연결 분산시스템은 처리장치들이 밀접하게 결합된 구조이고, 약연결 분산시스템은 통신망으로 연결된 독립 시스템의 성격이 강함.",
    examCue: "Data Flow Machine, LAN, WAN, Internet처럼 시스템 구조와 망 규모를 같은 보기 안에 섞어 제시.",
    studyAction: "결합도 문제는 성능보다 처리장치 사이의 물리적·논리적 결합 정도를 먼저 판단.",
    surrounding: ["강연결", "약연결", "LAN", "WAN"],
    variants: ["strongly coupled", "loosely coupled", "Local Area Network", "Wide Area Network"],
  },
  {
    id: "network-history-services",
    label: "통신망 역사와 대표 서비스",
    category: "통신망 기초",
    lectureIds: [1],
    refs: [
      "2015-1",
      "2015-2",
      "2015-3",
      "2016-2",
      "2016-3",
      "2016-4",
      "2017-2",
      "2017-3",
      "2017-4",
      "2017-5",
      "2018-2",
      "2018-3",
      "2019-2",
      "2019-3",
    ],
    sourceLabel: "1강·교재 1장",
    definition: "ARPANET은 인터넷의 효시가 된 패킷교환망이고, ALOHA는 무선 패킷교환 사례이며, 컴퓨터 통신망은 자원 공유와 원격 처리를 지원.",
    examCue: "ARPANET, ALOHA, SABRE, SAGE의 성격을 바꾸거나 통신망 목적에 정보 집중화를 넣어 흔듦.",
    studyAction: "역사 이름은 기능 키워드 하나씩 붙여 외우고, 통신망 목적은 분산·공유·원격 처리 관점으로 판별.",
    surrounding: ["ARPANET", "ALOHA", "전자우편", "원격 로그인"],
    variants: ["ARPA Network", "SABRE System", "SAGE System", "TELNET"],
  },
  {
    id: "protocol-layering-basics",
    label: "프로토콜 구성요소와 OSI 계층 순서",
    category: "프로토콜·계층",
    lectureIds: [1, 7],
    refs: ["2015-5", "2015-6", "2016-5", "2016-6", "2017-6", "2017-7", "2018-4", "2018-5", "2018-6", "2019-5", "2019-6"],
    sourceLabel: "1강·7강·교재 1장·7장",
    definition: "프로토콜은 구문, 의미, 타이밍을 포함하는 통신 규칙이고, OSI 모델은 물리 계층부터 응용 계층까지 7계층으로 통신 기능을 분해.",
    examCue: "계층 순서를 뒤섞거나 프로토콜 구성요소 자리에 변조·부호·스위칭 같은 물리 전송 용어를 넣음.",
    studyAction: "계층 순서는 아래에서 위로 외우고, 프로토콜 3요소는 구문·의미·타이밍으로 고정.",
    surrounding: ["구문", "의미", "타이밍", "네트워크 아키텍처"],
    variants: ["syntax", "semantics", "timing", "OSI 7계층"],
  },
  {
    id: "signal-coding",
    label: "신호 변환, PCM, 전송 부호",
    category: "신호·전송",
    lectureIds: [2],
    refs: ["2015-4", "2015-7", "2015-8", "2016-7", "2016-8", "2017-8", "2017-9", "2018-7", "2018-8", "2018-9", "2019-4", "2019-7", "2019-8"],
    sourceLabel: "2강·교재 2장",
    definition: "PCM은 표본화, 양자화, 부호화로 아날로그 정보를 디지털 부호로 바꾸며, ASCII·EBCDIC·Unicode는 문자 표현 비트 수와 적용 영역이 다름.",
    examCue: "복호화를 PCM 생성 과정에 끼워 넣거나 7비트 ASCII, 8비트 EBCDIC, 16비트 Unicode를 교차시킴.",
    studyAction: "변환 방향, 부호 비트 수, 장치 역할을 표로 묶어 확인.",
    surrounding: ["표본화", "양자화", "부호화", "DSU"],
    variants: ["PCM", "ASCII", "EBCDIC", "Unicode", "modulation"],
  },
  {
    id: "transmission-mode-efficiency",
    label: "전송 방식과 전송 효율",
    category: "신호·전송",
    lectureIds: [2, 4],
    refs: [
      "2015-9",
      "2015-10",
      "2015-11",
      "2015-12",
      "2016-9",
      "2016-10",
      "2016-11",
      "2016-12",
      "2017-10",
      "2017-11",
      "2017-12",
      "2018-10",
      "2018-11",
      "2018-12",
      "2019-9",
      "2019-10",
      "2019-11",
    ],
    sourceLabel: "2강·4강·교재 2장·4장",
    definition: "직렬·병렬, 단방향·반이중·전이중, 비동기·동기 전송은 전송 단위와 부가 비트에 따라 효율이 달라짐.",
    examCue: "ASCII 데이터 비트와 시작·정지 비트, SYN 문자 수를 이용해 효율을 계산하게 함.",
    studyAction: "비동기는 문자마다 시작·정지 비트, 동기는 블록 앞 SYN만 붙는다는 차이를 계산식으로 반복.",
    surrounding: ["SYN", "비동기식 전송", "동기식 전송", "반이중"],
    variants: ["serial", "parallel", "simplex", "half-duplex", "full-duplex"],
  },
  {
    id: "wireless-multidrop",
    label: "무선 통신, 위성 통신, 멀티드롭 선로",
    category: "신호·전송",
    lectureIds: [3, 4],
    refs: ["2015-13", "2016-13", "2017-13", "2018-13", "2019-12"],
    sourceLabel: "3강·4강·교재 3장·4장",
    definition: "무선 통신은 매체 특성과 전파 범위에 따라 비용·지연·방향성이 달라지고, 멀티드롭은 여러 단말이 하나의 선로를 공유.",
    examCue: "위성 통신의 지연, 라디오파의 방향성, 멀티드롭의 비용 특성을 뒤집어 제시.",
    studyAction: "통신 비용, 전송 지연, 선로 공유 여부를 기준으로 보기 문장을 분해.",
    surrounding: ["위성 통신", "마이크로파", "멀티드롭", "점대점"],
    variants: ["satellite", "radio wave", "multidrop", "point-to-point"],
  },
  {
    id: "topology-devices",
    label: "토폴로지와 네트워크 장비",
    category: "통신망 기초",
    lectureIds: [3, 11],
    refs: ["2015-14", "2015-15", "2016-14", "2016-15", "2017-14", "2017-15", "2018-14", "2018-15", "2019-13", "2019-14"],
    sourceLabel: "3강·11강·교재 3장·11장",
    definition: "토폴로지는 노드 연결 형태이고, 리피터·브리지·라우터·게이트웨이는 동작 계층과 연결 대상 네트워크의 동질성으로 구분.",
    examCue: "중앙 노드 장애 영향, 계층형 네트워크, 서로 다른 프로토콜 변환 장비를 묻는 방식이 반복.",
    studyAction: "장비명은 OSI 계층과 변환 범위를 함께 적어 암기.",
    surrounding: ["성형", "환형", "망형", "게이트웨이"],
    variants: ["star", "ring", "mesh", "gateway", "router"],
  },
  {
    id: "switching-multiplexing-sync",
    label: "교환, 다중화, 동기화",
    category: "신호·전송",
    lectureIds: [4],
    refs: ["2015-16", "2015-17", "2015-18", "2016-16", "2016-17", "2016-18", "2017-16", "2017-17", "2018-16", "2018-17", "2019-15", "2019-16", "2019-17"],
    sourceLabel: "4강·교재 4장",
    definition: "가상회선은 연결형 패킷교환이고, FDM/TDM/WDM은 하나의 전송로를 주파수·시간·파장 기준으로 나누며, 동기화는 송수신 시점을 맞춤.",
    examCue: "라디오 주파수 사례, 광섬유 파장 분할, 연결형 패킷교환의 명칭을 바꾸어 제시.",
    studyAction: "나누는 기준이 주파수인지 시간인지 파장인지 먼저 표시하고, 연결 설정 여부로 교환 방식을 구분.",
    surrounding: ["가상회선", "데이터그램", "FDM", "TDM", "WDM"],
    variants: ["virtual circuit", "frequency division", "time division", "wavelength division"],
  },
  {
    id: "addressing-routing-flow",
    label: "주소지정, 이름, 라우팅, 흐름제어 구분",
    category: "오류·흐름 제어",
    lectureIds: [4, 6],
    refs: ["2015-19", "2016-19", "2017-19", "2018-18", "2019-18"],
    sourceLabel: "4강·6강·교재 4장·6장",
    definition: "주소지정은 통신망에서 대상을 식별하는 기능이고, 라우팅은 경로 선택, 흐름제어는 송수신 속도 조절을 다룸.",
    examCue: "addressing 문항에 flow control을 섞어 기능 범위를 벗어난 선택지를 만들음.",
    studyAction: "문항의 제어 대상이 식별자, 경로, 송수신 속도 중 무엇인지 먼저 표시.",
    surrounding: ["naming", "identification", "routing", "flow control"],
    variants: ["주소지정", "명명", "식별", "경로 선택"],
  },
  {
    id: "error-detection-codes",
    label: "패리티, LRC, CRC",
    category: "오류·흐름 제어",
    lectureIds: [5],
    refs: ["2015-20", "2015-21", "2016-20", "2016-21", "2017-20", "2017-21", "2017-22", "2018-19", "2018-20", "2018-21", "2019-19", "2019-20", "2019-21"],
    sourceLabel: "5강·교재 5장",
    definition: "패리티 검사는 1의 개수를 기준으로 오류를 검출하고, LRC는 블록의 열 방향 패리티, CRC는 다항식 나눗셈의 나머지를 검사부호로 사용.",
    examCue: "표 안의 b7 패리티 비트, LRC 8비트, CRC 다항식 비트열을 계산하게 함.",
    studyAction: "홀수·짝수 패리티 기준을 먼저 적고, CRC는 최고차부터 계수 유무를 비트열로 변환.",
    surrounding: ["홀수 패리티", "짝수 패리티", "순환잉여검사", "검사합"],
    variants: ["parity", "LRC", "CRC", "cyclic code"],
  },
  {
    id: "arq-error-control",
    label: "ARQ 오류제어 방식",
    category: "오류·흐름 제어",
    lectureIds: [5],
    refs: ["2015-22", "2016-22", "2016-23", "2017-23", "2018-22", "2019-22", "2019-23"],
    sourceLabel: "5강·교재 5장",
    definition: "ARQ는 오류 검출 후 재전송으로 신뢰성을 확보하며, 정지-대기, Go-Back-N, 선택적 반복 방식은 재전송 범위가 다름.",
    examCue: "REJ, 응답 프레임 미수신, 먼 거리 탐사선 사례처럼 재전송 시나리오로 방식을 고르게 함.",
    studyAction: "오류 프레임 하나만 다시 보내는지, 이후 프레임까지 되돌리는지, 한 프레임씩 기다리는지로 구분.",
    surrounding: ["정지-대기", "Go-Back-N", "Selective Repeat", "Hamming code"],
    variants: ["ARQ", "REJ", "sliding window", "stop-and-wait"],
  },
  {
    id: "flow-control-principles",
    label: "흐름제어 원칙과 방법",
    category: "오류·흐름 제어",
    lectureIds: [6],
    refs: ["2015-23", "2016-24", "2017-24", "2018-23", "2019-24"],
    sourceLabel: "6강·교재 6장",
    definition: "흐름제어는 송신자가 수신자의 처리 능력을 넘지 않도록 조절하며, 속도 조절·거부·단일 승인·다중 승인 원칙으로 설명.",
    examCue: "ask-and-wait, stop-and-wait, sliding window, wait-before-go를 원칙명과 교차.",
    studyAction: "승낙을 받고 보내는지, 보내지 말라는 거부를 기다리는지, 여러 프레임을 한 번에 승인하는지 구분.",
    surrounding: ["ask-and-wait", "wait-before-go", "sliding window", "choke packet"],
    variants: ["속도 조절", "거부", "단일 승낙", "다중 승낙"],
  },
  {
    id: "routing-methods",
    label: "라우팅 방식",
    category: "오류·흐름 제어",
    lectureIds: [6],
    refs: ["2015-24", "2017-25", "2019-25"],
    sourceLabel: "6강·교재 6장",
    definition: "라우팅은 목적지까지 경로를 선택하는 기능이며, 고정·랜덤·플러딩·델타·분산형 같은 방식은 경로 결정 주체와 적응성으로 구분.",
    examCue: "플러딩의 '들어온 곳을 제외한 모든 방향'이나 분산형 라우팅의 적응성을 설명으로 제시.",
    studyAction: "경로 정보가 고정인지, 전체로 뿌리는지, 노드들이 분산 갱신하는지로 판단.",
    surrounding: ["고정 라우팅", "플러딩", "델타 라우팅", "분산형 라우팅"],
    variants: ["fixed", "flooding", "delta", "distributed"],
  },
  {
    id: "layering-encapsulation",
    label: "계층화 원칙과 캡슐화",
    category: "프로토콜·계층",
    lectureIds: [7],
    refs: ["2015-25", "2016-25", "2016-26", "2017-18", "2018-24", "2019-26"],
    sourceLabel: "7강·교재 7장",
    definition: "계층화는 기능을 계층별로 분리하고, 캡슐화는 상위 데이터에 제어정보를 붙여 하위 계층으로 내려보내는 과정.",
    examCue: "모든 계층이 모든 계층과 상호작용한다는 식의 과도한 연결 설명이나 캡슐화 방향을 바꿈.",
    studyAction: "인접 계층 인터페이스, 동등 계층 통신, 헤더 추가와 제거 방향을 도식으로 확인.",
    surrounding: ["PDU", "SDU", "PCI", "동등 계층"],
    variants: ["layering", "encapsulation", "decapsulation", "protocol control information"],
  },
  {
    id: "tcpip-model",
    label: "TCP/IP 모델과 계층 대응",
    category: "TCP/IP",
    lectureIds: [7, 8, 9],
    refs: ["2016-27", "2017-26", "2018-25", "2019-27"],
    sourceLabel: "7강·8강·9강·교재 7장",
    definition: "TCP/IP는 단일 프로토콜이 아니라 여러 프로토콜의 집합이며, 실제 인터넷 모델은 응용·전송·인터넷·네트워크 액세스 계층으로 설명.",
    examCue: "TCP/IP가 OSI 7계층을 그대로 따른다거나 단일 프로토콜이라고 표현.",
    studyAction: "OSI 계층명과 TCP/IP 계층명을 1:1로 억지 대응하지 말고 기능 대응으로 정리.",
    surrounding: ["DoD 모델", "인터넷 계층", "전송 계층", "프로토콜 스위트"],
    variants: ["TCP/IP", "protocol suite", "DoD", "Internet model"],
  },
  {
    id: "ip-helper-protocols",
    label: "IP 주소와 보조 프로토콜",
    category: "TCP/IP",
    lectureIds: [8],
    refs: ["2015-28", "2015-29", "2015-30", "2016-28", "2016-29", "2016-30", "2017-29", "2018-26", "2018-28", "2018-29", "2019-28", "2019-30"],
    sourceLabel: "8강·교재 8장",
    definition: "IPv4 주소는 32비트 논리주소이고, ARP/RARP/ICMP/IGMP/DHCP는 주소 변환, 오류 보고, 그룹 관리, 자동 설정 기능을 담당.",
    examCue: "IP 주소를 물리주소나 포트번호로 바꾸거나, IP 헤더 protocol 필드가 하위계층을 가리킨다고 서술.",
    studyAction: "각 프로토콜을 주소 변환, 오류·제어, 멀티캐스트, 동적 주소 할당으로 분류.",
    surrounding: ["ARP", "RARP", "ICMP", "IGMP", "DHCP"],
    variants: ["IPv4", "protocol field", "fragmentation", "MTU"],
  },
  {
    id: "tcp-udp-apps",
    label: "TCP, UDP, 응용 프로토콜",
    category: "TCP/IP",
    lectureIds: [9, 10],
    refs: ["2015-26", "2015-27", "2017-27", "2017-28", "2018-27", "2019-29"],
    sourceLabel: "9강·10강·교재 9장·10장",
    definition: "TCP는 연결형 신뢰성 전송 계층 프로토콜이고, UDP는 비연결형 전송 계층 프로토콜이며, 응용 프로토콜은 하위 전송 방식이 다름.",
    examCue: "TCP를 인터넷 계층으로 놓거나 UDP를 연결형·신뢰성 서비스로 설명.",
    studyAction: "프로토콜 이름을 계층, 연결성, 대표 응용과 함께 세 칸으로 암기.",
    surrounding: ["FTP", "DNS", "RTP", "ping"],
    variants: ["connection-oriented", "connectionless", "transport layer", "User Datagram Protocol"],
  },
  {
    id: "lan-model-mac",
    label: "LAN 참조 모델과 매체접근",
    category: "LAN",
    lectureIds: [11, 12],
    refs: ["2015-31", "2016-31", "2017-30", "2018-30", "2019-31"],
    sourceLabel: "11강·12강·교재 11장·12장",
    definition: "LAN 참조 모델에서 LLC와 MAC은 데이터링크 계층의 하위 기능이고, CSMA/CD·토큰링·토큰버스는 매체접근 방식.",
    examCue: "CSMA/CD 이더넷을 토큰 방식에 넣거나 LLC/MAC의 OSI 계층을 바꾸어 제시.",
    studyAction: "토큰을 쓰는 방식과 경쟁 기반 방식(CSMA/CD)을 분리.",
    surrounding: ["LLC", "MAC", "MAU", "CSMA/CD"],
    variants: ["IEEE 802.3", "Token Ring", "Token Bus", "Ethernet"],
  },
  {
    id: "wireless-lan",
    label: "무선 LAN 방식",
    category: "LAN",
    lectureIds: [12],
    refs: ["2015-32", "2016-32", "2017-31", "2018-31", "2019-32"],
    sourceLabel: "12강·교재 12장",
    definition: "무선 LAN은 IEEE 802.11 기반이며, 애드혹 방식은 단말 간 직접 통신, 인프라스트럭처 방식은 AP를 거쳐 통신.",
    examCue: "무선 LAN이 유선 LAN보다 보안이 강하다고 하거나 애드혹과 인프라스트럭처의 AP 유무를 뒤집음.",
    studyAction: "AP가 있으면 인프라스트럭처, 단말끼리 직접 통신하면 애드혹으로 판단.",
    surrounding: ["IEEE 802.11", "Ad-Hoc", "Infrastructure", "FDDI"],
    variants: ["무선 LAN", "AP", "wireless LAN", "infrastructure"],
  },
  {
    id: "security-requirements",
    label: "네트워크 보안 요구사항",
    category: "보안",
    lectureIds: [13],
    refs: ["2015-34", "2018-32"],
    sourceLabel: "13강·교재 13장",
    definition: "네트워크 보안 요구사항에는 데이터 무결성, 데이터 보안성, 실체 인증, 데이터 인증, 부인 방지 등이 포함.",
    examCue: "송수신 사실 확인은 부인 방지, 데이터 변경 여부는 무결성처럼 요구사항을 사례로 묻음.",
    studyAction: "무엇을 확인하는지: 내용 변경, 신원, 송수신 사실, 비밀 유지로 나누어 표시.",
    surrounding: ["기밀성", "무결성", "가용성", "부인 방지"],
    variants: ["CIA", "non-repudiation", "entity authentication", "data authentication"],
  },
  {
    id: "malware-fraud",
    label: "악성 프로그램과 인터넷 사기",
    category: "보안",
    lectureIds: [13],
    refs: ["2016-33", "2017-32", "2019-33"],
    sourceLabel: "13강·교재 13장",
    definition: "파밍은 DNS나 도메인·주소 변조로 사용자를 가짜 사이트로 유도하고, 트로이 목마는 정상 프로그램처럼 가장한 악성 프로그램.",
    examCue: "피싱, 파밍, 웜, 트로이 목마를 사용자 유인 방식과 감염 방식으로 구분하게 함.",
    studyAction: "사용자가 속아서 입력하는지, 주소 해석이 조작되는지, 자기 복제가 있는지로 나누어 판단.",
    surrounding: ["피싱", "파밍", "웜", "트로이 목마"],
    variants: ["phishing", "pharming", "worm", "Trojan horse"],
  },
  {
    id: "crypto-signature",
    label: "공개키 암호와 디지털 서명",
    category: "보안",
    lectureIds: [14],
    refs: ["2015-33", "2016-34", "2017-33", "2018-33", "2018-34", "2019-34", "2019-35"],
    sourceLabel: "14강·교재 14장",
    definition: "공개키 암호는 공개키와 개인키를 한 쌍으로 사용하며, 디지털 서명은 송신자의 개인키로 서명하고 송신자의 공개키로 검증.",
    examCue: "공개키·개인키 방향을 바꾸거나 디지털 서명을 공통키 방식으로 설명.",
    studyAction: "기밀성 암호화는 수신자 공개키, 서명은 송신자 개인키라는 방향을 따로 암기.",
    surrounding: ["RSA", "DES", "대칭키", "S/MIME"],
    variants: ["public key", "private key", "digital signature", "PKI"],
  },
  {
    id: "firewall-systems",
    label: "방화벽과 보안 장치",
    category: "보안",
    lectureIds: [14],
    refs: ["2015-35", "2016-35", "2017-34", "2017-35", "2018-35"],
    sourceLabel: "14강·교재 14장",
    definition: "방화벽은 네트워크 사이의 트래픽을 조건에 따라 통제하며, 프락시 서버, 스크리닝 라우터, 배스천 호스트, 이중 홈 게이트웨이 등이 관련.",
    examCue: "방화벽 구성요소가 아닌 일반 네트워크 장치나 메시지 다이제스트를 끼워 넣음.",
    studyAction: "패킷을 검사하는 위치와 역할을 기준으로 장치명을 분류.",
    surrounding: ["Proxy server", "Screening router", "Bastion host", "Dual-homed gateway"],
    variants: ["firewall", "packet filtering", "DMZ", "application gateway"],
  },
];

export const networkFrequentConcepts: NetworkFrequentConcept[] = networkExamPatterns
  .map((pattern) => ({
    ...pattern,
    visuals: networkConceptVisuals[pattern.id],
    frequency: pattern.refs.length,
    years: yearsFromRefs(pattern.refs),
  }))
  .sort((a, b) => b.frequency - a.frequency || a.label.localeCompare(b.label, "ko"));

export const networkReconstructedQuestions: NetworkReconstructedQuestion[] = [
  {
    id: "network-rebuilt-1",
    number: 1,
    patternId: "distributed-coupling",
    category: "통신망 기초",
    lectureRefs: [lectureRef(1, "분산시스템 결합도")],
    conceptTags: ["강연결", "약연결", "망 규모"],
    refs: ["2016-1", "2017-1", "2018-1", "2019-1"],
    sourceLabel: "2016·2017·2018·2019 기출형",
    prompt: "분산시스템의 결합도 관점에서 강연결 시스템에 가장 가까운 것은?",
    correctChoice: "1",
    explanation: "강연결 분산시스템은 처리장치들이 밀접하게 연결되어 하나의 시스템처럼 동작하는 구조를 가리킴.",
    examSkill: "LAN, WAN, Internet은 통신망 규모나 약연결 구조로 분류되므로 결합도 기준과 망 범위 기준을 섞지 않음.",
    choices: [
      c("1", "Data Flow Machine", "correct", "자료 흐름을 중심으로 여러 처리 요소가 밀접하게 동작하는 병렬 처리 구조로, 강연결 분산시스템의 예로 다룸.", "1강의 분산시스템 결합도 구분."),
      c("2", "Local Area Network", "wrong", "LAN은 제한된 지역의 컴퓨터를 통신망으로 연결한 규모 분류이며, 처리장치가 하나의 강결합 시스템처럼 구성된다는 뜻은 아님.", "1강의 LAN/MAN/WAN 규모 구분."),
      c("3", "Wide Area Network", "wrong", "WAN은 넓은 지역을 연결하는 통신망 범위 표현으로, 결합도가 강하다는 의미를 포함하지 않음.", "1강의 광역 통신망 구분."),
      c("4", "Internet", "wrong", "Internet은 서로 다른 네트워크들의 연결망이며 독립 시스템들이 프로토콜로 통신하는 구조라 강연결 사례가 아님.", "1강의 인터넷과 약연결 망 구조."),
    ],
  },
  {
    id: "network-rebuilt-2",
    number: 2,
    patternId: "network-history-services",
    category: "통신망 기초",
    lectureRefs: [lectureRef(1, "통신망 역사")],
    conceptTags: ["ARPANET", "ALOHA", "패킷교환"],
    refs: ["2015-1", "2015-2", "2017-2", "2017-3", "2018-2", "2019-2"],
    sourceLabel: "2015·2017·2018·2019 기출형",
    prompt: "초기의 무선 패킷 교환 통신망으로 가장 알맞은 것은?",
    correctChoice: "4",
    explanation: "ALOHA 시스템은 무선 환경에서 패킷 교환 방식을 사용한 초기 통신망 사례로 출제됨.",
    examSkill: "역사 문항은 이름을 외우는 문제처럼 보이지만 실제로는 '인터넷 효시', '무선 패킷', '항공 예약', '방공 시스템'의 기능 매칭 문제.",
    choices: [
      c("1", "ARPA Network", "wrong", "ARPANET은 인터넷의 효시가 된 패킷교환망으로 중요하지만, 무선 패킷 교환 사례로 묻는 경우에는 ALOHA와 구분해야 함.", "1강 통신망 발전사."),
      c("2", "SABRE System", "wrong", "SABRE는 항공 예약 시스템 맥락에서 등장하며 무선 패킷 교환 통신망의 명칭이 아님.", "1강 초기 통신망 사례."),
      c("3", "SAGE System", "wrong", "SAGE는 방공 시스템으로 다루는 사례이며 무선 패킷 교환망의 대표 사례는 아님.", "1강 초기 컴퓨터 통신망 사례."),
      c("4", "ALOHA System", "correct", "ALOHA는 무선 패킷 교환 방식을 채택한 통신망으로 반복 출제되는 역사 키워드.", "1강 통신망 발전사."),
    ],
  },
  {
    id: "network-rebuilt-3",
    number: 3,
    patternId: "network-history-services",
    category: "통신망 기초",
    lectureRefs: [lectureRef(1, "통신망 목적")],
    conceptTags: ["자원 공유", "분산 처리", "원격 처리"],
    refs: ["2016-3", "2017-4", "2018-3", "2019-3"],
    sourceLabel: "2016·2017·2018·2019 기출형",
    prompt: "컴퓨터 통신망의 목적과 가장 거리가 먼 것은?",
    correctChoice: "4",
    explanation: "통신망은 분산된 자원 공유, 신뢰성 향상, 원격 처리 등을 목적으로 하며 정보를 한곳에 집중시키는 것은 통신망의 대표 목적과 반대 방향.",
    examSkill: "목적 문항은 긍정 표현 세 개와 중앙 집중 표현 하나로 구성되는 경우가 많음.",
    choices: [
      c("1", "여러 지역의 자원을 공유할 수 있게 함", "wrong", "자원 공유는 통신망을 구축하는 핵심 목적에 해당하므로 제외 대상이 아님.", "1강 컴퓨터 통신망의 목적."),
      c("2", "원격으로 컴퓨터 처리를 가능하게 함", "wrong", "원격 로그인이나 원격 처리 서비스는 통신망의 대표적 활용에 포함됨.", "1강 통신망 서비스."),
      c("3", "시스템 신뢰도를 높일 수 있음", "wrong", "분산된 자원을 활용하면 일부 장애에도 서비스를 유지할 수 있어 신뢰성 향상 목적과 연결됨.", "1강 통신망 목적."),
      c("4", "정보를 한곳에 집중시켜 관리하게 함", "correct", "통신망은 분산 자원의 연결과 공유를 중시하므로, 정보의 중앙 집중 자체를 대표 목적으로 보기는 어려움.", "1강 통신망 목적과 분산 처리."),
    ],
  },
  {
    id: "network-rebuilt-4",
    number: 4,
    patternId: "protocol-layering-basics",
    category: "프로토콜·계층",
    lectureRefs: [lectureRef(1, "OSI 7계층"), lectureRef(7, "계층 구조")],
    conceptTags: ["OSI", "계층 순서"],
    refs: ["2015-5", "2016-5", "2017-6", "2018-4", "2019-6"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "OSI 참조 모델의 7계층을 아래 계층에서 위 계층 순서로 올바르게 나열한 것은?",
    correctChoice: "1",
    explanation: "OSI 모델은 물리, 데이터링크, 네트워크, 전송, 세션, 표현, 응용 계층 순서로 올라감.",
    examSkill: "보기에는 세션·표현 순서나 데이터링크·네트워크 순서를 바꾸는 함정이 자주 들어감.",
    choices: [
      c("1", "물리-데이터링크-네트워크-전송-세션-표현-응용", "correct", "물리 매체에서 시작해 응용 서비스로 올라가는 표준 순서와 일치.", "1강·7강 OSI 7계층."),
      c("2", "물리-네트워크-데이터링크-전송-세션-표현-응용", "wrong", "데이터링크 계층은 물리 계층 바로 위에서 프레임 전달을 담당하므로 네트워크 계층보다 아래에 위치.", "7강 계층별 기능."),
      c("3", "물리-데이터링크-네트워크-세션-전송-표현-응용", "wrong", "전송 계층은 종단 간 전송 기능으로 세션 계층보다 아래에 있어야 함.", "7강 전송 계층과 세션 계층 위치."),
      c("4", "물리-데이터링크-전송-네트워크-세션-응용-표현", "wrong", "네트워크 계층은 전송 계층 아래이며, 표현 계층은 응용 계층 아래에 위치.", "7강 OSI 계층 순서."),
    ],
  },
  {
    id: "network-rebuilt-5",
    number: 5,
    patternId: "protocol-layering-basics",
    category: "프로토콜·계층",
    lectureRefs: [lectureRef(1, "프로토콜 구성요소")],
    conceptTags: ["프로토콜", "구문", "의미", "타이밍"],
    refs: ["2018-5", "2019-5"],
    sourceLabel: "2018·2019 기출형",
    prompt: "통신 프로토콜의 기본 구성요소로 가장 알맞은 것은?",
    correctChoice: "4",
    explanation: "프로토콜은 송수신 규칙이므로 데이터 형식인 구문, 제어 의미인 의미, 교환 시점인 타이밍을 포함.",
    examSkill: "변조, 부호화, 스위칭 같은 전송 기술 용어는 프로토콜의 3요소가 아님.",
    choices: [
      c("1", "스위칭, 변조, 부호", "wrong", "스위칭과 변조는 전송 방식·신호 처리 용어이며 프로토콜 규칙의 구성요소가 아님.", "1강 프로토콜 정의."),
      c("2", "프로토콜, 변조, 부호", "wrong", "프로토콜은 상위 개념이고 변조·부호는 물리적 표현 기술에 가까워 구성요소 묶음이 되지 않음.", "1강 프로토콜 구성요소."),
      c("3", "스위칭, 구문, 의미", "wrong", "구문과 의미는 맞지만 스위칭은 경로·교환 방식 용어이므로 타이밍을 대체할 수 없음.", "1강 구문·의미·타이밍."),
      c("4", "구문, 의미, 타이밍", "correct", "통신 규약을 이루는 형식, 해석, 시간 제어 기준을 모두 포함.", "1강 프로토콜 3요소."),
    ],
  },
  {
    id: "network-rebuilt-6",
    number: 6,
    patternId: "signal-coding",
    category: "신호·전송",
    lectureRefs: [lectureRef(2, "PCM")],
    conceptTags: ["PCM", "표본화", "양자화", "부호화"],
    refs: ["2015-7", "2018-7"],
    sourceLabel: "2015·2018 기출형",
    prompt: "PCM 전송 코드 생성 과정에 포함되지 않는 것은?",
    correctChoice: "3",
    explanation: "PCM 생성은 아날로그 신호를 표본화, 양자화, 부호화하여 디지털 부호로 만드는 과정.",
    examSkill: "복호화는 수신 측에서 부호를 원래 정보로 되돌리는 방향이므로 생성 과정과 반대.",
    choices: [
      c("1", "표본화", "wrong", "표본화는 연속 신호를 일정 간격으로 취하는 PCM의 첫 단계이므로 포함됨.", "2강 PCM 처리 과정."),
      c("2", "양자화", "wrong", "양자화는 표본값을 유한한 단계값으로 근사하는 PCM 단계이므로 포함됨.", "2강 PCM 처리 과정."),
      c("3", "복호화", "correct", "복호화는 생성된 부호를 해석하는 수신 방향 처리이며 PCM 전송 코드 생성 단계가 아님.", "2강 PCM과 부호화/복호화 구분."),
      c("4", "부호화", "wrong", "부호화는 양자화된 값을 이진 부호로 표현하는 PCM 생성 단계.", "2강 PCM 처리 과정."),
    ],
  },
  {
    id: "network-rebuilt-7",
    number: 7,
    patternId: "signal-coding",
    category: "신호·전송",
    lectureRefs: [lectureRef(2, "전송 부호")],
    conceptTags: ["ASCII", "EBCDIC", "Unicode"],
    refs: ["2015-8", "2016-8", "2017-9", "2018-9", "2019-7"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "8비트를 사용하여 256개 문자를 표현할 수 있고 IBM 계열에서 많이 사용된 전송 부호는?",
    correctChoice: "3",
    explanation: "EBCDIC은 8비트 전송 부호로 256개의 문자 표현이 가능하다고 정리.",
    examSkill: "ASCII 7비트, EBCDIC 8비트, Unicode 16비트라는 비트 수 대응을 묻는 문항이 반복됨.",
    choices: [
      c("1", "ASCII", "wrong", "ASCII는 정보 표현에 7비트를 사용하는 표준 문자 코드로 출제됨.", "2강 ASCII 코드."),
      c("2", "Unicode", "wrong", "교재 범위의 Unicode 문항은 16비트 코드로 구분하는 형태가 반복됨.", "2강 문자 코드 비교."),
      c("3", "EBCDIC", "correct", "EBCDIC은 8비트 전체를 사용해 256개 문자를 표현하는 코드로 정리됨.", "2강 EBCDIC 코드."),
      c("4", "Baudot code", "wrong", "Baudot code는 오래된 5비트 계열 전송 부호로, 8비트 256문자 조건과 맞지 않음.", "2강 전송 부호 비교."),
    ],
  },
  {
    id: "network-rebuilt-8",
    number: 8,
    patternId: "transmission-mode-efficiency",
    category: "신호·전송",
    lectureRefs: [lectureRef(2, "전송 방향")],
    conceptTags: ["반이중", "전이중", "단방향"],
    refs: ["2015-10", "2016-10"],
    sourceLabel: "2015·2016 기출형",
    prompt: "하나의 통신 채널을 이용해 양방향 전송은 가능하지만 동시에 양방향 전송은 하지 못하는 방식은?",
    correctChoice: "2",
    explanation: "반이중 통신은 양방향 전송이 가능하되 한 시점에는 한 방향으로만 전송.",
    examSkill: "라디오 방송은 단방향, 전화망은 전이중의 전형 사례로 함께 비교됨.",
    choices: [
      c("1", "단방향 통신", "wrong", "단방향 통신은 한 방향으로만 전송되므로 양방향 전송 가능 조건을 만족하지 않음.", "2강 전송 방향."),
      c("2", "반이중 통신", "correct", "양방향으로 번갈아 전송하는 방식이므로 문항 조건과 일치.", "2강 반이중 방식."),
      c("3", "전이중 통신", "wrong", "전이중은 동시에 양방향 전송이 가능하므로 '동시에 하지 못한다'는 조건과 맞지 않음.", "2강 전이중 방식."),
      c("4", "병렬 전송", "wrong", "병렬 전송은 여러 비트를 동시에 보내는 전송 단위 방식이지 방향성 분류가 아님.", "2강 직렬/병렬 전송."),
    ],
  },
  {
    id: "network-rebuilt-9",
    number: 9,
    patternId: "transmission-mode-efficiency",
    category: "신호·전송",
    lectureRefs: [lectureRef(2, "전송 효율")],
    conceptTags: ["비동기", "동기", "SYN"],
    refs: ["2015-11", "2015-12", "2016-11", "2016-12", "2017-11", "2017-12", "2018-11", "2018-12", "2019-10", "2019-11"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "198개의 ASCII 문자 블록 앞에 2개의 SYN 문자를 붙여 동기식으로 전송할 때 최대 전송 효율은?",
    correctChoice: "3",
    explanation: "ASCII 문자 198개가 실제 데이터이고 SYN 2개가 동기용 오버헤드이므로 효율은 198/(198+2) = 99.0%.",
    examSkill: "비동기식은 문자마다 시작·정지 비트가 붙고, 동기식은 블록 앞의 SYN 문자만 오버헤드로 계산.",
    choices: [
      c("1", "80.0%", "wrong", "80.0%는 8비트 데이터에 시작 1비트와 정지 1비트를 붙이는 비동기식 문자 전송의 전형 계산값.", "2강 비동기식 전송 효율."),
      c("2", "95.0%", "wrong", "198개 데이터 문자와 2개 SYN 문자 조건에서는 전체 200개 중 198개가 데이터이므로 95.0%가 되지 않음.", "2강 동기식 전송 효율 계산."),
      c("3", "99.0%", "correct", "198/200 = 0.99이므로 최대 전송 효율은 99.0%.", "2강 동기식 전송 효율 계산."),
      c("4", "99.8%", "wrong", "99.8%는 오버헤드가 2개보다 훨씬 작을 때의 값이며, 198개 문자와 2개 SYN 조건에서는 과대 계산.", "2강 SYN 오버헤드 계산."),
    ],
  },
  {
    id: "network-rebuilt-10",
    number: 10,
    patternId: "switching-multiplexing-sync",
    category: "신호·전송",
    lectureRefs: [lectureRef(4, "다중화")],
    conceptTags: ["FDM", "TDM", "WDM"],
    refs: ["2015-17", "2016-17", "2017-17", "2018-17", "2019-16"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "서로 다른 라디오 방송을 서로 다른 주파수 대역에서 동시에 수신할 수 있게 하는 기능과 가장 가까운 것은?",
    correctChoice: "2",
    explanation: "서로 다른 주파수 대역을 나누어 여러 신호를 동시에 보내는 방식은 주파수분할 다중화.",
    examSkill: "다중화는 나누는 기준을 먼저 확인: 주파수는 FDM, 시간은 TDM, 광섬유 파장은 WDM.",
    choices: [
      c("1", "데이터 교환", "wrong", "데이터 교환은 데이터가 목적지까지 전달되는 방식의 문제이지 주파수 대역을 나누는 기능이 아님.", "4강 교환 방식과 다중화 구분."),
      c("2", "주파수분할 다중화", "correct", "여러 방송이 서로 다른 주파수를 사용하는 사례와 직접 대응.", "4강 FDM."),
      c("3", "시분할 다중화", "wrong", "TDM은 같은 전송로를 시간 슬롯으로 나누는 방식이므로 라디오 주파수 대역 사례와 다름.", "4강 TDM."),
      c("4", "파장분할 다중화", "wrong", "WDM은 광섬유에서 서로 다른 파장을 쓰는 방식으로, 라디오 주파수 방송 사례와 구분.", "4강 WDM."),
    ],
  },
  {
    id: "network-rebuilt-11",
    number: 11,
    patternId: "topology-devices",
    category: "통신망 기초",
    lectureRefs: [lectureRef(3, "네트워크 토폴로지")],
    conceptTags: ["성형", "중앙 노드", "토폴로지"],
    refs: ["2015-14", "2016-14", "2017-14", "2018-14", "2019-13"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "중앙 컴퓨터나 중앙 장치에 장애가 발생하면 전체 네트워크 통신이 중단되기 쉬운 토폴로지는?",
    correctChoice: "1",
    explanation: "성형 네트워크는 중앙 노드에 단말들이 연결되므로 중앙 장치 장애가 전체 통신에 큰 영향을 줌.",
    examSkill: "토폴로지는 모양보다 장애가 어느 노드에 영향을 주는지로 판단하면 오답을 줄일 수 있음.",
    choices: [
      c("1", "성형 네트워크", "correct", "중앙 장치가 허브 역할을 하므로 중앙 장애가 전체 연결에 영향을 줌.", "3강 스타형 토폴로지."),
      c("2", "환형 네트워크", "wrong", "환형은 노드들이 고리 형태로 연결되는 구조로 중앙 컴퓨터 하나에 모든 통신이 집중되는 형태가 아님.", "3강 링형 토폴로지."),
      c("3", "망형 네트워크", "wrong", "망형은 여러 경로를 갖도록 연결해 일부 장애에 대한 대체 경로가 생길 수 있음.", "3강 메시형 토폴로지."),
      c("4", "버스형 네트워크", "wrong", "버스형은 하나의 공통 전송매체를 공유하므로 중앙 컴퓨터 장애 조건으로 판별하지 않음.", "3강 버스형 토폴로지."),
    ],
  },
  {
    id: "network-rebuilt-12",
    number: 12,
    patternId: "topology-devices",
    category: "통신망 기초",
    lectureRefs: [lectureRef(3, "네트워크 장비")],
    conceptTags: ["게이트웨이", "라우터", "브리지"],
    refs: ["2015-15", "2016-15", "2018-15", "2019-14"],
    sourceLabel: "2015·2016·2018·2019 기출형",
    prompt: "서로 다른 통신 프로토콜을 사용하는 이기종 네트워크 사이에서 상호 연결을 제공하는 장치는?",
    correctChoice: "3",
    explanation: "게이트웨이는 서로 다른 프로토콜을 사용하는 네트워크 사이에서 프로토콜과 데이터 형식 변환을 담당.",
    examSkill: "라우터는 네트워크 계층 경로 선택, 브리지는 데이터링크 계층 연결, 리피터는 물리 신호 재생으로 구분.",
    choices: [
      c("1", "라우터", "wrong", "라우터는 IP 같은 네트워크 계층 주소를 기준으로 패킷 경로를 선택하지만, 서로 다른 프로토콜 전체를 변환하는 장비로 보기는 어려움.", "3강 라우터 역할."),
      c("2", "브리지", "wrong", "브리지는 데이터링크 계층에서 LAN 세그먼트를 연결하는 장비이며 이기종 프로토콜 변환 장비가 아님.", "3강 브리지 역할."),
      c("3", "게이트웨이", "correct", "서로 다른 통신 프로토콜을 사용하는 네트워크 사이에서 변환과 상호 연결을 수행.", "3강 게이트웨이 역할."),
      c("4", "스위칭 허브", "wrong", "스위칭 허브는 같은 LAN 안에서 프레임 전달을 효율화하는 장비에 가깝고, 프로토콜 변환 기능이 핵심이 아님.", "3강 LAN 장비 구분."),
    ],
  },
  {
    id: "network-rebuilt-13",
    number: 13,
    patternId: "switching-multiplexing-sync",
    category: "신호·전송",
    lectureRefs: [lectureRef(4, "패킷교환")],
    conceptTags: ["가상회선", "데이터그램", "연결형"],
    refs: ["2015-16", "2016-16", "2017-16", "2018-16", "2019-15"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "연결 설정과 연결 해제가 필요한 연결지향형 패킷 교환 방식은?",
    correctChoice: "2",
    explanation: "가상회선 패킷교환은 데이터를 보내기 전에 논리적 연결을 설정하고 전송 후 해제하는 연결형 방식.",
    examSkill: "데이터그램은 패킷마다 독립 경로를 택하는 비연결형이라는 점을 함께 기억.",
    choices: [
      c("1", "데이터그램 패킷교환", "wrong", "데이터그램은 연결 설정 없이 각 패킷이 독립적으로 전달되는 비연결형 방식.", "4강 데이터그램 방식."),
      c("2", "가상회선 패킷교환", "correct", "논리적 연결을 먼저 설정한 뒤 패킷을 순서대로 전달하는 연결지향형 방식.", "4강 가상회선 방식."),
      c("3", "메시지 교환", "wrong", "메시지 교환은 메시지 전체를 저장 후 전달하는 방식으로 연결 설정형 패킷교환과 구분.", "4강 교환 방식."),
      c("4", "축적 교환", "wrong", "축적 교환은 저장 후 전달의 일반적 성격을 가리키며 연결 설정·해제 조건을 직접 설명하지 않음.", "4강 저장 후 전달 개념."),
    ],
  },
  {
    id: "network-rebuilt-14",
    number: 14,
    patternId: "addressing-routing-flow",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(4, "주소지정"), lectureRef(6, "흐름제어")],
    conceptTags: ["주소지정", "흐름제어", "라우팅"],
    refs: ["2015-19", "2016-19", "2017-19", "2018-18", "2019-18"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "주소지정 기능과 가장 거리가 먼 것은?",
    correctChoice: "3",
    explanation: "주소지정은 통신망의 사용자나 장치를 식별하는 기능이고, 흐름제어는 송수신 속도와 처리량을 조절하는 기능.",
    examSkill: "naming, identification은 주소지정 주변 개념이고, flow control은 제어 대상 자체가 다름.",
    choices: [
      c("1", "명명", "wrong", "명명은 대상을 이름으로 식별하는 방식이므로 주소지정의 주변 기능으로 볼 수 있음.", "4강 주소지정 기능."),
      c("2", "식별", "wrong", "식별은 통신 상대나 자원을 구분하는 기능으로 주소지정과 밀접함.", "4강 주소지정 기능."),
      c("3", "흐름 제어", "correct", "흐름제어는 데이터가 너무 빠르게 전달되지 않도록 조절하는 기능이라 주소지정과 분리됨.", "6강 흐름제어."),
      c("4", "문자나 숫자로 사용자를 구분하는 방법", "wrong", "문자나 숫자를 이용한 구분은 주소나 이름 체계의 설명에 해당.", "4강 주소지정 방식."),
    ],
  },
  {
    id: "network-rebuilt-15",
    number: 15,
    patternId: "error-detection-codes",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(5, "패리티 검사")],
    conceptTags: ["홀수 패리티", "오류검출"],
    refs: ["2015-20", "2016-20", "2017-20", "2018-19", "2019-19"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "데이터 비트 1001101에 홀수 패리티를 적용하려고 한다. 패리티 비트 값은?",
    correctChoice: "2",
    explanation: "1001101에는 1이 4개 있으므로 전체 1의 개수를 홀수로 만들기 위해 패리티 비트는 1.",
    examSkill: "패리티 문항은 먼저 데이터 비트의 1 개수를 세고, 홀수/짝수 기준에 맞도록 b7을 결정.",
    choices: [
      c("1", "0", "wrong", "0을 붙이면 전체 1의 개수가 여전히 4개라 짝수가 되어 홀수 패리티 조건을 만족하지 못함.", "5강 홀수 패리티."),
      c("2", "1", "correct", "1을 붙이면 전체 1의 개수가 5개가 되어 홀수 패리티 조건을 만족.", "5강 홀수 패리티."),
      c("3", "10", "wrong", "패리티 비트는 한 자리 비트로 결정하며 두 비트 값을 붙이는 방식이 아님.", "5강 패리티 비트 정의."),
      c("4", "결정할 수 없음", "wrong", "데이터 비트와 패리티 종류가 주어졌으므로 계산으로 결정 가능.", "5강 패리티 검사 절차."),
    ],
  },
  {
    id: "network-rebuilt-16",
    number: 16,
    patternId: "error-detection-codes",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(5, "CRC")],
    conceptTags: ["CRC", "순환 코드", "다항식"],
    refs: ["2017-22", "2018-21", "2019-21"],
    sourceLabel: "2017·2018·2019 기출형",
    prompt: "CRC 방식에 대한 설명으로 가장 알맞은 것은?",
    correctChoice: "4",
    explanation: "CRC는 전송할 비트열을 다항식으로 보고 생성 다항식으로 나눈 나머지를 검사부호로 사용하는 오류검출 방식.",
    examSkill: "수식형 문제는 다항식의 계수 유무를 비트열로 바꾸고 나머지 계산 절차를 적용.",
    choices: [
      c("1", "각 문자마다 시작 비트와 정지 비트를 붙여 오류를 검출한다.", "wrong", "시작·정지 비트는 비동기 전송의 동기 보조 비트이지 CRC 검사부호가 아님.", "2강 비동기 전송과 5강 CRC 구분."),
      c("2", "문자 블록의 각 열에 대해 패리티를 계산하는 방식이다.", "wrong", "열 방향 패리티를 계산하는 방식은 LRC 설명에 가까움.", "5강 LRC."),
      c("3", "수신자가 오류 프레임 이후의 모든 프레임을 재전송한다.", "wrong", "재전송 범위는 ARQ 방식의 설명이며 CRC는 오류검출 부호.", "5강 ARQ와 오류검출 구분."),
      c("4", "비트열을 다항식으로 보고 나눗셈의 나머지를 검사부호로 붙인다.", "correct", "순환잉여검사의 핵심 절차를 설명.", "5강 CRC."),
    ],
  },
  {
    id: "network-rebuilt-17",
    number: 17,
    patternId: "arq-error-control",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(5, "ARQ")],
    conceptTags: ["Go-Back-N", "Selective Repeat", "정지-대기"],
    refs: ["2015-22", "2016-22", "2017-23", "2018-22", "2019-22"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "Go-Back-N ARQ 방식의 설명으로 가장 알맞은 것은?",
    correctChoice: "2",
    explanation: "Go-Back-N은 오류가 발생한 프레임부터 그 이후의 프레임을 다시 전송하는 슬라이딩 윈도우 기반 ARQ.",
    examSkill: "Selective Repeat은 오류 프레임만, Stop-and-Wait은 한 프레임씩 기다림이라는 차이로 고름.",
    choices: [
      c("1", "송신자가 한 프레임을 보낸 뒤 응답을 받을 때까지 다음 프레임을 보내지 않는다.", "wrong", "한 프레임씩 기다리는 설명은 정지-대기 ARQ에 해당.", "5강 정지-대기 ARQ."),
      c("2", "오류가 난 프레임부터 뒤의 프레임들을 다시 전송한다.", "correct", "Go-Back-N의 재전송 범위와 일치.", "5강 Go-Back-N ARQ."),
      c("3", "오류가 난 프레임만 선택적으로 다시 전송한다.", "wrong", "오류 프레임만 다시 보내는 방식은 선택적 반복 ARQ의 핵심.", "5강 Selective Repeat ARQ."),
      c("4", "오류를 스스로 정정하므로 재전송이 필요 없다.", "wrong", "ARQ는 자동 반복 요청 방식으로 오류 검출 후 재전송을 이용.", "5강 ARQ 정의."),
    ],
  },
  {
    id: "network-rebuilt-18",
    number: 18,
    patternId: "flow-control-principles",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(6, "흐름제어 원칙")],
    conceptTags: ["ask-and-wait", "stop-and-wait", "sliding window"],
    refs: ["2015-23", "2016-24", "2017-24", "2018-23", "2019-24"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "ask-and-wait 방법과 가장 관계가 깊은 흐름제어 원칙은?",
    correctChoice: "3",
    explanation: "ask-and-wait는 송신 전 수신자의 승낙을 기다리는 방식이므로 단일 승낙 원칙과 연결.",
    examSkill: "문항의 영어식 방법 이름과 원칙명을 서로 바꿔 묻는 형태가 반복됨.",
    choices: [
      c("1", "속도 조절의 원칙", "wrong", "속도 조절은 송신 속도 자체를 조절하는 원칙으로 ask-and-wait의 승낙 절차와 다름.", "6강 흐름제어 원칙."),
      c("2", "거부의 원칙", "wrong", "거부의 원칙은 수신자가 전송 중지를 알리는 방식과 연결됨.", "6강 wait-before-go 방식."),
      c("3", "단일 승낙의 원칙", "correct", "승낙을 기다린 뒤 보내는 ask-and-wait의 동작과 일치.", "6강 ask-and-wait."),
      c("4", "다중 승낙의 원칙", "wrong", "다중 승낙은 여러 프레임 전송과 윈도우 방식에 더 가까움.", "6강 sliding window."),
    ],
  },
  {
    id: "network-rebuilt-19",
    number: 19,
    patternId: "routing-methods",
    category: "오류·흐름 제어",
    lectureRefs: [lectureRef(6, "라우팅")],
    conceptTags: ["플러딩", "분산형 라우팅", "적응적 라우팅"],
    refs: ["2015-24", "2017-25", "2019-25"],
    sourceLabel: "2015·2017·2019 기출형",
    prompt: "데이터가 들어온 방향을 제외한 모든 방향으로 데이터를 전달하는 라우팅 방식은?",
    correctChoice: "4",
    explanation: "플러딩은 수신한 링크를 제외하고 가능한 모든 링크로 패킷을 복사해 전달하는 방식.",
    examSkill: "분산형, 고정, 랜덤, 플러딩은 경로 선택 주체와 전달 범위로 구분.",
    choices: [
      c("1", "랜덤 라우팅", "wrong", "랜덤 라우팅은 임의의 출력 경로를 선택하는 방식이지 모든 방향으로 복사 전송하는 방식이 아님.", "6강 라우팅 방식."),
      c("2", "델타 라우팅", "wrong", "델타 라우팅은 특정 비용 기준을 활용하는 방식으로, 모든 링크에 전파하는 설명과 다름.", "6강 라우팅 방식."),
      c("3", "분산형 라우팅", "wrong", "분산형 라우팅은 각 노드가 경로 정보를 분산 관리하는 방식이며 전 방향 복사 전송 자체를 뜻하지 않음.", "6강 분산형 라우팅."),
      c("4", "플러딩 라우팅", "correct", "들어온 곳을 제외한 모든 방향으로 전달한다는 설명과 일치.", "6강 플러딩."),
    ],
  },
  {
    id: "network-rebuilt-20",
    number: 20,
    patternId: "layering-encapsulation",
    category: "프로토콜·계층",
    lectureRefs: [lectureRef(7, "계층화 원칙")],
    conceptTags: ["계층화", "인터페이스"],
    refs: ["2015-25", "2016-25", "2017-18", "2018-24"],
    sourceLabel: "2015·2016·2017·2018 기출형",
    prompt: "OSI 계층화 원칙으로 적절하지 않은 것은?",
    correctChoice: "2",
    explanation: "계층화는 인접 계층 간 명확한 인터페이스를 두고 기능을 분리하는 방식이며 모든 계층이 모든 계층과 상호작용하도록 만들지 않음.",
    examSkill: "계층화 문제는 '최소 상호작용', '필요한 경계', '유사 기능 동일 계층' 같은 표현을 확인.",
    choices: [
      c("1", "쉽게 구분되는 기능을 하나의 계층으로 만든다.", "wrong", "기능을 계층별로 분리하는 방향은 계층화 원칙에 부합.", "7강 계층화 원칙."),
      c("2", "각 계층은 모든 계층과 직접 상호작용하도록 만든다.", "correct", "계층 구조는 인접 계층 인터페이스를 중심으로 하므로 모든 계층 간 직접 상호작용을 요구하지 않음.", "7강 계층 간 인터페이스."),
      c("3", "필요한 경우 표준화된 인터페이스를 가질 수 있는 곳에 경계를 둔다.", "wrong", "명확한 인터페이스 경계 설정은 계층화의 중요한 기준.", "7강 계층 경계 설정."),
      c("4", "유사한 기능은 같은 계층에 있도록 한다.", "wrong", "유사 기능을 같은 계층으로 묶는 것은 계층화 원칙과 일치.", "7강 기능 분리 원칙."),
    ],
  },
  {
    id: "network-rebuilt-21",
    number: 21,
    patternId: "layering-encapsulation",
    category: "프로토콜·계층",
    lectureRefs: [lectureRef(7, "캡슐화")],
    conceptTags: ["캡슐화", "역캡슐화", "PDU"],
    refs: ["2016-26", "2019-26"],
    sourceLabel: "2016·2019 기출형",
    prompt: "송신 측에서 상위 계층 데이터에 제어 정보를 붙여 하위 계층으로 전달하는 과정은?",
    correctChoice: "1",
    explanation: "캡슐화는 상위 계층의 데이터에 헤더 등 프로토콜 제어정보를 추가해 하위 계층으로 내려보내는 과정.",
    examSkill: "수신 측에서 제어 정보를 제거하는 역캡슐화와 방향을 혼동하지 않음.",
    choices: [
      c("1", "캡슐화", "correct", "송신 측에서 제어정보를 덧붙이는 과정이므로 캡슐화와 일치.", "7강 캡슐화."),
      c("2", "역캡슐화", "wrong", "역캡슐화는 수신 측에서 계층을 올라가며 헤더를 제거하는 과정.", "7강 역캡슐화."),
      c("3", "라우팅", "wrong", "라우팅은 목적지까지의 경로 선택 기능이며 상위 데이터에 제어정보를 붙이는 절차가 아님.", "6강 라우팅과 7강 캡슐화 구분."),
      c("4", "동기화", "wrong", "동기화는 송수신 타이밍을 맞추는 기능으로 계층별 제어정보 추가 절차와 구분.", "4강 동기화."),
    ],
  },
  {
    id: "network-rebuilt-22",
    number: 22,
    patternId: "tcpip-model",
    category: "TCP/IP",
    lectureRefs: [lectureRef(7, "TCP/IP 모델")],
    conceptTags: ["TCP/IP", "프로토콜 스위트", "DoD"],
    refs: ["2016-27", "2017-26", "2018-25", "2019-27"],
    sourceLabel: "2016·2017·2018·2019 기출형",
    prompt: "TCP/IP에 관한 설명으로 적절하지 않은 것은?",
    correctChoice: "1",
    explanation: "TCP/IP는 OSI 7계층을 그대로 따르는 단일 프로토콜이 아니라 여러 프로토콜로 구성된 인터넷 모델.",
    examSkill: "TCP/IP 문항은 '단일 프로토콜', 'OSI 7계층 그대로'라는 표현을 조심.",
    choices: [
      c("1", "TCP/IP 프로토콜 계층은 ISO의 OSI 7계층 모델을 그대로 따른다.", "correct", "TCP/IP는 OSI와 대응해 설명할 수는 있지만 OSI 7계층을 그대로 따르는 모델은 아님.", "7강 TCP/IP 모델."),
      c("2", "IP는 OSI 관점에서 네트워크 계층 기능에 해당한다.", "wrong", "IP는 인터넷 계층에서 데이터그램 전달을 맡고 OSI 네트워크 계층과 기능상 대응.", "8강 IP."),
      c("3", "TCP/IP는 여러 프로토콜의 집합으로 구성된다.", "wrong", "TCP, UDP, IP, ICMP 등 여러 프로토콜을 묶은 프로토콜 스위트로 설명.", "7강 프로토콜 스위트."),
      c("4", "TCP는 전송 계층 프로토콜로 다룬다.", "wrong", "TCP는 전송 계층에서 신뢰성 있는 연결형 전송을 제공.", "9강 TCP."),
    ],
  },
  {
    id: "network-rebuilt-23",
    number: 23,
    patternId: "ip-helper-protocols",
    category: "TCP/IP",
    lectureRefs: [lectureRef(8, "IP와 보조 프로토콜")],
    conceptTags: ["ARP", "RARP", "ICMP", "DHCP"],
    refs: ["2015-29", "2015-30", "2016-29", "2016-30", "2017-29", "2018-29", "2019-30"],
    sourceLabel: "2015~2019 반복 기출형",
    prompt: "호스트의 IP 주소는 알고 있지만 그에 대응하는 물리주소를 모를 때 사용하는 프로토콜은?",
    correctChoice: "1",
    explanation: "ARP는 IP 주소를 물리주소로 매핑해 같은 물리망 안에서 실제 프레임 전달에 필요한 주소를 얻음.",
    examSkill: "RARP는 물리주소에서 IP 주소를 얻는 방향, DHCP는 주소를 동적으로 임대하는 기능.",
    choices: [
      c("1", "ARP", "correct", "IP 주소를 알고 물리주소를 얻는 주소 변환 프로토콜.", "8강 ARP."),
      c("2", "RARP", "wrong", "RARP는 물리주소만 알고 자신의 IP 주소를 얻을 때 사용하는 반대 방향 프로토콜.", "8강 RARP."),
      c("3", "DNS", "wrong", "DNS는 도메인 이름과 IP 주소를 대응시키는 응용 계층 서비스로 물리주소 변환 기능이 아님.", "10강 DNS와 8강 ARP 구분."),
      c("4", "DHCP", "wrong", "DHCP는 IP 주소와 설정 정보를 동적으로 할당·임대하는 프로토콜.", "8강 DHCP."),
    ],
  },
  {
    id: "network-rebuilt-24",
    number: 24,
    patternId: "ip-helper-protocols",
    category: "TCP/IP",
    lectureRefs: [lectureRef(8, "IP 데이터그램")],
    conceptTags: ["IP 헤더", "프로토콜 필드", "상위 프로토콜"],
    refs: ["2016-28", "2018-26", "2019-28"],
    sourceLabel: "2016·2018·2019 기출형",
    prompt: "IP 데이터그램 헤더의 protocol 필드에 대한 설명으로 적절한 것은?",
    correctChoice: "2",
    explanation: "IP 헤더의 protocol 필드는 데이터그램의 데이터 부분이 어떤 상위 계층 프로토콜에 전달될지 식별.",
    examSkill: "기출에서는 이 필드를 하위 계층 프로토콜 식별이라고 뒤집어 제시하는 함정이 있었음.",
    choices: [
      c("1", "데이터링크 계층의 물리 매체 종류를 표시한다.", "wrong", "물리 매체 종류는 IP 헤더 protocol 필드가 담당하는 정보가 아님.", "8강 IP 헤더 필드."),
      c("2", "상위 계층 프로토콜을 식별한다.", "correct", "TCP, UDP, ICMP 같은 상위 전달 대상을 구분하는 필드.", "8강 IP protocol 필드."),
      c("3", "IP 주소의 클래스 A-E를 표시한다.", "wrong", "주소 클래스는 IP 주소의 비트 패턴과 범위로 구분하며 protocol 필드의 역할이 아님.", "8강 IPv4 주소."),
      c("4", "프레임의 MAC 주소를 저장한다.", "wrong", "MAC 주소는 데이터링크 계층 프레임에서 사용하며 IP 헤더 protocol 필드와 다름.", "8강 IP와 LAN 주소 구분."),
    ],
  },
  {
    id: "network-rebuilt-25",
    number: 25,
    patternId: "tcp-udp-apps",
    category: "TCP/IP",
    lectureRefs: [lectureRef(9, "TCP와 UDP")],
    conceptTags: ["TCP", "UDP", "전송 계층"],
    refs: ["2015-26", "2017-28", "2018-27", "2019-29"],
    sourceLabel: "2015·2017·2018·2019 기출형",
    prompt: "TCP와 UDP에 관한 설명으로 옳은 것은?",
    correctChoice: "3",
    explanation: "UDP는 TCP와 함께 전송 계층 프로토콜이며 비연결형 데이터그램 전송 서비스를 제공.",
    examSkill: "TCP는 연결형·신뢰성, UDP는 비연결형·낮은 오버헤드라는 대비가 핵심.",
    choices: [
      c("1", "TCP는 인터넷 계층 프로토콜이다.", "wrong", "TCP는 전송 계층 프로토콜이며 인터넷 계층 기능은 IP가 담당.", "9강 TCP 계층 위치."),
      c("2", "TCP는 비연결 전송 서비스만 제공한다.", "wrong", "TCP는 연결 설정 후 신뢰성 있는 전송을 제공하는 연결형 프로토콜.", "9강 TCP 특징."),
      c("3", "UDP는 전송 계층 프로토콜이다.", "correct", "UDP는 사용자 데이터그램을 제공하는 전송 계층 프로토콜.", "9강 UDP."),
      c("4", "UDP는 연결 전송 서비스로 신뢰성이 높다.", "wrong", "UDP는 비연결형이며 신뢰성 보장과 순서 제어를 TCP처럼 제공하지 않음.", "9강 UDP 특징."),
    ],
  },
  {
    id: "network-rebuilt-26",
    number: 26,
    patternId: "ip-helper-protocols",
    category: "TCP/IP",
    lectureRefs: [lectureRef(8, "DHCP")],
    conceptTags: ["DHCP", "BOOTP", "동적 주소 할당"],
    refs: ["2016-30", "2019-30"],
    sourceLabel: "2016·2019 기출형",
    prompt: "DHCP에 대한 설명으로 가장 알맞은 것은?",
    correctChoice: "4",
    explanation: "DHCP는 BOOTP에서 발전한 동적 주소 할당 프로토콜로, IP 주소를 일정 기간 임대하고 재사용할 수 있게 함.",
    examSkill: "DHCP는 응용 계층 프로토콜이지만 기능은 IP 설정 자동화이므로 ICMP·IGMP와 역할을 분리.",
    choices: [
      c("1", "IP 데이터그램 전송 오류에 대한 오류 메시지를 제공한다.", "wrong", "오류·제어 메시지 제공은 ICMP의 주요 역할.", "8강 ICMP."),
      c("2", "멀티캐스트 그룹 가입 정보를 라우터에 알린다.", "wrong", "멀티캐스트 그룹 관리는 IGMP의 역할.", "8강 IGMP."),
      c("3", "IP 주소를 물리주소로 변환한다.", "wrong", "IP 주소에서 물리주소를 얻는 기능은 ARP가 담당.", "8강 ARP."),
      c("4", "IP 주소와 설정 정보를 동적으로 할당한다.", "correct", "DHCP는 주소 풀에서 사용 가능한 주소를 임대하고 네트워크 설정을 자동 제공.", "8강 DHCP."),
    ],
  },
  {
    id: "network-rebuilt-27",
    number: 27,
    patternId: "lan-model-mac",
    category: "LAN",
    lectureRefs: [lectureRef(11, "LAN 매체접근"), lectureRef(12, "IEEE 802")],
    conceptTags: ["CSMA/CD", "토큰링", "토큰버스"],
    refs: ["2018-30", "2019-31"],
    sourceLabel: "2018·2019 기출형",
    prompt: "토큰 전달 방식과 가장 관련이 적은 LAN 기술은?",
    correctChoice: "1",
    explanation: "CSMA/CD 기반 이더넷은 경쟁 방식으로 매체에 접근하며 토큰을 순환시키는 방식이 아님.",
    examSkill: "토큰링·토큰버스는 토큰 방식, CSMA/CD는 경쟁 기반 이더넷으로 분리.",
    choices: [
      c("1", "CSMA/CD 이더넷", "correct", "충돌 감지 기반 경쟁 방식으로 토큰을 사용하지 않음.", "11강 LAN 매체접근 방식."),
      c("2", "토큰링", "wrong", "토큰링은 토큰을 가진 노드만 전송하는 대표적인 토큰 전달 방식.", "11강 토큰링."),
      c("3", "토큰버스", "wrong", "토큰버스는 논리적 토큰 순환을 사용하는 매체접근 방식.", "11강 토큰버스."),
      c("4", "IEEE 802.5", "wrong", "IEEE 802.5는 토큰링 표준과 연결되는 번호로 토큰 방식과 관련 있음.", "12강 IEEE 802 표준."),
    ],
  },
  {
    id: "network-rebuilt-28",
    number: 28,
    patternId: "wireless-lan",
    category: "LAN",
    lectureRefs: [lectureRef(12, "무선 LAN")],
    conceptTags: ["Ad-Hoc", "Infrastructure", "IEEE 802.11"],
    refs: ["2015-32", "2017-31", "2018-31", "2019-32"],
    sourceLabel: "2015·2017·2018·2019 기출형",
    prompt: "무선 LAN에 대한 설명으로 적절하지 않은 것은?",
    correctChoice: "4",
    explanation: "무선 LAN은 이동성과 설치 편의성이 장점이지만 전파 특성상 유선 LAN보다 보안에 취약한 면이 있음.",
    examSkill: "애드혹은 단말 간 직접 통신, 인프라스트럭처는 AP를 거치는 방식.",
    choices: [
      c("1", "IEEE 802.11 표준과 관련이 있다.", "wrong", "IEEE 802.11은 무선 LAN과 관련된 표준이므로 적절한 설명.", "12강 IEEE 802.11."),
      c("2", "Ad-Hoc 방식에서는 노드들이 직접 통신할 수 있다.", "wrong", "애드혹 방식은 AP 없이 단말 간 직접 통신하는 형태.", "12강 Ad-Hoc 방식."),
      c("3", "Infrastructure 방식에서는 AP를 통해 통신한다.", "wrong", "인프라스트럭처 방식은 AP가 중심 장치로 동작.", "12강 Infrastructure 방식."),
      c("4", "유선 LAN보다 보안성이 항상 강하다.", "correct", "무선 매체는 전파가 공간으로 퍼지므로 도청과 접근 통제가 어려워 보안 취약점이 생길 수 있음.", "12강 무선 LAN 특성."),
    ],
  },
  {
    id: "network-rebuilt-29",
    number: 29,
    patternId: "security-requirements",
    category: "보안",
    lectureRefs: [lectureRef(13, "네트워크 보안 요구사항")],
    conceptTags: ["부인 방지", "무결성", "인증"],
    refs: ["2015-34", "2018-32"],
    sourceLabel: "2015·2018 기출형",
    prompt: "데이터 송신이나 수신 사실에 대한 확인이 가능해야 한다는 요구사항은?",
    correctChoice: "2",
    explanation: "부인 방지는 송신자나 수신자가 이후에 송수신 사실을 부인하지 못하게 하는 보안 요구사항.",
    examSkill: "무결성은 내용 변경 여부, 인증은 신원 확인, 부인 방지는 행위 사실 확인에 초점.",
    choices: [
      c("1", "데이터 무결성", "wrong", "데이터 무결성은 전송 중 내용이 변경되지 않았는지 확인하는 요구사항.", "13강 데이터 무결성."),
      c("2", "부인 방지", "correct", "송신 또는 수신 사실을 나중에 부인하지 못하게 하는 요구사항.", "13강 부인 방지."),
      c("3", "실체 인증", "wrong", "실체 인증은 통신 주체가 누구인지 확인하는 요구사항.", "13강 실체 인증."),
      c("4", "데이터 보안성", "wrong", "데이터 보안성은 정보가 허가되지 않은 대상에게 노출되지 않도록 하는 기밀성 측면과 관련.", "13강 데이터 보안성."),
    ],
  },
  {
    id: "network-rebuilt-30",
    number: 30,
    patternId: "malware-fraud",
    category: "보안",
    lectureRefs: [lectureRef(13, "인터넷 사기와 악성 프로그램")],
    conceptTags: ["파밍", "피싱", "트로이 목마"],
    refs: ["2016-33", "2017-32", "2019-33"],
    sourceLabel: "2016·2017·2019 기출형",
    prompt: "도메인이나 DNS 이름을 속여 사용자를 가짜 사이트로 유도하고 개인정보를 훔치는 수법은?",
    correctChoice: "2",
    explanation: "파밍은 정상 주소를 입력해도 조작된 주소 해석 등을 통해 가짜 사이트로 유도하는 공격으로 정리.",
    examSkill: "피싱은 사용자를 속이는 유인 메시지, 파밍은 주소 해석 조작 단서가 핵심.",
    choices: [
      c("1", "피싱", "wrong", "피싱은 기관이나 사이트를 사칭한 메시지로 사용자를 유인하는 방식이 중심.", "13강 피싱."),
      c("2", "파밍", "correct", "DNS나 도메인 주소 조작으로 사용자가 진짜 사이트로 오인하게 만드는 방식.", "13강 파밍."),
      c("3", "웜", "wrong", "웜은 자기 복제를 통해 네트워크로 확산되는 악성 프로그램.", "13강 웜."),
      c("4", "트로이 목마", "wrong", "트로이 목마는 정상 프로그램처럼 가장해 실행되는 악성 프로그램.", "13강 트로이 목마."),
    ],
  },
  {
    id: "network-rebuilt-31",
    number: 31,
    patternId: "crypto-signature",
    category: "보안",
    lectureRefs: [lectureRef(14, "디지털 서명")],
    conceptTags: ["공개키", "개인키", "디지털 서명"],
    refs: ["2016-34", "2017-33", "2018-33", "2018-34", "2019-34", "2019-35"],
    sourceLabel: "2016~2019 반복 기출형",
    prompt: "송신자 A가 디지털 서명을 생성하고 수신자 B가 이를 검증하는 키 사용 방향으로 가장 알맞은 것은?",
    correctChoice: "1",
    explanation: "디지털 서명은 송신자 A의 개인키로 서명하고, 수신자는 A의 공개키로 검증.",
    examSkill: "기밀성 암호화는 수신자 공개키 방향, 디지털 서명은 송신자 개인키 방향이라는 차이를 분리.",
    choices: [
      c("1", "A의 개인키로 서명하고 B는 A의 공개키로 검증한다.", "correct", "서명은 송신자만 가진 개인키로 만들고 누구나 얻을 수 있는 송신자 공개키로 검증 가능.", "14강 디지털 서명."),
      c("2", "A의 공개키로 서명하고 B는 A의 개인키로 검증한다.", "wrong", "송신자의 개인키는 송신자만 보유해야 하므로 수신자가 A의 개인키로 검증한다는 설명은 키 관리 원칙에 맞지 않음.", "14강 공개키/개인키 역할."),
      c("3", "B의 개인키로 서명하고 A의 공개키로 검증한다.", "wrong", "서명자는 송신자 A이므로 B의 개인키가 서명 생성에 사용되지 않음.", "14강 디지털 서명 주체."),
      c("4", "공통키 하나로 서명과 검증을 모두 수행한다.", "wrong", "디지털 서명은 공개키 암호 기반의 키 쌍을 사용하는 구조로 설명.", "14강 공개키 기반 서명."),
    ],
  },
  {
    id: "network-rebuilt-32",
    number: 32,
    patternId: "firewall-systems",
    category: "보안",
    lectureRefs: [lectureRef(14, "방화벽")],
    conceptTags: ["방화벽", "패킷 필터링", "보안 장치"],
    refs: ["2015-35", "2016-35", "2017-34", "2017-35", "2018-35"],
    sourceLabel: "2015~2018 반복 기출형",
    prompt: "네트워크와 네트워크 사이에서 송수신되는 패킷을 검사해 조건에 맞는 패킷만 통과시키는 장치는?",
    correctChoice: "1",
    explanation: "방화벽은 보호 대상 망과 외부망 사이의 트래픽을 정책에 따라 통제하며 패킷 필터링 기능을 포함.",
    examSkill: "프락시 서버, 스크리닝 라우터, 배스천 호스트는 방화벽 구성요소로 자주 연결되고, 일반 허브류는 방화벽이 아님.",
    choices: [
      c("1", "방화벽", "correct", "네트워크 경계에서 트래픽을 통제하고 조건에 맞는 패킷만 허용하는 장치.", "14강 방화벽."),
      c("2", "디지털 서명", "wrong", "디지털 서명은 메시지 출처와 무결성을 확인하는 암호 기술이지 네트워크 경계 패킷 통제 장치가 아님.", "14강 디지털 서명과 방화벽 구분."),
      c("3", "트로이 목마", "wrong", "트로이 목마는 악성 프로그램 유형이며 보안 장치가 아님.", "13강 악성 프로그램."),
      c("4", "공개키 기반구조", "wrong", "PKI는 공개키 인증서와 키 관리를 위한 기반 구조로, 패킷 필터링 장치 자체가 아님.", "14강 공개키 기반구조."),
    ],
  },
  {
    id: "network-rebuilt-33",
    number: 33,
    patternId: "tcp-udp-apps",
    category: "TCP/IP",
    lectureRefs: [lectureRef(10, "응용 계층 프로토콜")],
    conceptTags: ["FTP", "DNS", "ping", "TCP/UDP"],
    refs: ["2015-27", "2017-27"],
    sourceLabel: "2015·2017 기출형",
    prompt: "다음 중 TCP를 이용하는 응용 프로그램으로 가장 알맞은 것은?",
    correctChoice: "1",
    explanation: "FTP는 파일 전송을 위해 TCP 기반의 신뢰성 있는 전송을 이용하는 대표 응용 프로토콜.",
    examSkill: "DNS는 일반적으로 UDP 기반, ping은 ICMP 이용, FTP·TELNET·SMTP 계열은 TCP 기반으로 정리.",
    choices: [
      c("1", "FTP", "correct", "FTP는 TCP를 이용하는 파일 전송 프로토콜로 반복 정리됨.", "10강 FTP."),
      c("2", "DNS", "wrong", "DNS는 일반 질의에서 UDP를 이용하는 대표 응용 계층 프로토콜로 다룸.", "10강 DNS."),
      c("3", "ICMP", "wrong", "ICMP는 인터넷 계층의 오류·제어 메시지 프로토콜이며 TCP를 이용하는 응용 프로그램이 아님.", "8강 ICMP."),
      c("4", "ping", "wrong", "ping은 TCP나 UDP가 아니라 ICMP를 이용해 동작하는 진단 기능으로 설명.", "8강 ICMP와 10강 응용 프로토콜 구분."),
    ],
  },
];
