import type { JavaLectureDeepDive } from "./types";

export const javaDeepDiveData: Record<number, JavaLectureDeepDive> = {
  1: {
    sourceBasis: "강의록 1강 Java 언어 개요, JDK와 이클립스 설치, Java 소스의 구성 / 교재 대응 장: 1장 / 공식 연습문제 1강",
    terms: [
      {
        term: "JDK",
        definition: "Java Development Kit. Java 프로그램을 만들기 위한 개발 도구 묶음이다.",
        role: "소스 코드를 컴파일하는 `javac`, 실행 명령 `java`, 표준 API 문서화 도구 등을 포함해 개발자가 코드를 작성하고 class 파일을 만들 수 있게 한다.",
        distinction: "JRE가 실행 환경 중심이라면 JDK는 개발 환경이다. JDK 안에는 보통 JRE에 해당하는 실행 구성도 함께 들어 있으므로 개발자는 JDK를 설치한다.",
        example: "`javac HelloWorld.java`로 `HelloWorld.class`를 만드는 단계는 JDK의 컴파일러가 담당한다.",
      },
      {
        term: "JRE",
        definition: "Java Runtime Environment. 이미 컴파일된 Java 프로그램을 실행하기 위한 환경이다.",
        role: "JVM과 표준 클래스 라이브러리를 제공해 `.class` 바이트코드가 운영체제 위에서 실행되도록 한다.",
        distinction: "JDK처럼 개발 도구 전체를 제공하지 않는다. 소스 작성과 컴파일이 아니라 실행에 초점이 있다.",
        example: "사용자가 완성된 Java 앱을 실행할 때 필요한 것은 컴파일러가 아니라 JRE의 실행 환경이다.",
      },
      {
        term: "JVM",
        definition: "Java Virtual Machine. Java 바이트코드를 실제 기계에서 실행되도록 해석하거나 컴파일해 실행하는 가상 머신이다.",
        role: "운영체제와 하드웨어 차이를 JVM 계층에서 흡수해 같은 바이트코드가 여러 환경에서 실행되도록 한다.",
        distinction: "JRE는 실행 환경 전체이고 JVM은 그 안에서 바이트코드를 실행하는 핵심 엔진이다.",
        example: "Windows용 JVM과 macOS용 JVM은 서로 다르지만 둘 다 같은 `HelloWorld.class`를 실행할 수 있다.",
      },
      {
        term: "바이트코드",
        definition: "Java 컴파일러가 `.java` 소스에서 생성하는 JVM용 중간 코드이다.",
        role: "특정 CPU의 기계어가 아니라 JVM이 이해하는 명령 형식이므로 Java의 플랫폼 독립성을 가능하게 한다.",
        distinction: "소스 코드는 사람이 읽고 수정하는 `.java` 파일이고, 바이트코드는 컴파일 후 생성되는 `.class` 파일의 내용이다.",
        example: "`public class A { } class B { }`가 들어 있는 `A.java`를 컴파일하면 `A.class`, `B.class` 바이트코드 파일이 생긴다.",
      },
      {
        term: "main 메소드",
        definition: "Java 응용 프로그램의 실행 시작점으로 사용되는 정해진 형식의 메소드이다.",
        role: "JVM은 지정된 클래스에서 `public static void main(String[] args)`를 찾아 프로그램 실행을 시작한다.",
        distinction: "클래스가 컴파일 가능하다는 것과 main이 있어 직접 실행 가능하다는 것은 다르다.",
        example: "`System.out.println(\"Hello, World!\");`는 main 안에 있어야 앱 실행 시 출력된다.",
      },
    ],
    studio: {
      kind: "pipeline",
      title: "Java 실행 플랫폼 파이프라인",
      subtitle: "개발 도구와 실행 환경이 어느 단계에서 쓰이는지 분리해서 확인",
      prompt: "소스가 실행 결과가 되기까지 JDK, JRE, JVM, 바이트코드의 위치를 따라가 보세요.",
      items: [
        { label: "소스 작성", value: ".java", detail: "개발자가 클래스와 main 메소드를 작성한다.", note: "사람이 읽고 고치는 단계" },
        { label: "컴파일", value: "JDK / javac", detail: "JDK의 컴파일러가 소스를 바이트코드로 변환한다.", note: "개발 환경의 역할" },
        { label: "중간 결과", value: ".class", detail: "JVM이 이해하는 바이트코드 파일이 만들어진다.", note: "플랫폼 독립성의 중심" },
        { label: "실행 환경", value: "JRE", detail: "JVM과 표준 라이브러리가 실행에 필요한 환경을 제공한다.", note: "사용자 실행 환경" },
        { label: "실제 실행", value: "JVM", detail: "바이트코드를 현재 운영체제와 CPU에서 실행되도록 처리한다.", note: "운영체제별 JVM이 차이를 흡수" },
      ],
    },
  },

  2: {
    sourceBasis: "강의록 2강 Java 프로그램 기본 사항, 자료형, 연산자와 제어문 / 교재 대응 장: 2장-1 / 공식 연습문제 2강",
    terms: [
      {
        term: "식별자",
        definition: "클래스, 변수, 메소드 등에 개발자가 붙이는 이름이다.",
        role: "프로그램 안에서 대상을 구별하고 참조하는 표지 역할을 한다.",
        distinction: "키워드는 Java가 예약한 단어라 식별자로 사용할 수 없다.",
        example: "`HelloApplication`, `szMsg`, `main`은 식별자이고 `public`, `class`, `boolean`은 키워드이다.",
      },
      {
        term: "키워드",
        definition: "Java 문법에서 특별한 의미로 예약된 단어이다.",
        role: "자료형, 접근 제어, 제어문, 클래스 선언처럼 문장 구조를 결정한다.",
        distinction: "`Integer`, `String`, `System`은 클래스 이름이지만 `boolean`은 기본 자료형 키워드이다.",
        example: "`public class Main`에서 `public`과 `class`는 키워드이다.",
      },
      {
        term: "기본 자료형",
        definition: "값 자체를 저장하는 Java의 내장 자료형이다.",
        role: "논리값, 문자, 정수, 실수를 작은 단위의 값으로 표현한다.",
        distinction: "참조형은 객체의 위치를 참조하지만 기본 자료형 변수는 값 자체를 담는다.",
        example: "`int count = 10;`, `boolean done = false;`, `char grade = 'A';`",
      },
      {
        term: "리터럴",
        definition: "소스 코드에 직접 적은 고정 값이다.",
        role: "변수 초기화나 연산식에서 값의 타입과 표기 방식을 결정한다.",
        distinction: "정수 리터럴은 접두사에 따라 진법이 달라진다. `00001010`은 10진 1010이 아니라 8진수 표기이다.",
        example: "`10`, `0x0A`, `0b0000_1010`은 모두 10이지만 `00001010`은 8진수 520이다.",
      },
      {
        term: "향상된 for문",
        definition: "배열이나 컬렉션의 원소를 하나씩 꺼내 반복 변수에 대입하는 반복문이다.",
        role: "인덱스가 필요 없는 순회 코드를 간결하게 만든다.",
        distinction: "일반 for문은 인덱스와 조건을 직접 제어하고, 향상된 for문은 원소 순회만 표현한다.",
        example: "`for (int value : a) { System.out.print(value + \" \"); }`",
      },
    ],
    studio: {
      kind: "classifier",
      title: "문법 토큰 판별기",
      subtitle: "보기를 식별자, 키워드, 리터럴, 제어문으로 분류",
      prompt: "문법 문제를 풀 때는 먼저 단어가 이름인지, 예약어인지, 값 표기인지 구분합니다.",
      items: [
        { label: "Integer", value: "클래스 이름", detail: "java.lang의 래퍼 클래스 이름이다.", note: "식별자로 쓰일 수 있는 타입 이름" },
        { label: "boolean", value: "키워드", detail: "논리값 기본 자료형을 나타내는 예약어이다.", note: "클래스 이름이 아님" },
        { label: "00001010", value: "8진 리터럴", detail: "앞의 0 때문에 8진 정수로 해석된다.", note: "값은 520" },
        { label: "0x0A", value: "16진 리터럴", detail: "0x 접두사는 16진수를 뜻한다.", note: "값은 10" },
        { label: "for (int v : a)", value: "향상된 for문", detail: "배열 a의 원소가 v에 차례로 대입된다.", note: "인덱스 없이 순회" },
      ],
    },
  },

  3: {
    sourceBasis: "강의록 3강 배열, 문자열, Scanner 클래스, 클래스 정의와 접근 제어자 / 교재 대응 장: 2장-2·3장-1 / 공식 연습문제 3강",
    terms: [
      {
        term: "배열",
        definition: "같은 자료형의 여러 값을 인덱스로 접근하는 참조형 객체이다.",
        role: "동일한 성격의 데이터를 하나의 이름 아래 연속된 위치처럼 다루게 한다.",
        distinction: "배열 변수는 배열 객체를 참조한다. 선언만으로 원소 공간이 생기지 않고 `new`나 초기화식이 필요하다.",
        example: "`int[] scores = new int[5];`는 int 원소 5개를 담는 배열 객체를 만든다.",
      },
      {
        term: "가변 길이 2차원 배열",
        definition: "행마다 열의 길이가 다를 수 있는 배열의 배열 구조이다.",
        role: "각 행을 별도 배열로 만들어 불규칙한 표 형태 데이터를 표현한다.",
        distinction: "`twoArray.length`는 행 수이고 `twoArray[i].length`는 i번째 행의 열 수이다.",
        example: "`int[][] c = new int[5][];`는 행 배열만 먼저 생성한 올바른 문장이다.",
      },
      {
        term: "String",
        definition: "문자열을 객체로 표현하는 java.lang 패키지의 클래스이다.",
        role: "문자열 리터럴, 문자열 결합, 검색, 추출 같은 문자열 처리를 제공한다.",
        distinction: "문자 하나의 산술 연산과 문자열 결합은 다르다. 문자열이 끼어들면 이후 `+`는 결합이 된다.",
        example: "`System.out.println(i + \" \" + j);`는 두 값을 공백으로 구분해 출력한다.",
      },
      {
        term: "Scanner",
        definition: "입력 소스에서 토큰을 읽는 java.util 패키지의 클래스이다.",
        role: "키보드 입력이나 문자열에서 정수, 단어 등 필요한 값을 읽어 변수에 넣는다.",
        distinction: "단순 이름 `Scanner`를 쓰려면 `import java.util.Scanner;`가 필요하다.",
        example: "`Scanner sc = new Scanner(System.in); int n = sc.nextInt();`",
      },
      {
        term: "protected",
        definition: "같은 패키지 또는 상속 관계의 하위 클래스에서 접근할 수 있는 접근 제어자이다.",
        role: "완전 공개는 피하면서 하위 클래스 재사용에 필요한 멤버 접근을 허용한다.",
        distinction: "패키지 밖의 무관 클래스는 protected 멤버를 사용할 수 없다.",
        example: "다른 패키지의 `Gamma`가 `Alpha`의 protected 필드에 직접 접근하면 오류가 된다.",
      },
    ],
    studio: {
      kind: "matrix",
      title: "배열·접근 제어 판별 행렬",
      subtitle: "문장 형태와 접근 위치를 기준으로 정오를 가르는 표",
      prompt: "배열 문법은 대괄호 위치를, 접근 제어는 패키지와 상속 관계를 함께 확인합니다.",
      items: [
        { label: "int[][] c = new int[5][];", value: "올바름", detail: "첫 번째 차원만 지정한 2차원 배열 생성은 가능하다.", note: "행 배열 먼저 생성" },
        { label: "int b[] = new int(10);", value: "오류", detail: "배열 크기는 괄호가 아니라 대괄호에 쓴다.", note: "`new int[10]`이어야 함" },
        { label: "System.out.println(i, j)", value: "오류", detail: "println은 두 값을 쉼표로 받지 않는다.", note: "문자열 결합으로 하나의 인자를 만든다" },
        { label: "같은 패키지", value: "protected 접근 가능", detail: "상속 여부와 별개로 같은 패키지 접근이 허용된다.", note: "package 관계 확인" },
        { label: "패키지 밖 무관 클래스", value: "protected 접근 불가", detail: "하위 클래스도 같은 패키지도 아니면 사용할 수 없다.", note: "Gamma 유형" },
      ],
    },
  },

  4: {
    sourceBasis: "강의록 4강 static/final, 필드 초기화, 메소드 오버로딩, 상속, this/super / 교재 대응 장: 3장-2 / 공식 연습문제 4강",
    terms: [
      {
        term: "static",
        definition: "객체가 아니라 클래스 자체에 소속되는 멤버를 나타내는 키워드이다.",
        role: "모든 객체가 공유하는 값이나 객체 없이 호출하는 기능을 표현한다.",
        distinction: "인스턴스 필드는 객체마다 따로 존재하고 static 필드는 클래스에 하나 존재한다.",
        example: "`Math.sqrt(4.0)`은 Math 객체를 만들지 않고 static 메소드를 호출한다.",
      },
      {
        term: "final",
        definition: "변경, 재정의, 상속을 제한하기 위해 변수·메소드·클래스에 붙이는 키워드이다.",
        role: "상수, 오버라이딩 금지 메소드, 상속 금지 클래스를 만들 때 사용한다.",
        distinction: "final 클래스는 하위 클래스를 만들 수 없지만 그 클래스의 객체 생성은 가능하다.",
        example: "`static final double PI = 3.14;`는 클래스 수준 상수 선언이다.",
      },
      {
        term: "오버로딩",
        definition: "같은 이름의 메소드를 매개변수 목록이 다르게 여러 개 정의하는 것이다.",
        role: "같은 동작 이름을 유지하면서 입력 형태별 처리를 제공한다.",
        distinction: "반환형만 다르게 하는 것은 오버로딩 구분 기준이 아니다.",
        example: "`println()`과 `println(String x)`는 매개변수 목록이 달라 함께 존재한다.",
      },
      {
        term: "오버라이딩",
        definition: "상속받은 메소드를 하위 클래스에서 같은 시그니처로 다시 정의하는 것이다.",
        role: "상위 타입으로 다루더라도 실제 객체에 맞는 동작을 실행하게 한다.",
        distinction: "오버로딩은 같은 클래스 안의 이름 재사용이고, 오버라이딩은 상속 관계에서 동작을 재정의하는 것이다.",
        example: "`Shape t = new Triangle(); t.getArea(...)`는 Triangle의 재정의 메소드가 실행된다.",
      },
      {
        term: "this",
        definition: "현재 객체 자신을 가리키는 참조이다.",
        role: "필드와 매개변수 이름이 같거나 현재 객체의 다른 메소드를 명확히 호출할 때 사용한다.",
        distinction: "`super`가 부모 클래스 부분을 가리키는 데 비해 `this`는 현재 객체를 가리킨다.",
        example: "`this.radius = radius;`에서 왼쪽은 필드, 오른쪽은 매개변수이다.",
      },
    ],
    studio: {
      kind: "state",
      title: "객체 생성과 메소드 선택 타임라인",
      subtitle: "static 초기화부터 동적 바인딩까지 시간 순서로 확인",
      prompt: "클래스 멤버와 객체 멤버가 언제 준비되고 어떤 메소드가 실행되는지 따라갑니다.",
      items: [
        { label: "클래스 로딩", value: "static 준비", detail: "static 필드와 static 초기화 블록이 클래스 단위로 준비된다.", note: "객체 생성 전" },
        { label: "객체 생성", value: "인스턴스 필드", detail: "new가 실행되면 객체별 필드 공간이 만들어진다.", note: "객체마다 별도" },
        { label: "생성자", value: "this 사용", detail: "매개변수 값을 현재 객체 필드에 대입한다.", note: "`this.radius = radius`" },
        { label: "오버로딩 선택", value: "컴파일 시점", detail: "전달 인자의 개수와 타입으로 호출 대상이 정해진다.", note: "매개변수 목록 기준" },
        { label: "오버라이딩 실행", value: "실행 시점", detail: "실제 객체 타입의 재정의 메소드가 실행된다.", note: "동적 바인딩" },
      ],
    },
  },

  5: {
    sourceBasis: "강의록 5강 추상 클래스와 인터페이스, 다형성 / 교재 대응 장: 4장 / 공식 연습문제 5강",
    terms: [
      {
        term: "추상 메소드",
        definition: "본문 없이 선언만 있는 메소드이다.",
        role: "상위 타입에서 필요한 동작 이름을 정하고 실제 구현은 하위 클래스에 맡긴다.",
        distinction: "일반 메소드는 본문을 가지고 실행될 수 있지만 추상 메소드는 구현 클래스가 완성해야 한다.",
        example: "`abstract public double getArea();`는 모양별 면적 계산을 하위 클래스에 맡긴다.",
      },
      {
        term: "추상 클래스",
        definition: "직접 완성 객체를 만들 수 없고 하위 클래스의 공통 틀로 쓰이는 클래스이다.",
        role: "공통 필드나 일반 메소드와 함께 구현을 강제할 추상 메소드를 담을 수 있다.",
        distinction: "인터페이스보다 구현을 더 많이 가질 수 있지만 클래스 상속은 하나만 가능하다.",
        example: "`abstract class Shape`를 상속한 `Triangle`이 `getArea`를 구현한다.",
      },
      {
        term: "인터페이스",
        definition: "클래스가 제공해야 하는 동작의 규약을 정의하는 타입이다.",
        role: "서로 다른 클래스가 같은 메소드 집합을 제공하도록 약속을 만든다.",
        distinction: "클래스는 인터페이스를 `implements`로 구현하고, 인터페이스끼리는 `extends`로 확장한다.",
        example: "`class Point implements Movable, Scalable`은 두 규약을 동시에 구현한다.",
      },
      {
        term: "다형성",
        definition: "같은 메시지가 실제 객체 타입에 따라 다른 동작으로 실행되는 성질이다.",
        role: "상위 타입 변수 하나로 여러 하위 객체를 다루고, 오버라이딩된 메소드를 실행할 수 있게 한다.",
        distinction: "참조 변수의 선언 타입보다 실제 생성 객체와 오버라이딩 여부가 실행 결과를 좌우한다.",
        example: "부모 타입 참조가 자식 객체를 가리키면 자식의 재정의 메소드가 실행될 수 있다.",
      },
      {
        term: "익명 클래스",
        definition: "이름 없이 하위 클래스나 구현 클래스를 정의하면서 동시에 객체를 만드는 문법이다.",
        role: "한 번만 쓸 구현을 별도 클래스 이름 없이 즉석에서 제공한다.",
        distinction: "`new CSuper()`만 있는 단순 객체 생성이 아니라 뒤의 `{ ... }`가 익명 하위 클래스 본문이다.",
        example: "`CSuper sub = new CSuper() { };`는 CSuper를 상속한 익명 하위 클래스 객체를 만든다.",
      },
    ],
    studio: {
      kind: "graph",
      title: "상속·구현 관계 그래프",
      subtitle: "extends와 implements가 연결하는 타입 관계를 시각적으로 구분",
      prompt: "클래스와 인터페이스의 관계는 선의 의미가 다릅니다. 상속인지 구현인지 먼저 보세요.",
      items: [
        { label: "class B extends A", value: "클래스 상속", detail: "B가 A의 멤버를 물려받고 재사용한다.", note: "단일 클래스 상속" },
        { label: "class Box implements Comparable", value: "인터페이스 구현", detail: "Box가 Comparable 규약의 메소드를 제공한다.", note: "implements" },
        { label: "interface Sub extends Super", value: "인터페이스 확장", detail: "Sub가 Super의 규약을 포함해 더 큰 규약이 된다.", note: "인터페이스끼리 extends" },
        { label: "Figure f = new Triangle()", value: "다형성", detail: "상위 타입으로 하위 객체를 참조한다.", note: "오버라이딩 실행 가능" },
        { label: "new CSuper() { }", value: "익명 하위 클래스", detail: "이름 없는 하위 클래스를 정의하고 객체를 만든다.", note: "일회성 구현" },
      ],
    },
  },

  6: {
    sourceBasis: "강의록 6강 제네릭 타입, 제네릭 메소드와 타입 제한, 람다식 / 교재 대응 장: 5장 / 공식 연습문제 6강",
    terms: [
      {
        term: "제네릭 타입",
        definition: "타입을 매개변수처럼 받아 다양한 실제 타입에 대해 재사용되는 클래스나 인터페이스이다.",
        role: "컴파일 시점에 타입 오류를 잡고 불필요한 강제 형변환을 줄인다.",
        distinction: "제네릭 타입 인자에는 `int` 같은 기본형이 아니라 `Integer` 같은 참조형을 사용한다.",
        example: "`Data<String>`은 `String` 값을 저장하는 Data로 제한된다.",
      },
      {
        term: "raw 타입",
        definition: "제네릭 타입에서 타입 인자를 생략한 형태이다.",
        role: "기존 코드 호환을 위해 허용되지만 타입 안정성을 약화한다.",
        distinction: "`Data d = new Data();`는 가능할 수 있지만 `Data<String>`처럼 타입 검사를 받지 못한다.",
        example: "raw 타입 Data에 Integer를 넣고 String으로 꺼내면 실행 오류가 날 수 있다.",
      },
      {
        term: "타입 제한",
        definition: "타입 매개변수가 사용할 수 있는 상위 타입 범위를 지정하는 문법이다.",
        role: "재사용성은 유지하면서 특정 상위 타입의 메소드나 성질을 안전하게 사용할 수 있게 한다.",
        distinction: "`<T extends Number>`는 T가 Number 또는 그 하위 타입이어야 한다는 뜻이다.",
        example: "`Data<Integer>`는 가능하지만 `Data<String>`은 제한에 걸린다.",
      },
      {
        term: "람다식",
        definition: "함수형 인터페이스의 추상 메소드 구현을 간결하게 표현하는 문법이다.",
        role: "익명 클래스보다 짧게 동작을 전달하고 컬렉션·스트림 처리와 잘 결합된다.",
        distinction: "식 본문은 return을 생략할 수 있지만 return 문을 쓰려면 중괄호 블록이 필요하다.",
        example: "`(a, b) -> a + b`는 두 값을 더하는 함수형 인터페이스 구현이다.",
      },
      {
        term: "Supplier<T>",
        definition: "인자를 받지 않고 T 타입 값을 공급하는 표준 함수형 인터페이스이다.",
        role: "필요할 때 값을 만들어 돌려주는 동작을 객체처럼 전달할 수 있게 한다.",
        distinction: "Consumer는 값을 받아 소비하고, Supplier는 값을 받지 않고 제공한다.",
        example: "`Supplier<String> s = () -> \"Java\";`의 추상 메소드는 `T get()`이다.",
      },
    ],
    studio: {
      kind: "classifier",
      title: "제네릭·람다 오류 판별기",
      subtitle: "컴파일 오류, 경고 가능 표현, 올바른 표현을 분리",
      prompt: "제네릭은 타입 인자가 참조형인지, 람다는 return 위치가 맞는지 확인합니다.",
      items: [
        { label: "Data<int>", value: "컴파일 오류", detail: "제네릭 타입 인자에는 기본형을 직접 사용할 수 없다.", note: "Integer 사용" },
        { label: "Data<Integer>", value: "올바름", detail: "Integer는 참조형 래퍼 클래스이다.", note: "타입 검사 가능" },
        { label: "Data d = new Data()", value: "raw 타입", detail: "문법상 가능할 수 있지만 타입 안정성이 떨어진다.", note: "경고 가능" },
        { label: "(a,b) -> return a+b", value: "오류", detail: "return은 블록 본문 안에서만 사용해야 한다.", note: "`{ return a+b; }`" },
        { label: "Supplier<T>", value: "T get()", detail: "인자 없이 값을 공급하는 함수형 인터페이스이다.", note: "get 메소드" },
      ],
    },
  },

  7: {
    sourceBasis: "강의록 7강 패키지, 사용자 정의 패키지, 예외와 예외처리 / 교재 대응 장: 6장 / 공식 연습문제 7강",
    terms: [
      {
        term: "package",
        definition: "클래스가 속한 이름 공간을 지정하는 선언이다.",
        role: "관련 클래스를 묶고 이름 충돌을 줄이며 접근 제어의 기준이 된다.",
        distinction: "package 선언에는 클래스 이름이 아니라 패키지 이름만 쓴다.",
        example: "`package myprogram.game;`은 Client가 myprogram.game 패키지에 속함을 뜻한다.",
      },
      {
        term: "import",
        definition: "다른 패키지의 클래스를 단순 이름으로 사용할 수 있게 하는 선언이다.",
        role: "완전한 이름을 매번 쓰지 않아도 소스 코드에서 클래스를 참조할 수 있게 한다.",
        distinction: "import는 클래스를 복사하거나 포함하는 명령이 아니라 이름 해석을 돕는 선언이다.",
        example: "`import java.util.Scanner;` 후 `Scanner sc`라고 쓸 수 있다.",
      },
      {
        term: "classpath",
        definition: "컴파일러와 JVM이 클래스를 찾을 때 살펴보는 경로 목록이다.",
        role: "사용자 정의 클래스나 외부 라이브러리의 위치를 찾는 기준이 된다.",
        distinction: "import가 소스의 이름 해석이라면 classpath는 실제 class 파일 탐색 경로이다.",
        example: "패키지 디렉터리 구조가 classpath 아래에 있어야 완전한 클래스 이름으로 찾을 수 있다.",
      },
      {
        term: "예외처리",
        definition: "실행 중 발생할 수 있는 비정상 상황을 잡거나 호출자에게 알리는 처리 방식이다.",
        role: "프로그램이 오류 상황에서 갑자기 중단되지 않고 적절한 복구나 정리를 하게 한다.",
        distinction: "직접 처리에는 try-catch-finally를 쓰고, 위임에는 메소드 선언부의 throws를 쓴다.",
        example: "`void read() throws IOException`은 IOException 처리를 호출자에게 위임한다.",
      },
      {
        term: "throw와 throws",
        definition: "throw는 예외 객체를 실제로 던지는 문장이고, throws는 메소드가 던질 수 있는 예외를 선언하는 키워드이다.",
        role: "예외 발생 지점과 예외 처리 책임을 코드에서 분명히 표시한다.",
        distinction: "`throw new IOException()`은 문장이고 `throws IOException`은 메소드 선언부의 일부이다.",
        example: "파일 읽기 메소드의 빈칸이 예외 위임이라면 `throws IOException`이 맞다.",
      },
    ],
    studio: {
      kind: "pipeline",
      title: "패키지 해석과 예외 처리 흐름",
      subtitle: "소스 맨 위 선언부터 예외 위임까지 순서로 이해",
      prompt: "패키지와 예외 문제는 선언 위치와 실행 흐름을 함께 봐야 합니다.",
      items: [
        { label: "패키지 선언", value: "package", detail: "소스 파일 맨 위에서 클래스의 소속 패키지를 정한다.", note: "클래스 이름 제외" },
        { label: "외부 클래스 이름", value: "import", detail: "다른 패키지 클래스를 단순 이름으로 사용할 수 있게 한다.", note: "이름 해석" },
        { label: "클래스 탐색", value: "classpath", detail: "컴파일러와 JVM이 실제 class 파일 위치를 찾는다.", note: "실제 경로" },
        { label: "예외 발생", value: "throw", detail: "예외 객체를 만들어 현재 흐름에 던진다.", note: "실행 문장" },
        { label: "예외 위임", value: "throws", detail: "메소드가 처리하지 않고 호출자에게 책임을 알린다.", note: "선언부" },
      ],
    },
  },

  8: {
    sourceBasis: "강의록 8강 Object 클래스, String 클래스, StringBuffer 클래스, System 클래스 / 교재 대응 장: 7장 / 공식 연습문제 8강",
    terms: [
      {
        term: "Object",
        definition: "모든 Java 클래스가 묵시적으로 상속하는 최상위 클래스이다.",
        role: "toString, equals, clone, getClass 같은 공통 메소드를 제공한다.",
        distinction: "사용자가 만든 클래스도 명시적으로 다른 클래스를 상속하지 않으면 Object를 상속한다.",
        example: "객체를 출력하면 기본적으로 Object의 toString 결과 형식이 사용될 수 있다.",
      },
      {
        term: "toString",
        definition: "객체를 문자열로 표현하기 위한 Object 메소드이다.",
        role: "객체 출력이나 문자열 결합에서 사람이 읽기 쉬운 표현을 제공하도록 재정의할 수 있다.",
        distinction: "재정의하지 않으면 클래스명과 해시코드 기반의 기본 표현이 나올 수 있다.",
        example: "`MyClass2`가 toString을 재정의하면 `System.out.println(myClass2)` 출력이 바뀐다.",
      },
      {
        term: "equals",
        definition: "두 객체의 동등성을 비교하기 위한 Object 메소드이다.",
        role: "String이나 Integer 같은 클래스는 내용 기준 비교가 되도록 equals를 재정의한다.",
        distinction: "`==`는 참조나 기본값 비교이고, equals는 클래스가 정의한 동등성 비교이다.",
        example: "`new String(\"Java\").equals(new String(\"Java\"))`는 내용이 같으면 true이다.",
      },
      {
        term: "String",
        definition: "문자열을 표현하는 불변 객체 클래스이다.",
        role: "검색, 추출, 변환, 결합 같은 문자열 처리 메소드를 제공한다.",
        distinction: "메소드가 문자열을 바꾸는 것처럼 보여도 기존 객체 내부가 아니라 새 문자열 결과를 만든다.",
        example: "`s = s.replace('a', 'o')`를 해야 `Java`가 `Jovo` 결과로 바뀐 참조를 가진다.",
      },
      {
        term: "StringBuffer/StringBuilder",
        definition: "내부 버퍼를 수정하는 가변 문자열 클래스이다.",
        role: "반복적인 문자열 결합에서 새 String 객체 생성을 줄인다.",
        distinction: "String은 불변이고, StringBuffer/StringBuilder는 append 등으로 같은 버퍼를 바꾼다.",
        example: "루프 안에서 많은 문자열을 이어 붙일 때 `StringBuilder.append`가 적합하다.",
      },
    ],
    studio: {
      kind: "matrix",
      title: "불변 문자열과 가변 버퍼 비교",
      subtitle: "String, StringBuffer, System, Object 역할을 분리",
      prompt: "문자열 문제는 객체가 바뀐 것인지 새 결과를 받은 것인지가 핵심입니다.",
      items: [
        { label: "String", value: "불변", detail: "수정 메소드는 새 문자열 결과를 반환한다.", note: "결과를 변수에 다시 대입" },
        { label: "StringBuffer", value: "가변", detail: "내부 버퍼를 수정해 반복 결합에 유리하다.", note: "동기화된 버퍼" },
        { label: "StringBuilder", value: "가변", detail: "StringBuffer와 비슷하지만 보통 단일 스레드에서 더 가볍게 사용한다.", note: "반복 append" },
        { label: "System.out", value: "표준 출력", detail: "표준 입출력 스트림은 System 클래스가 제공한다.", note: "String 클래스 아님" },
        { label: "Object.equals", value: "동등성 비교", detail: "클래스가 재정의한 기준에 따라 비교한다.", note: "`==`와 구분" },
      ],
    },
  },

  9: {
    sourceBasis: "강의록 9강 입출력 스트림, 바이트 스트림과 캐릭터 스트림, 파일 입출력, 콘솔 입출력과 보조 스트림 / 교재 대응 장: 8장 / 공식 연습문제 9강",
    terms: [
      {
        term: "스트림",
        definition: "프로그램과 데이터 소스 또는 목적지 사이에서 데이터가 흐르는 통로이다.",
        role: "파일, 메모리, 콘솔 같은 외부 대상과 데이터를 주고받는다.",
        distinction: "입력 스트림은 프로그램으로 들어오는 흐름이고 출력 스트림은 밖으로 나가는 흐름이다.",
        example: "파일 복사에서는 FileInputStream으로 읽고 FileOutputStream으로 쓴다.",
      },
      {
        term: "바이트 스트림",
        definition: "8비트 단위의 원시 데이터를 읽고 쓰는 스트림 계열이다.",
        role: "이미지, 실행 파일, 네트워크 데이터처럼 문자 해석이 필요 없는 데이터를 다룬다.",
        distinction: "Reader/Writer 계열의 문자 스트림과 달리 InputStream/OutputStream 계열이다.",
        example: "`System.in`은 바이트 단위의 표준 입력 스트림이다.",
      },
      {
        term: "캐릭터 스트림",
        definition: "문자 단위 입출력을 다루는 Reader/Writer 계열 스트림이다.",
        role: "문자 인코딩을 고려해 텍스트 데이터를 읽고 쓴다.",
        distinction: "바이트 스트림을 문자로 읽으려면 InputStreamReader 같은 변환 스트림이 필요하다.",
        example: "`FileReader`는 파일에서 문자 데이터를 읽는 기본 문자 스트림이다.",
      },
      {
        term: "보조 스트림",
        definition: "기존 스트림을 감싸 버퍼링, 변환, 객체 처리 같은 기능을 덧붙이는 스트림이다.",
        role: "기본 스트림의 성능이나 기능을 보강한다.",
        distinction: "데이터 원본에 직접 연결되는 기본 스트림과 달리 다른 스트림을 생성자 인자로 받는다.",
        example: "`BufferedReader`는 Reader를 감싸 `readLine()`과 버퍼링을 제공한다.",
      },
      {
        term: "InputStreamReader",
        definition: "바이트 입력 스트림을 문자 입력 스트림으로 변환하는 보조 스트림이다.",
        role: "System.in처럼 바이트로 들어오는 입력을 문자로 해석할 수 있게 한다.",
        distinction: "BufferedReader가 버퍼링과 readLine을 제공한다면 InputStreamReader는 바이트와 문자 사이를 연결한다.",
        example: "`new BufferedReader(new InputStreamReader(System.in))`은 키보드 문자 입력을 읽는 전형적 조합이다.",
      },
    ],
    studio: {
      kind: "stack",
      title: "스트림 감싸기 구조",
      subtitle: "기본 스트림 위에 변환과 버퍼링을 쌓는 방식",
      prompt: "보조 스트림은 혼자 데이터 원본에 붙지 않고, 기존 스트림을 감싸 기능을 더합니다.",
      items: [
        { label: "System.in", value: "바이트 입력", detail: "키보드에서 들어오는 표준 입력은 바이트 스트림이다.", note: "원본 스트림" },
        { label: "InputStreamReader", value: "바이트→문자", detail: "바이트를 문자로 해석하는 변환 계층이다.", note: "문자 처리 준비" },
        { label: "BufferedReader", value: "버퍼링", detail: "문자 입력에 버퍼와 readLine 기능을 더한다.", note: "보조 스트림" },
        { label: "readLine()", value: "한 줄 읽기", detail: "버퍼링된 문자 입력에서 한 줄 문자열을 얻는다.", note: "편의 메소드" },
      ],
    },
  },

  10: {
    sourceBasis: "강의록 10강 java.nio 패키지, 버퍼, FileChannel 클래스, WatchService 인터페이스 / 교재 대응 장: 9장 / 공식 연습문제 10강",
    terms: [
      {
        term: "Path",
        definition: "파일 시스템 안의 파일이나 디렉터리 경로를 표현하는 인터페이스이다.",
        role: "경로 이름, 부모 경로, 경로 요소 수처럼 경로 자체를 다룬다.",
        distinction: "Path는 경로 표현 중심이고 파일 내용 읽기·쓰기는 Files나 Channel이 담당한다.",
        example: "`path.getFileName()`은 경로의 마지막 이름 요소를 반환한다.",
      },
      {
        term: "Files",
        definition: "파일과 디렉터리 작업을 수행하는 정적 메소드 모음 클래스이다.",
        role: "존재 확인, 디렉터리 순회, 파일 생성, 속성 조회 같은 실제 파일 작업을 수행한다.",
        distinction: "Path가 주소라면 Files는 그 주소의 대상에 대해 작업하는 도구이다.",
        example: "`Files.newDirectoryStream(path)`는 디렉터리 항목을 순회한다.",
      },
      {
        term: "Buffer",
        definition: "NIO에서 채널 입출력 데이터를 임시로 담는 저장 공간이다.",
        role: "position, limit, capacity를 이용해 읽기와 쓰기의 현재 상태를 관리한다.",
        distinction: "스트림이 순차 흐름 중심이라면 NIO 채널은 버퍼에 담긴 데이터를 주고받는다.",
        example: "`ByteBuffer buffer = charset.encode(\"Java\")`로 문자열을 바이트 버퍼로 만든다.",
      },
      {
        term: "FileChannel",
        definition: "파일을 채널 방식으로 읽고 쓰는 NIO 클래스이다.",
        role: "ByteBuffer와 함께 파일의 읽기·쓰기 작업을 수행한다.",
        distinction: "FileChannelReader나 FileChannelWriter 같은 별도 클래스가 아니라 read/write 메소드를 사용한다.",
        example: "`FileChannel.open(path, CREATE, WRITE).write(buffer)`",
      },
      {
        term: "WatchKey",
        definition: "WatchService가 감시 중인 디렉터리에서 발생한 이벤트 묶음을 나타내는 키 객체이다.",
        role: "이벤트 목록을 가져오고 처리 후 다시 감시 상태로 돌아가게 한다.",
        distinction: "`take()`가 WatchKey를 반환하고, `pollEvents()`와 `reset()`은 WatchKey에서 호출한다.",
        example: "`key.pollEvents(); key.reset();`",
      },
    ],
    studio: {
      kind: "pipeline",
      title: "NIO 파일 처리와 감시 흐름",
      subtitle: "경로 표현, 파일 작업, 버퍼 입출력, 이벤트 감시를 분리",
      prompt: "Path가 직접 파일 내용을 읽지 않는다는 점을 흐름 안에서 확인합니다.",
      items: [
        { label: "경로 만들기", value: "Paths.get", detail: "문자열 경로를 Path 객체로 만든다.", note: "주소 표현" },
        { label: "파일 작업", value: "Files", detail: "디렉터리 순회나 파일 생성 같은 작업을 수행한다.", note: "작업 도구" },
        { label: "데이터 준비", value: "Buffer", detail: "채널이 읽고 쓸 데이터를 임시로 담는다.", note: "position/limit" },
        { label: "채널 입출력", value: "FileChannel", detail: "버퍼를 통해 파일 내용을 읽고 쓴다.", note: "read/write" },
        { label: "디렉터리 감시", value: "WatchService", detail: "이벤트 발생 시 WatchKey를 받아 처리한다.", note: "pollEvents/reset" },
      ],
    },
  },

  11: {
    sourceBasis: "강의록 11강 JCF, HashSet, ArrayList, LinkedList, HashMap 클래스 / 교재 대응 장: 10장 / 공식 연습문제 11강",
    terms: [
      {
        term: "JCF",
        definition: "Java Collections Framework. 자료 묶음을 다루는 인터페이스와 구현 클래스의 표준 체계이다.",
        role: "List, Set, Queue, Map 같은 자료구조를 일관된 방식으로 선언하고 조작하게 한다.",
        distinction: "Collection 계열과 Map 계열은 구조가 다르다. Map은 key/value 쌍을 다룬다.",
        example: "`List<String> list = new ArrayList<>();`",
      },
      {
        term: "List",
        definition: "순서가 있는 원소 목록을 표현하는 컬렉션 인터페이스이다.",
        role: "인덱스로 원소를 접근하고 같은 값을 여러 번 저장할 수 있다.",
        distinction: "Set은 중복을 허용하지 않지만 List는 중복을 허용한다.",
        example: "`ArrayList`는 List 구현 클래스이며 `list.add(1, \"one\")`처럼 위치 삽입이 가능하다.",
      },
      {
        term: "Set",
        definition: "중복 원소를 허용하지 않는 컬렉션 인터페이스이다.",
        role: "동일한 값이 한 번만 존재해야 하는 집합형 자료를 표현한다.",
        distinction: "HashSet은 key/value를 저장하는 Map이 아니라 단일 원소 집합이다.",
        example: "HashSet에 이미 있는 `\"one\"`을 다시 add하면 false가 반환될 수 있다.",
      },
      {
        term: "Queue",
        definition: "먼저 들어간 원소를 먼저 꺼내는 대기열 자료구조 인터페이스이다.",
        role: "작업 대기열, 메시지 처리 순서처럼 순차 처리 모델에 쓰인다.",
        distinction: "LinkedList는 List로도 쓸 수 있고 Queue 구현으로도 쓸 수 있다.",
        example: "`queue.offer(\"one\")`, `queue.poll()`",
      },
      {
        term: "Map",
        definition: "key와 value의 쌍을 저장하는 자료구조 인터페이스이다.",
        role: "이름에서 점수, ID에서 객체처럼 키로 값을 빠르게 찾는다.",
        distinction: "Collection의 원소 목록이 아니라 key/value 쌍 구조이므로 HashSet과 다르다.",
        example: "`Map<String, Integer> scores = new HashMap<>(); scores.put(\"Kim\", 90);`",
      },
    ],
    studio: {
      kind: "graph",
      title: "JCF 선택 지도",
      subtitle: "요구 조건에 따라 List, Set, Queue, Map을 선택",
      prompt: "중복, 순서, FIFO, key/value 중 무엇이 중요한지 먼저 고릅니다.",
      items: [
        { label: "순서 + 중복", value: "List / ArrayList", detail: "인덱스 순서가 있고 같은 값도 여러 번 저장한다.", note: "학생 점수 목록" },
        { label: "중복 제거", value: "Set / HashSet", detail: "동등한 원소는 하나만 유지한다.", note: "태그 집합" },
        { label: "대기열", value: "Queue / LinkedList", detail: "offer로 넣고 poll로 꺼낸다.", note: "FIFO 처리" },
        { label: "키로 값 찾기", value: "Map / HashMap", detail: "key와 value 쌍을 저장한다.", note: "이름→점수" },
      ],
    },
  },

  12: {
    sourceBasis: "강의록 12강 forEach 메소드, 스트림, 스트림 파이프라인, 중간연산과 종료연산 / 교재 대응 장: 11장 / 공식 연습문제 12강",
    terms: [
      {
        term: "forEach",
        definition: "각 원소에 대해 전달된 동작을 수행하는 내부 반복 메소드이다.",
        role: "반복 제어보다 원소마다 수행할 작업을 람다식으로 표현하게 한다.",
        distinction: "외부 반복은 for/Iterator가 반복을 직접 제어하고, forEach는 컬렉션 API가 반복한다.",
        example: "`names.forEach(name -> System.out.println(name));`",
      },
      {
        term: "Stream",
        definition: "데이터 소스의 원소를 연산 파이프라인으로 처리하는 API이다.",
        role: "배열, 컬렉션, 파일, 숫자 범위에 대해 선언형 데이터 처리를 제공한다.",
        distinction: "스트림은 원본 데이터를 저장하는 자료구조가 아니라 처리 흐름이다.",
        example: "`Arrays.stream(numbers)`는 int 배열에서 IntStream을 만든다.",
      },
      {
        term: "중간연산",
        definition: "스트림을 입력받아 다시 스트림을 반환하는 연산이다.",
        role: "필터링, 변환, 정렬처럼 처리 단계를 파이프라인에 추가한다.",
        distinction: "종료연산이 호출되기 전까지 지연 실행된다.",
        example: "`filter`, `map`, `sorted`, `distinct`",
      },
      {
        term: "종료연산",
        definition: "스트림 처리를 실제로 수행하고 결과나 부수효과를 만든 뒤 파이프라인을 끝내는 연산이다.",
        role: "count, collect, forEach처럼 최종 값을 만들거나 출력한다.",
        distinction: "종료연산 후 같은 스트림 파이프라인은 다시 사용할 수 없다.",
        example: "`words.stream().filter(...).count()`에서 `count()`가 종료연산이다.",
      },
      {
        term: "filter",
        definition: "조건을 만족하는 원소만 통과시키는 중간연산이다.",
        role: "Predicate가 true를 반환하는 원소만 다음 단계로 보낸다.",
        distinction: "map은 원소를 변환하고 filter는 원소를 선별한다.",
        example: "`filter(word -> word.length() >= 6)`",
      },
    ],
    studio: {
      kind: "pipeline",
      title: "스트림 파이프라인 실행기",
      subtitle: "생성, 중간연산, 종료연산의 실행 시점을 분리",
      prompt: "중간연산은 줄을 세우는 단계이고, 종료연산이 와야 실제 처리가 시작됩니다.",
      items: [
        { label: "생성", value: "Arrays.stream", detail: "배열에서 스트림을 만든다.", note: "원본 소스 연결" },
        { label: "선별", value: "filter", detail: "길이 조건을 만족하는 단어만 통과시킨다.", note: "중간연산" },
        { label: "변환", value: "map", detail: "통과한 단어를 대문자로 변환한다.", note: "중간연산" },
        { label: "정렬", value: "sorted", detail: "출력 순서를 정렬한다.", note: "중간연산" },
        { label: "실행", value: "forEach/count", detail: "파이프라인을 실제로 실행하고 끝낸다.", note: "종료연산" },
      ],
    },
  },

  13: {
    sourceBasis: "강의록 13강 프로세스와 스레드, 스레드의 생성, 스레드 제어하기, 스레드 동기화 / 교재 대응 장: 12장 / 공식 연습문제 13강",
    terms: [
      {
        term: "프로세스",
        definition: "실행 중인 프로그램의 독립적인 실행 단위이다.",
        role: "운영체제에서 자원과 주소 공간을 할당받아 실행된다.",
        distinction: "스레드는 프로세스 내부의 실행 흐름이고, 프로세스는 더 큰 실행 단위이다.",
        example: "Java 프로그램 하나를 실행하면 JVM 프로세스가 만들어진다.",
      },
      {
        term: "스레드",
        definition: "프로세스 안에서 실행되는 작업 흐름 단위이다.",
        role: "하나의 프로그램 안에서 여러 작업을 동시에 또는 번갈아 수행하게 한다.",
        distinction: "여러 스레드는 같은 프로세스의 메모리를 공유할 수 있어 동기화 문제가 생긴다.",
        example: "main 스레드와 작업 스레드 thd1, thd2가 출력 순서를 섞어 실행할 수 있다.",
      },
      {
        term: "Runnable",
        definition: "스레드가 실행할 작업을 `run()` 메소드로 정의하는 인터페이스이다.",
        role: "Thread 상속 대신 실행 작업을 별도 객체로 분리해 전달한다.",
        distinction: "Runnable은 JDBC가 아니라 멀티 스레드 프로그래밍의 인터페이스이다.",
        example: "`new Thread(new MyThread(), \"thd0\").start();`",
      },
      {
        term: "join",
        definition: "대상 스레드가 종료될 때까지 현재 스레드를 기다리게 하는 메소드이다.",
        role: "작업 스레드가 끝난 뒤 다음 코드를 실행해야 할 때 순서를 맞춘다.",
        distinction: "sleep은 현재 스레드를 일정 시간 쉬게 하고, join은 특정 스레드의 종료를 기다린다.",
        example: "`my_thread1.join();` 뒤의 main 출력은 my_thread1 종료 후 실행된다.",
      },
      {
        term: "synchronized",
        definition: "공유 객체의 임계 영역에 한 번에 하나의 스레드만 접근하게 하는 키워드이다.",
        role: "동시 접근으로 인한 데이터 불일치와 경쟁 상태를 막는다.",
        distinction: "동기화는 여러 스레드가 동시에 접근하게 하는 것이 아니라 동시에 접근하지 못하게 제어하는 것이다.",
        example: "`public synchronized void deposit(...)`",
      },
    ],
    studio: {
      kind: "state",
      title: "스레드 상태와 제어 메소드",
      subtitle: "start, sleep, join, wait, synchronized가 흐름을 바꾸는 위치",
      prompt: "스레드 문제는 현재 스레드가 기다리는지, 대상 스레드를 기다리는지 구분해야 합니다.",
      items: [
        { label: "생성", value: "new Thread", detail: "스레드 객체를 만들었지만 아직 실행되지 않았다.", note: "new 상태" },
        { label: "실행 요청", value: "start()", detail: "JVM에 새 스레드 실행을 요청한다.", note: "run 직접 호출과 다름" },
        { label: "실행 가능/실행", value: "scheduler", detail: "스케줄러가 실행 순서를 정하므로 출력 순서는 섞일 수 있다.", note: "비결정적" },
        { label: "대기", value: "join/wait/sleep", detail: "각 메소드는 기다리는 대상과 조건이 다르다.", note: "문장 설명 판별" },
        { label: "임계 영역", value: "synchronized", detail: "공유 객체 접근을 한 스레드로 제한한다.", note: "상호 배제" },
      ],
    },
  },

  14: {
    sourceBasis: "강의록 14강 JDBC와 MariaDB, MariaDB 서버 연결, 연동 프로그래밍, PreparedStatement와 메타데이터 / 교재 대응 장: 13장 / 공식 연습문제 14강",
    terms: [
      {
        term: "JDBC",
        definition: "Java 프로그램이 데이터베이스에 접속하고 SQL을 실행하기 위한 표준 API이다.",
        role: "Java 코드와 DBMS 사이의 연결, SQL 실행, 결과 처리를 표준 인터페이스로 제공한다.",
        distinction: "JDBC는 DBMS 자체가 아니며 MariaDB 같은 DBMS에 연결하기 위한 Java API이다.",
        example: "`DriverManager.getConnection(url, user, pass)`로 DB 연결을 얻는다.",
      },
      {
        term: "Connection",
        definition: "데이터베이스와 연결된 세션을 나타내는 JDBC 인터페이스이다.",
        role: "Statement나 PreparedStatement를 만들고 트랜잭션과 연결 상태를 관리한다.",
        distinction: "DriverManager가 연결을 생성하고 Connection은 생성된 연결 자체를 나타낸다.",
        example: "`try (Connection conn = DriverManager.getConnection(...)) { ... }`",
      },
      {
        term: "Statement",
        definition: "SQL 문장을 데이터베이스에 보내 실행하는 JDBC 인터페이스이다.",
        role: "SELECT, INSERT, UPDATE, DELETE 같은 SQL을 실행한다.",
        distinction: "SELECT 결과는 ResultSet이고, 변경 SQL은 보통 변경 행 수를 반환한다.",
        example: "`stmt.executeQuery(\"SELECT * FROM city\")`",
      },
      {
        term: "ResultSet",
        definition: "SELECT 질의 결과를 행과 열로 나타내는 객체이다.",
        role: "커서를 행 단위로 이동하며 컬럼 값을 읽는다.",
        distinction: "SQL을 실행하는 객체가 아니라 실행 결과를 담고 순회하는 객체이다.",
        example: "`while (rs.next()) { rs.getString(\"Name\"); }`",
      },
      {
        term: "PreparedStatement",
        definition: "매개변수가 있는 SQL을 미리 준비해 실행할 수 있는 Statement의 하위 인터페이스이다.",
        role: "같은 SQL을 여러 번 실행하거나 값만 바꿔 실행할 때 효율적이고 안전하게 사용할 수 있다.",
        distinction: "Statement의 부모가 아니라 하위 인터페이스이다.",
        example: "`conn.prepareStatement(\"select * from city where id=?\")`",
      },
    ],
    studio: {
      kind: "pipeline",
      title: "JDBC 질의 실행 파이프라인",
      subtitle: "연결부터 결과 행 읽기까지 객체의 책임 분리",
      prompt: "JDBC 문제는 어떤 객체가 어떤 단계의 책임을 지는지 따라가면 풀립니다.",
      items: [
        { label: "드라이버/URL", value: "jdbc:mariadb", detail: "어떤 DBMS와 데이터베이스에 접속할지 지정한다.", note: "연결 정보" },
        { label: "연결 획득", value: "DriverManager", detail: "URL과 계정 정보로 Connection을 만든다.", note: "getConnection" },
        { label: "SQL 실행 객체", value: "Statement", detail: "SQL 문장을 데이터베이스에 보낸다.", note: "executeQuery/update" },
        { label: "결과 집합", value: "ResultSet", detail: "SELECT 결과를 행 단위로 순회한다.", note: "next/getXXX" },
        { label: "매개변수 SQL", value: "PreparedStatement", detail: "미리 준비된 SQL에 값을 바인딩한다.", note: "Statement의 하위" },
      ],
    },
  },

  15: {
    sourceBasis: "강의록 15강 라이브러리, 모듈, Java 표준 모듈 / 교재 대응 장: 14장 / 공식 연습문제 15강",
    terms: [
      {
        term: "라이브러리",
        definition: "재사용 가능한 클래스와 자원을 묶어 다른 프로그램에서 사용할 수 있게 한 산출물이다.",
        role: "공통 기능을 매번 새로 만들지 않고 가져다 쓰게 한다.",
        distinction: "라이브러리는 기능 묶음이고 JAR는 Java에서 이를 배포하는 대표 파일 형식이다.",
        example: "외부 유틸리티 클래스 묶음을 `util.jar`로 배포할 수 있다.",
      },
      {
        term: "JAR",
        definition: "Java Archive. class 파일과 자원을 하나로 묶은 Java 배포 파일 형식이다.",
        role: "라이브러리나 실행 가능한 Java 프로그램을 파일 하나로 배포한다.",
        distinction: "JAR 파일을 전통적인 방식으로 사용하려면 classpath에 넣어 클래스 검색 대상이 되게 한다.",
        example: "`javac -classpath lib/util.jar Main.java`",
      },
      {
        term: "Classpath",
        definition: "Java 컴파일러와 JVM이 클래스와 라이브러리를 찾는 경로 목록이다.",
        role: "외부 JAR나 사용자 정의 class 파일이 어디 있는지 알려 준다.",
        distinction: "module path는 모듈 시스템의 경로이고 classpath는 전통적인 클래스 검색 경로이다.",
        example: ".jar 라이브러리 사용 문제에서 정답은 Classpath이다.",
      },
      {
        term: "module-info.java",
        definition: "모듈의 이름, 의존 모듈, 공개 패키지를 선언하는 모듈 기술자 파일이다.",
        role: "모듈 경계를 명확히 하고 어떤 패키지를 외부에 공개할지 통제한다.",
        distinction: "`requires`는 필요한 모듈을, `exports`는 공개할 패키지를 선언한다.",
        example: "`module MyProject { requires java.sql; }`",
      },
      {
        term: "java.base",
        definition: "모든 Java 모듈이 기본으로 읽는 핵심 표준 모듈이다.",
        role: "Object, String, System 같은 가장 기본적인 API를 제공한다.",
        distinction: "java.lang은 패키지 이름이고 java.base는 모듈 이름이다.",
        example: "java.base는 requires 선언 없이 사용할 수 있지만 java.sql은 `requires java.sql;`이 필요하다.",
      },
    ],
    studio: {
      kind: "graph",
      title: "라이브러리와 모듈 의존 그래프",
      subtitle: "classpath와 module-info의 책임을 분리해 보기",
      prompt: "JAR 사용과 모듈 사용은 모두 재사용을 다루지만 선언 위치와 경로 체계가 다릅니다.",
      items: [
        { label: "util.jar", value: "Classpath", detail: "전통적 라이브러리 검색 경로에 넣어 사용한다.", note: "JAR 배포" },
        { label: "module-info.java", value: "모듈 기술자", detail: "모듈 이름과 의존성, 공개 패키지를 선언한다.", note: "모듈 경계" },
        { label: "requires", value: "의존 모듈", detail: "사용할 다른 모듈을 읽겠다고 선언한다.", note: "모듈 이름 대상" },
        { label: "exports", value: "공개 패키지", detail: "외부 모듈에서 접근 가능한 패키지를 지정한다.", note: "패키지 이름 대상" },
        { label: "java.sql", value: "표준 모듈", detail: "JDBC 관련 패키지를 쓰려면 명시적으로 requires 한다.", note: "`requires java.sql;`" },
      ],
    },
  },
};
