import { aiPastExamOcrText } from "./ocrText";
import type { ChoiceKey, PastExamQuestion, PastExamQuestionImage } from "./types";

type Topic = {
  concept: string;
  lectureId: number;
  lectureLabel: string;
  tags: string[];
  basis: string;
  wrongRule: string;
  examSkill: string;
  textbook: string;
};

const TOPICS: Record<string, Topic> = {
  minimax: {
    concept: "최대최소 탐색",
    lectureId: 4,
    lectureLabel: "4강 게임트리",
    tags: ["게임트리", "최대최소"],
    basis: "게임트리에서는 MAX와 MIN이 번갈아 선택한다고 보고, 말단 노드 평가값을 부모 노드로 역전파하여 현재 노드의 값을 정한다.",
    wrongRule: "MAX/MIN의 역할, 자식 노드 선택 순서, 역전파되는 평가값을 바꾸면 오답이다.",
    examSkill: "게임트리 값 역전파",
    textbook: "교재 4장 게임트리",
  },
  alphaBeta: {
    concept: "알파-베타 가지치기",
    lectureId: 4,
    lectureLabel: "4강 게임트리",
    tags: ["게임트리", "알파-베타"],
    basis: "알파-베타 가지치기는 이미 더 나은 선택이 보장된 분기를 더 탐색하지 않고 잘라 내어 최대최소 탐색량을 줄인다.",
    wrongRule: "가지치기 조건과 alpha, beta의 의미를 반대로 두거나, 평가가 끝난 노드를 다시 확장하면 오답이다.",
    examSkill: "가지치기 조건 판별",
    textbook: "교재 4장 게임트리",
  },
  mcts: {
    concept: "몬테카를로 트리 탐색",
    lectureId: 4,
    lectureLabel: "4강 게임트리",
    tags: ["게임트리", "MCTS"],
    basis: "몬테카를로 트리 탐색은 선택, 확장, 시뮬레이션, 역전파 단계를 반복하여 탐사와 활용의 균형을 맞춘다.",
    wrongRule: "단계 순서, 선택 전략, 시뮬레이션 결과의 역전파를 다른 탐색 절차와 혼동하면 오답이다.",
    examSkill: "MCTS 절차 판별",
    textbook: "교재 4장 게임트리",
  },
  expertSystem: {
    concept: "전문가 시스템",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["지식기반", "전문가 시스템"],
    basis: "전문가 시스템은 문제 분야 지식과 추론기관을 분리하여 전문가 수준의 문제 해결을 지원한다.",
    wrongRule: "일반 프로그램, 사용자 인터페이스, 지식 공학자 역할을 전문가 시스템의 핵심 구조와 혼동하면 오답이다.",
    examSkill: "지식기반 시스템 특징 판별",
    textbook: "교재 5장 지식과 인공지능",
  },
  semanticNetwork: {
    concept: "시맨틱 네트",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["지식표현", "시맨틱 네트"],
    basis: "시맨틱 네트는 개념을 노드로, 개념 사이의 관계를 아크로 표현하는 그래프 기반 지식표현이다.",
    wrongRule: "노드-아크 구조를 논리식, 규칙, 단순 절차와 혼동하면 오답이다.",
    examSkill: "지식표현 방법 구분",
    textbook: "교재 5장 지식과 인공지능",
  },
  inheritance: {
    concept: "특성상속",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["지식표현", "특성상속"],
    basis: "특성상속은 상위 개념의 속성을 하위 개념이 물려받아 중앙집중적으로 지식을 표현하게 한다.",
    wrongRule: "상속 방향, 상위/하위 개념 관계, 프레임 슬롯의 공유 의미를 잘못 두면 오답이다.",
    examSkill: "상속 관계 판별",
    textbook: "교재 5장 지식과 인공지능",
  },
  frame: {
    concept: "프레임",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["지식표현", "프레임"],
    basis: "프레임은 대상이나 상황의 속성을 슬롯으로 묶고, 특성상속으로 상위 개념의 지식을 재사용한다.",
    wrongRule: "슬롯, 상속, 중앙 집중식 표현의 역할을 규칙이나 논리식과 혼동하면 오답이다.",
    examSkill: "프레임 구성요소 판별",
    textbook: "교재 5장 지식과 인공지능",
  },
  knowledgeRepresentation: {
    concept: "선언적 지식표현",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["지식표현", "선언적 지식"],
    basis: "선언적 지식표현은 지식을 명시적으로 나타내고 추론기관이 이를 이용해 결론을 도출한다.",
    wrongRule: "절차적 지식, 규칙 네트워크, 논리의 역할을 서로 바꾸면 오답이다.",
    examSkill: "지식표현 유형 구분",
    textbook: "교재 5장 지식과 인공지능",
  },
  propositionalLogic: {
    concept: "명제논리와 조건명제",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["명제논리", "조건명제"],
    basis: "조건명제와 논리연산은 진리값 규칙에 따라 동치식과 추론 규칙을 판별한다.",
    wrongRule: "함의, 부정, 논리합, 논리곱의 진리조건을 바꾸면 오답이다.",
    examSkill: "논리식 동치 판별",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  normalForm: {
    concept: "연언표준형",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["명제논리", "표준형"],
    basis: "연언표준형은 리터럴들의 논리합으로 된 절을 논리곱으로 결합한 형태이다.",
    wrongRule: "절과 리터럴의 결합 방향이나 부정 이동 기준을 바꾸면 오답이다.",
    examSkill: "표준형 구조 판별",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  predicateLogic: {
    concept: "술어논리",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["술어논리", "정형식"],
    basis: "술어논리는 술어, 개체변수, 개체상수, 함수기호, 한정기호로 명제보다 풍부한 관계를 표현한다.",
    wrongRule: "변수와 상수, 술어와 함수, 전칭과 존재 한정의 역할을 바꾸면 오답이다.",
    examSkill: "술어식 구성요소 판별",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  predicateNegation: {
    concept: "한정기호 부정",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["술어논리", "부정"],
    basis: "한정기호가 붙은 명제를 부정하면 전칭과 존재가 서로 바뀌고, 내부 명제도 부정된다.",
    wrongRule: "한정기호만 바꾸거나 내부 명제의 부정을 빠뜨리면 오답이다.",
    examSkill: "한정기호 부정 변환",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  modusPonens: {
    concept: "긍정논법",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["추론", "긍정논법"],
    basis: "긍정논법은 p→q와 p가 참일 때 q를 결론으로 얻는 타당한 추론 규칙이다.",
    wrongRule: "후건긍정, 전건부정처럼 타당하지 않은 추론형을 긍정논법으로 보면 오답이다.",
    examSkill: "추론 규칙 판별",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  resolution: {
    concept: "도출연역",
    lectureId: 6,
    lectureLabel: "6강 논리에 의한 지식표현",
    tags: ["도출연역", "절"],
    basis: "도출연역은 상보 리터럴을 포함한 절들에서 새 절을 도출하여 증명이나 결론 도출에 사용한다.",
    wrongRule: "상보 리터럴 제거, 공리 리스트, false 도출의 의미를 잘못 해석하면 오답이다.",
    examSkill: "도출 절 계산",
    textbook: "교재 6장 논리에 의한 지식표현",
  },
  fuzzySet: {
    concept: "퍼지집합",
    lectureId: 7,
    lectureLabel: "7강 퍼지이론",
    tags: ["퍼지집합", "소속함수"],
    basis: "퍼지집합은 원소가 0부터 1 사이의 소속함수 값으로 부분적으로 속할 수 있음을 나타낸다.",
    wrongRule: "고전집합처럼 소속 여부를 0 또는 1로만 보거나 소속함수의 범위를 벗어나면 오답이다.",
    examSkill: "퍼지집합 정의 판별",
    textbook: "교재 7장 퍼지이론",
  },
  fuzzyOp: {
    concept: "퍼지집합 연산",
    lectureId: 7,
    lectureLabel: "7강 퍼지이론",
    tags: ["퍼지연산", "합집합/교집합/여집합"],
    basis: "표준 퍼지연산에서 합집합은 최대값, 교집합은 최소값, 여집합은 1에서 소속값을 뺀 값으로 계산한다.",
    wrongRule: "최대/최소/보수 계산 규칙이나 원소별 대응을 잘못 적용하면 오답이다.",
    examSkill: "퍼지연산 계산",
    textbook: "교재 7장 퍼지이론",
  },
  fuzzyLaw: {
    concept: "퍼지논리 등식",
    lectureId: 7,
    lectureLabel: "7강 퍼지이론",
    tags: ["퍼지논리", "등식"],
    basis: "퍼지논리는 고전논리와 유사한 법칙도 있지만 배중률과 모순율처럼 그대로 성립하지 않는 법칙이 있다.",
    wrongRule: "고전집합 법칙을 퍼지집합에 그대로 적용하면 오답이다.",
    examSkill: "퍼지 법칙 예외 판별",
    textbook: "교재 7장 퍼지이론",
  },
  fuzzyInference: {
    concept: "퍼지추론",
    lectureId: 7,
    lectureLabel: "7강 퍼지이론",
    tags: ["퍼지추론", "퍼지규칙"],
    basis: "퍼지추론은 입력 사실과 퍼지규칙의 조건부를 대조하고, 조건부 만족 정도에 따라 결론부의 소속함수를 정한다.",
    wrongRule: "조건부와 결론부의 언어 변수, 규칙 만족도, 비퍼지화 단계를 혼동하면 오답이다.",
    examSkill: "퍼지추론 절차 판별",
    textbook: "교재 7장 퍼지이론",
  },
  productionSystem: {
    concept: "생성 시스템",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["규칙", "생성 시스템"],
    basis: "생성 시스템은 규칙 집합, 현재 사실, 추론 절차를 이용해 조건에 맞는 규칙을 적용한다.",
    wrongRule: "규칙 메모리, 사실 메모리, 인터프리터 역할을 서로 바꾸면 오답이다.",
    examSkill: "생성 시스템 구성요소 판별",
    textbook: "교재 5장 지식과 인공지능",
  },
  inferenceMethod: {
    concept: "추론방법",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["추론", "연역/귀납/유도"],
    basis: "추론방법은 전제와 결론의 관계에 따라 연역, 귀납, 유도, 유사추론 등으로 구분된다.",
    wrongRule: "추론 결과가 항상 참인지, 사례에서 일반화하는지, 가설을 세우는지를 혼동하면 오답이다.",
    examSkill: "추론방법 구분",
    textbook: "교재 5장 지식과 인공지능",
  },
  forwardChaining: {
    concept: "전방향 추론",
    lectureId: 5,
    lectureLabel: "5강 지식과 인공지능",
    tags: ["규칙기반", "전방향 추론"],
    basis: "전방향 추론은 현재 사실에서 실행 가능한 규칙을 찾아 결론을 새 사실로 추가하며 진행한다.",
    wrongRule: "목표에서 출발하는 후방향 추론이나 규칙 선택 기준을 혼동하면 오답이다.",
    examSkill: "규칙 적용 순서 판별",
    textbook: "교재 5장 지식과 인공지능",
  },
  visionPipeline: {
    concept: "컴퓨터 시각 처리 단계",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["컴퓨터 시각", "처리 단계"],
    basis: "컴퓨터 시각은 영상 표현, 전처리, 분할, 특징 추출 등의 단계로 처리 대상을 구조화한다.",
    wrongRule: "표준화, 정규화, 분할, 영상 표현의 역할을 서로 바꾸면 오답이다.",
    examSkill: "영상 처리 단계 구분",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  digitization: {
    concept: "표본화와 양자화",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["디지털 영상", "표본화/양자화"],
    basis: "아날로그 영상을 디지털 영상으로 바꾸려면 공간 위치를 표본화하고 밝기 값을 양자화한다.",
    wrongRule: "표본화와 양자화의 대상이나 순서를 평활화·분할과 혼동하면 오답이다.",
    examSkill: "디지털 영상 변환 단계 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  smoothingFilter: {
    concept: "평활화 필터",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["전처리", "평활화"],
    basis: "평활화는 주변 픽셀 값을 이용해 잡음을 줄이고 영상의 급격한 변화를 완화한다.",
    wrongRule: "잡음 제거 필터를 에지 검출이나 이진화와 혼동하면 오답이다.",
    examSkill: "필터 목적 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  medianFilter: {
    concept: "중간값 필터",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["전처리", "중간값 필터"],
    basis: "중간값 필터는 이웃 영역의 픽셀 값 중 중간값을 사용하여 salt-and-pepper 잡음 제거에 효과적이다.",
    wrongRule: "평균, 미분, 경계 검출 목적과 중간값 필터의 목적을 혼동하면 오답이다.",
    examSkill: "필터 효과 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  sobel: {
    concept: "소벨 연산자",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["에지", "소벨"],
    basis: "소벨 연산자는 밝기 변화의 기울기를 이용해 에지의 강도와 방향을 구한다.",
    wrongRule: "평활화, 잡음 제거, 양자화와 에지 검출 목적을 혼동하면 오답이다.",
    examSkill: "에지 검출 연산자 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  segmentation: {
    concept: "영상분할",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["영상분할", "영역"],
    basis: "영상분할은 유사한 성질을 가진 부분은 같은 영역으로 묶고 서로 다른 성질은 다른 영역으로 나눈다.",
    wrongRule: "영상 표현, 잡음 제거, 표본화처럼 분할 전후 단계와 혼동하면 오답이다.",
    examSkill: "분할 조건 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  connectivity8: {
    concept: "8-이웃 연결성",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["연결성", "8-이웃"],
    basis: "8-이웃 연결성은 상하좌우뿐 아니라 대각선으로 인접한 픽셀까지 연결된 것으로 본다.",
    wrongRule: "4-이웃과 8-이웃의 연결 기준을 바꾸면 오답이다.",
    examSkill: "연결 경로 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  histogramEqualization: {
    concept: "히스토그램 평활화",
    lectureId: 8,
    lectureLabel: "8강 컴퓨터 시각과 패턴인식(1)",
    tags: ["히스토그램", "명암"],
    basis: "히스토그램 평활화는 누적분포를 이용해 명암 대비가 고르게 퍼지도록 밝기 값을 변환한다.",
    wrongRule: "임계치 위치, 최대 빈도 위치, 단순 평균과 평활화의 기준을 혼동하면 오답이다.",
    examSkill: "히스토그램 변환 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  featureExtraction: {
    concept: "특징추출",
    lectureId: 9,
    lectureLabel: "9강 컴퓨터 시각과 패턴인식(2)",
    tags: ["특징추출", "패턴인식"],
    basis: "특징추출은 패턴 공간의 차원을 낮추고 식별에 도움이 되는 성분을 표현하는 단계이다.",
    wrongRule: "특징 선택, 확대, 전처리, 잡음 제거의 목적을 특징추출과 혼동하면 오답이다.",
    examSkill: "특징추출 목적 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  pca: {
    concept: "주성분 분석",
    lectureId: 9,
    lectureLabel: "9강 컴퓨터 시각과 패턴인식(2)",
    tags: ["특징공간", "PCA"],
    basis: "주성분 분석은 직교 변환을 통해 상관이 큰 특징을 더 적은 차원의 성분으로 표현한다.",
    wrongRule: "차원 축소 목적을 이진화, 정규화, 단순 필터링과 혼동하면 오답이다.",
    examSkill: "차원 축소 기법 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  patternGrammar: {
    concept: "언어이론적 패턴인식",
    lectureId: 9,
    lectureLabel: "9강 컴퓨터 시각과 패턴인식(2)",
    tags: ["패턴인식", "문법"],
    basis: "언어이론적 패턴인식은 패턴을 문법과 생성규칙으로 표현하고 인식한다.",
    wrongRule: "원시패턴, 인식대상 패턴, 결합 패턴의 계층을 혼동하면 오답이다.",
    examSkill: "문법 기반 패턴인식 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  distanceMetric: {
    concept: "거리측정자",
    lectureId: 9,
    lectureLabel: "9강 컴퓨터 시각과 패턴인식(2)",
    tags: ["거리측정자", "패턴공간"],
    basis: "거리측정자는 비음성, 동일성, 대칭성, 삼각부등식 같은 공리를 만족해야 한다.",
    wrongRule: "부호, 대칭성, 삼각부등식 방향을 잘못 두면 오답이다.",
    examSkill: "거리측정자 공리 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  bayes: {
    concept: "베이즈 분류기",
    lectureId: 9,
    lectureLabel: "9강 컴퓨터 시각과 패턴인식(2)",
    tags: ["베이즈", "분류"],
    basis: "베이즈 분류는 사전확률, 조건부확률, 사후확률을 비교해 가장 가능성이 큰 클래스를 선택한다.",
    wrongRule: "사전확률과 사후확률, 우도와 주변확률의 비교 대상을 바꾸면 오답이다.",
    examSkill: "베이즈 판정 조건 판별",
    textbook: "교재 8장 컴퓨터 시각과 패턴인식",
  },
  mle: {
    concept: "최대가능도 추정",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["확률밀도", "MLE"],
    basis: "최대가능도 추정은 관찰된 학습표본이 나올 가능성을 최대화하는 매개변수를 찾는다.",
    wrongRule: "최근접이웃, 특징공간, 단순 평활화와 매개변수 추정 방식을 혼동하면 오답이다.",
    examSkill: "확률 추정 방식 판별",
    textbook: "교재 9장 머신러닝",
  },
  knn: {
    concept: "k-근접이웃",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["분류", "k-NN"],
    basis: "k-근접이웃은 미지 패턴과 가까운 k개의 학습표본을 찾아 다수 클래스로 분류한다.",
    wrongRule: "k의 의미, 이웃 표본 수, 클래스 다수결 원칙을 바꾸면 오답이다.",
    examSkill: "최근접 이웃 분류",
    textbook: "교재 9장 머신러닝",
  },
  supervised: {
    concept: "지도학습",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["학습유형", "지도학습"],
    basis: "지도학습은 입력과 기대 출력이 함께 주어진 학습표본으로 입력-출력 대응을 학습한다.",
    wrongRule: "출력값이 없는 자율학습, 보상 기반 강화학습, 단순 군집화와 혼동하면 오답이다.",
    examSkill: "학습 유형 분류",
    textbook: "교재 9장 머신러닝",
  },
  unsupervised: {
    concept: "자율학습",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["학습유형", "자율학습"],
    basis: "자율학습은 기대 출력 없이 입력 데이터의 구조나 분포를 스스로 찾는다.",
    wrongRule: "정답 출력이나 보상 신호가 주어지는 학습과 혼동하면 오답이다.",
    examSkill: "학습 유형 분류",
    textbook: "교재 9장 머신러닝",
  },
  reinforcement: {
    concept: "강화학습",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["학습유형", "강화학습"],
    basis: "강화학습은 환경에서 행동하고 보상을 받아 누적 보상을 크게 하는 정책을 학습한다.",
    wrongRule: "입력-정답 쌍을 직접 주는 지도학습이나 군집화와 혼동하면 오답이다.",
    examSkill: "학습 유형 분류",
    textbook: "교재 9장 머신러닝",
  },
  confusion: {
    concept: "거짓 양성",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["분류성능", "오류"],
    basis: "거짓 양성은 실제로는 음성인데 양성으로 판단한 오류이다.",
    wrongRule: "실제값과 예측값의 축을 바꾸거나 거짓 음성과 혼동하면 오답이다.",
    examSkill: "분류 오류 유형 판별",
    textbook: "교재 9장 머신러닝",
  },
  decisionTree: {
    concept: "결정트리",
    lectureId: 10,
    lectureLabel: "10강 머신러닝(1)",
    tags: ["결정트리", "불순도"],
    basis: "결정트리는 노드의 불순도를 줄이는 방향으로 분할하며, 엔트로피나 지니계수 등을 분할 기준으로 쓴다.",
    wrongRule: "불순도가 높은 노드를 좋은 말단으로 보거나 분할 기준을 반대로 적용하면 오답이다.",
    examSkill: "결정트리 분기 기준 판별",
    textbook: "교재 9장 머신러닝",
  },
  linearRegression: {
    concept: "선형회귀",
    lectureId: 11,
    lectureLabel: "11강 머신러닝(2)",
    tags: ["회귀", "선형회귀"],
    basis: "선형회귀는 독립변수와 종속변수 사이의 선형 관계를 모델링한다.",
    wrongRule: "군집화, 결정트리, 주성분 분석처럼 목적이 다른 기법과 혼동하면 오답이다.",
    examSkill: "회귀 문제 판별",
    textbook: "교재 9장 머신러닝",
  },
  gradientDescent: {
    concept: "경사하강법",
    lectureId: 11,
    lectureLabel: "11강 머신러닝(2)",
    tags: ["최적화", "경사하강법"],
    basis: "경사하강법은 비용함수를 줄이기 위해 기울기의 반대 방향으로 계수를 갱신한다.",
    wrongRule: "기울기 방향, 학습률 곱, 비용함수 최소화 목적을 바꾸면 오답이다.",
    examSkill: "계수 갱신 규칙 판별",
    textbook: "교재 9장 머신러닝",
  },
  logisticRegression: {
    concept: "로지스틱 회귀",
    lectureId: 11,
    lectureLabel: "11강 머신러닝(2)",
    tags: ["분류", "로지스틱 회귀"],
    basis: "로지스틱 회귀는 입력에 따른 종속변수가 0 또는 1이 될 확률을 가설함수로 학습한다.",
    wrongRule: "2차 함수 회귀, 군집화, 보상 기반 학습과 혼동하면 오답이다.",
    examSkill: "로지스틱 회귀 목적 판별",
    textbook: "교재 9장 머신러닝",
  },
  kmeans: {
    concept: "k-평균 군집화",
    lectureId: 11,
    lectureLabel: "11강 머신러닝(2)",
    tags: ["군집화", "k-means"],
    basis: "k-평균 군집화는 각 표본을 가장 가까운 평균벡터에 배정하고 중심을 다시 계산하는 과정을 반복한다.",
    wrongRule: "지도학습, 강화학습, 평균벡터 갱신 방향을 혼동하면 오답이다.",
    examSkill: "군집화 절차 판별",
    textbook: "교재 9장 머신러닝",
  },
  neuralNetwork: {
    concept: "신경회로망",
    lectureId: 12,
    lectureLabel: "12강 인공 신경망(1)",
    tags: ["신경망", "연결가중치"],
    basis: "신경회로망은 뉴런 사이의 연결가중치 벡터에 학습된 정보를 분산 저장한다.",
    wrongRule: "순차처리, 단일 프로세서, 전문가가 직접 저장하는 파라미터와 혼동하면 오답이다.",
    examSkill: "신경망 특징 판별",
    textbook: "교재 10장 인공 신경망",
  },
  activation: {
    concept: "활성함수",
    lectureId: 12,
    lectureLabel: "12강 인공 신경망(1)",
    tags: ["뉴런", "활성함수"],
    basis: "활성함수는 뉴런의 가중합을 출력으로 변환하며 계단, 시그모이드, tanh, ReLU 등이 쓰인다.",
    wrongRule: "함수식의 형태와 출력 범위를 다른 활성함수와 혼동하면 오답이다.",
    examSkill: "활성함수 식 판별",
    textbook: "교재 10장 인공 신경망",
  },
  relu: {
    concept: "ReLU",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["활성함수", "ReLU"],
    basis: "ReLU는 입력이 0 이상이면 x, 0보다 작으면 0을 출력해 심층망 학습에서 자주 사용된다.",
    wrongRule: "시그모이드, tanh, 계단 함수와 식을 혼동하면 오답이다.",
    examSkill: "ReLU 함수식 판별",
    textbook: "교재 11장 딥러닝",
  },
  perceptron: {
    concept: "단층 퍼셉트론",
    lectureId: 12,
    lectureLabel: "12강 인공 신경망(1)",
    tags: ["퍼셉트론", "선형분리"],
    basis: "단층 퍼셉트론은 선형 결정경계를 학습할 수 있지만 XOR처럼 선형분리되지 않는 문제는 해결하지 못한다.",
    wrongRule: "비선형 경계, 군집화, 확률적 모델과 단층 퍼셉트론의 한계를 혼동하면 오답이다.",
    examSkill: "퍼셉트론 한계 판별",
    textbook: "교재 10장 인공 신경망",
  },
  perceptronXor: {
    concept: "퍼셉트론 선형분리",
    lectureId: 12,
    lectureLabel: "12강 인공 신경망(1)",
    tags: ["퍼셉트론", "XOR"],
    basis: "단층 퍼셉트론은 하나의 직선으로 구분 가능한 패턴만 학습할 수 있다.",
    wrongRule: "좌표 공간의 두 클래스가 직선으로 분리되는지 확인하지 않으면 오답이다.",
    examSkill: "선형분리 시각 판별",
    textbook: "교재 10장 인공 신경망",
  },
  mlp: {
    concept: "다층 퍼셉트론",
    lectureId: 13,
    lectureLabel: "13강 인공 신경망(2)",
    tags: ["다층 퍼셉트론", "은닉층"],
    basis: "다층 퍼셉트론은 은닉층을 포함해 단층 퍼셉트론보다 복잡한 결정경계를 학습할 수 있다.",
    wrongRule: "단층 모델, k-평균, LVQ처럼 구조와 학습 목적이 다른 모델과 혼동하면 오답이다.",
    examSkill: "신경망 구조 판별",
    textbook: "교재 10장 인공 신경망",
  },
  momentum: {
    concept: "모멘텀",
    lectureId: 13,
    lectureLabel: "13강 인공 신경망(2)",
    tags: ["오차역전파", "모멘텀"],
    basis: "모멘텀은 이전 가중치 변화량을 반영해 학습이 지역최소치나 고원에서 더 안정적으로 진행되도록 돕는다.",
    wrongRule: "활성함수 제거, 자율학습, 선형분리 기능과 모멘텀의 목적을 혼동하면 오답이다.",
    examSkill: "학습 개선 용도 판별",
    textbook: "교재 10장 인공 신경망",
  },
  som: {
    concept: "자기조직화 지도",
    lectureId: 13,
    lectureLabel: "13강 인공 신경망(2)",
    tags: ["SOM", "자율학습"],
    basis: "자기조직화 지도는 승자 노드와 그 이웃의 가중치를 입력 벡터에 가까워지도록 조정하는 자율학습 모델이다.",
    wrongRule: "지도학습, 출력 노드 클래스 일치, 가중치가 멀어지는 갱신과 혼동하면 오답이다.",
    examSkill: "SOM 갱신 규칙 판별",
    textbook: "교재 10장 인공 신경망",
  },
  lvq: {
    concept: "LVQ",
    lectureId: 13,
    lectureLabel: "13강 인공 신경망(2)",
    tags: ["LVQ", "경쟁학습"],
    basis: "LVQ는 입력과 가장 유사한 출력 노드가 승자가 되고, 클래스 일치 여부에 따라 가중치가 입력 쪽 또는 반대쪽으로 조정된다.",
    wrongRule: "SOM의 이웃 갱신과 LVQ의 클래스 기반 갱신을 혼동하면 오답이다.",
    examSkill: "LVQ 가중치 갱신 판별",
    textbook: "교재 10장 인공 신경망",
  },
  overfitting: {
    concept: "과적합",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["일반화", "과적합"],
    basis: "과적합은 학습 데이터에 지나치게 의존하여 학습되지 않은 데이터에 대한 성능이 저하되는 현상이다.",
    wrongRule: "경사 소멸, 자원 부족, 초기화 문제와 일반화 오류를 혼동하면 오답이다.",
    examSkill: "학습 문제 유형 판별",
    textbook: "교재 11장 딥러닝",
  },
  vanishing: {
    concept: "경사 소멸 문제",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["심층학습", "경사 소멸"],
    basis: "경사 소멸은 출력층의 오차가 입력층 방향으로 내려갈수록 작아져 앞쪽 층 학습이 진행되지 않는 문제이다.",
    wrongRule: "지역최소치, 과적합, 능선 문제와 경사 소멸의 원인을 혼동하면 오답이다.",
    examSkill: "심층학습 문제 판별",
    textbook: "교재 11장 딥러닝",
  },
  dbn: {
    concept: "심층 신뢰망",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["심층 신뢰망", "확률 모델"],
    basis: "심층 신뢰망은 제한 볼츠만 머신을 여러 층 쌓아 학습표본의 확률 분포를 학습하는 모델이다.",
    wrongRule: "LVQ, ReLU, 볼츠만 머신 단일 구조와 심층 신뢰망의 계층 구조를 혼동하면 오답이다.",
    examSkill: "딥러닝 모델 구분",
    textbook: "교재 11장 딥러닝",
  },
  cnn: {
    concept: "합성곱층",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["CNN", "합성곱"],
    basis: "CNN에서 합성곱층은 필터를 적용해 국소 특징을 검출한다.",
    wrongRule: "ReLU층, 풀링층, 완전연결층의 역할과 합성곱층의 특징 검출 역할을 혼동하면 오답이다.",
    examSkill: "CNN 층 역할 판별",
    textbook: "교재 11장 딥러닝",
  },
  pooling: {
    concept: "풀링층",
    lectureId: 14,
    lectureLabel: "14강 딥러닝(1)",
    tags: ["CNN", "풀링"],
    basis: "풀링층은 합성곱 결과를 서브샘플링하여 공간 크기를 줄이고 대표 특징을 보존한다.",
    wrongRule: "합성곱의 특징 검출, ReLU의 비선형 변환, 완전연결층의 분류 역할과 혼동하면 오답이다.",
    examSkill: "CNN 층 역할 판별",
    textbook: "교재 11장 딥러닝",
  },
};

const ANSWERS: Record<2017 | 2018 | 2019, string> = {
  2017: "14223412133241241412334123324214133",
  2018: "13413242412431342134124213342131224",
  2019: "41243113423231213442124134123343214",
};

const TOPIC_BY_YEAR: Record<2017 | 2018 | 2019, string[]> = {
  2017: [
    "expertSystem", "semanticNetwork", "inheritance", "expertSystem", "propositionalLogic",
    "normalForm", "modusPonens", "resolution", "predicateLogic", "predicateNegation",
    "resolution", "resolution", "productionSystem", "inferenceMethod", "forwardChaining",
    "fuzzySet", "fuzzyOp", "fuzzyInference", "connectivity8", "smoothingFilter",
    "sobel", "segmentation", "histogramEqualization", "featureExtraction", "patternGrammar",
    "distanceMetric", "knn", "supervised", "decisionTree", "kmeans",
    "supervised", "neuralNetwork", "perceptron", "mlp", "som",
  ],
  2018: [
    "minimax", "alphaBeta", "mcts", "mcts", "expertSystem",
    "knowledgeRepresentation", "frame", "normalForm", "propositionalLogic", "resolution",
    "fuzzyOp", "fuzzyLaw", "fuzzyInference", "smoothingFilter", "segmentation",
    "sobel", "distanceMetric", "mle", "bayes", "reinforcement",
    "supervised", "decisionTree", "linearRegression", "gradientDescent", "logisticRegression",
    "kmeans", "neuralNetwork", "relu", "perceptronXor", "mlp",
    "som", "lvq", "overfitting", "dbn", "pooling",
  ],
  2019: [
    "minimax", "alphaBeta", "mcts", "mcts", "expertSystem",
    "frame", "propositionalLogic", "normalForm", "predicateLogic", "fuzzySet",
    "fuzzyOp", "fuzzyInference", "visionPipeline", "digitization", "medianFilter",
    "sobel", "pca", "distanceMetric", "mle", "knn",
    "unsupervised", "confusion", "decisionTree", "linearRegression", "gradientDescent",
    "logisticRegression", "kmeans", "neuralNetwork", "activation", "perceptron",
    "momentum", "som", "vanishing", "dbn", "cnn",
  ],
};

const CHOICE_LABELS: Record<ChoiceKey, string> = {
  "1": "1번",
  "2": "2번",
  "3": "3번",
  "4": "4번",
};

const PROMPT_OVERRIDES: Partial<Record<string, string>> = {
  "2017-2-q10": "10. 다음 술어논리식과 동치인 것은?\n아래 수식 자료를 보고 선택하시오.",
  "2017-2-q12": "12. 다음 절들로부터 도출될 수 있는 결론에 해당되는 것은?\n단, P와 Q는 술어기호, x, y, z는 객체변수, A와 B는 객체상수이다.",
  "2017-2-q15": "15. 생성시스템에서 규칙과 현재의 사실이 아래와 같다. 전방향 추론을 할 때 현재 상태에서 실행 가능한 규칙은?",
  "2017-2-q17": "17. 다음 퍼지집합 A와 B의 교집합은?",
  "2017-2-q19": "19. 다음 중 8-이웃 연결성을 적용하였을 때, p1~p4 중 p로부터 연결되는 경로가 존재하는 픽셀을 모두 나열한 것은?\n① 모두\n② p1, p3\n③ p2, p4\n④ p1, p2, p3",
  "2017-2-q20": "20. 다음 중 영상의 평활화에 사용될 수 있는 필터 마스크는?",
  "2017-2-q24": "24. 다음 중 패턴인식을 위한 특징추출의 목적에 해당되는 것을 모은 것은?",
  "2018-2-q01": "1. 이 탐색트리에서 A의 가치와 다음으로 선택할 수는 무엇인가?\n① 4, B\n② 5, C\n③ 9, D\n④ 1, E",
  "2018-2-q02": "2. α-β 가지치기를 적용하는 과정 중 C에서 α는 4이고 β는 ∞이다. 노드 J의 가치인 2를 구한 후의 처리에 대한 설명으로 옳은 것은?\n① 노드 K의 가치를 계산하기 위한 처리를 한다.\n② 노드 J의 가치가 잘못 평가된 것이며, 노드 J를 재평가한다.\n③ 2 < α이므로 K, L은 가치를 구할 필요 없이 가지치기한다.\n④ 2 < α이므로 노드 D, E는 가지치기한다.",
  "2018-2-q10": "10. 다음 절들로부터 도출될 수 있는 결론은 무엇인가?\n단, P, Q, R은 술어기호, x와 y는 객체변수, A, B, C, D는 객체상수이다.",
  "2018-2-q11": "11. 퍼지집합 X와 Y가 다음과 같을 때 퍼지집합 연산이 올바른 것은?\n단, 보수 기호는 해당 퍼지집합의 여집합을 나타낸다.",
  "2018-2-q28": "28. 다음 중 ReLU 함수에 해당되는 것은?",
  "2018-2-q29": "29. x와 o를 식별할 수 있도록 학습하려고 한다. 다음 중 단층 퍼셉트론으로 학습할 수 있는 것은?",
  "2018-2-q32": "32. LVQ의 t번째 학습 과정에서 학습표본 xj와 가장 유사한 연결가중치 벡터 wi를 갖는 출력노드 ci가 승자노드가 되었을 때, xj와 ci의 클래스가 동일할 경우 wi는 어떻게 조정하는가?\n단, α(t)는 적응 이득이다.",
  "2019-2-q01": "1. 다음 최대최소 탐색트리의 A에서 다음 수로 D를 선택하게 되는 노드 L의 평가함수 값 (ㄱ)과 그때의 A의 가치 (ㄴ)은?\n리프의 값들은 그 노드에 대한 가치를 예측한 평가함수 값이다.\n① (ㄱ) 5, (ㄴ) 8\n② (ㄱ) 5, (ㄴ) 13\n③ (ㄱ) 9, (ㄴ) 13\n④ (ㄱ) 10, (ㄴ) 8",
  "2019-2-q08": "8. 다음 중 연언 표준형에 해당되는 논리식은?\n단, p, q, r, s는 기본명제이다.",
  "2019-2-q09": "9. 다음 술어논리식에서 (ㄱ) 부모절의 쌍과 (ㄴ) 도출절이 올바른 것은?\n단, P, Q, R은 술어, x와 y는 객체변수, A와 B는 객체상수이다.",
  "2019-2-q11": "11. 다음 중 퍼지논리 연산자를 적절히 정의한 것은?",
  "2019-2-q29": "29. 다음 중 뉴런의 활성함수로 적합하지 않은 것은?",
  "2019-2-q32": "32. 다음 중 자기조직화 지도 학습의 t번째 단계에서 학습표본 xj에 대한 승자 노드 및 그 이웃집합에 속하는 노드의 가중치벡터 wm을 조정하는 방법은?\n단, 적응 이득 α(t)는 양수이다.",
  "2019-2-q34": "34. 제한 볼츠만 머신과 같은 자율학습 신경망을 여러 층 쌓은 모델로, 학습표본 집합의 확률 분포를 학습할 수 있는 확률적 심층 신경망 모델에 해당되는 것은?\n① 심층 신뢰망(deep belief nets)\n② LVQ(Learning Vector Quantization)\n③ ReLU(Rectified Linear Unit)\n④ 볼츠만 머신(Boltzmann machine)",
};

function visual(
  fileName: string,
  alt: string,
  aiDescriptionHidden: string,
  sourcePageInternal: 1 | 2,
  width: number,
  height: number,
): PastExamQuestionImage {
  return {
    src: `/ai/past-exam/figures/${fileName}`,
    alt,
    aiDescriptionHidden,
    sourcePageInternal,
    cropBoxInternal: { x: 0, y: 0, width, height },
  };
}

const VISUAL_CROPS: Partial<Record<string, PastExamQuestionImage[]>> = {
  "2017-2-q10": [
    visual(
      "2017-2-q10-formula.jpg",
      "술어논리식과 선택지 식",
      "술어논리식의 한정기호 부정 변환을 묻는 수식 영역이다. 전칭 한정과 조건명제 부정, 존재 한정으로 바뀌는 후보 식들이 선택지로 제시되어 있다.",
      1,
      658,
      220,
    ),
  ],
  "2017-2-q12": [
    visual(
      "2017-2-q12-clauses.jpg",
      "도출연역 절 목록",
      "술어 P, Q와 상수 A, B가 포함된 부모절 목록과 도출 가능한 결론 후보가 제시된 수식 영역이다.",
      1,
      641,
      235,
    ),
  ],
  "2017-2-q15": [
    visual(
      "2017-2-q15-rules.jpg",
      "생성시스템 사실과 규칙 표",
      "현재 사실과 여러 생성 규칙이 표 형태로 제시되어 있으며, 전방향 추론에서 현재 실행 가능한 규칙을 고르는 조건을 제공한다.",
      1,
      625,
      165,
    ),
  ],
  "2017-2-q17": [
    visual(
      "2017-2-q17-fuzzy.jpg",
      "퍼지집합 A와 B의 원소별 소속도",
      "퍼지집합 A와 B가 원소 a, b, c, d와 각 소속함수 값의 쌍으로 제시되어 있다. 교집합 계산에는 공통 원소별 최소 소속도 비교가 필요하다.",
      1,
      635,
      200,
    ),
  ],
  "2017-2-q19": [
    visual(
      "2017-2-q19-grid.jpg",
      "픽셀 연결성 격자",
      "p에서 p1, p2, p3, p4 후보 픽셀로 이어지는 격자 구조가 제시되어 있으며, 8-이웃 연결 기준으로 경로 존재 여부를 판단해야 한다.",
      2,
      475,
      160,
    ),
  ],
  "2017-2-q20": [
    visual(
      "2017-2-q20-masks.jpg",
      "필터 마스크 선택지",
      "평활화에 사용할 수 있는 여러 3x3 필터 마스크 후보가 제시되어 있다. 계수 부호와 합, 중앙값 강조 여부를 비교해야 한다.",
      2,
      565,
      165,
    ),
  ],
  "2017-2-q24": [
    visual(
      "2017-2-q24-feature-box.jpg",
      "특징추출 목적 항목 목록",
      "패턴 공간 차수 감소, 판별에 적합한 값 획득, 잡음 제거, 패턴 확대 등 특징추출 목적 후보 항목이 묶음 보기로 제시되어 있다.",
      2,
      618,
      143,
    ),
  ],
  "2018-2-q01": [
    visual(
      "2018-2-q01-tree.jpg",
      "최대최소 탐색트리",
      "루트 A 아래 B, C, D, E가 있고 각 내부 노드 아래 말단 노드 F부터 Q까지가 배치된 깊이 2 탐색트리이다. 말단에는 5, 6, 4, 6, 2, 7, 5, 9, 3, 5, 1, 2 평가값이 붙어 있다.",
      1,
      505,
      210,
    ),
  ],
  "2018-2-q02": [
    visual(
      "2018-2-q01-tree.jpg",
      "알파-베타 가지치기 대상 탐색트리",
      "1번과 같은 최대최소 탐색트리이다. A의 자식 B, C, D, E와 말단 평가값을 기준으로 C에서 alpha와 beta 조건을 비교하는 문제에 사용된다.",
      1,
      505,
      210,
    ),
  ],
  "2018-2-q10": [
    visual(
      "2018-2-q10-clauses.jpg",
      "도출연역 절과 결론 후보",
      "P, Q, R 술어와 x, y 변수, A, B, C, D 상수가 포함된 절들이 한 줄 표처럼 제시되어 있고, 아래에 도출 결론 후보가 배열되어 있다.",
      1,
      660,
      195,
    ),
  ],
  "2018-2-q11": [
    visual(
      "2018-2-q11-fuzzy.jpg",
      "퍼지집합 X와 Y 및 연산 후보",
      "퍼지집합 X와 Y의 원소별 소속도와 합집합, 교집합, 여집합 후보가 제시되어 있다. 원소별 최대, 최소, 보수 계산을 대조해야 한다.",
      1,
      640,
      225,
    ),
  ],
  "2018-2-q28": [
    visual(
      "2018-2-q28-relu.jpg",
      "활성함수 식 선택지",
      "계단 함수, 시그모이드, 하이퍼볼릭 탄젠트, ReLU 형태의 함수식 후보가 제시되어 있다. ReLU는 입력이 0 이상이면 입력값, 0보다 작으면 0을 출력하는 식이다.",
      2,
      625,
      135,
    ),
  ],
  "2018-2-q29": [
    visual(
      "2018-2-q29-scatter.jpg",
      "두 클래스 산점도 후보",
      "x와 o 두 클래스가 좌표평면에 배치된 여러 후보 그림이다. 단층 퍼셉트론으로 가능한지 판단하려면 한 직선으로 두 클래스를 분리할 수 있는지 보아야 한다.",
      2,
      515,
      230,
    ),
  ],
  "2018-2-q32": [
    visual(
      "2018-2-q32-lvq.jpg",
      "LVQ 가중치 갱신식 선택지",
      "LVQ에서 승자 출력노드와 학습표본의 클래스가 동일한 경우 사용할 가중치 벡터 갱신식 후보가 제시되어 있다.",
      2,
      640,
      270,
    ),
  ],
  "2019-2-q01": [
    visual(
      "2019-2-q01-tree.jpg",
      "최대최소 탐색트리",
      "루트 A 아래 B, C, D가 있고 말단 노드 평가값 중 일부가 물음표로 남아 있는 최대최소 탐색트리이다. D를 선택하게 되는 L의 평가값과 A의 가치를 묻는다.",
      1,
      485,
      200,
    ),
  ],
  "2019-2-q08": [
    visual(
      "2019-2-q08-formulas.jpg",
      "연언표준형 논리식 선택지",
      "p, q, r, s 기본명제를 포함한 논리식 후보가 제시되어 있다. 리터럴의 논리합으로 된 절들이 논리곱으로 결합되어 있는지를 판단해야 한다.",
      1,
      635,
      90,
    ),
  ],
  "2019-2-q09": [
    visual(
      "2019-2-q09-clauses.jpg",
      "부모절 쌍과 도출절 후보",
      "술어 P, Q와 객체 변수, 객체 상수를 포함한 부모절 쌍 및 도출절 후보가 제시되어 있다. 상보 리터럴 제거 후 남는 절을 비교해야 한다.",
      1,
      635,
      115,
    ),
  ],
  "2019-2-q11": [
    visual(
      "2019-2-q11-fuzzy-ops.jpg",
      "퍼지논리 연산자 후보",
      "퍼지논리의 논리곱, 논리합, 부정 연산 정의 후보가 수식으로 제시되어 있다. 표준 정의의 min, max, 1-a 기준과 대조해야 한다.",
      1,
      485,
      80,
    ),
  ],
  "2019-2-q29": [
    visual(
      "2019-2-q29-activations.jpg",
      "활성함수 식 후보",
      "계단 함수, 시그모이드, 하이퍼볼릭 탄젠트, ReLU와 유사한 함수식 후보가 제시되어 있다. 뉴런 활성함수로 적합하지 않은 형태를 판별한다.",
      2,
      635,
      140,
    ),
  ],
  "2019-2-q32": [
    visual(
      "2019-2-q32-som.jpg",
      "SOM 가중치 갱신식 선택지",
      "자기조직화 지도에서 승자 노드와 이웃 노드의 가중치 벡터를 학습표본 쪽으로 이동시키는 갱신식 후보가 제시되어 있다.",
      2,
      640,
      240,
    ),
  ],
};

function makeQuestion(year: 2017 | 2018 | 2019, number: number): PastExamQuestion {
  const topic = TOPICS[TOPIC_BY_YEAR[year][number - 1]];
  const correctChoice = ANSWERS[year][number - 1] as ChoiceKey;
  const page = number <= 16 || (year === 2017 && number <= 17) ? 1 : 2;
  const id = `${year}-2-q${String(number).padStart(2, "0")}`;

  return {
    id,
    year,
    semester: "2",
    examName: `${year}학년도 2학기 기말시험`,
    number,
    prompt: PROMPT_OVERRIDES[id] ?? aiPastExamOcrText[id] ?? `${year}학년도 2학기 인공지능 ${number}번`,
    images: VISUAL_CROPS[id],
    choices: (["1", "2", "3", "4"] as ChoiceKey[]).map((key) => ({
      key,
      label: CHOICE_LABELS[key],
      explanation:
        key === correctChoice
          ? {
              verdict: "correct",
              reason: `${topic.concept}의 강의 기준을 만족하는 선택지다.`,
              conceptBasis: topic.basis,
            }
          : {
              verdict: "wrong",
              reason: topic.wrongRule,
              conceptBasis: topic.basis,
            },
    })),
    correctChoice,
    lectureRefs: [
      {
        lectureId: topic.lectureId,
        label: topic.lectureLabel,
        href: `/ai/lecture/${topic.lectureId}`,
        concept: topic.concept,
      },
    ],
    conceptTags: topic.tags,
    basis: topic.basis,
    wrongRule: topic.wrongRule,
    examSkill: topic.examSkill,
    sourceBasis: [
      {
        learnerLabel: "강의 내용과 교재 개념 기준",
        concept: topic.concept,
        internalLectureSource: `인공지능 ${topic.lectureId}강 강의록`,
        internalTextbookSource: topic.textbook,
      },
    ],
    answerSourceInternal: `${year}학년도 2학기 정답표 인공지능 행 ${number}번`,
    questionSourceInternal: `${year}학년도 2학기 인공지능 기출문제 ${page}쪽 ${number}번`,
  };
}

export const aiPastExamQuestions: PastExamQuestion[] = ([2017, 2018, 2019] as const).flatMap((year) =>
  Array.from({ length: 35 }, (_, index) => makeQuestion(year, index + 1)),
);

export const aiPastExamYears = [2019, 2018, 2017] as const;
