export type JavaFrequentConcept = {
  id: string;
  label: string;
  category: string;
  lectureIds: number[];
  refs: string[];
  years: number[];
  frequency: number;
  sourceLabel: string;
  definition: string;
  examCue: string;
  surrounding: string[];
  variants: string[];
  note?: string;
};

type ConceptSeed = Omit<JavaFrequentConcept, "years" | "frequency">;

function yearFromRef(ref: string) {
  return Number(ref.slice(0, 4));
}

const concepts: ConceptSeed[] = [
  {
    id: "java-platform-tools",
    label: "Java 플랫폼 구성",
    category: "개발 환경",
    lectureIds: [1],
    refs: ["2018-36"],
    sourceLabel: "1강 Java 언어 개요",
    definition: "Java 프로그램 작성과 실행에 필요한 JDK, Java Platform, Java VM의 역할과 JavaScript 도구처럼 범위 밖인 항목을 구분하는 개념.",
    examCue: "Java라는 이름이 들어간 도구를 모두 같은 범주로 보게 만들고, 실습 환경에 필요한 구성요소가 아닌 것을 고르게 한다.",
    surrounding: ["JDK", "JRE", "JVM", "Java Platform", "Eclipse"],
    variants: ["Java VM", "JDK", "개발 도구"],
  },
  {
    id: "array-declaration-initializer",
    label: "배열 선언·생성·초기화",
    category: "기본문법",
    lectureIds: [3],
    refs: ["2018-37", "2019-36"],
    sourceLabel: "3강 배열과 클래스 기초",
    definition: "배열은 같은 자료형 원소를 고정 길이로 저장하며, 선언 위치, new 생성식, 초기화 블록, 다차원 배열의 차원 수가 문법적으로 맞아야 한다.",
    examCue: "초기화 블록을 대입문 오른쪽에 단독으로 쓰거나 2차원 배열을 1차원 생성식으로 만드는 보기를 섞는다.",
    surrounding: ["int[]", "배열 초기화 블록", "다차원 배열", "참조형 변수"],
    variants: ["array", "initializer", "new int[]"],
  },
  {
    id: "println-expression",
    label: "출력문과 문자열 연결",
    category: "기본문법",
    lectureIds: [2],
    refs: ["2018-38"],
    sourceLabel: "2강 Java 기본 문법",
    definition: "System.out.println은 하나의 인수를 출력하므로 여러 값을 함께 보이려면 `+`로 문자열 표현식을 만들어 전달해야 한다.",
    examCue: "println에 쉼표로 여러 인수를 넘기는 C 스타일 표기를 오답으로 제시한다.",
    surrounding: ["System.out", "println", "문자열 연결 연산", "표현식"],
    variants: ["print", "console output"],
  },
  {
    id: "object-creation-reference",
    label: "객체 생성과 참조 변수",
    category: "객체지향",
    lectureIds: [4],
    refs: ["2017-36"],
    sourceLabel: "4강 클래스와 객체",
    definition: "`new`는 객체 메모리를 확보하고 생성자를 호출하며, 좌변 변수에는 객체 자체가 아니라 해당 객체를 가리키는 참조값이 저장된다.",
    examCue: "객체 생성 과정과 초기화 블록·생성자 실행을 섞어 참조 변수, 메모리 할당, 초기화 절차를 구분하게 한다.",
    surrounding: ["new", "생성자", "참조형", "초기화 블록"],
    variants: ["constructor", "reference variable"],
  },
  {
    id: "access-control-overriding",
    label: "접근 제어와 오버라이딩 조건",
    category: "객체지향",
    lectureIds: [3, 4],
    refs: ["2017-37", "2018-40"],
    sourceLabel: "3강·4강 클래스 멤버와 상속",
    definition: "접근 제어자는 멤버 사용 범위를 제한하고, 오버라이딩은 부모 메소드와 같은 시그니처·호환 반환형·좁아지지 않는 접근 범위를 만족해야 한다.",
    examCue: "가장 넓은 접근 범위를 묻거나, protected 메소드를 더 좁은 접근자로 재정의하는 후보를 섞는다.",
    surrounding: ["public", "protected", "private", "method signature", "overriding"],
    variants: ["access modifier", "override"],
  },
  {
    id: "abstract-interface-inheritance",
    label: "추상 클래스·인터페이스·상속 관계",
    category: "객체지향",
    lectureIds: [5],
    refs: ["2017-38", "2017-39", "2018-39", "2018-43", "2019-37", "2019-38", "2019-39"],
    sourceLabel: "5강 인터페이스와 다형성",
    definition: "클래스 상속은 단일 `extends`, 인터페이스 구현은 `implements`, 인터페이스 확장은 `extends`를 사용하며 추상 클래스와 인터페이스는 직접 인스턴스화 가능 여부와 멤버 규칙이 다르다.",
    examCue: "클래스 다중 상속, 인터페이스가 클래스를 extends하는 문장, 추상 클래스 인스턴스 생성, default 메소드 키워드를 함께 출제한다.",
    surrounding: ["extends", "implements", "abstract", "interface", "default method", "다형성"],
    variants: ["abstract class", "interface inheritance", "dynamic binding"],
  },
  {
    id: "anonymous-class",
    label: "익명 클래스",
    category: "객체지향",
    lectureIds: [5],
    refs: ["2017-40", "2018-41", "2018-42"],
    sourceLabel: "5강 인터페이스와 다형성",
    definition: "익명 클래스는 이름 없는 하위 클래스나 구현 클래스를 선언하는 동시에 객체를 생성하는 표현이며, 컴파일 시 별도 내부 클래스 파일이 만들어질 수 있다.",
    examCue: "`new 상위타입() { ... }`를 일반 클래스 정의, 다중 상속, 제네릭 매개변수화와 혼동시키는 보기를 낸다.",
    surrounding: ["anonymous class", "inner class", "상위 타입", "객체 생성식"],
    variants: ["anonymous inner class", "무명 클래스"],
  },
  {
    id: "main-method-signature",
    label: "main 메소드 시그니처",
    category: "기본문법",
    lectureIds: [6],
    refs: ["2017-41"],
    sourceLabel: "6강 제네릭과 람다식 도입부",
    definition: "Java 응용 프로그램의 시작점은 `public static void main(String[] args)` 형식이며, 명령행 인수는 문자열 배열로 전달된다.",
    examCue: "`String args`, `Char[] args`, 이중 배열 표기처럼 시작점 규칙과 맞지 않는 후보를 섞는다.",
    surrounding: ["public", "static", "void", "String[] args"],
    variants: ["entry point", "main function"],
  },
  {
    id: "generic-type-safety",
    label: "제네릭 타입 안정성",
    category: "제네릭·컬렉션",
    lectureIds: [6, 11],
    refs: ["2017-42", "2018-44", "2019-45"],
    sourceLabel: "6강 제네릭·11강 컬렉션",
    definition: "제네릭은 타입 매개변수로 저장 원소의 타입을 제한해 캐스팅을 줄이고, 타입 인수에는 기본 자료형이 아니라 참조형을 사용한다.",
    examCue: "raw 타입에서 꺼낸 값을 곧바로 String에 대입하거나 `Data<int>`처럼 기본형을 타입 인수로 쓰는 코드를 묻는다.",
    surrounding: ["타입 매개변수", "raw type", "ArrayList<String>", "래퍼 클래스"],
    variants: ["generics", "type parameter", "diamond operator"],
  },
  {
    id: "enhanced-for",
    label: "향상된 for문",
    category: "제네릭·컬렉션",
    lectureIds: [12],
    refs: ["2017-48", "2019-46"],
    sourceLabel: "12강 컬렉션과 스트림",
    definition: "향상된 for문은 `for (원소자료형 변수 : 배열또는컬렉션)` 형식으로 배열이나 컬렉션의 원소를 순서대로 하나씩 꺼내 처리한다.",
    examCue: "콜론 좌우 순서를 바꾸거나 원소 변수의 자료형을 생략한 후보를 제시한다.",
    surrounding: ["for-each", "Iterable", "컬렉션 순회", "원소 변수"],
    variants: ["enhanced for", "foreach"],
  },
  {
    id: "exception-propagation",
    label: "예외 처리와 예외 전파",
    category: "예외",
    lectureIds: [7],
    refs: ["2017-43", "2017-51", "2018-53", "2019-43", "2019-53"],
    sourceLabel: "7강 패키지와 예외처리",
    definition: "`try-catch-finally`는 예외 발생 지점 이후 흐름과 마지막 정리 코드를 다루며, 메소드가 예외를 호출자에게 넘길 때는 `throws` 절을 사용한다.",
    examCue: "finally 생략 가능 여부, catch 매개변수 문법, `throw`와 `throws`, InterruptedException 전파 조건을 섞어 묻는다.",
    surrounding: ["try", "catch", "finally", "throw", "throws", "InterruptedException"],
    variants: ["exception handling", "exception propagation"],
  },
  {
    id: "string-immutability",
    label: "String 불변성과 문자열 비교",
    category: "java.lang",
    lectureIds: [8],
    refs: ["2017-44", "2018-45", "2018-46", "2019-40", "2019-41"],
    sourceLabel: "8강 java.lang 패키지",
    definition: "String은 불변 객체이므로 연결·변경 연산에서 새 객체가 만들어지고, 참조 비교(`==`)와 내용 비교(`equals`)를 구분해야 한다.",
    examCue: "StringBuffer와 역할을 뒤집거나, `==`와 `equals` 결과, 반복 연결의 메모리·속도 영향을 묻는다.",
    surrounding: ["immutable", "equals", "StringBuffer", "문자열 연결", "객체 생성"],
    variants: ["String class", "문자열 불변성"],
  },
  {
    id: "wrapper-boxing",
    label: "래퍼 클래스와 박싱",
    category: "java.lang",
    lectureIds: [8],
    refs: ["2017-45"],
    sourceLabel: "8강 java.lang 패키지",
    definition: "박싱은 기본형 값을 Integer 같은 래퍼 클래스 객체로 감싸는 변환이며, 문자열 변환이나 문자열 파싱과는 다른 개념이다.",
    examCue: "Integer.toString, parseInt, String.valueOf를 박싱 코드처럼 보이게 제시한다.",
    surrounding: ["Integer", "wrapper class", "boxing", "parseInt", "valueOf"],
    variants: ["boxing", "wrapper"],
  },
  {
    id: "io-stream-classes",
    label: "입출력 스트림 클래스",
    category: "입출력",
    lectureIds: [9],
    refs: ["2017-46", "2018-47", "2019-42"],
    sourceLabel: "9강 java.io 패키지",
    definition: "java.io는 바이트 스트림과 문자 스트림을 구분하며, 파일 대상과 데이터 단위에 따라 FileInputStream, FileOutputStream, FileReader, FileWriter를 선택한다.",
    examCue: "텍스트 파일의 문자 단위 입출력과 바이트 단위 입출력을 뒤섞어 클래스 이름을 고르게 한다.",
    surrounding: ["바이트 스트림", "문자 스트림", "FileReader", "FileWriter", "FileInputStream"],
    variants: ["stream", "reader", "writer"],
  },
  {
    id: "nio-path-buffer",
    label: "java.nio Path·Buffer·Channel",
    category: "입출력",
    lectureIds: [10],
    refs: ["2017-47", "2018-48", "2019-44"],
    sourceLabel: "10강 java.nio 패키지",
    definition: "Path는 파일·디렉터리 경로를 표현하고 조작하는 타입이며, Buffer와 Channel은 채널 기반 입출력에서 데이터 임시 저장과 전송 통로 역할을 한다.",
    examCue: "Path가 파일 내용을 직접 읽고 쓰는 타입이라고 하거나, Buffer에 읽기·쓰기 방향을 뒤집은 설명을 제시한다.",
    surrounding: ["Path", "Buffer", "FileChannel", "charset", "java.nio.file"],
    variants: ["NIO", "channel I/O"],
  },
  {
    id: "collection-interfaces",
    label: "컬렉션 인터페이스와 구현 클래스",
    category: "제네릭·컬렉션",
    lectureIds: [11],
    refs: ["2017-49", "2017-50", "2018-49", "2018-50", "2019-47", "2019-48"],
    sourceLabel: "11강 컬렉션",
    definition: "List는 순서와 중복을 허용하고, Set은 중복 없는 집합을, Map은 key-value 쌍을 다루며 구현 클래스와 메소드도 그 의미에 맞게 선택해야 한다.",
    examCue: "ArrayList가 중복을 금지한다고 하거나, LinkedList를 Map 구현체로 제시하거나, HashMap의 get/put을 다른 자료구조 메소드와 섞는다.",
    surrounding: ["List", "Set", "Map", "ArrayList", "HashMap", "get", "put"],
    variants: ["collections", "map entry", "hash table"],
  },
  {
    id: "thread-control-sync",
    label: "스레드 생성·제어·동기화",
    category: "멀티스레드",
    lectureIds: [13],
    refs: ["2017-52", "2017-53", "2017-54", "2018-51", "2018-52", "2019-49", "2019-50", "2019-51", "2019-52"],
    sourceLabel: "13강 멀티 스레드 프로그래밍",
    definition: "Thread 상속 또는 Runnable 구현으로 스레드를 만들고, start/run, yield, join, synchronized를 통해 실행 흐름과 공유 자원 접근을 제어한다.",
    examCue: "yield와 join의 효과, Thread 서브클래스 선언, 공유 자원 식별, synchronized 위치 문법을 코드 보기로 묻는다.",
    surrounding: ["Thread", "Runnable", "yield", "join", "synchronized", "공유 자원"],
    variants: ["multithreading", "monitor", "critical section"],
  },
  {
    id: "awt-event-layout",
    label: "AWT 컴포넌트·배치·이벤트",
    category: "GUI",
    lectureIds: [15],
    refs: [
      "2017-55",
      "2017-56",
      "2017-57",
      "2017-58",
      "2018-54",
      "2018-55",
      "2018-56",
      "2018-57",
      "2018-58",
      "2019-54",
      "2019-55",
      "2019-56",
      "2019-57",
      "2019-58",
    ],
    sourceLabel: "15강 라이브러리와 GUI",
    definition: "AWT GUI는 Component/Container 계층, 배치관리자, 이벤트 소스와 리스너 등록으로 동작하며 각 이벤트 클래스에 대응되는 리스너 또는 어댑터를 사용한다.",
    examCue: "List 컨트롤, FlowLayout·GridLayout 화면, ActionListener·WindowAdapter, import 의미를 실행 화면과 코드 빈칸으로 반복 출제한다.",
    surrounding: ["Component", "Container", "FlowLayout", "GridLayout", "ActionListener", "WindowAdapter"],
    variants: ["AWT", "event listener", "layout manager"],
  },
  {
    id: "jdbc-core-flow",
    label: "JDBC 연결과 SQL 실행 흐름",
    category: "JDBC",
    lectureIds: [14],
    refs: ["2017-59", "2017-60", "2018-59", "2018-60", "2019-59", "2019-60"],
    sourceLabel: "14강 JDBC 프로그래밍",
    definition: "JDBC는 Connection으로 DBMS와 연결하고 Statement 또는 PreparedStatement로 SQL을 표현·실행하며, SELECT 결과는 ResultSet으로 처리한다.",
    examCue: "Connection, Statement, PreparedStatement, ResultSet의 순서와 executeQuery/executeUpdate의 용도를 코드 빈칸으로 묻는다.",
    surrounding: ["Connection", "Statement", "PreparedStatement", "ResultSet", "executeQuery", "executeUpdate"],
    variants: ["JDBC", "SQL execution", "database connection"],
  },
];

export const javaFrequentConcepts: JavaFrequentConcept[] = concepts.map((concept) => ({
  ...concept,
  frequency: concept.refs.length,
  years: Array.from(new Set(concept.refs.map(yearFromRef))).sort((a, b) => a - b),
}));

export const javaFrequentConceptCategories = Array.from(
  new Set(javaFrequentConcepts.map((concept) => concept.category)),
).sort((a, b) => a.localeCompare(b, "ko"));
