import type { GlossaryTerm } from "@/lib/mlGlossaryTypes";

/**
 * 5강 데이터 표현: 특징추출(교재 7장)에서 다루는 용어.
 *
 * 정의는 교재·강의록 표현을 보존하되 한 문장으로 읽히게 다듬었다.
 * 1강에서 이름만 소개된 PCA·LDA·MDS·t-SNE 등은 같은 id로 더 자세히 정의한다.
 */
export const lecture5Terms: GlossaryTerm[] = [
  /* ─────────── 특징추출과 변환함수 ─────────── */
  {
    id: "t-feature-extraction",
    term: "특징추출",
    en: "feature extraction",
    category: "개념",
    short: "원래 데이터 x를 변환해 새로운 특징벡터 y로 표현하는 과정.",
    definition:
      "분류기나 군집분석기를 수행함에 앞서 원래 데이터를 그대로 쓰는 대신 분석에 불필요한 정보를 제거하고 핵심이 되는 정보만 추출하거나, 데이터의 차원 축소를 통해 학습시스템의 효율을 향상하기 위한 목적으로 원래 데이터 x를 변환하여 새로운 특징벡터 y로 표현하는 과정. n차원 입력 벡터 x에 변환함수 φ를 적용해 m차원 특징벡터 y를 얻는 변환 y = φ(x)다.",
    role: "학습의 결과물은 변환함수 y = φ(x; θ)이고, 새 데이터가 들어오면 y_new = φ(x_new; θ)로 특징을 만든다.",
    formula: [
      { expr: "y = φ(x)", note: "n차원 x → m차원 y" },
      { expr: "y = φ(x) = Wᵀx", note: "선형변환인 경우" },
    ],
    example: "64차원 숫자 영상을 PCA나 LDA로 2차원 특징으로 줄이는 것, 6개 도시의 이동 비용표를 MDS로 2차원 좌표로 나타내는 것.",
    distinctions: [
      {
        from: "무조건적인 차원 축소",
        how: "특징추출의 목적은 분석 목적에 맞는 핵심 정보를 얻는 것이다. 차원을 가능한 최대한 줄여야 한다는 서술은 틀린 것이다.",
      },
    ],
    prereqs: ["pre-column-vector", "pre-matrix-mult"],
    related: ["t-transform-function", "t-linear-transform", "t-representation-learning", "t-handcrafted-feature", "t-subspace-analysis", "t-pca", "t-lda"],
    lectures: [5],
    basis: "교재 7장 도입 · 강의록 5강 특징추출",
    emphasis: "핵심이 되는 정보가 무엇인지는 데이터 집합과 분석 목적에 따라 달라지며, 효율 향상은 계산량·메모리 절감을 넘어 성능 향상까지 뜻한다.",
    aliases: ["feature extraction", "특징 추출", "데이터 표현"],
  },
  {
    id: "t-transform-function",
    term: "변환함수",
    en: "transformation function / embedding function",
    category: "개념",
    short: "입력 x를 특징 y로 바꾸는 함수 φ. 선형변환과 비선형변환으로 구분.",
    definition:
      "특징추출에서 원래 데이터 x를 특징벡터 y로 바꾸는 함수 y = φ(x). 선형변환은 n차원 열벡터 x에 변환행렬 W(n × m)를 곱해 m차원 특징을 얻고, 비선형변환은 복잡한 비선형함수 φ(x)로 n차원 벡터를 m차원 벡터로 매핑한다.",
    role: "특징추출 학습의 결과물. 학습이 끝나면 새로운 데이터에도 같은 함수를 적용해 특징을 얻는다.",
    formula: [
      { expr: "선형변환: y = φ(x) = Wᵀx" },
      { expr: "비선형변환: y = φ(x), φ는 복잡한 비선형함수" },
    ],
    distinctions: [
      {
        from: "거리 기반 차원 축소",
        how: "MDS, t-SNE, Isomap은 입력과 특징 사이의 변환함수(매핑 함수)를 정의하지 않는다. 그래서 새 데이터의 특징을 구할 수 없다.",
      },
    ],
    related: ["t-feature-extraction", "t-linear-transform", "t-representation-learning", "t-distance-based-reduction"],
    lectures: [5],
    basis: "교재 7장 도입 · 강의록 5강 변환함수",
    aliases: ["transformation function", "embedding function", "φ", "임베딩 함수"],
  },
  {
    id: "t-linear-transform",
    term: "선형변환에 의한 특징추출",
    en: "feature extraction by linear transformation",
    category: "개념",
    short: "입력 데이터를 변환행렬 W가 정하는 방향으로 사영해 저차원 특징값을 얻는 것.",
    definition:
      "주어진 데이터를 변환행렬 W에 의해 정해지는 방향으로 사영함으로써 저차원 특징값을 얻는 것. 이때 변환행렬 W의 각 열은 사영할 저차원 부분공간의 기저를 이루어 해당 부분공간을 정의한다. 데이터의 특성에 의존하지 않고 일반적인 데이터에 적용할 수 있다.",
    role: "통계적 방법으로 특징벡터 y가 원하는 분포가 되도록 하는 W를 찾는 것이 목적. 대표 방법은 PCA와 LDA.",
    formula: [
      { expr: "y = Wᵀx = [w₁ᵀx, …, w_mᵀx]ᵀ", note: "식 7-1, 7-2" },
      { expr: "Y = WᵀX = [Wᵀx₁, …, Wᵀx_N]", note: "식 7-3 — X는 n × N, Y는 m × N" },
    ],
    example: "x = [2, 2]ᵀ를 W = [1, 0]ᵀ로 변환하면 y = 2, W = [2, 1]ᵀ/√5로 변환하면 y = 6/√5.",
    prereqs: ["pre-matrix-mult", "pre-transpose", "pre-unit-vector", "pre-basis-vector"],
    related: ["t-transformation-matrix", "t-projection", "t-subspace-analysis", "t-pca", "t-lda"],
    lectures: [5],
    basis: "교재 7.1 선형변환에 의한 특징추출 · 강의록 5강 선형변환에 의한 특징추출",
    emphasis: "이 내용을 따라가려면 행렬 곱셈의 크기 관계와 사영 두 가지를 먼저 알아야 한다.",
    aliases: ["선형변환", "linear transformation", "Y = WᵀX"],
  },
  {
    id: "t-handcrafted-feature",
    term: "수작업에 의한 특징추출",
    en: "hand-crafted feature extraction",
    category: "개념",
    short: "데이터 종류·특성과 분석 목적에 맞는 특징을 개발자가 일일이 설계하는 방법.",
    definition:
      "입력 데이터의 종류, 특성과 분석 목적에 맞는 적절한 특징을 개발자가 일일이 설계하는 특징추출 접근 방법. 비선형변환의 접근 방법 중 하나다.",
    example: "숫자인식 — 격자 특징(120 × 120 → 12 × 12), 수직 히스토그램, 방향 성분. 영상분석 — 에지, 가로/세로 방향 성분. 문서분석 — 단어의 발생 빈도.",
    distinctions: [
      {
        from: "표현학습",
        how: "수작업은 사람이 특징을 설계하고, 표현학습은 신경망 등 머신러닝 모델이 학습으로 변환함수를 찾는다. 개발자가 일일이 설계하는 과정을 표현학습이라고 한 선택지는 틀린 것이다.",
      },
    ],
    related: ["t-representation-learning", "t-feature-extraction", "t-transform-function"],
    lectures: [5],
    basis: "강의록 5강 특징추출을 위한 접근 방법 — 수작업에 의한 특징추출",
    aliases: ["수작업 특징", "hand-crafted feature", "특징 설계"],
  },
  {
    id: "t-representation-learning",
    term: "표현학습",
    en: "representation learning",
    category: "학습 유형",
    short: "특징추출용 비선형 변환함수를 신경망 등 머신러닝 모델로 표현하고 학습으로 최적화하는 것.",
    definition:
      "특징추출을 위한 비선형 변환함수를 신경망 등의 머신러닝 모델로 표현하고, 학습을 통해 분석이 잘 되도록 하는 최적화된 변환함수를 찾는 것. 딥러닝 등으로 복잡한 변환함수를 정의하고 학습으로 최적화한다.",
    example: "딥러닝 모델(DeepFace)을 이용한 얼굴인식용 특징추출 — 앞쪽 층에서는 저수준 특징, 뒤쪽 층으로 갈수록 추상화된 고수준 특징이 추출된다.",
    distinctions: [
      { from: "수작업에 의한 특징추출", how: "표현학습은 특징을 사람이 설계하지 않고 모델이 데이터로부터 학습한다." },
    ],
    related: ["t-handcrafted-feature", "t-feature-extraction", "t-deep-learning"],
    lectures: [5],
    basis: "교재 7장 도입 · 강의록 5강 특징추출을 위한 접근 방법 — 표현학습",
    aliases: ["representation learning", "표현 학습"],
  },
  {
    id: "t-curse-of-dimensionality",
    term: "차원의 저주",
    en: "curse of dimensionality",
    category: "개념",
    short: "입력 차원이 늘어나면 계산량이 급증하고 처리의 정확도도 오히려 떨어지는 현상.",
    definition:
      "영상 데이터와 같은 고차원 데이터에서 계산량이 급격히 증가하여 처리에 큰 비용이 들 뿐 아니라, 입력 차원이 늘어남에 따라 처리의 정확도도 저하되는 현상.",
    role: "선형변환에 의한 특징추출에서 차원 축소가 중요한 이유.",
    related: ["t-subspace-analysis", "t-feature-extraction", "t-overfitting"],
    lectures: [5],
    basis: "교재 7.1 선형변환에 의한 특징추출 · 강의록 5강 차원축소 관점에서의 특징추출",
    emphasis: "차원이 늘면 처음에는 성능이 오르지만 어느 시점부터는 오히려 떨어진다. 입력 차원이 무작정 큰 것이 좋은 것은 아니다.",
    aliases: ["curse of dimensionality", "차원 저주"],
  },
  {
    id: "t-subspace-analysis",
    term: "부분공간분석",
    en: "subspace analysis",
    category: "개념",
    short: "선형변환으로 저차원 특징 공간에 매핑하는, 차원 축소의 가장 대표적인 방법.",
    definition:
      "차원 축소의 가장 대표적인 방법으로, 선형변환에 의해 저차원 특징 공간으로 매핑하는 것. n차원 입력벡터 x는 n × m 크기의 변환행렬 W에 의해 m차원 특징벡터 y로 변환된다(n > m).",
    formula: [{ expr: "y = Wᵀx", note: "식 7-1" }],
    prereqs: ["pre-basis-vector", "pre-matrix-mult"],
    related: ["t-linear-transform", "t-transformation-matrix", "t-curse-of-dimensionality"],
    lectures: [5],
    basis: "교재 7.1 · 강의록 5강 차원축소 관점에서의 특징추출",
    aliases: ["subspace analysis", "부분 공간 분석"],
  },
  {
    id: "t-transformation-matrix",
    term: "변환행렬",
    en: "transformation matrix",
    category: "수식·지표",
    short: "n차원 입력을 m차원 특징으로 바꾸는 n × m 행렬 W. 각 열이 사영할 기저 벡터.",
    definition:
      "선형변환 y = Wᵀx에서 쓰는 n × m 행렬. 각 열 wᵢ는 입력 벡터를 사영시킬 기저 벡터이며, 사영으로 얻어지는 값들이 특징벡터 y를 이룬다. 어떤 변환행렬을 쓰느냐에 따라 얻어지는 특징의 분포 형태가 확연하게 달라진다.",
    formula: [
      { expr: "W = [w₁, w₂, …, w_m]", note: "n × m" },
      { expr: "W_a = [[1,0],[0,1],[0,0]], W_b = [[0,0],[1,0],[0,1]], W_c = [[1,0],[0,0],[0,1]]", note: "식 7-4 — 3차원 → 2차원의 서로 다른 기저" },
    ],
    role: "좋은 특징추출이란 변환행렬 W를 적절히 조정해 분석 목적에 맞는 특징 분포를 만드는 것.",
    related: ["t-linear-transform", "t-subspace-analysis", "t-projection", "t-principal-component"],
    lectures: [5],
    basis: "교재 7.1 식 7-2 ~ 7-4 · 강의록 5강 변환행렬에 따른 특징의 분포",
    aliases: ["W", "기저행렬", "transformation matrix"],
  },
  {
    id: "t-projection",
    term: "사영",
    en: "projection",
    category: "수식·지표",
    short: "x를 단위벡터 w 방향으로 수선을 내려 얻는 크기 y = wᵀx.",
    definition:
      "데이터 x에서 방향 벡터 w가 이루는 직선(또는 여러 기저가 이루는 부분공간)으로 수선을 내려 얻는 값. 특징값 yᵢ = wᵢᵀx는 x를 W의 열벡터 wᵢ 위로 사영한 값이며, 이때 wᵢ는 단위벡터다.",
    role: "선형변환에 의한 특징추출의 기본 연산. 변환행렬의 열 개수만큼 사영해 m차원 특징을 얻는다.",
    formula: [
      { expr: "yᵢ = wᵢᵀx", note: "‖wᵢ‖ = 1" },
      { expr: "y = wᵀx / ‖w‖", note: "w가 단위벡터가 아닐 때" },
    ],
    example: "x = [2, 2]ᵀ를 w = [1, 0]ᵀ로 사영하면 2, w = [2, 1]ᵀ/√5로 사영하면 (2·2 + 1·2)/√5 = 6/√5.",
    distinctions: [
      {
        from: "단순 내적",
        how: "w가 단위벡터가 아니면 wᵀx는 사영한 길이의 ‖w‖배가 된다. 사영한 크기를 얻으려면 ‖w‖로 나눠야 한다.",
      },
    ],
    prereqs: ["pre-dot-product", "pre-unit-vector"],
    related: ["t-linear-transform", "t-transformation-matrix", "t-pca", "t-lda"],
    lectures: [5],
    basis: "교재 7.1 [그림 7-1] · 강의록 5강 2차원 데이터 x를 1차원 특징값 y로의 변환",
    emphasis: "wᵢ가 단위벡터일 때 비로소 wᵢᵀx가 사영한 크기이며, 단위벡터가 아니면 그 크기로 나눠야 한다.",
    aliases: ["projection", "프로젝션", "정사영"],
  },

  /* ─────────── 주성분분석법 ─────────── */
  {
    id: "t-pca",
    term: "주성분분석법 (PCA)",
    en: "principal component analysis",
    category: "알고리즘",
    short: "차원 축소 후에도 원래 정보를 최대한 유지하도록, 분산이 가장 큰 방향으로 사영하는 방법.",
    definition:
      "변환 전의 데이터 X가 가지고 있는 정보를 차원 축소 후에도 최대한 유지하도록 하는 선형변환 특징추출 방법. 데이터 집합의 분산이 가장 큰 방향으로 선형변환하며, 그 방향은 공분산행렬의 고유벡터 중 고유치가 가장 큰 것으로 정해진다. 클래스 레이블 정보를 쓰지 않는 비지도학습이다.",
    role: "데이터 분석에 대한 특별한 목적이 없는 경우 가장 합리적·일반적인 차원 축소 방법.",
    formula: [
      { expr: "① μₓ = (1/N)Σxᵢ, Σₓ = (1/N)(X − Mₓ)(X − Mₓ)ᵀ" },
      { expr: "② Σₓ = UΛUᵀ  ③ 큰 고유치부터 m개  ④ W = [u₁, …, u_m]  ⑤ Y = WᵀX" },
    ],
    distinctions: [
      {
        from: "LDA",
        how: "PCA는 클래스 정보를 쓰지 않는 비지도학습으로 정보손실 최소화가 목적이고, LDA는 클래스 정보를 쓰는 지도학습으로 클래스 간 판별이 잘 되는 방향을 찾는다.",
      },
    ],
    prereqs: ["pre-covariance-matrix", "pre-eigen", "pre-variance", "pre-mean-vector"],
    related: ["t-principal-component", "t-eigenvalue-analysis", "t-information-loss", "t-info-ratio", "t-eigenface", "t-lda"],
    lectures: [5],
    basis: "교재 7.2 주성분분석법 · 강의록 5강 주성분분석",
    emphasis:
      "PCA는 분산이 가장 큰 방향을 고른다. '분산이 가장 작은 방향'이라는 선택지는 틀린 것이다. 또한 클래스 레이블을 쓰지 않아 분류의 핵심 정보를 잃을 수 있고, 비선형 구조를 반영하지 못한다.",
    aliases: ["PCA", "principal component analysis", "주성분분석", "주성분 분석"],
  },
  {
    id: "t-principal-component",
    term: "주성분 벡터",
    en: "principal component",
    category: "개념",
    short: "공분산행렬의 고유벡터. 고유치가 큰 순서대로 1차, 2차, … 주성분.",
    definition:
      "주성분분석에서 데이터를 사영할 방향으로 쓰는 공분산행렬의 고유벡터. 고유치가 가장 큰 것이 1차 주성분 벡터이며, 각 데이터를 주성분 벡터로 사영해 얻는 실수값이 주성분분석이 추출하는 특징값이다.",
    example: "3차원 데이터에서 1차 주성분만 쓰면 1차원 특징, 1·2차를 쓰면 두 벡터가 이루는 평면 위의 2차원 특징. 1·2·3차를 모두 쓰면 차원은 줄지 않고 각 요소 간 상관관계가 사라진 형태의 분포가 된다.",
    prereqs: ["pre-eigen"],
    related: ["t-pca", "t-eigenvalue-analysis", "t-transformation-matrix"],
    lectures: [5],
    basis: "교재 7.2.1 [그림 7-6] · 강의록 5강 PCA 적용의 예",
    emphasis: "주성분 벡터를 모두 쓰면 차원 축소 효과는 없고, 공분산이 대각 형태가 되는 대각화 변환이 된다.",
    aliases: ["주성분", "principal component", "PC1", "1차 주성분"],
  },
  {
    id: "t-eigenvalue-analysis",
    term: "고유치 분석",
    en: "eigenvalue decomposition",
    category: "수식·지표",
    short: "정방행렬을 고유벡터행렬 U와 고유치행렬 Λ로 분해하는 것. Σ = UΛUᵀ.",
    definition:
      "행렬을 고유치를 대각 성분으로 가지는 대각행렬인 고유치행렬 Λ와, 고유벡터를 열벡터로 가지는 고유벡터행렬 U로 분해하는 것. PCA는 공분산행렬 Σₓ, LDA는 S_W⁻¹S_B를 대상으로 수행한다.",
    formula: [
      { expr: "Σₓ = UΛUᵀ = [u₁, …, u_n] diag(λ₁, …, λ_n) [u₁, …, u_n]ᵀ", note: "PCA 수행 단계 ②" },
      { expr: "S_W⁻¹S_B = UΛUᵀ", note: "LDA 수행 단계 ②" },
    ],
    distinctions: [
      { from: "PCA와 LDA의 대상 행렬", how: "PCA는 공분산행렬, LDA는 S_W⁻¹S_B. ③단계 이후(큰 고유치부터 m개 → W 생성 → Y = WᵀX)는 같다." },
    ],
    prereqs: ["pre-eigen", "pre-diagonal"],
    related: ["t-pca", "t-lda", "t-principal-component"],
    lectures: [5],
    basis: "교재 7.2.1, 7.3.1 수행 단계 ② · 강의록 5강 PCA·LDA 알고리즘의 수행 단계",
    emphasis: "계산 결과가 고유치를 작은 것부터 내놓더라도 고유치의 크기로 고유벡터를 골라야 한다(강의록 예: 55.35와 202.39 중 202.39).",
    aliases: ["고유치분석", "eigenvalue decomposition", "고유값 분해", "UΛUᵀ"],
  },
  {
    id: "t-information-loss",
    term: "정보손실량",
    en: "information loss",
    category: "수식·지표",
    short: "원래 x와 m개 기저로 근사한 x̃의 차이를 모두 더한 값 = 버린 고유치의 합.",
    definition:
      "원래 입력 벡터 x와 m개의 기저벡터만으로 근사한 x̃의 차이가 손실되는 정보이며, 데이터 집합 전체에 대해 두 벡터 차의 크기를 모두 더해 정의한다. 공분산행렬의 고유치 분석으로 계산하면 선택하지 않은 고유치들의 합이 된다.",
    formula: [
      { expr: "J = (1/N)Σᵢ‖xᵢ − x̃ᵢ‖² = Σⱼ₌ₘ₊₁ⁿ uⱼᵀSuⱼ", note: "식 7-7" },
      { expr: "J = Σⱼ₌ₘ₊₁ⁿ λⱼ", note: "식 7-12" },
    ],
    example: "고유치가 6, 3, 0.8, 0.2일 때 m = 2이면 J = 0.8 + 0.2 = 1.0.",
    prereqs: ["pre-eigen", "pre-norm", "pre-sigma"],
    related: ["t-pca", "t-info-ratio", "t-eigenvalue-analysis"],
    lectures: [5],
    basis: "교재 7.2.2 주성분분석법의 수학적 유도",
    aliases: ["정보 손실량", "손실되는 정보량", "J"],
  },
  {
    id: "t-info-ratio",
    term: "표현 가능한 정보의 비율 r(n, m)",
    en: "ratio of retained information",
    category: "수식·지표",
    short: "m개의 특징으로 표현할 수 있는 정보의 비율. θ를 넘는 가장 작은 m을 고른다.",
    definition:
      "(식 7-12)의 정보손실량을 전체 고유치 합으로 나누면 손실되는 정보량의 비중을 알 수 있고, m개의 특징으로 표현 가능한 정보의 비율은 큰 고유치 m개의 합을 전체 고유치 합으로 나눈 값이다. 사용자가 정한 역치값 θ를 넘도록 m을 결정한다.",
    formula: [
      { expr: "r(n, m) = Σᵢ₌₁ᵐ λᵢ / Σᵢ₌₁ⁿ λᵢ", note: "식 7-13" },
      { expr: "Σᵢ₌₁ᵐ λᵢ / Σᵢ₌₁ⁿ λᵢ > θ", note: "예: θ = 0.98 → 손실 2% 이하" },
    ],
    example: "고유치 6, 3, 0.8, 0.2에서 θ = 0.9이면 r(4, 2) = 0.9는 θ를 넘지 못하므로 m = 3(r = 0.98).",
    related: ["t-information-loss", "t-pca"],
    lectures: [5],
    basis: "교재 7.2.2 식 7-13 · 강의록 5강 PCA의 수학적 유도 — 축소되는 차원 m을 선택하는 기준",
    emphasis: "미리 비율 θ를 정하는 방법 외에, 고유치를 늘어놓고 값이 급격히 변하는 지점에서 끊는 방법도 쓴다.",
    aliases: ["r(n,m)", "역치값", "θ", "누적 비율", "설명 비율"],
  },
  {
    id: "t-eigenface",
    term: "아이겐페이스",
    en: "Eigenface",
    category: "개념",
    short: "얼굴 영상에 PCA를 적용하여 찾아진 고유벡터를 영상으로 표현한 것.",
    definition:
      "n차원 얼굴 영상을 m개의 기저벡터로 표현할 때 W를 구성하는 좋은 기저벡터. 얼굴 영상에 PCA를 적용하여 찾아진 고유벡터를 영상으로 표현한 것이다.",
    formula: [
      { expr: "y = Wᵀx" },
      { expr: "x ≈ Wy = y₁w₁ + y₂w₂ + … + y_m w_m", note: "특징값을 계수로 아이겐페이스를 더해 복원" },
    ],
    example: "강의록 예에서는 69개의 아이겐페이스로 원 영상과 비슷한 복원 영상을 만든다.",
    related: ["t-pca", "t-principal-component"],
    lectures: [5],
    basis: "강의록 5강 [예] 얼굴 영상의 표현",
    aliases: ["Eigenface", "eigenface", "고유얼굴", "아이겐 페이스"],
  },

  /* ─────────── 선형판별분석법 ─────────── */
  {
    id: "t-lda",
    term: "선형판별분석법 (LDA)",
    en: "linear discriminant analysis",
    category: "알고리즘",
    short: "클래스 레이블을 활용해 클래스 간 판별이 잘 되는 방향으로 차원을 축소하는 방법.",
    definition:
      "주성분분석과 마찬가지로 선형변환에 의해 특징을 추출하되, 변환행렬 W를 최적화하는 목적함수를 정의하면서 클래스 정보를 적극적으로 활용하는 방법. 클래스 간의 거리는 멀어지게 하고 같은 클래스 내에서는 결집되게 하여 분류에 적합한 특징으로의 변환을 유도한다. 지도학습이다.",
    formula: [
      { expr: "w ∝ S_W⁻¹(m₁ − m₂)", note: "이진 분류, 식 7-18" },
      { expr: "S_W⁻¹S_B = UΛUᵀ, W = [u₁, …, u_m]", note: "다중 클래스" },
    ],
    distinctions: [
      { from: "PCA", how: "LDA는 클래스 정보를 쓰는 지도학습, PCA는 쓰지 않는 비지도학습. 고유치 분석 대상도 S_W⁻¹S_B와 공분산행렬로 다르다." },
    ],
    prereqs: ["pre-inverse", "pre-eigen", "pre-mean-vector"],
    related: ["t-fisher-objective", "t-between-scatter", "t-within-scatter", "t-lda-dimension-limit", "t-small-sample-problem", "t-pca", "t-supervised-learning"],
    lectures: [5],
    basis: "교재 7.3 선형판별분석법 · 강의록 5강 선형판별분석",
    emphasis: "클래스 레이블에 따라 데이터를 나누는 첫 단계가 곧 지도학습이라는 뜻이다. 선형변환의 한계, 고유벡터 개수 제한, 작은 표본 집합의 문제가 함께 나온다.",
    aliases: ["LDA", "linear discriminant analysis", "선형판별분석", "선형 판별 분석"],
  },
  {
    id: "t-fisher-objective",
    term: "LDA 목적함수 J(w)",
    en: "LDA objective function",
    category: "수식·지표",
    short: "사영한 클래스 평균 사이 거리를 클래스 내 흩어짐으로 나눈 값. 최대로 하는 w를 찾는다.",
    definition:
      "선형판별분석에서 클래스 간의 거리를 각 클래스의 평균을 이용해 측정하는 목적함수. 분자는 사영한 특징값들의 클래스 평균 사이 거리, 분모는 변환 후 클래스별 분산에 비례하는 값이다. J를 최대로 하는 w는 분자를 최대로, 분모를 최소로 하는 방향이다.",
    formula: [
      { expr: "J = (m₂ − m₁)² / (s₁² + s₂²)", note: "식 7-14" },
      { expr: "m_k = (1/|C_k|) Σ wᵀxᵢ = wᵀm_k,  s_k = Σ (wᵀxᵢ − m_k)²", note: "식 7-15, 7-16" },
      { expr: "J(w) = wᵀS_Bw / wᵀS_Ww", note: "식 7-17" },
      { expr: "J(W) = Trace{(WS_WWᵀ)⁻¹(WS_BWᵀ)}", note: "다중 클래스, 식 7-19" },
    ],
    role: "S_W를 고려하지 않으면 w는 두 평균의 차 벡터에 비례하는 방향이 된다.",
    prereqs: ["pre-quadratic-form", "pre-trace"],
    related: ["t-lda", "t-between-scatter", "t-within-scatter"],
    lectures: [5],
    basis: "교재 7.3.1 식 7-14 ~ 7-19 · 강의록 5강 LDA: 이진 분류, LDA: 다중 클래스 분류",
    emphasis: "s_k에는 1/N이 없어 엄밀히 분산은 아니고 클래스별 분산에 비례하는 값이다.",
    aliases: ["J(w)", "피셔 기준", "클래스 간 거리에 대한 목적함수"],
  },
  {
    id: "t-scatter-matrix",
    term: "산점행렬",
    en: "scatter matrix",
    category: "수식·지표",
    short: "데이터가 흩어진 정도를 Σ(x − m)(x − m)ᵀ 꼴로 모은 행렬. LDA의 S_B와 S_W.",
    definition:
      "데이터가 평균 주변에 흩어진 정도를 (x − m)(x − m)ᵀ를 더해 나타낸 행렬. 공분산과 달리 데이터 수로 나누지 않는다. 선형판별분석에서 클래스 간 산점행렬 S_B와 클래스 내 산점행렬 S_W로 쓰인다.",
    formula: [{ expr: "S_k = Σ_{xᵢ∈C_k} (xᵢ − m_k)(xᵢ − m_k)ᵀ" }],
    prereqs: ["pre-covariance-matrix", "pre-mean-vector"],
    related: ["t-between-scatter", "t-within-scatter", "t-lda"],
    lectures: [5],
    basis: "교재 7.3.1 식 7-17, 7-20",
    aliases: ["scatter matrix", "산점 행렬"],
  },
  {
    id: "t-between-scatter",
    term: "클래스 간 산점행렬 S_B",
    en: "between-scatter matrix",
    category: "수식·지표",
    short: "클래스 평균들이 서로 흩어진 정도. LDA 목적함수의 분자.",
    definition:
      "두 클래스 간의 흩어진 정도를 나타내는 행렬. 다중 클래스에서는 각 클래스 평균과 전체 평균의 차이에 클래스의 데이터 수 N_k를 곱해 더한다. 클래스 개수만큼의 평균 벡터로 정의되므로 랭크가 M − 1로 한정된다.",
    formula: [
      { expr: "S_B = (m₁ − m₂)(m₁ − m₂)ᵀ", note: "이진 분류" },
      { expr: "S_B = Σₖ₌₁ᴹ N_k (m_k − m)(m_k − m)ᵀ", note: "다중 클래스, m은 전체 평균" },
    ],
    prereqs: ["pre-rank"],
    related: ["t-within-scatter", "t-scatter-matrix", "t-fisher-objective", "t-lda-dimension-limit"],
    lectures: [5],
    basis: "교재 7.3.1 식 7-17, 7-20 · 강의록 5강 LDA: 이진 분류",
    aliases: ["between-scatter matrix", "S_B", "SB", "클래스간 산점행렬"],
  },
  {
    id: "t-within-scatter",
    term: "클래스 내 산점행렬 S_W",
    en: "within-scatter matrix",
    category: "수식·지표",
    short: "각 클래스 안에서 데이터가 흩어진 정도를 모두 합한 것. LDA 목적함수의 분모.",
    definition:
      "각 클래스 내에서 데이터가 흩어진 정도를 계산하여 모두 합한 행렬. LDA의 고유치 분석을 위해 역행렬 S_W⁻¹을 계산해야 한다.",
    formula: [{ expr: "S_W = Σₖ₌₁ᴹ S_k = Σₖ₌₁ᴹ Σ_{xᵢ∈C_k} (xᵢ − m_k)(xᵢ − m_k)ᵀ", note: "식 7-20" }],
    distinctions: [
      { from: "S_B", how: "역행렬이 필요한 것은 S_W다. 작은 표본 집합의 문제에서 역행렬이 없어지는 것도 S_W다." },
    ],
    prereqs: ["pre-inverse"],
    related: ["t-between-scatter", "t-scatter-matrix", "t-small-sample-problem", "t-fisher-objective"],
    lectures: [5],
    basis: "교재 7.3.1 식 7-17, 7-20 · 강의록 5강 LDA: 이진 분류",
    aliases: ["within-scatter matrix", "S_W", "SW", "클래스내 산점행렬"],
  },
  {
    id: "t-lda-dimension-limit",
    term: "LDA 특징 차원의 제한 (M − 1)",
    en: "LDA dimension limit",
    category: "개념",
    short: "클래스가 M개면 LDA로 얻는 특징벡터는 최대 (M − 1)차원.",
    definition:
      "클래스 간 산점행렬 S_B의 랭크가 M − 1이므로 S_W⁻¹S_B의 랭크도 최대 M − 1이 되어, 고유치가 0이 아닌 고유벡터는 최대 M − 1개만 찾을 수 있다. 따라서 LDA로 찾는 특징벡터는 그 차원이 최대 M − 1로 제한된다.",
    example: "이진 분류(M = 2)는 하나의 특징값만 얻으며, 특징값의 범위로 클래스가 정해지므로 특징추출이 판별함수 계산과 같아진다 — '선형판별분석법'이라는 이름의 유래.",
    prereqs: ["pre-rank", "pre-eigen"],
    related: ["t-lda", "t-between-scatter", "t-decision-function"],
    lectures: [5],
    basis: "교재 7.3.2 · 강의록 5강 LDA의 특성과 문제점 — 선택하는 고유벡터의 개수 m의 결정",
    emphasis: "입력 차원과 무관하게 클래스 개수가 상한을 정한다. 이진 분류면 특징은 값 하나다.",
    aliases: ["M-1", "M − 1차원", "고유벡터 개수 제한"],
  },
  {
    id: "t-small-sample-problem",
    term: "작은 표본 집합의 문제",
    en: "small sample set problem",
    category: "개념",
    short: "데이터 수가 입력 차원보다 크지 않아 S_W의 역행렬을 구할 수 없는 문제.",
    definition:
      "고유치 분석을 위해 클래스 내 산점행렬 S_W의 역행렬을 계산해야 하는데, 데이터의 수가 입력 차원보다 크지 않으면 S_W가 특이행렬이 되어 역행렬을 찾을 수 없는 문제. 영상 데이터처럼 입력 차원이 큰 데이터에서 자주 발생한다.",
    role: "실제 응용에서는 PCA로 먼저 차원을 축소한 특징을 얻고, 그 특징 데이터에 대해 LDA를 수행한다.",
    example: "150 × 100 영상은 15,000차원인데 학습 영상이 5,000장뿐이면 S_W의 역행렬이 존재하지 않는다.",
    prereqs: ["pre-inverse"],
    related: ["t-within-scatter", "t-lda", "t-pca"],
    lectures: [5],
    basis: "교재 7.3.2 · 강의록 5강 LDA의 특성과 문제점 — 작은 표본집합의 문제",
    aliases: ["small sample set problem", "small sample size problem", "작은 표본집합 문제", "SSS"],
  },

  /* ─────────── 거리 기반 차원 축소 ─────────── */
  {
    id: "t-distance-based-reduction",
    term: "거리 기반 차원 축소 방법",
    en: "distance-based dimensionality reduction",
    category: "개념",
    short: "원래 데이터 간의 거리가 저차원 특징 사이에서도 최대한 유지되도록 차원을 축소하는 방법.",
    definition:
      "두 데이터 간의 거리(또는 유사도)를 핵심 정보로 사용하여 차원을 축소하는 방법. 원래 데이터 x와 특징 y 사이의 매핑 함수를 명백하게 정의하지 않고, 저차원 특징값 {y₁, …, y_N}에 대한 목적함수를 정의해 이를 최적화하는 값을 찾는다.",
    formula: [
      { expr: "dᵢⱼ = dist(xᵢ, xⱼ), δᵢⱼ = dist(yᵢ, yⱼ)", note: "식 7-21, 7-22" },
      { expr: "Σ(dᵢⱼ − δᵢⱼ)² 최소화" },
    ],
    role: "새 데이터에 대응하는 특징을 찾는 방법을 주지 않으므로, 주로 현재 데이터의 분포를 이해하는 데이터 시각화에 쓴다.",
    distinctions: [
      { from: "PCA·LDA", how: "선형변환 방법은 변환행렬 W라는 매핑 함수를 얻어 새 데이터에도 적용하지만, 거리 기반 방법은 학습 데이터의 특징값만 얻는다." },
    ],
    related: ["t-mds", "t-tsne", "t-isomap", "t-distance-matrix", "t-data-visualization"],
    lectures: [5],
    basis: "교재 7.4 거리 기반 차원 축소 방법 · 강의록 5강 거리 기반 차원 축소 방법",
    emphasis: "매핑 함수가 없어 새로운 데이터의 특징값을 얻을 수 없다는 점이 일반적인 특징추출과의 가장 큰 차이다.",
    aliases: ["거리 기반 차원 축소", "distance-based reduction"],
  },
  {
    id: "t-distance-matrix",
    term: "거리행렬",
    en: "distance matrix",
    category: "수식·지표",
    short: "모든 데이터 쌍의 거리를 모은 행렬. 원래 데이터는 D, 특징은 Δ.",
    definition:
      "데이터 쌍 사이의 거리를 (i, j) 원소로 가지는 행렬. 원래 데이터의 거리행렬 D = {dᵢⱼ}와 특징 벡터의 거리행렬 Δ = {δᵢⱼ}가 최대한 가까워지도록 하는 것이 MDS의 목적이다. 원래 데이터의 거리는 유클리디안 거리 외에 이동 비용 같은 값으로 주어질 수도 있다.",
    example: "서울·대구·대전·광주·원주·부산 6개 도시 간의 이동에 드는 비용을 6 × 6 거리행렬 D로 나타낸 것.",
    prereqs: ["pre-euclidean"],
    related: ["t-mds", "t-distance-based-reduction", "t-distance-function"],
    lectures: [5],
    basis: "교재 7.4.1 [그림 7-10] · 강의록 5강 다차원 척도법",
    aliases: ["distance matrix", "D", "Δ"],
  },
  {
    id: "t-mds",
    term: "다차원 척도법 (MDS)",
    en: "multi-dimensional scaling",
    category: "알고리즘",
    short: "거리행렬 D와 특징의 유클리디안 거리행렬 Δ가 최대한 가까워지는 저차원 좌표를 찾는 방법.",
    definition:
      "주어진 데이터에 맞게 적절한 값으로 정의된 거리행렬 D가 주어졌을 때, 특징벡터로부터 계산되는 유클리디안 거리행렬 Δ가 최대한 가까워지도록 하는 방법. 행렬 D에 대한 분석을 통해 Σ(dᵢⱼ − δᵢⱼ)²를 최소화하는 특징 {y₁, …, y_N}을 찾으며, 얻은 특징값은 원래 데이터의 거리 관계를 유클리디안 좌표 평면상의 거리로 나타낸다.",
    formula: [{ expr: "Σᵢ,ⱼ (dᵢⱼ − δᵢⱼ)² 최소화" }],
    example: "6개 도시의 이동 비용표에 MDS를 적용하면 비용이 작은 도시(대구–부산 110)는 가깝게, 큰 도시(서울–부산 480)는 멀게 2차원 평면에 놓인다.",
    distinctions: [
      { from: "t-SNE, Isomap", how: "세 방법은 거리 함수의 정의가 다르다. MDS는 유클리디안 거리, t-SNE는 확률밀도함수로 정의한 유사도, Isomap은 측지 거리." },
    ],
    prereqs: ["pre-euclidean"],
    related: ["t-distance-matrix", "t-distance-based-reduction", "t-tsne", "t-isomap", "t-data-visualization"],
    lectures: [5],
    basis: "교재 7.4.1 다차원 척도법 · 강의록 5강 다차원 척도법",
    emphasis: "입력 좌표값이 따로 주어지지 않고 데이터 간 거리 함수만 주어진 경우에도 적용할 수 있다.",
    aliases: ["MDS", "multi-dimensional scaling", "multidimensional scaling", "다차원척도법"],
  },
  {
    id: "t-stochastic-neighbor-embedding",
    term: "통계적 이웃 임베딩 (SNE)",
    en: "stochastic neighbor embedding",
    category: "알고리즘",
    short: "데이터 간·특징 간 거리를 조건부확률로 정의한 유사도로 바꿔 차원을 축소하는 방법.",
    definition:
      "데이터 간의 거리와 특징 간의 거리를 조건부확률을 이용하여 정의하는 거리 기반 차원 축소 방법. 데이터가 가우시안 분포를 따른다는 가정하에 두 데이터의 유사도를 확률값 p_{j|i}로, 특징벡터의 유사도는 분산이 1인 정규분포를 가정해 q_{j|i}로 정의한다.",
    formula: [
      { expr: "p_{j|i} = exp(−‖xᵢ − xⱼ‖²/2σᵢ²) / Σ_{k≠i} exp(−‖xᵢ − x_k‖²/2σᵢ²)", note: "식 7-23" },
      { expr: "q_{j|i} = exp(−‖yᵢ − yⱼ‖²) / Σ_{k≠i} exp(−‖yᵢ − y_k‖²)", note: "식 7-24" },
    ],
    prereqs: ["pre-conditional-prob", "pre-gaussian", "pre-exp-log"],
    related: ["t-tsne", "t-kl-divergence", "t-distance-based-reduction"],
    lectures: [5],
    basis: "교재 7.4.2 다양한 거리 기반 축소 방법",
    aliases: ["SNE", "stochastic neighbor embedding", "통계적 이웃 임베딩"],
  },
  {
    id: "t-tsne",
    term: "t-SNE",
    en: "t-stochastic neighbor embedding",
    category: "알고리즘",
    short: "특징 쪽 유사도에 t-분포를 쓰는 SNE의 변형. 데이터 시각화에 주로 쓰임.",
    definition:
      "기본 SNE의 변형으로, 특징 데이터의 유사도 δᵢⱼ를 정의할 때 정규분포 대신 t-분포를 사용하는 방법. 입력 데이터는 가우시안 분포를 가정한다. 랜덤한 특징값에서 시작해 두 확률분포의 KL-divergence로 정의되는 목적함수를 최소화하도록 특징값을 반복적으로 업데이트하며, 얻어진 특징값은 원래 데이터가 가지는 확률적 유사도를 잘 표현한다.",
    formula: [{ expr: "q_{j|i} = (1 + ‖yᵢ − yⱼ‖²)⁻¹ / Σ_{k≠i}(1 + ‖yᵢ − y_k‖²)⁻¹", note: "식 7-25" }],
    role: "t-분포를 씀으로써 거리가 멀리 떨어진 데이터 사이의 관계를 더 잘 반영하도록 개선됨.",
    example: "28 × 28(784차원) 손글씨 숫자 영상을 t-SNE로 2차원에 나타내면 같은 숫자끼리 가깝게 뭉친다.",
    distinctions: [
      { from: "PCA·LDA", how: "매핑 함수가 없어 새 데이터의 특징은 구할 수 없고, 현재 데이터를 시각화하는 용도로 주로 쓴다." },
    ],
    prereqs: ["pre-conditional-prob", "pre-gaussian"],
    related: ["t-stochastic-neighbor-embedding", "t-kl-divergence", "t-data-visualization", "t-mds", "t-isomap"],
    lectures: [5],
    basis: "교재 7.4.2 식 7-25, 7.4.3 · 강의록 5강 t-SNE, 거리 기반 차원 축소 방법의 특징",
    emphasis: "특징추출 방법 중 데이터 시각화에 주로 사용되는 것을 고르라면 t-SNE다.",
    aliases: ["t-SNE", "tSNE", "TSNE", "t-stochastic neighbor embedding"],
  },
  {
    id: "t-kl-divergence",
    term: "KL-divergence",
    en: "Kullback–Leibler divergence",
    category: "수식·지표",
    short: "두 확률분포가 얼마나 다른지 재는 값. t-SNE의 목적함수.",
    definition:
      "두 확률분포 사이의 차이를 나타내는 값. t-SNE는 입력 쪽 확률분포 p_{j|i}와 특징 쪽 확률분포 q_{j|i}의 KL-divergence로 목적함수를 정의하고, 이를 최소화하도록 특징값을 반복 업데이트해 두 분포를 서로 가깝게 만든다.",
    formula: [{ expr: "Σᵢ Σⱼ p_{j|i} log(p_{j|i} / q_{j|i})" }],
    prereqs: ["pre-exp-log"],
    related: ["t-tsne", "t-stochastic-neighbor-embedding"],
    lectures: [5],
    basis: "교재 7.4.2 다양한 거리 기반 축소 방법",
    aliases: ["KL divergence", "쿨백-라이블러 발산", "KL"],
  },
  {
    id: "t-isomap",
    term: "Isomap",
    en: "isometric mapping",
    category: "알고리즘",
    short: "데이터가 이루는 다양체 위의 측지 거리를 사용하는 차원 축소 방법.",
    definition:
      "기하학적 다양체상에서의 측지 거리를 사용하는 차원 축소 방법. 데이터들을 정점으로 가지는 그래프의 경로로 측지 거리를 구하며, 이 거리는 다익스트라(데이크스트라) 알고리즘으로 계산한다. 전체 데이터에 대한 거리행렬이 얻어지면 MDS와 같은 방법으로 저차원 특징값을 찾는다.",
    example: "롤 형태로 휘어진 2차원 곡면 위의 3차원 데이터에서, 두 점 사이를 직선이 아니라 곡면을 따라 잰 거리를 쓰면 데이터 구조를 더 잘 반영한다.",
    prereqs: ["pre-euclidean"],
    related: ["t-geodesic-distance", "t-manifold", "t-mds", "t-distance-based-reduction"],
    lectures: [5],
    basis: "교재 7.4.2 [그림 7-11] · 강의록 5강 Isomap",
    aliases: ["Isomap", "ISOMAP", "아이소맵"],
  },
  {
    id: "t-geodesic-distance",
    term: "측지 거리",
    en: "geodesic distance",
    category: "수식·지표",
    short: "데이터가 이루는 곡면(다양체)을 따라 잰 거리.",
    definition:
      "데이터가 이루는 복잡한 비선형 다양체의 기하학적 구조를 반영한 거리. 공간을 가로지르는 유클리디안 거리와 달리 데이터가 실제로 존재하는 곡면을 따라 측정한다. Isomap에서는 데이터를 정점으로 하는 그래프 경로로 근사하며, 그 경로 길이가 실제 측지 거리와 거의 유사하다.",
    distinctions: [
      { from: "유클리디안 거리", how: "휘어진 곡면의 서로 다른 부분에 있는 두 점은 유클리디안 거리로는 가깝지만 측지 거리로는 멀 수 있다." },
    ],
    prereqs: ["pre-euclidean"],
    related: ["t-isomap", "t-manifold"],
    lectures: [5],
    basis: "교재 7.4.2 [그림 7-11] · 강의록 5강 Isomap",
    aliases: ["geodesic distance", "측지거리"],
  },
  {
    id: "t-manifold",
    term: "다양체 (매니폴드)",
    en: "manifold",
    category: "개념",
    short: "고차원 공간에서 데이터 집합이 실제로 놓여 있는 저차원의 휘어진 구조.",
    definition:
      "고차원 공간상에서 주어진 데이터 집합이 이루는 저차원의 구조. 예를 들어 3차원 데이터가 공간 전체가 아니라 롤 형태로 휘어진 2차원 곡면 위에만 존재할 때 그 곡면이 다양체다.",
    role: "다양체 구조를 반영한 거리를 쓰면 데이터 구조를 더 잘 반영할 수 있다. PCA·LDA의 비선형 한계를 해결하는 방법으로 비선형 매니폴드 학습법이 제시된다.",
    related: ["t-isomap", "t-geodesic-distance", "t-pca"],
    lectures: [5],
    basis: "교재 7.4.2 · 7.2.3, 7.3.2 해결 방안 · 강의록 5강 LDA의 특성과 문제점",
    aliases: ["manifold", "매니폴드", "비선형 매니폴드 학습법"],
  },
  {
    id: "t-data-visualization",
    term: "데이터 시각화",
    en: "data visualization",
    category: "개념",
    short: "고차원 데이터를 2·3차원으로 줄여 데이터가 어떻게 분포하는지 보여 주는 것.",
    definition:
      "MDS나 t-SNE 등으로 고차원 데이터를 2차원 또는 3차원으로 축소함으로써 주어진 데이터들이 어떻게 분포하고 있는지를 보여 주는 것. 각 데이터의 구체적인 값보다 데이터 간의 상호 관계(유사도나 거리)가 더 중요한 의미를 가지므로 거리 기반 차원 축소가 유용하다.",
    distinctions: [
      { from: "군집화", how: "데이터 시각화에 주로 쓰이는 것은 특징추출 방법인 t-SNE다. 시각화를 군집화의 응용으로 드는 것은 적합하지 않다." },
    ],
    related: ["t-tsne", "t-mds", "t-distance-based-reduction", "t-clustering"],
    lectures: [5],
    basis: "교재 7.4.3 [그림 7-12] · 강의록 5강 거리 기반 차원 축소 방법의 특징 — 용도",
    aliases: ["data visualization", "시각화"],
  },
];
