import type { GlossaryTerm } from "@/lib/mlGlossaryTypes";

/**
 * 8강 SVM과 커널법(교재 10장)에서 다루는 용어.
 *
 * 정의는 교재·강의록 표현을 보존하되 한 문장으로 읽히게 다듬었다.
 */
export const lecture8Terms: GlossaryTerm[] = [
  /* ─────────── 선형 분류기 ─────────── */
  {
    id: "t-svm",
    term: "서포트 벡터 머신",
    en: "Support Vector Machine, SVM",
    category: "알고리즘",
    short: "일반화 오차를 최소화할 수 있는 방향으로 학습이 이루어지도록 설계된 선형 분류기.",
    definition:
      "일반화 오차를 최소화할 수 있는 방향으로 학습이 이루어지도록 설계된 선형 분류기. 여러 선형 결정경계 중 마진을 최대로 하는 결정경계를 찾으므로 최대 마진 분류기라고도 한다. 기본적으로 이진 분류기이며, 커널법을 적용해 복잡한 결정경계를 가진 문제로 확장된다.",
    role: "선형 분류기의 장점(과다적합 회피)을 취해 논의를 시작하고, 슬랙변수와 커널법으로 선형 분리가 불가능한 문제까지 다룬다.",
    formula: [
      { expr: "g(x) = wᵀx + w₀", note: "선형 판별함수" },
      { expr: "f(x) = sign(Σ α̂ᵢyᵢ k(xᵢ, x) + ŵ₀)", note: "서포트 벡터만으로 계산하는 분류 함수" },
    ],
    distinctions: [
      {
        from: "신경망",
        how: "SVM은 라그랑주 승수와 이차계획법으로 이원적 문제 Q(α)를 풀어 학습하고, 오류 역전파는 신경망의 학습 방법이다.",
      },
    ],
    prereqs: ["pre-hyperplane", "pre-dot-product", "pre-lagrange"],
    related: [
      "t-linear-classifier",
      "t-max-margin-classifier",
      "t-margin",
      "t-support-vector",
      "t-dual-problem",
      "t-kernel-method",
      "t-slack-variable",
    ],
    lectures: [8],
    basis: "교재 10.1.2, 10.2.1 · 강의록 선형 초평면 분류기, SVM",
    emphasis:
      "SVM은 목표 출력값 1과 −1이 주어지는 이진 분류, 곧 지도학습이다. 다중 클래스는 1대 나머지 또는 1대 1 방법으로 확장한다.",
    aliases: ["SVM", "서포트벡터머신", "support vector machine"],
  },
  {
    id: "t-linear-classifier",
    term: "선형 분류기",
    en: "linear classifier",
    category: "개념",
    short: "선형 판별함수를 기반으로 분류를 수행하는 분류기(학습 시스템).",
    definition:
      "선형 판별함수를 기반으로 분류를 수행하는 분류기. 학습 시스템의 분류 복잡도가 가장 낮아 표현할 수 있는 결정경계에 제약이 많고 분류 성능 측면에서 좋은 결과를 기대하기 힘드나, 과다적합의 문제를 피할 수 있다.",
    role: "SVM이 학습 시스템의 설계를 시작하는 기본 단계.",
    distinctions: [
      {
        from: "비선형 분류기",
        how: "비선형 분류기는 복잡도가 높아 학습 데이터를 완벽히 분류할 수 있지만, 학습 데이터가 전체 분포를 대표하지 못하면 더 큰 일반화 오차를 가질 수 있다.",
      },
    ],
    prereqs: ["pre-hyperplane"],
    related: ["t-linear-discriminant", "t-svm", "t-model-complexity", "t-overfitting"],
    lectures: [8],
    basis: "교재 10.1.2 선형 초평면 분류기 · 강의록 선형 초평면 분류기",
    emphasis: "복잡도가 가장 낮아 성능은 좋지 못하지만 과다적합을 피할 수 있다는 장단점을 짝으로 기억.",
    aliases: ["선형분류기", "linear classifier"],
  },
  {
    id: "t-linear-discriminant",
    term: "선형 초평면 판별함수",
    en: "linear hyperplane discriminant function",
    category: "수식·지표",
    short: "g(x) = wᵀx + w₀. 입력의 1차식으로 된 판별함수.",
    definition:
      "입력 x에 대해 g(x) = w·x + w₀ = wᵀx + w₀ = Σwᵢxᵢ + w₀로 정의되는 선형 판별함수. 결정규칙 f(x) = sign(g(x))로 분류하며, f(x) = 1이면 C₁, −1이면 C₂에 할당한다.",
    formula: [
      { expr: "g(x) = wᵀx + w₀ = Σᵢ wᵢxᵢ + w₀", note: "식 10-1" },
      { expr: "f(x) = sign(g(x))", note: "식 10-2" },
    ],
    example: "2차원이면 g(x) = w₁x₁ + w₂x₂ + w₀ = 0이 직선의 방정식, 3차원이면 평면.",
    prereqs: ["pre-dot-product", "pre-transpose", "pre-sign-function"],
    related: ["t-linear-classifier", "t-hyperplane", "t-normal-vector", "t-decision-boundary"],
    lectures: [8],
    basis: "교재 10.1.2 (식 10-1, 10-2) · 강의록 선형 초평면 분류기",
    aliases: ["선형 판별함수", "linear discriminant"],
  },
  {
    id: "t-hyperplane",
    term: "초평면",
    en: "hyperplane",
    category: "개념",
    short: "n차원 공간을 둘로 나누는 평평한 경계. 2차원은 직선, 3차원은 평면.",
    definition:
      "3차원 이상의 공간으로 평면을 일반화한 것. SVM에서는 선형 판별함수 g(x) = wᵀx + w₀ = 0이 결정경계인 초평면이 되며, w는 초평면의 법선 벡터, w₀는 원점에서 초평면까지의 거리를 결정하는 값이다.",
    prereqs: ["pre-hyperplane"],
    related: ["t-normal-vector", "t-plus-plane", "t-minus-plane", "t-linear-discriminant"],
    lectures: [8],
    basis: "교재 10.2.1 (식 10-3) · 강의록 최대 마진 분류기",
  },
  {
    id: "t-normal-vector",
    term: "법선 벡터",
    en: "normal vector",
    category: "개념",
    short: "초평면에 수직인 벡터. g(x) = wᵀx + w₀ = 0에서 w.",
    definition:
      "초평면에 수직인 벡터. 판별함수 g(x) = wᵀx + w₀ = 0에서 w가 초평면의 법선 벡터가 된다. 한 점에서 결정경계까지의 거리는 x를 w 방향으로 사영한 길이에서 계산된다.",
    formula: [{ expr: "d = (wᵀx + w₀) / ‖w‖", note: "한 점 x에서 결정경계까지의 거리 (식 10-4)" }],
    prereqs: ["pre-point-plane-distance", "pre-norm"],
    related: ["t-hyperplane", "t-margin"],
    lectures: [8],
    basis: "교재 10.2.1 (그림 10-4) · 강의록 최대 마진 분류기",
    aliases: ["법선벡터", "w"],
  },

  /* ─────────── SVM 분류기 ─────────── */
  {
    id: "t-margin",
    term: "마진",
    en: "margin",
    category: "개념",
    short: "학습 데이터 중에서 결정경계에 가장 가까운 데이터로부터 결정경계까지의 거리.",
    definition:
      "학습 데이터 중에서 결정경계에 가장 가까운 데이터로부터 결정경계까지의 거리. 결정경계에 따라 달라진다. 플러스 평면 위의 서포트 벡터 χ⁺와 마이너스 평면 위의 서포트 벡터 χ⁻에서 결정경계까지의 거리를 합한 마진 M은 2/‖w‖이다.",
    role: "SVM이 여러 선형 결정경계 가운데 일반화 오차가 작은 것을 고르는 기준. 마진을 최대로 하는 결정경계를 찾는다.",
    formula: [
      { expr: "M = (1/‖w‖)((wᵀχ⁺ + w₀) − (wᵀχ⁻ + w₀)) = 2/‖w‖", note: "식 10-6" },
    ],
    example: "ŵ = (−0.5, 0.5)이면 ‖ŵ‖ = √0.5 ≈ 0.707, 마진 M = 2/0.707 ≈ 2.83.",
    distinctions: [
      {
        from: "서포트 벡터",
        how: "서포트 벡터는 결정경계에 가장 가까운 데이터이고, 마진은 그 데이터에서 결정경계까지의 거리다.",
      },
    ],
    prereqs: ["pre-point-plane-distance", "pre-norm"],
    related: ["t-support-vector", "t-max-margin-classifier", "t-plus-plane", "t-minus-plane"],
    lectures: [8],
    basis: "교재 10.2.1 최대 마진 분류기 · 강의록 SVM, 마진 계산",
    emphasis: "마진의 최대화는 ‖w‖의 최소화와 같다. SVM은 마진을 최소화하지 않는다.",
    aliases: ["margin", "마진 M"],
  },
  {
    id: "t-support-vector",
    term: "서포트 벡터",
    en: "support vector",
    category: "개념",
    short: "결정경계에 가장 가까운 곳에 있는 학습 데이터.",
    definition:
      "결정경계에 가장 가까운 곳에 있는 데이터. 마진을 결정하며, 학습 후에는 yᵢ(wᵀxᵢ + w₀) − 1 = 0을 만족해 라그랑주 승수 α̂ᵢ가 0이 아닌 값을 가지는 데이터로 나타난다. 이들의 집합을 Xₛ = {xᵢ ∈ X | α̂ᵢ ≠ 0}로 쓴다.",
    role: "분류할 때 서포트 벡터와 그 α̂ᵢ만 저장하면 되므로 저장할 데이터 수와 계산량이 현격히 준다.",
    formula: [{ expr: "Xₛ = {xᵢ ∈ X | α̂ᵢ ≠ 0}", note: "Nₛ는 Xₛ의 원소의 수" }],
    example: "교재 그림 10-5에서는 서포트 벡터가 3개로, 오직 세 개의 α̂ᵢ만 의미 있는 값을 가진다.",
    prereqs: ["pre-point-plane-distance"],
    related: ["t-margin", "t-lagrange-multiplier", "t-svm-decision-function", "t-plus-plane"],
    lectures: [8],
    basis: "교재 10.2.1, 10.2.2 · 강의록 SVM, SVM의 학습",
    emphasis: "결정경계와 떨어져 있는 대부분의 데이터는 α̂ᵢ = 0이 되어 사라지고, 서포트 벡터만 남는다.",
    aliases: ["서포트벡터", "support vector", "SV"],
  },
  {
    id: "t-max-margin-classifier",
    term: "최대 마진 분류기",
    en: "maximum margin classifier",
    category: "알고리즘",
    short: "마진을 최대로 하는 선형 결정경계를 찾도록 최적화된 분류기. 곧 SVM.",
    definition:
      "일반화 오차를 작게 하려면 두 클래스 간의 간격을 최대로 하는 것이 좋으므로, 마진을 최대로 하는 결정경계를 찾는 목적에 맞추어 최적화된 선형 결정경계를 찾는 분류기. 일반적으로 서포트 벡터 머신으로 알려져 있다.",
    prereqs: ["pre-hyperplane"],
    related: ["t-svm", "t-margin"],
    lectures: [8],
    basis: "교재 10.2.1 최대 마진 분류기 · 강의록 SVM",
    emphasis: "일반화 오차를 작게 → 클래스 간 간격을 최대로 → 마진을 최대로.",
    aliases: ["maximum margin classifier"],
  },
  {
    id: "t-plus-plane",
    term: "플러스 평면",
    en: "plus plane",
    category: "개념",
    short: "클래스 C₁의 서포트 벡터를 지나는 초평면 wᵀx + w₀ = +1.",
    definition:
      "서포트 벡터 χ에 대해 w와 w₀의 비율을 적절히 조절해 wᵀχ + w₀ = +1이 되게 했을 때, 클래스 C₁의 서포트 벡터를 지나는 초평면. C₁의 모든 데이터는 이 평면보다 위쪽, 곧 wᵀx + w₀ ≥ 1인 곳에 있다.",
    formula: [{ expr: "wᵀx + w₀ = +1" }],
    related: ["t-minus-plane", "t-support-vector", "t-margin"],
    lectures: [8],
    basis: "교재 10.2.1 (식 10-5, 그림 10-5) · 강의록 최대 마진 분류기",
    aliases: ["plus plane"],
  },
  {
    id: "t-minus-plane",
    term: "마이너스 평면",
    en: "minus plane",
    category: "개념",
    short: "클래스 C₂의 서포트 벡터를 지나는 초평면 wᵀx + w₀ = −1.",
    definition:
      "클래스 C₂의 서포트 벡터를 지나는 초평면 wᵀx + w₀ = −1. C₂의 모든 데이터는 wᵀx + w₀ ≤ −1을 만족한다. 플러스 평면과 마이너스 평면 사이의 간격이 마진 M = 2/‖w‖이다.",
    formula: [{ expr: "wᵀx + w₀ = −1" }],
    related: ["t-plus-plane", "t-support-vector", "t-margin"],
    lectures: [8],
    basis: "교재 10.2.1 (식 10-5, 그림 10-5) · 강의록 최대 마진 분류기",
    aliases: ["minus plane"],
  },
  {
    id: "t-lagrange-multiplier",
    term: "라그랑주 승수",
    en: "Lagrange multiplier",
    category: "수식·지표",
    short: "목적함수와 조건을 하나의 함수식으로 묶기 위해 도입하는 변수 αᵢ ≥ 0.",
    definition:
      "하나의 함수식 J(w)를 최소화하는 동시에 조건 yᵢ(wᵀxᵢ + w₀) − 1 ≥ 0을 만족시키는 파라미터를 찾기 위해 도입하는 변수 αᵢ ≥ 0 (i = 1, …, N). 학습 데이터마다 하나씩 있으며, 추정치 α̂ᵢ는 서포트 벡터에서만 0이 아니다.",
    formula: [{ expr: "αᵢ ≥ 0 (i = 1, …, N)", note: "슬랙변수를 가진 SVM에서는 0 ≤ αᵢ ≤ c" }],
    prereqs: ["pre-lagrange"],
    related: ["t-lagrangian-function", "t-dual-problem", "t-support-vector"],
    lectures: [8],
    basis: "교재 10.2.2 SVM의 학습 · 강의록 SVM의 학습",
    emphasis: "서포트 벡터 (xᵢ, yᵢ)와 라그랑주 승수 α̂ᵢ만 계산되면 ŵ₀와 분류 함수가 모두 계산된다.",
    aliases: ["라그랑지 승수", "Lagrange multiplier", "α"],
  },
  {
    id: "t-lagrangian-function",
    term: "라그랑주 함수",
    en: "Lagrangian function",
    category: "수식·지표",
    short: "목적함수와 조건을 라그랑주 승수로 묶은 하나의 함수 J(w, w₀, α).",
    definition:
      "목적함수 ‖w‖²/2와 조건 yᵢ(wᵀxᵢ + w₀) − 1 ≥ 0을 라그랑주 승수 αᵢ로 결합한 함수. 파라미터 w, w₀에 대해 극소화하고 α에 대해 극대화하면 원하는 조건을 만족하는 파라미터를 찾을 수 있다.",
    formula: [
      { expr: "J(w, w₀, α) = ½‖w‖² − Σᵢ αᵢ{yᵢ(wᵀxᵢ + w₀) − 1}", note: "식 10-11" },
      { expr: "∂J/∂w = w − Σαᵢyᵢxᵢ = 0, ∂J/∂w₀ = −Σαᵢyᵢ = 0", note: "식 10-12, 10-13" },
    ],
    prereqs: ["pre-lagrange", "pre-partial-derivative"],
    related: ["t-lagrange-multiplier", "t-dual-problem"],
    lectures: [8],
    basis: "교재 10.2.2 (식 10-11~10-13) · 강의록 SVM의 학습",
    aliases: ["라그랑지안", "Lagrangian"],
  },
  {
    id: "t-dual-problem",
    term: "이원적 문제",
    en: "dual problem",
    category: "수식·지표",
    short: "라그랑주 함수를 α만의 함수 Q(α)로 바꿔 쓴 최적화 문제.",
    definition:
      "w = Σαᵢyᵢxᵢ와 Σαᵢyᵢ = 0을 라그랑주 함수에 대입해 α에 대하여 표현한 새로운 목적함수 Q(α)의 최적화 문제. J(w, w₀, α)를 최적화하는 대신 Q(α)를 최대화해 파라미터를 얻는다. Q(α)는 αᵢ에 대한 이차함수로 이차계획법으로 간단히 해를 구할 수 있고, 유일한 최대값을 갖는다.",
    formula: [
      { expr: "Q(α) = Σᵢ αᵢ − ½ Σᵢ Σⱼ αᵢαⱼyᵢyⱼxᵢᵀxⱼ", note: "식 10-14" },
      { expr: "Σᵢ αᵢyᵢ = 0, αᵢ ≥ 0", note: "식 10-15" },
    ],
    prereqs: ["pre-sigma", "pre-dot-product"],
    related: ["t-lagrangian-function", "t-quadratic-programming", "t-kernel-function"],
    lectures: [8],
    basis: "교재 10.2.2 (식 10-14, 10-15) · 강의록 SVM의 학습",
    aliases: ["dual problem", "Q(α)", "쌍대 문제"],
  },
  {
    id: "t-quadratic-programming",
    term: "이차계획법",
    en: "quadratic programming",
    category: "알고리즘",
    short: "이차함수인 목적함수를 조건 아래에서 최적화하는 방법. SVM에서 Q(α)를 최대화하는 α̂ᵢ를 찾음.",
    definition:
      "이차함수 형태의 목적함수를 주어진 조건 아래에서 최적화하는 방법. SVM에서는 조건 Σαᵢyᵢ = 0, αᵢ ≥ 0(슬랙변수가 있으면 0 ≤ αᵢ ≤ c)을 만족하면서 Q(α)를 최대화하는 추정치 α̂ᵢ를 찾는 데 쓴다.",
    related: ["t-dual-problem", "t-lagrange-multiplier"],
    lectures: [8],
    basis: "교재 10.2.2 SVM의 학습 · 강의록 SVM의 학습",
    aliases: ["quadratic programming", "QP", "이차 계획법"],
  },
  {
    id: "t-svm-decision-function",
    term: "SVM의 분류 함수",
    en: "SVM decision function",
    category: "수식·지표",
    short: "f(x) = sign(Σ α̂ᵢyᵢxᵢᵀx + ŵ₀). 서포트 벡터만으로 계산.",
    definition:
      "추정된 파라미터 ŵ = Σα̂ᵢyᵢxᵢ, ŵ₀를 판별함수에 대입한 f(x) = sign(ŵᵀx + ŵ₀) = sign(Σα̂ᵢyᵢxᵢᵀx + ŵ₀). 1이면 C₁, −1이면 C₂로 분류한다. α̂ᵢ가 0인 데이터는 합에서 사라지므로 서포트 벡터만 저장해 계산한다.",
    formula: [
      { expr: "ŵ = Σᵢ α̂ᵢyᵢxᵢ", note: "식 10-16" },
      { expr: "ŵ₀ = (1/Nₛ) Σ_{xᵢ∈Xₛ} (yᵢ − Σ_{xⱼ∈Xₛ} α̂ⱼyⱼxⱼᵀxᵢ)", note: "학습 단계 ②-4" },
      { expr: "f(x) = sign(Σ_{xᵢ∈Xₛ} α̂ᵢyᵢxᵢᵀx + ŵ₀)", note: "식 10-19" },
    ],
    prereqs: ["pre-sign-function", "pre-dot-product"],
    related: ["t-support-vector", "t-lagrange-multiplier", "t-kernel-function"],
    lectures: [8],
    basis: "교재 10.2.3 SVM에 의한 분류 · 강의록 SVM에 의한 분류",
    aliases: ["분류 함수", "f(x)"],
  },
  {
    id: "t-one-vs-rest",
    term: "1대 나머지 방법",
    en: "one-versus-the-rest",
    category: "알고리즘",
    short: "k개의 이진 SVM으로 각 클래스와 나머지를 나눠 다중 클래스를 분류.",
    definition:
      "가장 보편적인 다중 클래스 적용 방법. k개의 개별적인 이진 분류기를 만들고, k번째 분류기는 클래스 C_k 데이터를 +1, 나머지 k − 1개 클래스 데이터를 −1로 학습한다. 새 데이터는 k개 분류기 중 양수에 해당하는 클래스로 할당한다.",
    distinctions: [
      {
        from: "1대 1 방법",
        how: "1대 나머지는 분류기 k개, 1대 1은 모든 클래스 쌍에 대해 k(k − 1)/2개를 만들고 보팅한다.",
      },
    ],
    related: ["t-one-vs-one", "t-svm"],
    lectures: [8],
    basis: "교재 10.2.3 · 강의록 다중 클래스 분류 문제에 적용 방법",
    emphasis: "이론상 하나만 양수여야 하지만 실제로는 그렇지 않아 애매한 결정 영역이 생기고, 학습 데이터 집합의 크기가 불균형하다.",
    aliases: ["one-versus-the-rest", "one-vs-rest", "OvR", "일대나머지"],
  },
  {
    id: "t-one-vs-one",
    term: "1대 1 방법",
    en: "one-versus-one",
    category: "알고리즘",
    short: "모든 클래스 쌍마다 SVM을 만들고 보팅으로 최종 클래스를 결정.",
    definition:
      "가능한 모든 클래스의 쌍에 대해 분류를 수행하는 k(k − 1)/2개의 서로 다른 SVM을 만들고, 각 이진 분류기의 결과에 대한 보팅을 통해 최종 클래스를 결정하는 방법.",
    formula: [{ expr: "k(k − 1)/2", note: "필요한 SVM의 개수" }],
    example: "k = 5이면 5×4/2 = 10개의 SVM.",
    related: ["t-one-vs-rest", "t-voting", "t-svm"],
    lectures: [8],
    basis: "교재 10.2.3 · 강의록 다중 클래스 분류 문제에 적용 방법",
    emphasis: "최종 클래스가 하나로 정해지지 않는 애매한 영역이 생길 수 있고, 학습과 테스트에 계산 비용이 많이 든다.",
    aliases: ["one-versus-one", "one-vs-one", "OvO", "일대일"],
  },

  /* ─────────── 슬랙변수 ─────────── */
  {
    id: "t-linear-separability",
    term: "선형 분리",
    en: "linear separability",
    category: "개념",
    short: "모든 학습 데이터를 하나의 선형 초평면으로 바르게 나눌 수 있는 성질.",
    definition:
      "학습 데이터를 하나의 선형 결정경계(초평면)로 모두 바르게 분류할 수 있는 성질. 선형 분리가 가능하면 학습 오차가 0인 결정경계가 매우 많으며, 일반적으로 주어지는 학습 데이터가 선형 분리 가능하다고 가정하는 것은 무리가 있다.",
    related: ["t-slack-variable", "t-kernel-method", "t-linear-classifier"],
    lectures: [8],
    basis: "교재 10.1.2, 10.2.4 · 강의록 슬랙변수를 가진 SVM",
    aliases: ["선형 분리 가능", "linearly separable"],
  },
  {
    id: "t-slack-variable",
    term: "슬랙변수",
    en: "slack variable",
    category: "수식·지표",
    short: "잘못 분류된 데이터로부터 해당 클래스의 경계까지의 거리 ξᵢ.",
    definition:
      "선형 분리가 불가능한 데이터를 처리하기 위해 도입하는 변수 ξᵢ (i = 1, …, N). 잘못 분류된 데이터로부터 해당 클래스의 경계까지의 거리를 나타내며, 분류 조건을 yᵢ(wᵀxᵢ + w₀) ≥ 1 − ξᵢ로 완화한다. ξᵢ가 클수록 더 심한 오분류를 허용함을 의미한다.",
    formula: [
      { expr: "yᵢ(wᵀxᵢ + w₀) ≥ 1 − ξᵢ, ξᵢ ≥ 0", note: "식 10-22, 10-24" },
      { expr: "J(w, ξ) = ½‖w‖² + c Σᵢ ξᵢ", note: "식 10-23" },
    ],
    distinctions: [
      {
        from: "커널법",
        how: "슬랙변수는 오분류 허용 정도를 조절할 뿐 결정경계는 여전히 선형 초평면이라 제한적으로만 해결한다. 비선형 문제를 적극적으로 해결하는 것은 커널법이다.",
      },
    ],
    related: ["t-slack-penalty-c", "t-linear-separability", "t-kernel-method"],
    lectures: [8],
    basis: "교재 10.2.4 슬랙변수를 가진 SVM · 강의록 슬랙변수를 가진 SVM",
    emphasis: "값이 클수록 더 심한 오분류를 허용한다. 작을수록이 아니다.",
    aliases: ["슬랙 변수", "ξ", "크사이", "slack variable"],
  },
  {
    id: "t-slack-penalty-c",
    term: "하이퍼파라미터 c (슬랙변수)",
    en: "penalty parameter c",
    category: "수식·지표",
    short: "cΣξᵢ 항을 얼마나 반영할지 정하는 사용자 정의 값. 크면 오분류 오차가 적어짐.",
    definition:
      "목적함수 J(w, ξ) = ½‖w‖² + cΣξᵢ에서 ξᵢ를 최소화하는 조건을 반영하는 정도를 결정하는 값으로, 사용자가 적절히 정해 주어야 한다. c가 크면 ξᵢ가 커지는 것을 강하게 저지해 오분류 오차가 적어지고, c가 작으면 오분류 허용도가 높아진다. 이원적 문제에서는 0 ≤ αᵢ ≤ c 조건으로 나타난다.",
    formula: [{ expr: "Σαᵢyᵢ = 0, 0 ≤ αᵢ ≤ c", note: "식 10-27" }],
    distinctions: [
      {
        from: "다항식 커널의 c",
        how: "다항식 커널 (x·y + c)ᵈ의 c는 같은 글자를 쓰지만 커널 함수의 파라미터로 서로 다른 값이다.",
      },
    ],
    related: ["t-slack-variable", "t-hyperparameter"],
    lectures: [8],
    basis: "교재 10.2.4 (2) 파라미터의 추정 · 강의록 슬랙변수와 커널을 가진 SVM 분류기의 학습과 인식 과정",
    aliases: ["C", "c", "페널티 파라미터"],
  },
  {
    id: "t-hyperparameter",
    term: "하이퍼파라미터",
    en: "hyperparameter",
    category: "개념",
    short: "학습으로 정해지지 않고 사용자가 문제의 성격에 맞추어 정하는 파라미터.",
    definition:
      "학습을 통해 추정되는 파라미터와 달리, 문제의 성격에 맞추어 사용자가 적절히 조정해 주어야 하는 사용자 정의 파라미터. SVM에서는 슬랙변수의 c와 커널 함수의 고유 파라미터(다항식 커널의 c와 d, 시그모이드 커널의 θ, 가우시안 커널의 σ)가 해당한다.",
    related: ["t-slack-penalty-c", "t-kernel-function", "t-gaussian-kernel"],
    lectures: [8],
    basis: "교재 10.3.2 (표 10-1) · 강의록 커널법과 SVM",
    aliases: ["사용자 정의 파라미터", "hyperparameter"],
  },

  /* ─────────── 커널법 ─────────── */
  {
    id: "t-high-dim-mapping",
    term: "고차원 매핑",
    en: "high-dimensional mapping",
    category: "개념",
    short: "저차원의 입력 x를 더 고차원 공간의 값 Φ(x)로 보내는 함수 Φ.",
    definition:
      "저차원의 입력 x를 좀 더 고차원 공간의 값 Φ(x)로 매핑시키는 함수. 입력 데이터의 차원을 높여 비선형 문제를 선형화하면 간단한 선형 분류기로 분류할 수 있지만, 계산량의 증가와 같은 부작용이 생긴다.",
    formula: [{ expr: "Φ : R² → R³, (x₁, x₂) ↦ (x₁², √2x₁x₂, x₂²)", note: "식 10-30" }],
    example: "2차원에서 원형의 결정경계 x₁² + x₂² = 1이 필요한 데이터가 3차원에서는 평면 z₁ + z₃ = 1로 나뉜다.",
    related: ["t-kernel-function", "t-kernel-method"],
    lectures: [8],
    basis: "교재 10.3.1 커널의 필요성 · 강의록 비선형 분류 문제의 해결 방법",
    aliases: ["Φ", "phi", "특징 공간 매핑"],
  },
  {
    id: "t-kernel-function",
    term: "커널 함수",
    en: "kernel function",
    category: "수식·지표",
    short: "고차원 매핑 후의 내적 Φ(x)·Φ(y)를 하나의 함수 k(x, y)로 정의한 것.",
    definition:
      "SVM의 연산이 개개의 값 Φ(x)가 아니라 두 벡터의 내적 Φ(x)·Φ(y)를 사용한다는 점에 착안해, 고차원 매핑 Φ(x)와 Φ(y)를 직접 정의하는 대신 Φ(x)·Φ(y)를 하나의 함수 k(x, y)로 정의하여 사용하는 함수.",
    formula: [
      { expr: "k(x, y) = Φ(x)·Φ(y)" },
      { expr: "(x₁², √2x₁x₂, x₂²)·(y₁², √2y₁y₂, y₂²) = (x·y)²", note: "식 10-31" },
      { expr: "Q(α) = Σαᵢ − ½ΣΣαᵢαⱼyᵢyⱼk(xᵢ, xⱼ)", note: "식 10-33" },
    ],
    example: "x = (1, 2), y = (3, 1)이면 Φ(x)·Φ(y) = 9 + 12 + 4 = 25 = (x·y)² = 5².",
    prereqs: ["pre-dot-product", "pre-exp-log"],
    related: [
      "t-kernel-method",
      "t-high-dim-mapping",
      "t-linear-kernel",
      "t-polynomial-kernel",
      "t-sigmoid-kernel",
      "t-gaussian-kernel",
    ],
    lectures: [8],
    basis: "교재 10.3.2 커널법과 SVM · 강의록 커널법과 SVM",
    emphasis: "3차원 벡터 연산 없이 원래 차원인 2차원 계산만으로 값이 얻어져 계산 비용 문제를 해결한다.",
    aliases: ["kernel function", "k(x, y)", "커널"],
  },
  {
    id: "t-kernel-method",
    term: "커널법",
    en: "kernel method",
    category: "알고리즘",
    short: "고차원 매핑으로 비선형 문제를 선형화하면서 커널 함수로 계산량 증가 문제를 해결하는 방법.",
    definition:
      "고차원 매핑을 통해 비선형 문제를 선형화하여 해결하면서 커널 함수를 통해 계산량 증가의 문제를 해결하는 방법. SVM을 비롯한 선형성을 가정하는 방법론에서 사용된다.",
    role: "SVM의 식에서 xᵢᵀxⱼ가 들어가던 자리를 k(xᵢ, xⱼ)로 바꾸면 선형 SVM이 비선형 결정경계를 가진 분류기로 확장된다.",
    distinctions: [
      {
        from: "슬랙변수",
        how: "슬랙변수는 선형 초평면을 유지한 채 오분류를 허용하는 제한적 해결책이고, 커널법은 비선형 문제를 고차원의 선형 문제로 바꾸는 적극적 해결책이다.",
      },
    ],
    related: ["t-kernel-function", "t-high-dim-mapping", "t-svm", "t-slack-variable"],
    lectures: [8],
    basis: "교재 10.3 커널법 · 강의록 비선형 분류 문제의 해결 방법, 커널법과 SVM",
    emphasis: "정의의 두 축 — 고차원 매핑으로 선형화, 커널 함수로 계산량 해결 — 을 함께 기억.",
    aliases: ["kernel method", "커널 트릭", "kernel trick"],
  },
  {
    id: "t-linear-kernel",
    term: "선형 커널",
    en: "linear kernel",
    category: "수식·지표",
    short: "k(x, y) = (x·y). 원래 입력 공간의 내적 그대로.",
    definition: "두 벡터의 내적을 그대로 쓰는 커널 함수 k(x, y) = (x·y). 결정경계는 원래 입력 공간의 선형 초평면이 된다.",
    formula: [{ expr: "k(x, y) = (x·y)" }],
    related: ["t-kernel-function", "t-polynomial-kernel"],
    lectures: [8],
    basis: "교재 표 10-1 · 강의록 커널법과 SVM",
    aliases: ["linear kernel"],
  },
  {
    id: "t-polynomial-kernel",
    term: "다항식 커널",
    en: "polynomial kernel",
    category: "수식·지표",
    short: "k(x, y) = (x·y + c)ᵈ. 하이퍼파라미터 c와 d.",
    definition:
      "k(x, y) = (x·y + c)ᵈ로 정의되는 커널 함수. c와 d는 사용자 정의 파라미터이며, c = 0, d = 2이면 식 10-31의 (x·y)²가 된다.",
    formula: [{ expr: "k(x, y) = (x·y + c)ᵈ" }],
    example: "강의록 실험에서 c = 1, d = 2인 다항식 커널로 곡선 결정경계를 얻었고 서포트 벡터는 5개였다.",
    related: ["t-kernel-function", "t-linear-kernel", "t-hyperparameter"],
    lectures: [8],
    basis: "교재 표 10-1 · 강의록 커널법과 SVM, 비선형 결정경계를 가진 이진 분류의 예",
    aliases: ["polynomial kernel"],
  },
  {
    id: "t-sigmoid-kernel",
    term: "시그모이드 커널",
    en: "sigmoid kernel",
    category: "수식·지표",
    short: "k(x, y) = tanh(θ₁x·y + θ₂). 하이퍼파라미터 θ₁, θ₂.",
    definition: "k(x, y) = tanh(θ₁ x·y + θ₂)로 정의되는 커널 함수. θ₁, θ₂는 사용자 정의 파라미터.",
    formula: [{ expr: "k(x, y) = tanh(θ₁ x·y + θ₂)" }],
    related: ["t-kernel-function", "t-hyperparameter"],
    lectures: [8],
    basis: "교재 표 10-1 · 강의록 커널법과 SVM",
    aliases: ["sigmoid kernel"],
  },
  {
    id: "t-gaussian-kernel",
    term: "가우시안 커널",
    en: "gaussian kernel",
    category: "수식·지표",
    short: "k(x, y) = exp{−‖x − y‖²/2σ²}. σ에 따라 결정경계가 크게 달라짐.",
    definition:
      "k(x, y) = exp{−‖x − y‖² / 2σ²}로 정의되는 커널 함수. 두 벡터의 거리로 계산되며, σ는 사용자 정의 파라미터다. σ 값에 따라 결정경계의 모양이 달라진다.",
    formula: [{ expr: "k(x, y) = exp{−‖x − y‖² / 2σ²}" }],
    example:
      "강의록 실험에서 σ = 1일 때 서포트 벡터 9개. σ = 0.2이면 결정경계가 데이터 몇 개씩을 감싸는 작은 영역들로 나뉘고, σ가 커질수록 완만해진다.",
    prereqs: ["pre-exp-log", "pre-euclidean"],
    related: ["t-kernel-function", "t-hyperparameter"],
    lectures: [8],
    basis: "교재 표 10-1 · 강의록 비선형 결정경계를 가진 이진 분류의 예",
    aliases: ["gaussian kernel", "RBF 커널", "가우스 커널"],
  },

  /* ─────────── 앞 강의 개념이 이 강의에서 쓰이는 자리 ─────────── */
  {
    id: "t-overfitting",
    term: "과다적합",
    en: "overfitting",
    category: "개념",
    short: "학습이 과다하게 일어나서 일반화 성능이 저하되는 현상.",
    definition:
      "학습이 과다하게 일어나서 일반화 성능이 저하되는 현상. 학습 데이터가 전체 데이터의 분포를 제대로 표현하지 못함에도 복잡도가 높은 분류기가 학습 데이터만 잘 분류하도록 과다하게 학습했을 때 발생한다.",
    related: ["t-model-complexity", "t-linear-classifier"],
    lectures: [8],
    basis: "교재 10.1.1 과다적합과 일반화 오차 · 강의록 학습 시스템의 복잡도와 일반화 오차의 관계",
  },
  {
    id: "t-generalization-error",
    term: "일반화 오차",
    en: "generalization error",
    category: "수식·지표",
    short: "학습에 사용되지 않은 데이터에 대한 오차.",
    definition:
      "학습되지 않은, 앞으로 주어질 데이터에 대한 오차. 학습 오차가 작은 복잡한 분류기라도 일반화 오차는 더 클 수 있으며, SVM은 일반화 오차를 최소화하는 방향으로 학습이 이루어지도록 설계되었다.",
    related: ["t-overfitting", "t-svm"],
    lectures: [8],
    basis: "교재 10.1.1 · 강의록 학습 시스템의 복잡도와 일반화 오차의 관계",
  },
  {
    id: "t-model-complexity",
    term: "학습 시스템의 복잡도",
    en: "model complexity",
    category: "개념",
    short: "표현할 수 있는 결정경계가 얼마나 복잡한지의 정도.",
    definition:
      "학습 시스템이 표현할 수 있는 결정경계의 복잡한 정도. 과다학습을 피하고 일반화 오차를 줄이려면 복잡도를 적절히 조정하는 것이 매우 중요하며, SVM은 복잡도가 가장 낮은 선형 분류기에서 설계를 시작한다.",
    related: ["t-overfitting", "t-linear-classifier"],
    lectures: [8],
    basis: "교재 10.1.1 · 강의록 학습 시스템의 복잡도와 일반화 오차의 관계",
  },
];
