import type { GlossaryTerm } from "@/lib/mlGlossaryTypes";

/**
 * 7강 결정 트리와 랜덤 포레스트에서 다루는 용어.
 *
 * 정의는 교재 9장과 강의록 표현을 보존한다.
 */
export const lecture7Terms: GlossaryTerm[] = [
  /* ─────────── 결정 트리 개요 ─────────── */
  {
    id: "t-decision-tree",
    term: "결정 트리",
    en: "decision tree",
    category: "알고리즘",
    short: "주어진 문제(입력)에 관해 결정을 내리는 함수를 트리 형태로 구성한 것.",
    definition:
      "주어진 문제(또는 입력)에 관해 결정을 내리는 함수를 학습을 통해 트리 형태로 구성한 것. 루트 노드와 내부 노드는 속성, 가지는 속성값에 따른 구분, 리프 노드는 최종 결과에 대응한다. 기본적으로 분류 문제를 위해 개발되었고 회귀 문제로 확장되어 CART라고도 부른다.",
    role: "트리 구조를 이용한 데이터 분석으로 분류나 회귀를 수행하며, 학습 결과에 대한 설명이 가능한 분류기.",
    example:
      "세탁기 동작 여부: Weather가 Rainy면 OFF, Sunny면 Humidity < 80일 때 ON, Cloudy면 Amount가 Large일 때 ON.",
    distinctions: [
      {
        from: "규칙(IF ~ THEN ~)의 집합",
        how: "같은 판단을 규칙으로도 쓸 수 있지만 규칙은 개발자가 임의로 정의하고, 결정 트리는 데이터를 이용한 학습으로 자동 생성된다.",
      },
      {
        from: "신경망 같은 블랙박스 분류기",
        how: "결정 트리는 트리 구조에 각 입력 요소의 역할이 드러나 결과를 설명할 수 있다. 블랙박스 분류기는 내부 처리를 이해하기 어렵다.",
      },
    ],
    related: [
      "t-cart",
      "t-root-node",
      "t-leaf-node",
      "t-tree-attribute",
      "t-explainability",
      "t-gini-impurity",
      "t-random-forest",
    ],
    lectures: [7],
    basis: "교재 9.1.1 결정 트리 개요 · 강의록 7강 결정 트리",
    emphasis:
      "장점은 뛰어난 설명 능력, 단점은 과다적합. 과다적합을 풀기 위해 앙상블 학습을 결합한 랜덤 포레스트가 등장한다는 흐름으로 기억.",
    aliases: ["decision tree", "결정트리", "의사결정나무"],
  },
  {
    id: "t-cart",
    term: "CART",
    en: "Classification And Regression Trees",
    category: "알고리즘",
    short: "분류 문제에서 회귀 문제로 확장된 결정 트리를 부르는 이름.",
    definition:
      "결정 트리는 기본적으로 분류 문제를 위해 개발되었으나 이후 회귀 문제에도 적용되도록 확장되었으며, 이를 CART(Classification And Regression Trees)라는 이름으로 부른다.",
    related: ["t-decision-tree", "t-regression-tree"],
    lectures: [7],
    basis: "교재 9장 도입, 9.1.1 · 강의록 7강 결정 트리",
    aliases: ["CART", "분류 회귀 트리"],
  },
  {
    id: "t-root-node",
    term: "루트 노드",
    en: "root node",
    category: "개념",
    short: "결정 트리의 맨 위 노드. 판단에 쓰는 첫 속성이 배정됨.",
    definition:
      "결정 트리에서 판단이 시작되는 맨 위의 노드. 내부 노드와 함께 판단을 내리는 데 사용하는 결정 요인(속성)에 대응한다. 분할이 이루어지기 전이므로 학습 데이터 전체가 할당된다.",
    example: "세탁기 예의 루트 노드는 Weather. 할당된 데이터 14개(ON 5, OFF 9), I(R) = 0.4592.",
    related: ["t-internal-node", "t-leaf-node", "t-tree-branch", "t-tree-depth"],
    lectures: [7],
    basis: "교재 9.1.1 · 강의록 정리하기 — 결정 트리",
    aliases: ["root node", "루트"],
  },
  {
    id: "t-internal-node",
    term: "내부 노드",
    en: "internal node",
    category: "개념",
    short: "루트와 리프 사이의 노드. 속성이 배정되어 데이터를 다시 나눔.",
    definition:
      "루트 노드와 리프 노드 사이에 있는 노드. 판단을 내리는 데 사용하는 결정 요인(속성)에 대응하며, 그 속성값에 따라 가지를 나눈다.",
    example: "세탁기 예의 Humidity < 80 노드와 Amount 노드.",
    related: ["t-root-node", "t-leaf-node", "t-tree-attribute"],
    lectures: [7],
    basis: "교재 9.1.1 · 강의록 정리하기 — 결정 트리",
    aliases: ["internal node", "중간 노드"],
  },
  {
    id: "t-tree-branch",
    term: "가지",
    en: "branch",
    category: "개념",
    short: "노드의 속성값에 따라 나뉘는 갈래.",
    definition:
      "루트 노드나 내부 노드에 배정된 속성이 가지는 값에 따라 나뉘는 갈래. 속성값을 구분하며, 가지의 개수는 속성이 가질 수 있는 값의 종류에 따라 결정된다.",
    example: "Weather의 가지는 Sunny, Rainy, Cloudy 세 개. Amount의 가지는 Large, Small 두 개.",
    related: ["t-root-node", "t-attribute-value"],
    lectures: [7],
    basis: "교재 9.1.1, 9.1.2 · 강의록 정리하기 — 결정 트리",
    aliases: ["branch", "분기"],
  },
  {
    id: "t-leaf-node",
    term: "리프 노드",
    en: "leaf node",
    category: "개념",
    short: "최종 결정 결과를 나타내는 맨 끝 노드.",
    definition:
      "루트 노드에서 시작해 속성값에 따라 가지를 선택하여 내려가는 과정을 반복해 도달하는 노드로, 최종 결정 결과를 나타낸다. 학습 과정에서 어떤 자식 노드에 할당된 데이터의 클래스 레이블이 모두 동일하면 더 이상 분할할 필요가 없으므로 그 노드는 리프 노드가 된다.",
    example: "세탁기 예에서 Weather = Rainy인 자식 노드는 데이터 4개가 모두 OFF라 리프 노드(OFF)가 된다.",
    distinctions: [
      {
        from: "분류 트리의 리프 vs 회귀 트리의 리프",
        how: "분류는 할당된 데이터 중 다수 클래스를, 회귀는 목표 출력값의 평균을 출력한다.",
      },
    ],
    related: ["t-root-node", "t-gini-impurity", "t-node-output"],
    lectures: [7],
    basis: "교재 9.1.1, 9.1.2 · 강의록 정리하기 — 결정 트리",
    aliases: ["leaf node", "리프", "잎 노드", "단말 노드"],
  },
  {
    id: "t-tree-attribute",
    term: "속성 (결정 요인)",
    en: "attribute",
    category: "개념",
    short: "판단을 내리는 데 사용하는 결정 요인. 루트·내부 노드에 배정됨.",
    definition:
      "결정 트리에서 판단을 내리는 데 사용하는 결정 요인. 루트 노드와 내부 노드에 배정되며, 각 노드에 어떤 속성을 배정하느냐에 따라 나뉘는 데이터 그룹의 형태가 달라진다.",
    example: "세탁기 예의 속성: 날씨(Weather), 온도(Temperature), 습도(Humidity), 세탁량(Amount).",
    related: ["t-attribute-value", "t-gini-criterion"],
    lectures: [7],
    basis: "교재 9.1.1, 9.1.2 · 강의록 결정 트리 — 세탁기 예",
    emphasis: "완성된 세탁기 트리에는 온도가 전혀 쓰이지 않는다. 주어진 속성을 모두 쓰는 것이 아니다.",
    aliases: ["attribute", "결정 요인", "속성"],
  },
  {
    id: "t-attribute-value",
    term: "속성값",
    en: "attribute value",
    category: "개념",
    short: "속성이 가지는 값. 이 값에 따라 가지가 나뉨.",
    definition:
      "속성이 가지는 값. 범주형 속성은 값의 종류마다 가지를 만들고, 연속한 실수값을 가지는 속성은 x₁ ≤ 0.555처럼 속성의 특정 실숫값을 기준으로 데이터를 분할한다. 적절한 속성과 속성값 역시 지니 평가지수로 선택한다.",
    example: "2차원 데이터 분류에서 루트 노드의 속성과 속성값 x₁ = 0.555 → 수직선으로 데이터를 구분.",
    related: ["t-tree-attribute", "t-tree-branch", "t-staircase-boundary"],
    lectures: [7],
    basis: "교재 9.1.3 결정 트리를 이용한 2차원 데이터 분류 · 강의록 결정 트리를 이용한 분류",
    aliases: ["attribute value", "분할 기준값"],
  },
  {
    id: "t-explainability",
    term: "설명력",
    en: "explainability",
    category: "개념",
    short: "학습 결과가 왜 나왔는지 설명할 수 있는 능력.",
    definition:
      "학습을 통해 얻어지는 트리 구조에 데이터의 각 입력 요소의 역할이 잘 나타나, 결과에 대한 설명이 가능한 성질. 신경망과 같은 블랙박스 형태의 분류기가 갖추지 못한 결정 트리의 장점이다.",
    related: ["t-decision-tree", "t-black-box"],
    lectures: [7],
    basis: "교재 9장 도입 · 강의록 결정 트리 — 뛰어난 설명 능력 제공",
    emphasis: "구름 낀 날 세탁량이 많아서 돌린다처럼, 트리를 따라가면 결과의 이유를 그대로 읽을 수 있다.",
    aliases: ["explainability", "설명 능력", "해석 가능성"],
  },
  {
    id: "t-black-box",
    term: "블랙박스 형태의 분류기",
    en: "black-box classifier",
    category: "개념",
    short: "입력과 결과만 보이고 내부 처리를 이해하기 어려운 분류기.",
    definition:
      "입력이 주어지면 결과가 나오지만 그 안에서 어떤 처리가 일어나 그런 결과가 나왔는지 이해하기 어려운 분류기. 신경망이나 딥러닝 시스템이 이렇게 여겨진다.",
    distinctions: [{ from: "결정 트리", how: "결정 트리는 트리를 따라가면 결과의 근거가 드러나는 설명력을 가진다." }],
    related: ["t-explainability", "t-neural-network"],
    lectures: [7],
    basis: "교재 9장 도입",
    aliases: ["black box", "블랙박스"],
  },
  {
    id: "t-rule-based",
    term: "규칙 기반의 표현",
    en: "rule-based representation",
    category: "개념",
    short: "IF ~ THEN ~ 조건문 규칙의 집합으로 결정을 표현하는 것.",
    definition:
      "결정 규칙을 조건문(IF ~ THEN ~)의 집합으로 표현하는 것. 개발자나 전문가가 임의로 규칙을 정의하고 표현한다. 결정 트리는 같은 내용을 표현할 수 있지만 데이터를 이용한 학습으로 트리를 자동 생성한다는 점이 다르다.",
    example: "If (Weather == Sunny) and (Humidity < 80) then Machine = ON",
    related: ["t-decision-tree"],
    lectures: [7],
    basis: "교재 9.1.1 · 강의록 결정 트리 vs 규칙 기반의 표현",
    emphasis: "문제가 작으면 둘 사이에 별 차이가 없지만, 문제가 커지면 규칙을 일일이 정의하는 데 무리가 따른다.",
    aliases: ["IF-THEN 규칙", "규칙의 집합"],
  },
  /* ─────────── 속성 선택 평가지수 ─────────── */
  {
    id: "t-gini-impurity",
    term: "지니 불순도",
    en: "Gini impurity",
    category: "수식·지표",
    short: "노드에 할당된 클래스 레이블의 혼합 정도. 섞일수록 높음.",
    definition:
      "각 노드에 할당된 클래스 레이블이 얼마나 다른지 그 혼합 정도를 측정하는 값. 하나의 그룹 안에 서로 다른 클래스 레이블이 혼재할수록 불순도는 높아진다.",
    formula: [
      { expr: "I(N) = Σᵢ₌₁ᴷ pᵢ(1 − pᵢ) = 1 − Σᵢ₌₁ᴷ (pᵢ)²", note: "K: 클래스의 개수, pᵢ: 노드 N에 할당된 데이터 그룹에 속한 i번째 클래스의 비율 (식 9-1)" },
    ],
    example: "ON 3·OFF 2 → 1 − (3/5)² − (2/5)² = 0.48. 모두 OFF → 0. 세탁기 전체(ON 5·OFF 9) → 0.4592.",
    distinctions: [
      {
        from: "지니 평가지수",
        how: "지니 불순도는 노드 하나의 값, 지니 평가지수는 속성으로 나눈 자식 노드들의 지니 불순도를 가중합한 값.",
      },
    ],
    prereqs: ["pre-proportion", "pre-sigma"],
    related: ["t-gini-criterion", "t-entropy", "t-leaf-node"],
    lectures: [7],
    basis: "교재 9.1.2 식 9-1 · 강의록 결정 트리의 학습 — 속성 선택을 위한 평가 기준",
    aliases: ["Gini impurity", "I(N)"],
  },
  {
    id: "t-gini-criterion",
    term: "지니 평가지수",
    en: "Gini criterion",
    category: "수식·지표",
    short: "자식 노드들의 지니 불순도를 데이터 개수 비율로 가중합한 값. 최소인 속성을 선택.",
    definition:
      "속성 a를 갖는 부모 노드 R_a가 M개의 자식 노드 C₁, …, C_M을 가질 때, 자식 노드들의 지니 불순도의 가중합. 결정 트리 학습에서는 루트 노드(깊이 1, 레벨 0)에서 시작해 지니 평가지수를 최소화하는 속성 노드를 선택하여 레벨을 확장하는 과정을 반복한다.",
    formula: [
      { expr: "G(R_a) = Σᵢ₌₁ᴹ (|Cᵢ| / |R_a|) · I(Cᵢ)", note: "|R_a|, |C₁|, …, |C_M|: 각 노드에 속하는 데이터 개수 (식 9-4)" },
    ],
    example:
      "G(R_Weather) = 5/14 × 0.48 + 4/14 × 0 + 5/14 × 0.48 = 0.3429 < G(R_Amount) = 0.4286 < G(R_Temperature) = 0.4405 → Weather 선택.",
    prereqs: ["pre-weighted-average", "pre-argmax-argmin"],
    related: ["t-gini-impurity", "t-information-gain", "t-tree-attribute"],
    lectures: [7],
    basis: "교재 9.1.2 식 9-4, 식 9-5 · 강의록 결정 트리의 학습",
    emphasis:
      "관심은 노드 하나의 불순도가 아니라 부모 노드의 속성으로 나눴을 때의 전체 효과. 그래서 단순 합이 아니라 데이터 개수 비율로 가중해 더한다.",
    aliases: ["Gini criterion", "G(R_a)"],
  },
  {
    id: "t-entropy",
    term: "엔트로피",
    en: "entropy",
    category: "수식·지표",
    short: "주어진 데이터 집합의 혼잡도.",
    definition:
      "주어진 데이터 집합의 혼잡도. 여러 클래스가 많이 섞여 있을수록 엔트로피가 높다. 정보 이득은 데이터 집합의 분할 전후의 엔트로피 차이로 정의된다.",
    formula: [{ expr: "H = −Σᵢ pᵢ log₂ pᵢ", note: "pᵢ: i번째 클래스의 비율 (엔트로피를 구하는 대표적인 식)" }],
    example: "세탁기 전체(ON 5·OFF 9): H = −(5/14)log₂(5/14) − (9/14)log₂(9/14) ≈ 0.9403.",
    prereqs: ["pre-log-base2", "pre-proportion"],
    related: ["t-information-gain", "t-gini-impurity"],
    lectures: [7],
    basis: "강의록 속성 노드 선택을 위한 그 밖의 평가지수 — 정보 이득",
    emphasis: "엔트로피↑ → 정보 이득↓. 방향을 거꾸로 외우지 않도록.",
    aliases: ["entropy", "혼잡도"],
  },
  {
    id: "t-information-gain",
    term: "정보 이득",
    en: "information gain",
    category: "수식·지표",
    short: "분할 전후 엔트로피의 차이. 높은 속성을 선택.",
    definition:
      "데이터 집합의 분할 전후의 엔트로피의 차이. 정보 이득이 높은 속성을 기준으로 선택한다. 엔트로피(혼잡도)가 높으면 정보 이득은 낮다.",
    formula: [{ expr: "정보 이득 = H(분할 전) − Σᵢ (|Cᵢ| / |R|) · H(Cᵢ)" }],
    example: "세탁기 루트: Weather 0.2467, Amount 0.0481, Temperature 0.0292 → Weather 선택(지니 평가지수와 같은 결론).",
    distinctions: [{ from: "지니 평가지수", how: "지니 평가지수는 최소인 속성을, 정보 이득은 최대인 속성을 고른다." }],
    prereqs: ["pre-log-base2"],
    related: ["t-entropy", "t-gini-criterion", "t-variance-reduction", "t-chi-square"],
    lectures: [7],
    basis: "교재 9.1.2 · 강의록 속성 노드 선택을 위한 그 밖의 평가지수",
    aliases: ["information gain", "IG"],
  },
  {
    id: "t-variance-reduction",
    term: "분산 감소량",
    en: "variance reduction",
    category: "수식·지표",
    short: "모든 노드에 대한 분산의 가중평균을 이용하는 평가지수. 회귀 문제에서 주로 사용.",
    definition:
      "모든 노드에 대한 분산의 가중평균을 이용하는 평가지수. 분산은 데이터의 동질성을 표시하며 데이터가 완전히 같으면 분산은 0이 된다. 회귀 문제에서 주로 사용한다.",
    prereqs: ["pre-variance", "pre-weighted-average"],
    related: ["t-regression-tree", "t-information-gain"],
    lectures: [7],
    basis: "교재 9.1.2 · 강의록 속성 노드 선택을 위한 그 밖의 평가지수",
    emphasis: "분산이 작다는 것은 데이터가 흩어지지 않고 뭉쳐 동질성이 높다는 뜻.",
    aliases: ["variance reduction"],
  },
  {
    id: "t-chi-square",
    term: "카이제곱 (Chi-square)",
    en: "chi-square",
    category: "수식·지표",
    short: "부모 노드와 하위 노드 간 차이의 통계적 유의성을 활용하는 평가지수.",
    definition:
      "부모 노드와 하위 노드 간 차이의 통계적 유의성을 활용하는 속성 선택 평가지수. 목표 출력이 범주형인 경우에 적합하다.",
    related: ["t-information-gain", "t-gini-criterion"],
    lectures: [7],
    basis: "강의록 속성 노드 선택을 위한 그 밖의 평가지수",
    aliases: ["Chi-square", "χ²", "카이스퀘어"],
  },
  /* ─────────── 분류·회귀 트리 ─────────── */
  {
    id: "t-tree-depth",
    term: "트리의 깊이",
    en: "tree depth",
    category: "개념",
    short: "루트 노드(깊이 1)부터 센 트리의 층 수. 깊을수록 복잡한 함수 표현.",
    definition:
      "루트 노드를 깊이 1(레벨 0)로 두고 센 트리의 층 수. 복잡한 함수를 표현하려면 트리의 깊이가 깊어져야 하는데, 그 과정에서 데이터의 노이즈에 민감해진다. 결정 트리를 학습할 때는 적절한 깊이를 사전에 정해 두고 해당 깊이까지만 확장하는 방법이 권장된다.",
    example: "2차원 분류 예: 깊이 4에서는 불순도가 0이 아닌 리프가 남고, 깊이 5에서 모든 리프의 지니 불순도가 0이 되어 이 데이터의 최대 깊이가 5.",
    related: ["t-overfitting", "t-early-stopping", "t-staircase-boundary"],
    lectures: [7],
    basis: "교재 9.1.2, 9.1.3 · 강의록 결정 트리를 이용한 분류",
    aliases: ["depth", "깊이", "레벨"],
  },
  {
    id: "t-staircase-boundary",
    term: "계단 형태의 결정경계",
    en: "staircase decision boundary",
    category: "개념",
    short: "결정 트리가 만드는 축에 평행한 계단 모양의 불연속 결정경계.",
    definition:
      "결정 트리의 결정경계는 베이즈나 K-최근접이웃 분류기와 달리 계단 형태의 불연속 함수로 주어진다. 트리의 깊이가 깊지 않을수록 불연속성이 뚜렷하게 나타나며, 다양한 형태의 결정경계를 표현하기 어렵다.",
    example: "실제 결정경계가 대각선 x₁ = x₂여도 트리는 수직·수평선의 조합으로만 근사한다.",
    related: ["t-decision-boundary", "t-tree-depth", "t-attribute-value"],
    lectures: [7],
    basis: "교재 9.1.3 그림 9-6 · 강의록 결정 트리를 이용한 분류 — 결정경계",
    aliases: ["계단형 결정경계", "불연속 결정경계"],
  },
  {
    id: "t-regression-tree",
    term: "회귀를 위한 결정 트리",
    en: "regression tree",
    category: "알고리즘",
    short: "리프 노드가 목표 출력값의 평균(실수값)을 출력하는 결정 트리.",
    definition:
      "분류 문제를 위한 결정 트리의 간단한 변형. 기본 구조와 분할 기준(속성과 속성값)은 그대로이고, 리프 노드가 가지는 출력값이 클래스 레이블이 아닌 실수값이 되어야 하므로 해당 노드에 할당된 데이터들이 가지는 목표 출력값의 평균값을 사용한다. 노드에는 지니 불순도 대신 제곱오차가 표시된다.",
    example: "y = 0인 데이터 3개, y = 1인 데이터 8개가 할당된 리프의 출력값 = 8/11 = 0.727.",
    related: ["t-cart", "t-node-output", "t-variance-reduction", "t-squared-error"],
    lectures: [7],
    basis: "교재 9.1.4 회귀를 위한 결정 트리 · 강의록 회귀를 위한 결정 트리",
    emphasis: "깊이가 깊어지면 분할 영역 수가 기하급수적으로 늘어 노이즈에 과다적합되기 쉽다.",
    aliases: ["regression tree", "회귀 트리", "회귀 결정 트리"],
  },
  {
    id: "t-node-output",
    term: "노드의 출력값",
    en: "node output",
    category: "개념",
    short: "분류: 다수 클래스, 회귀: 목표 출력값의 평균.",
    definition:
      "리프 노드가 내는 결과. 분류 문제에서는 해당 노드에 할당된 데이터 중 다수의 데이터가 포함된 클래스를 레이블로 설정하고, 회귀 문제에서는 해당 노드에 속한 데이터의 목표 출력값의 평균을 출력값으로 한다.",
    example: "루트 노드 100개 중 목표 출력 1이 42개 → 분류 출력 class 0, 회귀 출력 0.42.",
    related: ["t-leaf-node", "t-regression-tree"],
    lectures: [7],
    basis: "교재 9.1.4 · 강의록 회귀를 위한 결정 트리 — 노드의 출력값",
    aliases: ["리프 출력", "value"],
  },
  /* ─────────── 과다적합과 해결책 ─────────── */
  {
    id: "t-overfitting",
    term: "과다적합",
    en: "overfitting",
    category: "개념",
    short: "학습 데이터의 노이즈까지 완벽히 학습해 일반화 성능이 떨어지는 현상.",
    definition:
      "모든 학습 데이터에 대해 노이즈까지 완벽히 학습하여 일반화 성능이 저하되는 현상. 결정 트리는 복잡한 함수를 표현하는 과정에서 트리의 깊이가 깊어지고 그 과정에서 데이터의 노이즈에 민감해져 과다적합 문제가 발생한다.",
    related: ["t-early-stopping", "t-pruning", "t-random-forest", "t-tree-depth"],
    lectures: [7],
    basis: "교재 9.1.3, 9.2.1 · 강의록 결정 트리의 문제",
    aliases: ["overfitting", "과적합"],
  },
  {
    id: "t-early-stopping",
    term: "조기 종료",
    en: "early stopping",
    category: "개념",
    short: "더 분할해도 성능이 향상되지 않는 시점에 노드의 분할을 종료.",
    definition:
      "결정 트리의 과다적합에 대한 간단한 해결책의 하나. 데이터를 더 분할해도 성능이 향상되지 않은 시점에 노드의 분할을 종료하여 트리의 깊이를 조절한다.",
    distinctions: [{ from: "가지치기", how: "조기 종료는 트리를 만드는 도중에 멈추고, 가지치기는 전체 트리를 만든 후 불필요한 노드를 제거한다." }],
    related: ["t-pruning", "t-overfitting", "t-tree-depth"],
    lectures: [7],
    basis: "교재 9.2.1 · 강의록 결정 트리의 문제 — 간단한 해결책",
    aliases: ["early stopping"],
  },
  {
    id: "t-pruning",
    term: "가지치기",
    en: "pruning",
    category: "개념",
    short: "전체 트리를 만든 후 불필요한 노드들을 제거.",
    definition:
      "결정 트리의 과다적합에 대한 간단한 해결책의 하나. 전체 트리를 만든 후 불필요한 노드들을 제거한다.",
    distinctions: [{ from: "조기 종료", how: "가지치기는 다 만든 트리에서 잘라 내고, 조기 종료는 만드는 도중에 분할을 멈춘다." }],
    related: ["t-early-stopping", "t-overfitting"],
    lectures: [7],
    basis: "교재 9.2.1 · 강의록 결정 트리의 문제 — 간단한 해결책",
    aliases: ["pruning", "프루닝"],
  },
  /* ─────────── 랜덤 포레스트 ─────────── */
  {
    id: "t-random-forest",
    term: "랜덤 포레스트",
    en: "random forest",
    category: "알고리즘",
    short: "배깅으로 리샘플링한 데이터로 M개의 결정 트리를 학습하고 결합하는 방법.",
    definition:
      "결정 트리와 앙상블 학습 기법을 결합한 방법. 배깅 방법으로 데이터를 리샘플링하여 M개의 결정 트리를 학습하고 결합한다. 결합 방법은 분류 문제에서 주로 보팅법, 회귀 문제에서 출력값의 평균. ‘포레스트’는 M개의 서로 다른 결정 트리가 결합된 숲 구조를, ‘랜덤’은 결정 트리 간의 차이가 랜덤하게 추출된 데이터 샘플에 기인함을 뜻한다.",
    formula: [{ expr: "f(h₁(x), h₂(x), …, h_M(x))", note: "hᵢ(x): i번째 결정 트리의 판별함수(또는 회귀함수), f: 결합 함수" }],
    role: "결정 트리의 과다적합 문제를 완화하는 발전된 해결책. 트리 수가 증가할수록 정교한 결정경계를 만들고 일반화 성능이 향상된다.",
    distinctions: [
      {
        from: "결정 트리",
        how: "결정 트리는 높은 설명 능력과 빠른 학습이 장점이지만 과다적합이 생긴다. 랜덤 포레스트는 이 장점에 앙상블의 일반화 성능 향상을 더하지만, 생성에 많은 시간이 걸리고 예측 결과를 해석하기 어렵다.",
      },
    ],
    prereqs: ["pre-sampling-with-replacement"],
    related: ["t-decision-tree", "t-bagging", "t-bootstrap", "t-voting", "t-ensemble-learning", "t-overfitting"],
    lectures: [7],
    basis: "교재 9.2 랜덤 포레스트 · 강의록 랜덤 포레스트",
    emphasis: "용어의 유래(숲 = 나무가 많이 모인 것, 랜덤 = 무작위 추출된 샘플에서 오는 트리 간 차이)를 함께 기억.",
    aliases: ["random forest", "랜덤포레스트", "RF"],
  },
  {
    id: "t-bagging",
    term: "배깅",
    en: "bagging",
    category: "알고리즘",
    short: "데이터를 리샘플링해 여러 학습기를 만들고 결합하는 앙상블 방법.",
    definition:
      "전체 학습 데이터 집합에서 데이터를 리샘플링(복원추출)하여 여러 데이터 집합을 만들고, 각각으로 학습한 학습기를 결합하는 앙상블 학습 방법. 랜덤 포레스트는 배깅 방법으로 데이터를 리샘플링하여 M개의 결정 트리를 학습한다.",
    related: ["t-random-forest", "t-bootstrap", "t-ensemble-learning", "t-voting"],
    lectures: [7],
    basis: "교재 9.2.1 · 강의록 랜덤 포레스트?",
    aliases: ["bagging", "bootstrap aggregating"],
  },
  {
    id: "t-bootstrap",
    term: "복원추출 (리샘플링)",
    en: "sampling with replacement",
    category: "개념",
    short: "같은 데이터가 중복해서 선출되는 것을 허락하며 랜덤하게 뽑는 것.",
    definition:
      "학습 데이터 집합 X로부터 Ñ(≤ N)개의 데이터를 랜덤하게 선출하되, 같은 데이터가 중복해서 선출되는 것도 허락하는 추출 방법. 랜덤 포레스트에서 i번째 결정 트리의 데이터 집합 Xᵢ를 만드는 데 사용한다.",
    example: "N = 40에서 Ñ = 40개를 복원추출하면 어떤 데이터는 두세 번 뽑히고 어떤 데이터는 한 번도 뽑히지 않는다.",
    prereqs: ["pre-sampling-with-replacement"],
    related: ["t-bagging", "t-random-forest"],
    lectures: [7],
    basis: "교재 9.2.1 랜덤 포레스트의 학습 ② · 강의록 랜덤 포레스트의 학습",
    aliases: ["bootstrap", "부트스트랩", "리샘플링", "resampling", "복원 추출"],
  },
  {
    id: "t-voting",
    term: "보팅",
    en: "voting",
    category: "알고리즘",
    short: "여러 학습기의 분류 결과를 투표(다수결)로 결합하는 방법.",
    definition:
      "여러 학습기의 출력을 투표로 결합하는 방법. 랜덤 포레스트를 분류 문제에 적용할 때 M개 결정 트리의 결과를 결합하는 방법으로 주로 사용한다. 회귀 문제에서는 보팅 대신 출력값의 평균을 취한다.",
    related: ["t-random-forest", "t-bagging", "t-ensemble-learning"],
    lectures: [7],
    basis: "교재 9.2.1 · 강의록 랜덤 포레스트? — 결합 방법",
    aliases: ["voting", "보팅법", "다수결"],
  },
  {
    id: "t-ensemble-learning",
    term: "앙상블 학습",
    en: "ensemble learning",
    category: "학습 유형",
    short: "간단한 학습기 여러 개를 결합해 복잡한 함수 표현과 일반화 성능 향상을 얻는 기법.",
    definition:
      "간단한 학습기를 여러 개 결합하여 복잡한 함수를 표현하고 일반화 성능을 향상시키는 학습 기법. 결정 트리는 앙상블 학습 기법과 결합될 때 일반화 성능 향상 효과가 매우 뛰어나며, 이렇게 결합한 방법이 랜덤 포레스트다.",
    related: ["t-random-forest", "t-bagging", "t-voting"],
    lectures: [7],
    basis: "교재 9.1.3, 9.2.2 · 강의록 랜덤 포레스트? — 장점",
    aliases: ["ensemble learning", "앙상블"],
  },
];
