import type { GlossaryTerm } from "@/lib/mlGlossaryTypes";

/**
 * 6강 앙상블 학습에서 다루는 용어 (교재 8장).
 *
 * 정의는 교재·강의록 표현을 보존하되 한 문장으로 읽히게 다듬었다.
 */
export const lecture6Terms: GlossaryTerm[] = [
  /* ─────────── 앙상블 학습의 개념 ─────────── */
  {
    id: "t-ensemble-learning",
    term: "앙상블 학습",
    en: "ensemble learning",
    category: "알고리즘",
    short: "복수 개의 간단한 학습기를 결합해 더 좋은 성능의 학습기를 만드는 방법.",
    definition:
      "선형 분류기와 같은 간단한 학습기로 학습을 수행하지만, 복수 개의 간단한 학습기를 결합함으로써 결과적으로 더 좋은 성능을 가진 학습기를 만드는 방법. 주어진 문제에 대해 M개의 서로 다른 가설(결과)을 만들고 이를 적절히 결합하여 최종 결과를 도출한다.",
    role: "복잡·대규모 학습기의 긴 학습 시간, 최적해 탐색의 어려움, 과다학습 문제를 피하면서 간단한 학습기의 표현력 한계를 넘는다.",
    formula: [
      { expr: "hᵢ(x) = h(x, θᵢ)", note: "기본 모델은 같고 학습 데이터가 달라 파라미터 θᵢ가 달라짐 (식 8-1)" },
      { expr: "f_M(x) = f(h₁(x), h₂(x), …, h_M(x))", note: "결합 함수 f로 얻는 최종 결과 (식 8-2)" },
    ],
    example: "선형 분류기 200개를 AdaBoost로 결합하면 cos 모양의 실제 결정경계를 거의 따라가는 결정경계를 얻는다.",
    distinctions: [
      {
        from: "단일 복잡 학습기(신경망, SVM 등)",
        how: "하나의 정교한 학습기로 문제를 푸는 대신, 간단한 학습기 여럿을 결합해 비슷한 성능을 얻는다.",
      },
    ],
    related: [
      "t-learner-diversification",
      "t-parallel-combination",
      "t-sequential-combination",
      "t-bagging",
      "t-boosting",
      "t-weak-learner",
      "t-generalization-error",
      "t-overfitting",
    ],
    lectures: [6],
    basis: "교재 8.1 앙상블 학습의 개념 · 강의록 6강 학습기 결합",
    emphasis:
      "고려사항은 두 가지 — 어떤 학습기를 쓸 것인가(간단하면서 서로 차별성이 있는 것), 어떻게 결합할 것인가(각 학습기의 특성을 고려).",
    aliases: ["ensemble", "앙상블", "학습기 결합"],
  },
  {
    id: "t-learner-diversification",
    term: "학습기의 차별화 방법",
    category: "개념",
    short: "서로 다른 학습기를 얻는 세 수준 — 알고리즘, 모델 선택 파라미터, 학습 데이터.",
    definition:
      "앙상블에 쓸 서로 다른 복수 개의 학습기를 선택하는 방법. 학습 알고리즘의 차별화(베이즈 분류기 & K-NN, 신경망 & SVM), 모델 선택과 관련된 파라미터의 차별화(K값이 다른 K-NN, 은닉층 뉴런 수가 다른 신경망), 학습 데이터의 차별화(같은 모델, 다른 학습 데이터 집합)가 있다.",
    role: "결합 효과를 높이려면 학습기 간 차별성이 있어야 한다. 교재는 이 가운데 학습 데이터의 차별화를 중심으로 다룬다.",
    related: ["t-ensemble-learning", "t-bagging", "t-knn-classifier", "t-neural-network"],
    lectures: [6],
    basis: "교재 8.1.1 학습기 결합의 필요성 · 강의록 학습기 결합에서 고려사항",
    emphasis:
      "학습 데이터만 달리해도 하나의 학습기로는 얻을 수 없는 성능 향상을 얻을 수 있고 이론적 연구도 충실해 이 방법에 중점을 둔다.",
  },
  {
    id: "t-parallel-combination",
    term: "병렬적 결합",
    category: "개념",
    short: "각 학습기의 결과를 한 번에 모두 함께 고려해 하나의 최종 결과를 내는 결합.",
    definition:
      "각 학습기로부터 얻어진 결과를 한 번에 모두 함께 고려하여 하나의 최종 결과를 얻는 학습기 결합 방법.",
    distinctions: [
      {
        from: "순차적 결합",
        how: "병렬적 결합은 결과를 한꺼번에 모으고, 순차적 결합은 앞 단계 학습기의 결과가 뒤 단계 학습기의 학습과 분류에 영향을 준다.",
      },
    ],
    related: ["t-sequential-combination", "t-voting", "t-averaging"],
    lectures: [6],
    basis: "교재 8.1.1 · 강의록 학습기 결합 방법",
  },
  {
    id: "t-sequential-combination",
    term: "순차적 결합",
    category: "개념",
    short: "각 학습기의 결과를 단계별로 나누어 결합. 앞 단계 결과가 뒤 단계에 영향.",
    definition:
      "각 학습기의 결과를 단계별로 나누어, 앞 단계에 배치된 학습기의 결과가 뒤에 배치된 학습기의 학습과 분류에 영향을 미치도록 결합하는 방법.",
    example: "필터링에 의한 부스팅, 캐스케이딩.",
    related: ["t-parallel-combination", "t-boosting", "t-cascading"],
    lectures: [6],
    basis: "교재 8.1.1 · 강의록 학습기 결합 방법",
  },
  {
    id: "t-weak-learner",
    term: "간단한 학습기",
    en: "weak learner",
    category: "개념",
    short: "개별적으로는 성능이 그다지 좋지 못한 간단한 학습기.",
    definition:
      "개별적인 학습기로는 그 성능이 그다지 좋지 못한 간단한 학습기. 앙상블의 결합 방법들은 이런 학습기들을 결합해 성능을 증폭시켜, 복잡한 학습기로부터 기대할 수 있는 처리 결과를 얻고자 한다.",
    example: "선형 분류기, 퍼셉트론 하나.",
    related: ["t-ensemble-learning", "t-boosting", "t-adaboost"],
    lectures: [6],
    basis: "교재 8.1.2 앙상블 학습의 개요",
    emphasis: "대표적인 결합 방법에 'Boost'라는 단어가 붙은 것도 이 증폭의 목적 때문이다.",
    aliases: ["weak learner", "약한 학습기"],
  },
  {
    id: "t-filtering-method",
    term: "필터링에 의한 방법",
    en: "filtering",
    category: "개념",
    short: "새 데이터를 이미 학습된 학습기에 통과시켜 제대로 처리 못한 데이터만 학습.",
    definition:
      "각 학습기의 학습 때마다 새로운 데이터를 생성하되, 이를 바로 학습에 적용하기에 앞서 이미 학습이 완료된 학습기에 적용하여 제대로 처리되지 못하는 데이터들만 필터링하여 학습하는 학습 데이터 생성 방법.",
    example: "초기 부스팅(필터링에 의한 부스팅), 캐스케이딩.",
    related: ["t-resampling", "t-reweighting", "t-boosting-by-filtering", "t-cascading"],
    lectures: [6],
    basis: "교재 8.1.2 · 강의록 학습 데이터 생성 방법의 구분",
  },
  {
    id: "t-resampling",
    term: "리샘플링에 의한 방법",
    en: "resampling",
    category: "개념",
    short: "전체 학습 데이터에서 일부 집합을 추출해 각 학습기를 학습.",
    definition:
      "각 학습기의 학습 때마다 학습 데이터를 매번 새로 생성하지 않고, 주어진 전체 학습 데이터로부터 일부 집합을 추출하여 각 학습기를 학습하는 학습 데이터 생성 방법.",
    example: "배깅, MadaBoost.",
    prereqs: ["pre-sampling-with-replacement"],
    related: ["t-bagging", "t-bootstrap", "t-madaboost", "t-filtering-method", "t-reweighting"],
    lectures: [6],
    basis: "교재 8.1.2 · 강의록 학습 데이터 생성 방법의 구분",
  },
  {
    id: "t-reweighting",
    term: "가중치 조정에 의한 방법",
    en: "reweighting",
    category: "개념",
    short: "모든 학습기에 같은 데이터를 쓰되 데이터별 가중치로 영향도를 조정.",
    definition:
      "모든 학습기에 대해 같은 학습 데이터를 사용하되, 각 데이터에 가중치를 주어 학습에 대한 영향도를 조정하는 학습 데이터 생성 방법.",
    example: "가장 대표적인 앙상블 학습 방법인 AdaBoost.",
    related: ["t-adaboost", "t-data-weight", "t-resampling", "t-filtering-method"],
    lectures: [6],
    basis: "교재 8.1.2 · 강의록 학습 데이터 생성 방법의 구분",
  },
  {
    id: "t-madaboost",
    term: "MadaBoost",
    en: "Modification of AdaBoost",
    category: "알고리즘",
    short: "학습이 잘되지 않는 샘플이 더 자주 선택되도록 샘플링하는 리샘플링 방법.",
    definition:
      "리샘플링에 의한 방법의 하나로, 학습이 잘되지 않는 샘플들이 더 자주 선택될 수 있도록 하는 샘플링 기법을 적용한 방법(Modification of AdaBoost).",
    related: ["t-resampling", "t-adaboost", "t-bagging"],
    lectures: [6],
    basis: "교재 8.1.2 · 강의록 학습 데이터 생성 방법의 구분",
  },
  /* ─────────── 배깅과 보팅 ─────────── */
  {
    id: "t-bagging",
    term: "배깅",
    en: "bagging (bootstrap aggregating)",
    category: "알고리즘",
    short: "부트스트랩으로 만든 서로 다른 데이터 집합으로 M개의 학습기를 학습하는 방법.",
    definition:
      "부트스트랩 방법을 앙상블 학습에 적용한 것으로, bootstrap aggregating의 약자. 학습 데이터 집합 X로부터 Ñ개(Ñ ≤ N)의 데이터를 복원 추출해 Xᵢ를 만들고 i번째 학습기를 학습하는 과정을 M번 반복하여 서로 다른 M개의 학습기를 생성한 뒤 결합한다. 학습기의 선택과 관련된 방법이다.",
    role: "가장 단순한 리샘플링 방법으로, 데이터 변화만으로 학습기 간 차별성을 만든다.",
    formula: [{ expr: "Xᵢ ← X에서 Ñ개 복원 추출 → hᵢ(x, θᵢ), i = 1, …, M" }],
    example:
      "전체 데이터가 충분히 크지 않으면 Ñ = N으로 둔다. 복원 추출이므로 그래도 매 단계 생성되는 데이터 집합은 동일하지 않다.",
    distinctions: [
      {
        from: "보팅",
        how: "배깅은 학습기의 선택(학습 데이터 생성)과 관련된 방법이고, 보팅은 학습기의 결합과 관련된 방법이다.",
      },
      {
        from: "부스팅",
        how: "배깅은 확률적 리샘플링에만 의존해 학습기 간 차이를 주고, 부스팅은 앞 학습기의 결과를 다음 학습에 반영해 순차적으로 학습한다.",
      },
    ],
    prereqs: ["pre-sampling-with-replacement"],
    related: ["t-bootstrap", "t-voting", "t-resampling", "t-boosting", "t-random-forest", "t-knn-classifier"],
    lectures: [6],
    basis: "교재 8.2.1 배깅에 의한 학습과 보팅에 의한 결합 · 강의록 배깅에 의한 학습",
    emphasis:
      "학습기 모델은 판별함수가 데이터 집합의 변화에 민감한 것이 바람직하다 — K-최근접이웃 분류기, 다층 퍼셉트론.",
    aliases: ["bagging", "bootstrap aggregating", "배깅법"],
  },
  {
    id: "t-bootstrap",
    term: "부트스트랩",
    en: "bootstrap",
    category: "개념",
    short: "제한된 데이터 집합으로 학습과 평가를 동시에 하기 위해 제안된 리샘플링 기법.",
    definition:
      "원래 제한된 데이터 집합을 이용하여 시스템의 학습과 평가를 동시에 수행하기 위하여 제안된 리샘플링 기법. 같은 데이터가 중복해서 선출되는 것을 허락하는 복원 추출로 데이터 집합을 만든다.",
    prereqs: ["pre-sampling-with-replacement"],
    related: ["t-bagging", "t-resampling"],
    lectures: [6],
    basis: "교재 8.2.1 · 강의록 배깅에 의한 학습",
    aliases: ["bootstrap", "부트스트래핑"],
  },
  {
    id: "t-voting",
    term: "보팅법",
    en: "voting (committee machine)",
    category: "알고리즘",
    short: "M개 학습기의 결과를 동일한 정도로 반영해 평균하는 결합 방법. 커미티 머신.",
    definition:
      "M개의 학습기 결과를 모두 동일한 정도로 반영하여 평균한 결과를 얻는 방법(단순평균법). 각 학습기가 일종의 위원회(committee) 역할을 하여 최종 결과에 각각 한 표씩 투표하는 것으로 볼 수 있어 보팅법(투표법) 또는 커미티 머신이라 한다.",
    formula: [{ expr: "f(x) = (1/M) Σᵢ hᵢ(x)", note: "식 8-5" }],
    role: "연속된 실수값을 내는 함수 근사 문제에 적합. 분류 문제에서는 결합함수 결과로 클래스 레이블을 결정하는 추가 처리가 필요.",
    distinctions: [
      {
        from: "배깅",
        how: "보팅은 결과의 결합, 배깅은 학습기의 선택(학습 데이터 생성)과 관련된다.",
      },
    ],
    prereqs: ["pre-weighted-average", "pre-sigma"],
    related: ["t-bagging", "t-simple-average", "t-majority-voting", "t-weighted-voting", "t-hard-voting", "t-soft-voting"],
    lectures: [6],
    basis: "교재 8.2.1 · 강의록 보팅에 의한 결합",
    emphasis: "각 학습기의 오차가 서로 독립이면 결합된 학습기의 일반화 오차는 개별 학습기 평균의 1/M로 감소.",
    aliases: ["voting", "투표법", "committee machine", "커미티 머신", "위원회 기계"],
  },
  {
    id: "t-error-independence",
    term: "학습기 오차의 독립성",
    category: "수식·지표",
    short: "서로 다른 학습기 오차 곱의 기대치가 0 — 이때 일반화 오차가 1/M로 감소.",
    definition:
      "각 학습기가 내는 오차값들이 서로 독립적이어서 Eₓ[eᵢ(x)eⱼ(x)] = 0이 성립하는 조건. 이때 보팅으로 결합한 학습기의 일반화 오차는 개별 학습기의 평균적인 일반화 오차의 1/M배가 된다.",
    formula: [
      { expr: "Eₓ[{f(x) − f*(x)}²] = (1/M²) Σᵢ Eₓ[eᵢ²(x)] + (1/M²) Σ_{i≠j} Eₓ[eᵢ(x)eⱼ(x)]", note: "식 8-8" },
      { expr: "Eₓ[eᵢ(x)eⱼ(x)] = 0", note: "식 8-9" },
      { expr: "Eₓ[{f(x) − f*(x)}²] = (1/M) · {(1/M) Σᵢ Eₓ[eᵢ²(x)]}", note: "식 8-10" },
    ],
    distinctions: [
      {
        from: "양의 상관관계",
        how: "오차가 양의 상관관계를 가지면 일반화 오차는 1/M만큼 줄지 않는다. 단순한 배깅이 이 경우라 식 8-10만큼의 감소를 기대하기 어렵다. 음의 상관관계를 가지면 더욱 감소한다.",
      },
    ],
    prereqs: ["pre-expectation", "pre-covariance"],
    related: ["t-voting", "t-generalization-error", "t-bagging", "t-mixture-of-experts"],
    lectures: [6],
    basis: "교재 8.2.2 배깅과 보팅의 효과 · 강의록 배깅과 보팅에 의한 효과_일반화 오차",
    emphasis: "1/M 감소에는 '독립'이라는 조건이 붙어 있다는 점.",
  },
  /* ─────────── 부스팅 ─────────── */
  {
    id: "t-boosting",
    term: "부스팅",
    en: "boosting",
    category: "알고리즘",
    short: "간단한 학습기들을 순차적으로 학습해 서로의 결점을 보완하도록 결합하는 방법.",
    definition:
      "간단한 학습기들이 상호보완적 역할을 할 수 있도록 단계적으로 학습을 수행하여 결합함으로써 성능을 증폭(boost)시키기 위한 방법. 학습기들을 순차적으로 학습하도록 하여 먼저 학습된 학습기의 결과가 다음 학습기의 학습에 정보를 제공하고, 이전 학습기의 결점을 보완하는 방향으로 학습을 진행한다.",
    distinctions: [
      {
        from: "배깅",
        how: "배깅은 확률적 리샘플링에만 의존하지만, 부스팅은 먼저 학습된 학습기의 결과로 다음 학습을 전략적으로 조정한다.",
      },
    ],
    related: ["t-boosting-by-filtering", "t-adaboost", "t-bagging", "t-sequential-combination", "t-weak-learner"],
    lectures: [6],
    basis: "교재 8.3 부스팅 · 강의록 부스팅 boosting",
    aliases: ["boosting"],
  },
  {
    id: "t-boosting-by-filtering",
    term: "필터링에 의한 부스팅",
    en: "boosting by filtering",
    category: "알고리즘",
    short: "학습기별로 새 데이터 집합을 만들어 앞 학습기로 걸러 학습하는 최초의 부스팅.",
    definition:
      "가장 처음 제안된 부스팅 방법(Schapire). h₁은 X₁로 학습, h₂는 새 데이터 X₂ 중 h₁이 잘못된 결과를 낸 데이터와 바르게 결과를 낸 데이터 일부를 같은 비율로 모아 학습, h₃는 새 데이터 X₃ 중 h₁과 h₂의 결과가 서로 일치하지 않는 데이터로 학습한다. 추론에서는 h₁과 h₂의 결과가 일치하면 그 결과를, 아니면 h₃의 결과를 최종 결과로 한다.",
    role: "간단한 분류기의 분류 성능을 증폭시킬 수 있음을 보인 첫 방법.",
    distinctions: [
      {
        from: "AdaBoost",
        how: "학습기별로 서로 다른 데이터 집합을 새로 만들고 그 일부만 학습에 쓰므로 학습 데이터 규모가 매우 커야 한다. AdaBoost는 같은 데이터 집합을 반복해서 쓰고 가중치만 조정한다.",
      },
    ],
    related: ["t-boosting", "t-adaboost", "t-filtering-method"],
    lectures: [6],
    basis: "교재 8.3 부스팅 · 강의록 필터링에 의한 부스팅",
  },
  {
    id: "t-adaboost",
    term: "AdaBoost",
    en: "Adaptive Boost",
    category: "알고리즘",
    short: "같은 데이터에 적응적으로 바뀌는 가중치를 주며 학습하고, 중요도 αᵢ로 가중 보팅하는 부스팅.",
    definition:
      "같은 데이터 집합을 반복해서 사용하되, 학습할 때마다 각 데이터에 대한 중요도(가중치)를 조정하여 학습에 변화를 주는 부스팅 방법. 데이터의 중요도가 적응적으로 변한다는 특성에서 Adaptive Boost라는 이름이 붙었다. 학습 방법과 결합 방법을 함께 고려하여, 분류기의 중요도 αᵢ를 결합계수로 하는 가중치를 가진 보팅으로 결합한다.",
    formula: [
      { expr: "wⱼ⁽¹⁾ = 1/N, tⱼ ∈ {−1, 1}", note: "①" },
      { expr: "εᵢ = Σⱼ wⱼ⁽ⁱ⁾ I(hᵢ(xⱼ) ≠ tⱼ)", note: "②-1 가중 오분류율" },
      { expr: "αᵢ = ½ ln{(1 − εᵢ)/εᵢ}", note: "②-3 분류기의 중요도" },
      { expr: "wⱼ⁽ⁱ⁺¹⁾ = wⱼ⁽ⁱ⁾ exp{−αᵢtⱼhᵢ(xⱼ)} / Zᵢ", note: "②-4 가중치 수정" },
      { expr: "f_M(x) = sign(Σᵢ αᵢhᵢ(x))", note: "③ 최종 판별함수" },
    ],
    example:
      "x = 0…9, t = (+,+,+,−,−,−,+,+,+,−)에서 한 점 기준 분류기를 쓰면 ε₁ = 0.3, α₁ ≈ 0.4236 → ε₂ ≈ 0.2143, α₂ ≈ 0.6496 → ε₃ ≈ 0.1818, α₃ ≈ 0.7520이고, 세 분류기를 결합한 f₃는 학습 데이터 10개를 모두 맞힌다.",
    distinctions: [
      {
        from: "배깅",
        how: "배깅은 학습기 선택 방법만 정하고 결합은 따로 정한다. AdaBoost는 학습 방법과 결합 방법을 함께 고려한다.",
      },
      {
        from: "전문가 혼합",
        how: "AdaBoost의 αᵢ는 분류기마다 하나로 정해지는 상수, 전문가 혼합의 πᵢ(x)는 입력의 함수.",
      },
    ],
    prereqs: ["pre-exp-log", "pre-sigma"],
    related: [
      "t-boosting",
      "t-weighted-error-rate",
      "t-classifier-importance",
      "t-data-weight",
      "t-normalization-factor",
      "t-reweighting",
      "t-weighted-voting",
      "t-supervised-learning",
    ],
    lectures: [6],
    basis: "교재 8.3 부스팅 — AdaBoost · 강의록 AdaBoost 알고리즘",
    emphasis:
      "목표 출력값이 주어지는 지도학습이며 이진 분류 문제에 적합. 다중 클래스는 클래스별 판별함수나 클래스 쌍 판별함수로 대응. 간단한 분류기의 오분류율이 0.5보다 작다는 조건만 만족하면 학습 데이터 오차를 기하급수적으로 줄일 수 있다(Freund & Schapire).",
    aliases: ["AdaBoost", "아다부스트", "Adaptive Boosting"],
  },
  {
    id: "t-weighted-error-rate",
    term: "가중 오분류율",
    en: "weighted error rate",
    category: "수식·지표",
    short: "잘못 분류된 데이터들의 가중치 합 εᵢ.",
    definition:
      "각 학습 데이터에 가중치가 적용된 오분류율. hᵢ(xⱼ) ≠ tⱼ인 데이터들의 가중치 wⱼ⁽ⁱ⁾를 모두 더한 값이며, AdaBoost ②-2는 이를 최소화하는 분류기 hᵢ를 학습으로 얻는다.",
    formula: [{ expr: "εᵢ = Σⱼ wⱼ⁽ⁱ⁾ I(hᵢ(xⱼ) ≠ tⱼ)" }],
    example: "가중치가 모두 0.1인 10개 가운데 3개를 틀리면 ε = 0.3.",
    related: ["t-adaboost", "t-indicator-function", "t-classifier-importance", "t-classification-error"],
    lectures: [6],
    basis: "교재 8.3 AdaBoost ②-1 · 강의록 AdaBoost에 의한 분류기의 학습과 분류 과정",
    emphasis: "첫 분류기는 모든 가중치가 1/N이라 일반적인 오분류율과 같고, 그 뒤로는 수정된 가중치가 쓰인다.",
    aliases: ["오분류율", "εᵢ", "epsilon"],
  },
  {
    id: "t-indicator-function",
    term: "지시 함수 I(·)",
    category: "수식·지표",
    short: "조건이 만족할 때만 1, 아니면 0을 내는 함수.",
    definition:
      "I(hᵢ(xⱼ) ≠ tⱼ)는 hᵢ(xⱼ) ≠ tⱼ가 만족할 때만 1의 값을 가지고, 그렇지 않은 경우는 0의 값을 가지는 함수. 가중 오분류율에서 틀린 데이터의 가중치만 골라 더하는 역할을 한다.",
    related: ["t-weighted-error-rate", "t-adaboost"],
    lectures: [6],
    basis: "교재 8.3 AdaBoost ②-1 · 강의록 AdaBoost ②-1",
    aliases: ["indicator", "1(·)"],
  },
  {
    id: "t-classifier-importance",
    term: "분류기의 중요도 αᵢ",
    category: "수식·지표",
    short: "오분류율이 작을수록 큰 값. 가중치 수정과 최종 결합의 계수로 쓰임.",
    definition:
      "오분류율 εᵢ를 이용하여 계산한 각 분류기 hᵢ(x)의 중요도. εᵢ가 작을수록 크고, εᵢ < 0.5(랜덤한 분류기보다 성능이 좋을 때)이면 양수, 그렇지 못하면 음수다. 다음 분류기를 위한 데이터 가중치 수정과 최종 판별함수의 결합계수에 쓰인다.",
    formula: [{ expr: "αᵢ = ½ ln{(1 − εᵢ)/εᵢ}" }],
    example: "εᵢ = 0.2 → αᵢ = ½ ln 4 = ln 2 ≈ 0.693. εᵢ = 0.5 → αᵢ = 0.",
    prereqs: ["pre-exp-log"],
    related: ["t-adaboost", "t-weighted-error-rate", "t-data-weight", "t-weighted-voting"],
    lectures: [6],
    basis: "교재 8.3 AdaBoost ②-3, 그림 8-3(a) · 강의록 AdaBoost 알고리즘 ②-3",
    emphasis: "오분류율 0.5는 둘 중 하나를 찍는 랜덤 분류기에 해당하는 기준점.",
    aliases: ["alpha", "αᵢ", "결합 중요도", "결합계수"],
  },
  {
    id: "t-data-weight",
    term: "데이터 가중치 wⱼ⁽ⁱ⁾",
    category: "수식·지표",
    short: "i번째 분류기 학습에서 j번째 데이터의 중요도. 틀리면 커지고 맞히면 작아짐.",
    definition:
      "AdaBoost에서 각 학습 데이터에 주는 중요도. 처음에는 1/N으로 초기화하고, 매 단계 exp{−αᵢtⱼhᵢ(xⱼ)}를 곱한 뒤 Zᵢ로 정규화하여 수정한다. 바른 출력을 낸 데이터는 exp(−αᵢ) < 1이 곱해져 감소하고, 잘못된 출력의 데이터는 exp(αᵢ) > 1이 곱해져 증가한다.",
    formula: [
      { expr: "wⱼ⁽¹⁾ = 1/N" },
      { expr: "wⱼ⁽ⁱ⁺¹⁾ = wⱼ⁽ⁱ⁾ exp{−αᵢtⱼhᵢ(xⱼ)} / Zᵢ" },
    ],
    prereqs: ["pre-exp-log"],
    related: ["t-adaboost", "t-normalization-factor", "t-classifier-importance", "t-reweighting"],
    lectures: [6],
    basis: "교재 8.3 AdaBoost ①, ②-4, 그림 8-3(b) · 강의록 AdaBoost 알고리즘 ②-4",
    emphasis:
      "오분류율이 0.5에 가까우면 가중치 변화폭이 작지만, 오분류율이 작아질수록 틀린 데이터의 가중치 증가 폭이 급격히 커진다.",
    aliases: ["w_j", "가중치 수정"],
  },
  {
    id: "t-normalization-factor",
    term: "정규화 값 Zᵢ",
    category: "수식·지표",
    short: "수정된 가중치들의 합이 1이 되도록 나누는 값.",
    definition:
      "AdaBoost ②-4에서 가중치들의 합이 1이 되도록 정규화하기 위한 값. 이전 가중치에 exp{−αᵢtⱼhᵢ(xⱼ)}를 곱한 값을 모든 데이터에 대해 더한 것이다.",
    formula: [{ expr: "Zᵢ = Σⱼ wⱼ⁽ⁱ⁾ exp{−αᵢtⱼhᵢ(xⱼ)}" }],
    example: "ε₁ = 0.3, α₁ ≈ 0.4236이면 Z₁ = 0.7·e^(−0.4236) + 0.3·e^(0.4236) ≈ 0.9165.",
    related: ["t-data-weight", "t-adaboost", "t-weighted-error-rate"],
    lectures: [6],
    basis: "교재 8.3 AdaBoost ②-4 · 강의록 AdaBoost ②-4",
    aliases: ["Z_i", "Zi"],
  },
  /* ─────────── 결합 방법 ─────────── */
  {
    id: "t-averaging",
    term: "평균법",
    category: "알고리즘",
    short: "학습기의 출력이 수치형일 때 적합한 결합 — 단순평균과 가중평균.",
    definition: "학습기의 출력이 수치형일 때 적합한 결합 방법으로, 단순평균과 가중평균으로 구분한다.",
    distinctions: [
      {
        from: "보팅법",
        how: "평균법은 수치형 출력, 보팅법은 분류 문제의 클래스 레이블 출력에 주로 쓴다.",
      },
    ],
    prereqs: ["pre-weighted-average"],
    related: ["t-simple-average", "t-weighted-average", "t-voting"],
    lectures: [6],
    basis: "교재 8.4.1 기본적인 결합 방법 · 강의록 기본적인 결합 방법 — 평균법",
  },
  {
    id: "t-simple-average",
    term: "단순평균",
    en: "simple average",
    category: "수식·지표",
    short: "M개 학습기 출력을 똑같이 1/M씩 반영한 평균.",
    definition: "M개 학습기의 출력을 모두 동일한 정도로 반영하여 평균한 결합. 배깅에서 언급된 보팅(식 8-5)이 이에 해당한다.",
    formula: [{ expr: "f(x) = (1/M) Σᵢ hᵢ(x)", note: "식 8-11" }],
    role: "학습기들이 비슷한 성능을 가진 경우에 적용.",
    prereqs: ["pre-weighted-average"],
    related: ["t-weighted-average", "t-averaging", "t-voting"],
    lectures: [6],
    basis: "교재 8.4.1 식 8-11 · 강의록 기본적인 결합 방법 — 평균법",
    aliases: ["단순평균법"],
  },
  {
    id: "t-weighted-average",
    term: "가중평균",
    en: "weighted average",
    category: "수식·지표",
    short: "학습기마다 가중치 wᵢ(wᵢ ≥ 0, Σwᵢ = 1)를 곱해 더한 결합.",
    definition:
      "학습기 출력에 가중치 wᵢ를 곱해 더하는 결합. 가중치는 일반적으로 학습 데이터를 사용한 학습 과정에서 얻는다.",
    formula: [{ expr: "f(x) = Σᵢ wᵢhᵢ(x), wᵢ ≥ 0, Σᵢ wᵢ = 1", note: "식 8-12" }],
    role: "학습기 간의 성능 차이가 비교적 큰 경우에 적용.",
    prereqs: ["pre-weighted-average"],
    related: ["t-simple-average", "t-averaging", "t-weighted-voting"],
    lectures: [6],
    basis: "교재 8.4.1 식 8-12 · 강의록 기본적인 결합 방법 — 평균법",
    emphasis: "학습기 성능이 비슷하면 단순평균, 성능 차이가 크면 가중평균.",
  },
  {
    id: "t-majority-voting",
    term: "다수결 투표",
    en: "majority voting",
    category: "수식·지표",
    short: "최대 득표를 한 클래스 레이블을 출력으로 하는 보팅.",
    definition:
      "각 학습기가 낸 클래스 레이블 가운데 최대 득표를 한 레이블을 출력 레이블로 하는 결합. 과반수 개념을 도입해 최대 득표가 과반수를 넘지 못할 때 분류 결과를 기각하는 처리도 포함시킬 수 있다.",
    formula: [{ expr: "f(x) = argmaxⱼ Σᵢ hᵢʲ(x)", note: "식 8-13 — hᵢʲ(x)는 학습기 hᵢ의 출력 클래스 레이블이 j임을 나타냄" }],
    prereqs: ["pre-argmax-argmin"],
    related: ["t-weighted-voting", "t-voting", "t-hard-voting"],
    lectures: [6],
    basis: "교재 8.4.1 식 8-13 · 강의록 기본적인 결합 방법 — 보팅법",
    aliases: ["다수결", "majority vote"],
  },
  {
    id: "t-weighted-voting",
    term: "가중 보팅",
    en: "weighted voting",
    category: "수식·지표",
    short: "학습기마다 가중치를 곱해 득표를 세는 보팅.",
    definition: "학습기별 가중치 wᵢ를 곱한 득표로 클래스 레이블을 정하는 보팅. AdaBoost의 결합은 분류기의 중요도 αᵢ를 가중치로 쓴 가중 보팅이다.",
    formula: [{ expr: "f(x) = argmaxⱼ Σᵢ wᵢhᵢʲ(x), wᵢ ≥ 0, Σᵢ wᵢ = 1", note: "식 8-14" }],
    prereqs: ["pre-argmax-argmin", "pre-weighted-average"],
    related: ["t-majority-voting", "t-adaboost", "t-classifier-importance"],
    lectures: [6],
    basis: "교재 8.4.1 식 8-14 · 강의록 기본적인 결합 방법 — 보팅법",
  },
  {
    id: "t-hard-voting",
    term: "하드 보팅",
    en: "hard voting",
    category: "개념",
    short: "학습기 출력 hᵢʲ(x)가 0 또는 1인 보팅.",
    definition: "보팅법에서 학습기의 출력값 hᵢʲ(x)가 0 또는 1의 값으로 클래스를 표현하는 경우(hᵢʲ(x) ∈ {0, 1}).",
    distinctions: [
      {
        from: "소프트 보팅",
        how: "하드 보팅은 확신의 크기와 상관없이 한 표씩만 세고, 소프트 보팅은 0~1 사이의 확률값을 그대로 더한다. 그래서 두 결과가 달라질 수 있다.",
      },
    ],
    example: "C₁일 확률 0.9, 0.4, 0.4 → 하드 보팅은 C₂(2표 대 1표).",
    related: ["t-soft-voting", "t-majority-voting"],
    lectures: [6],
    basis: "교재 8.4.1 · 강의록 기본적인 결합 방법 — 보팅법",
  },
  {
    id: "t-soft-voting",
    term: "소프트 보팅",
    en: "soft voting",
    category: "개념",
    short: "학습기 출력 hᵢʲ(x)가 0과 1 사이의 확률값인 보팅.",
    definition: "보팅법에서 학습기의 출력값 hᵢʲ(x)가 0과 1 사이의 확률값을 갖는 경우(hᵢʲ(x) ∈ [0, 1]).",
    example: "C₁일 확률 0.9, 0.4, 0.4 → 합 1.7 대 1.3으로 소프트 보팅은 C₁.",
    related: ["t-hard-voting", "t-majority-voting"],
    lectures: [6],
    basis: "교재 8.4.1 · 강의록 기본적인 결합 방법 — 보팅법",
  },
  {
    id: "t-combiner",
    term: "결합기",
    category: "개념",
    short: "기본 학습기들의 출력을 입력으로 받아 결합하도록 학습된 또 다른 학습기.",
    definition:
      "학습기들의 출력값에 대한 평균이나 투표 대신, 기본 학습기의 결과를 결합하기 위해 사용하는 다른 하나의 학습기. 기본 학습기의 학습을 완료한 뒤, 기본 학습기의 학습에 사용되지 않은 새로운 데이터 (xᵢ, yᵢ)에 대한 기본 학습기 출력 zᵢⱼ로 학습 데이터 ((zᵢ₁, …, zᵢ_M), yᵢ)를 구성해 학습한다.",
    formula: [{ expr: "((zᵢ₁, zᵢ₂, …, zᵢ_M), yᵢ), zᵢⱼ = hⱼ(xᵢ)" }],
    distinctions: [
      {
        from: "평균법·보팅법",
        how: "결합 규칙을 식으로 정해 두지 않고, 결합 자체를 데이터로 학습한다.",
      },
    ],
    related: ["t-averaging", "t-voting", "t-overfitting"],
    lectures: [6],
    basis: "교재 8.4.1 · 강의록 기본적인 결합 방법 — 결합기",
    emphasis: "기본 학습기의 학습 데이터를 그대로 쓰면 과다적합의 위험이 커지므로 새로운 데이터를 준비한다.",
    aliases: ["combiner", "결합을 위한 학습기"],
  },
  {
    id: "t-cascading",
    term: "캐스케이딩",
    en: "cascading",
    category: "알고리즘",
    short: "여러 복잡도의 학습기를 순차적으로 결합해 계산 효율과 안정적 성능을 얻는 전략.",
    definition:
      "처리에 많은 계산 비용이 요구되는 문제에서 계산 효율을 높이면서 안정적인 성능을 얻기 위하여 전략적으로 여러 가지 복잡도를 가진 학습기를 순차적으로 결합하는 방법. 앞 단계 학습기의 오류가 일정 수준(ε) 이상이거나 신뢰도가 일정 수준(γ)보다 높지 않은 데이터가 다음 단계로 넘어간다.",
    role: "간단한 데이터는 첫 단계에서 빠르게 처리하고 어려운 데이터만 뒤의 복잡한 학습기가 맡아 계산 시간을 절약한다. 영상의 객체 인식·객체 탐지에 효과적.",
    distinctions: [
      {
        from: "필터링에 의한 부스팅",
        how: "둘 다 앞 단계에서 제대로 처리되지 못한 데이터를 다음 단계로 넘기지만, 캐스케이딩은 단계가 높을수록 더 복잡하고 성능이 좋은 학습기를 쓰는 데 중점을 둔다.",
      },
    ],
    related: ["t-sequential-combination", "t-filtering-method", "t-mixture-of-experts"],
    lectures: [6],
    basis: "교재 8.4.2 캐스케이딩 · 강의록 캐스케이딩 cascading",
    emphasis: "키워드는 '복잡도'와 '순차적 결합' — 앞단은 간단한 학습기, 뒤로 갈수록 복잡한 학습기.",
    aliases: ["cascading", "cascade", "캐스케이드"],
  },
  {
    id: "t-mixture-of-experts",
    term: "전문가 혼합",
    en: "mixture of experts",
    category: "알고리즘",
    short: "입력에 따라 달라지는 계수 πᵢ(x)로 복수 개의 학습기를 가중합하는 결합.",
    definition:
      "복수 개의 학습기를 가중합하여 최종 학습기를 만드는 결합 방법으로, 가중합에 사용되는 계수 πᵢ(x)가 입력에 대한 함수로 주어진다. 어떤 입력이 주어지느냐에 따라 어떤 학습기를 중요하게 사용할 것인가가 달라진다.",
    formula: [{ expr: "f(x) = Σᵢ πᵢ(x)hᵢ(x)", note: "식 8-15" }],
    role: "입력 공간을 복수 개의 영역으로 나누어 각 학습기가 특정 영역을 중점적으로 담당하도록 학습하는 전략이 효과적. 학습기 간 상관관계가 줄거나 음이 되어 일반화 오차를 줄일 수 있다.",
    distinctions: [
      {
        from: "AdaBoost 가중 결합",
        how: "AdaBoost의 αᵢ는 분류 성능에 의존해 분류기마다 하나로 정해지는 값이고, 전문가 혼합의 πᵢ(x)는 입력의 함수다.",
      },
    ],
    prereqs: ["pre-weighted-average"],
    related: ["t-moe-weight-function", "t-adaboost", "t-error-independence", "t-cascading"],
    lectures: [6],
    basis: "교재 8.4.3 전문가 혼합 · 강의록 전문가 혼합 mixture of experts",
    emphasis: "'전문가'는 입력 공간의 특정 영역을 담당한다는 의미에서 붙여진 이름.",
    aliases: ["mixture of experts", "MoE", "전문가 혼합법"],
  },
  {
    id: "t-moe-weight-function",
    term: "가중치 함수 πᵢ(x)",
    category: "수식·지표",
    short: "전문가 혼합에서 입력에 따라 각 학습기의 비중을 정하는 계수 함수.",
    definition:
      "전문가 혼합의 가중합에 사용되는 입력에 대한 함수 형태의 계수. 주어진 입력에 따라 어떤 학습기를 중요하게 사용할지를 결정한다. 각 학습기가 담당하는 입력 영역이 명시적으로 정해지면 그에 맞추어 정할 수 있고, 스스로 담당 영역을 학습하게 할 수도 있다.",
    related: ["t-mixture-of-experts", "t-classifier-importance"],
    lectures: [6],
    basis: "교재 8.4.3 전문가 혼합 · 강의록 전문가 혼합",
    aliases: ["π(x)", "pi(x)", "게이팅 함수"],
  },
];
